<?php
require __DIR__ . '/includes/data.php';
require __DIR__ . '/includes/media_delivery.php';
require_once __DIR__ . '/includes/media_pipeline.php';
require_once __DIR__ . '/includes/posts.php';

$slug = $_GET['slug'] ?? 'first-to-fall-full-episode';
$currentVideo = sf_video_by_slug($videoCatalog, $slug) ?? $videoCatalog[0];
$currentEpisode = !empty($currentVideo['episode_slug']) ? sf_episode_by_slug($episodes, $currentVideo['episode_slug']) : null;
$member = sf_member_snapshot();
$requiredLevel = $currentVideo['access_level'] ?? 'subscriber';
$canWatch = sf_access_allows($requiredLevel, $member['access_level']);
$isPublished = ($currentVideo['status'] ?? 'draft') === 'published';
$playback = sf_media_video_playback($currentVideo, $canWatch && $isPublished);
$manifestObject = ($canWatch && $isPublished && !empty($currentVideo['id'])) ? sf_mp_ready_object('video',(int)$currentVideo['id'],'manifest') : null;
if ($manifestObject) $playback=['file_type'=>'adaptive HLS','file_path'=>(string)$manifestObject['storage_key'],'exists'=>true,'mime_type'=>'application/vnd.apple.mpegurl','url'=>sf_mp_manifest_url($manifestObject,sf_current_user_id(),1800)];
$playbackReady = $playback['url'] !== '' && !empty($playback['exists']);
$isHls = $playbackReady && $playback['mime_type']==='application/vnd.apple.mpegurl';
$nextVideo = sf_media_video_next($videoCatalog, $currentVideo);
$nextUrl = $nextVideo ? sf_url('watch.php?slug=' . urlencode($nextVideo['slug'])) : '';
$chapters = [['time'=>'0:00','label'=>'Cold open'],['time'=>'8:00','label'=>'Band conflict'],['time'=>'18:00','label'=>'Studio scene'],['time'=>'32:00','label'=>'Showdown'],['time'=>'44:00','label'=>'Final beat']];
$pageTitle = 'Watch ' . ($currentVideo['title'] ?? 'Stonefellow');
$pageDescription = 'Stonefellow secure adaptive video player with signed playback, access checks, watch progress, next episode controls, and fan comments.';
$pageClass = 'watch-page membership-page';
require __DIR__ . '/includes/header.php';
?>
<section class="sf-watch-shell" data-sf-video-page data-video-id="<?= (int)$currentVideo['id'] ?>" data-episode-id="<?= (int)($currentVideo['episode_id'] ?? 0) ?>" data-required-access="<?= htmlspecialchars($requiredLevel) ?>" data-next-url="<?= htmlspecialchars($nextUrl) ?>">
  <header class="sf-watch-topbar"><div><a href="<?= sf_url(!empty($currentVideo['episode_slug']) ? 'episode.php?slug=' . urlencode($currentVideo['episode_slug']) : 'episodes.php') ?>">← Back</a><span><?= htmlspecialchars($currentVideo['video_type'] === 'trailer' ? 'Public trailer' : sf_access_label($requiredLevel)) ?></span><span>Signed <?= htmlspecialchars($playback['file_type']) ?></span></div><div><a href="#fan-thread"><?= (int)sf_post_comment_count('video', (int)$currentVideo['id'], (string)$currentVideo['slug']) ?> Comments</a><a href="<?= sf_url('member.php') ?>">Member Home</a><a href="<?= sf_url('subscribe.php') ?>">Subscribe</a></div></header>
  <section class="sf-video-stage"><video class="sf-watch-video" controls preload="metadata" poster="<?= sf_asset($currentVideo['poster']) ?>" data-sf-video-player<?= $isHls?' data-hls-source="'.htmlspecialchars($playback['url']).'"':'' ?>><?php if ($playbackReady && !$isHls): ?><source src="<?= htmlspecialchars($playback['url']) ?>" type="<?= htmlspecialchars($playback['mime_type']) ?>"><?php elseif($playbackReady): ?><source src="<?= htmlspecialchars($playback['url']) ?>" type="application/vnd.apple.mpegurl"><?php endif; ?>Your browser does not support the video tag.</video><?php if (!$canWatch && $requiredLevel !== 'public'): ?><div class="sf-video-lock-overlay"><span>Membership Required</span><h1><?= htmlspecialchars($currentVideo['title']) ?></h1><p>You are seeing the preview path when available. Subscribe to unlock signed full-episode streaming, progress sync, and member library features.</p><a href="<?= sf_url('subscribe.php') ?>">Unlock Access</a></div><?php elseif (!$isPublished): ?><div class="sf-video-lock-overlay"><span>Coming Soon</span><h1><?= htmlspecialchars($currentVideo['title']) ?></h1><p>This video is registered in the catalog and access system. Publish it from the admin catalog when ready.</p><a href="<?= sf_url('episodes.php') ?>">Back to Episodes</a></div><?php elseif (!$playbackReady): ?><div class="sf-video-lock-overlay"><span>Source Needed</span><h1><?= htmlspecialchars($currentVideo['title']) ?></h1><p>The secure watch page is ready. Upload and process the protected video master from the media pipeline.</p><a href="<?= sf_url('admin/media-pipeline.php') ?>">Open Media Pipeline</a></div><?php endif; ?></section>
  <section class="sf-watch-info-grid"><article class="sf-watch-main-copy"><span class="sf-panel-eyebrow"><?= htmlspecialchars($currentEpisode['number'] ?? str_replace('_', ' ', $currentVideo['video_type'])) ?></span><h1><?= htmlspecialchars($currentVideo['title']) ?></h1><p><?= htmlspecialchars($currentVideo['description'] ?? '') ?></p><div class="sf-episode-meta-row"><span><?= htmlspecialchars($currentVideo['runtime']) ?></span><span><?= htmlspecialchars(sf_access_label($requiredLevel)) ?></span><span><?= $canWatch ? 'Full access' : 'Preview mode' ?></span><span data-sf-video-save-state>Tracking ready</span></div><div class="sf-episode-action-row"><?php if ($nextVideo): ?><a class="sf-secondary-action" href="<?= htmlspecialchars($nextUrl) ?>">Next: <?= htmlspecialchars($nextVideo['title']) ?></a><?php endif; ?><button class="sf-secondary-action" type="button" data-sf-library-save data-content-type="video" data-content-id="<?= (int)$currentVideo['id'] ?>" data-library-status="watchlist">Save to Watchlist</button><button class="sf-secondary-action" type="button" data-sf-library-save data-content-type="video" data-content-id="<?= (int)$currentVideo['id'] ?>" data-library-status="saved">Save to Library</button><a class="sf-secondary-action" href="#fan-thread">Open Comments</a></div></article><aside class="sf-member-panel sf-watch-progress-card"><span class="sf-panel-eyebrow">Resume Tracking</span><h2 data-sf-resume-label>0:00 saved</h2><div class="sf-wide-progress"><i data-sf-video-progress-bar style="width:0%"></i></div><p>Full episodes use signed adaptive HLS manifests and segments when processed. Playback progress syncs to the member library.</p></aside></section>
  <section class="sf-member-section"><div class="sf-member-section-head"><div><span class="sf-panel-eyebrow">Chapter Markers</span><h2>Episode timeline</h2></div></div><div class="sf-video-card-grid"><?php foreach ($chapters as $chapter): ?><article class="sf-video-card"><span><?= htmlspecialchars($chapter['time']) ?></span><strong><?= htmlspecialchars($chapter['label']) ?></strong><small>Chapter marker</small></article><?php endforeach; ?></div></section>
  <section class="sf-member-section"><div class="sf-member-section-head"><div><span class="sf-panel-eyebrow">More to Watch</span><h2>Episode library</h2></div><a href="<?= sf_url('episodes.php') ?>">Browse all</a></div><div class="sf-video-card-grid"><?php foreach (array_slice($videoCatalog, 0, 4) as $video): ?><a class="sf-video-card" href="<?= sf_url('watch.php?slug=' . urlencode($video['slug'])) ?>"><img src="<?= sf_asset($video['poster']) ?>" alt="<?= htmlspecialchars($video['title']) ?> poster"><span><?= htmlspecialchars(sf_access_label($video['access_level'])) ?></span><strong><?= htmlspecialchars($video['title']) ?></strong><small><?= htmlspecialchars($video['runtime']) ?> · <?= htmlspecialchars(str_replace('_', ' ', $video['video_type'])) ?></small></a><?php endforeach; ?></div></section>
  <div id="fan-thread"><?php sf_inline_comment_widget('video', (int)$currentVideo['id'], (string)$currentVideo['slug'], 'Video comments'); ?></div>
</section>
<?php if($isHls): ?><script src="https://cdn.jsdelivr.net/npm/hls.js@1.6.16/dist/hls.min.js"></script><script>document.addEventListener('DOMContentLoaded',()=>{const video=document.querySelector('[data-hls-source]'),src=video?.dataset.hlsSource;if(!video||!src)return;if(video.canPlayType('application/vnd.apple.mpegurl')){video.src=src;return}if(window.Hls&&Hls.isSupported()){const hls=new Hls({enableWorker:true,lowLatencyMode:false,capLevelToPlayerSize:true});hls.loadSource(src);hls.attachMedia(video);window.addEventListener('beforeunload',()=>hls.destroy(),{once:true})}});</script><?php endif; ?>
<?php require __DIR__ . '/includes/footer.php'; ?>
