CREATE TABLE IF NOT EXISTS ai_platform_actions (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  action_area VARCHAR(80) NOT NULL,
  action_type VARCHAR(80) NOT NULL,
  target_table VARCHAR(120) NULL,
  target_id INT UNSIGNED NULL,
  title VARCHAR(190) NOT NULL,
  description TEXT NULL,
  payload_json LONGTEXT NULL,
  risk_level ENUM('low','medium','high','critical') NOT NULL DEFAULT 'low',
  approval_status ENUM('draft','proposed','approved','rejected','blocked','ready_for_execution') NOT NULL DEFAULT 'proposed',
  execution_status ENUM('not_ready','ready','executed','failed','cancelled') NOT NULL DEFAULT 'not_ready',
  created_by_ai TINYINT(1) NOT NULL DEFAULT 1,
  approved_by_user_id INT UNSIGNED NULL,
  executed_by_user_id INT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  approved_at DATETIME NULL,
  executed_at DATETIME NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_ai_platform_actions_area (action_area),
  KEY idx_ai_platform_actions_type (action_type),
  KEY idx_ai_platform_actions_target (target_table, target_id),
  KEY idx_ai_platform_actions_approval (approval_status),
  KEY idx_ai_platform_actions_execution (execution_status),
  KEY idx_ai_platform_actions_risk (risk_level)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
