CREATE TABLE IF NOT EXISTS story_ai_media_generation_jobs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  media_prompt_id INT UNSIGNED NOT NULL,
  storyboard_id INT UNSIGNED NOT NULL,
  story_season_id INT UNSIGNED NULL,
  story_episode_id INT UNSIGNED NULL,
  prompt_type VARCHAR(80) NOT NULL,
  prompt_title VARCHAR(190) NOT NULL,
  prompt_body MEDIUMTEXT NOT NULL,
  provider_hint VARCHAR(80) NULL,
  aspect_ratio VARCHAR(40) NULL,
  generation_status ENUM('queued','blocked','needs_review','generated','failed','cancelled') NOT NULL DEFAULT 'queued',
  request_notes TEXT NULL,
  requested_by_user_id INT UNSIGNED NULL,
  reviewed_by_user_id INT UNSIGNED NULL,
  reviewed_at DATETIME NULL,
  generated_asset_id INT UNSIGNED NULL,
  provider_job_ref VARCHAR(190) NULL,
  error_message TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_story_ai_media_jobs_prompt (media_prompt_id),
  KEY idx_story_ai_media_jobs_storyboard (storyboard_id),
  KEY idx_story_ai_media_jobs_episode (story_episode_id),
  KEY idx_story_ai_media_jobs_status (generation_status),
  KEY idx_story_ai_media_jobs_type (prompt_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
