-- Stonefellow Migration 021: Storyboarding persistence and admin AI settings

CREATE TABLE IF NOT EXISTS ai_provider_settings (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  provider_key VARCHAR(40) NOT NULL UNIQUE,
  provider_label VARCHAR(120) NOT NULL,
  provider_type ENUM('text','image','multimodal') NOT NULL DEFAULT 'text',
  default_model VARCHAR(120) NULL,
  image_model VARCHAR(120) NULL,
  encrypted_api_key LONGTEXT NULL,
  api_key_hint VARCHAR(120) NULL,
  api_key_last4 VARCHAR(8) NULL,
  key_status ENUM('missing','configured','needs_test','connected','failed','disabled') NOT NULL DEFAULT 'missing',
  is_default_text TINYINT(1) NOT NULL DEFAULT 0,
  is_default_image TINYINT(1) NOT NULL DEFAULT 0,
  monthly_budget_cents INT UNSIGNED NOT NULL DEFAULT 0,
  monthly_token_limit INT UNSIGNED NOT NULL DEFAULT 0,
  monthly_image_limit INT UNSIGNED NOT NULL DEFAULT 0,
  timeout_seconds INT UNSIGNED NOT NULL DEFAULT 90,
  max_retries INT UNSIGNED NOT NULL DEFAULT 2,
  temperature DECIMAL(4,2) NOT NULL DEFAULT 0.70,
  status ENUM('active','inactive','disabled') NOT NULL DEFAULT 'inactive',
  test_status VARCHAR(40) NULL,
  test_message TEXT NULL,
  tested_at DATETIME NULL,
  created_by_user_id INT UNSIGNED NULL,
  updated_by_user_id INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_ai_provider_type (provider_type),
  INDEX idx_ai_provider_status (status),
  INDEX idx_ai_provider_default_text (is_default_text),
  INDEX idx_ai_provider_default_image (is_default_image)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_usage_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  provider_key VARCHAR(40) NOT NULL,
  feature_key VARCHAR(80) NOT NULL DEFAULT 'storyboarding',
  related_type VARCHAR(80) NULL,
  related_id BIGINT UNSIGNED NULL,
  model_key VARCHAR(120) NULL,
  request_type ENUM('text','image','rewrite','vision','upload') NOT NULL DEFAULT 'text',
  prompt_tokens INT UNSIGNED NOT NULL DEFAULT 0,
  completion_tokens INT UNSIGNED NOT NULL DEFAULT 0,
  image_count INT UNSIGNED NOT NULL DEFAULT 0,
  estimated_cost_cents INT UNSIGNED NOT NULL DEFAULT 0,
  request_status ENUM('queued','success','failed','canceled') NOT NULL DEFAULT 'queued',
  error_message TEXT NULL,
  created_by_user_id INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_ai_usage_provider (provider_key),
  INDEX idx_ai_usage_feature (feature_key),
  INDEX idx_ai_usage_related (related_type, related_id),
  INDEX idx_ai_usage_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS storyboards (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  owner_user_id INT UNSIGNED NULL,
  title VARCHAR(190) NOT NULL,
  slug VARCHAR(190) NOT NULL,
  short_prompt TEXT NULL,
  source_script MEDIUMTEXT NULL,
  logline TEXT NULL,
  genre VARCHAR(120) NULL,
  tone VARCHAR(120) NULL,
  visual_style VARCHAR(190) NULL,
  aspect_ratio VARCHAR(40) NOT NULL DEFAULT '16:9',
  scene_count TINYINT UNSIGNED NOT NULL DEFAULT 9,
  default_text_provider VARCHAR(40) NULL,
  default_image_provider VARCHAR(40) NULL,
  generation_status ENUM('draft','queued','generating','complete','failed','archived') NOT NULL DEFAULT 'draft',
  storyboard_status ENUM('concept','draft','in_review','ready','archived') NOT NULL DEFAULT 'concept',
  last_generated_at DATETIME NULL,
  created_by_user_id INT UNSIGNED NULL,
  updated_by_user_id INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_storyboards_slug (slug),
  INDEX idx_storyboards_owner (owner_user_id),
  INDEX idx_storyboards_status (storyboard_status),
  INDEX idx_storyboards_generation (generation_status),
  INDEX idx_storyboards_updated (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS storyboard_characters (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  storyboard_id BIGINT UNSIGNED NOT NULL,
  character_name VARCHAR(160) NOT NULL,
  role_label VARCHAR(120) NULL,
  character_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  appearance_notes TEXT NULL,
  personality_notes TEXT NULL,
  wardrobe_notes TEXT NULL,
  consistency_prompt TEXT NULL,
  reference_asset_id INT UNSIGNED NULL,
  likeness_strength ENUM('loose','medium','strong') NOT NULL DEFAULT 'medium',
  status ENUM('active','hidden','archived') NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_storyboard_characters_storyboard (storyboard_id),
  INDEX idx_storyboard_characters_status (status),
  CONSTRAINT fk_storyboard_characters_storyboard FOREIGN KEY (storyboard_id) REFERENCES storyboards(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS storyboard_character_references (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  storyboard_id BIGINT UNSIGNED NOT NULL,
  character_id BIGINT UNSIGNED NOT NULL,
  media_asset_id INT UNSIGNED NULL,
  reference_path VARCHAR(255) NULL,
  reference_type ENUM('uploaded_image','generated_image','external_note') NOT NULL DEFAULT 'uploaded_image',
  reference_label VARCHAR(160) NULL,
  is_primary TINYINT(1) NOT NULL DEFAULT 0,
  consistency_notes TEXT NULL,
  created_by_user_id INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_storyboard_refs_storyboard (storyboard_id),
  INDEX idx_storyboard_refs_character (character_id),
  INDEX idx_storyboard_refs_primary (is_primary),
  CONSTRAINT fk_storyboard_refs_storyboard FOREIGN KEY (storyboard_id) REFERENCES storyboards(id) ON DELETE CASCADE,
  CONSTRAINT fk_storyboard_refs_character FOREIGN KEY (character_id) REFERENCES storyboard_characters(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS storyboard_scenes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  storyboard_id BIGINT UNSIGNED NOT NULL,
  scene_number TINYINT UNSIGNED NOT NULL,
  scene_title VARCHAR(190) NOT NULL,
  scene_summary TEXT NULL,
  scene_prompt TEXT NULL,
  image_prompt MEDIUMTEXT NULL,
  dialog_text MEDIUMTEXT NULL,
  action_notes MEDIUMTEXT NULL,
  location_label VARCHAR(190) NULL,
  time_of_day VARCHAR(80) NULL,
  generated_image_asset_id INT UNSIGNED NULL,
  uploaded_image_asset_id INT UNSIGNED NULL,
  image_status ENUM('none','queued','generating','generated','uploaded','failed') NOT NULL DEFAULT 'none',
  rewrite_status ENUM('none','queued','rewritten','failed') NOT NULL DEFAULT 'none',
  scene_status ENUM('draft','ready','needs_review','archived') NOT NULL DEFAULT 'draft',
  last_rewritten_at DATETIME NULL,
  last_image_generated_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_storyboard_scene_number (storyboard_id, scene_number),
  INDEX idx_storyboard_scenes_storyboard (storyboard_id),
  INDEX idx_storyboard_scenes_status (scene_status),
  INDEX idx_storyboard_scenes_image_status (image_status),
  CONSTRAINT fk_storyboard_scenes_storyboard FOREIGN KEY (storyboard_id) REFERENCES storyboards(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS storyboard_scene_characters (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  storyboard_id BIGINT UNSIGNED NOT NULL,
  scene_id BIGINT UNSIGNED NOT NULL,
  character_id BIGINT UNSIGNED NOT NULL,
  presence_label VARCHAR(80) NOT NULL DEFAULT 'in_scene',
  scene_notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_scene_character (scene_id, character_id),
  INDEX idx_scene_characters_storyboard (storyboard_id),
  INDEX idx_scene_characters_scene (scene_id),
  INDEX idx_scene_characters_character (character_id),
  CONSTRAINT fk_scene_characters_storyboard FOREIGN KEY (storyboard_id) REFERENCES storyboards(id) ON DELETE CASCADE,
  CONSTRAINT fk_scene_characters_scene FOREIGN KEY (scene_id) REFERENCES storyboard_scenes(id) ON DELETE CASCADE,
  CONSTRAINT fk_scene_characters_character FOREIGN KEY (character_id) REFERENCES storyboard_characters(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS storyboard_jobs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  storyboard_id BIGINT UNSIGNED NULL,
  scene_id BIGINT UNSIGNED NULL,
  provider_key VARCHAR(40) NULL,
  job_type ENUM('generate_storyboard','rewrite_scene','generate_scene_image','regenerate_scene_image','upload_scene_image','character_reference') NOT NULL,
  job_status ENUM('queued','running','complete','failed','canceled') NOT NULL DEFAULT 'queued',
  input_json LONGTEXT NULL,
  output_json LONGTEXT NULL,
  error_message TEXT NULL,
  attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
  max_attempts TINYINT UNSIGNED NOT NULL DEFAULT 2,
  run_after DATETIME NULL,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  created_by_user_id INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_storyboard_jobs_status (job_status),
  INDEX idx_storyboard_jobs_type (job_type),
  INDEX idx_storyboard_jobs_storyboard (storyboard_id),
  INDEX idx_storyboard_jobs_scene (scene_id),
  INDEX idx_storyboard_jobs_run_after (run_after),
  CONSTRAINT fk_storyboard_jobs_storyboard FOREIGN KEY (storyboard_id) REFERENCES storyboards(id) ON DELETE SET NULL,
  CONSTRAINT fk_storyboard_jobs_scene FOREIGN KEY (scene_id) REFERENCES storyboard_scenes(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO ai_provider_settings (provider_key, provider_label, provider_type, default_model, image_model, key_status, is_default_text, is_default_image, monthly_budget_cents, monthly_token_limit, monthly_image_limit, status)
VALUES
('chatgpt', 'ChatGPT / OpenAI', 'multimodal', 'gpt-4.1', 'gpt-image-1', 'missing', 1, 1, 0, 0, 0, 'inactive'),
('claude', 'Claude / Anthropic', 'text', 'claude-3-5-sonnet-latest', NULL, 'missing', 0, 0, 0, 0, 0, 'inactive')
ON DUPLICATE KEY UPDATE
  provider_label = VALUES(provider_label),
  provider_type = VALUES(provider_type),
  default_model = COALESCE(ai_provider_settings.default_model, VALUES(default_model)),
  image_model = COALESCE(ai_provider_settings.image_model, VALUES(image_model)),
  updated_at = NOW();
