-- Stonefellow migration 027: local clip creator, rendering queue, and VP3 Clips publishing bridge.
-- Clips remain authoritative in this creator-owned platform.

CREATE TABLE IF NOT EXISTS vp3_clips (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  clip_uuid CHAR(36) NOT NULL,
  public_token CHAR(64) NOT NULL,
  source_media_object_id BIGINT NOT NULL,
  source_entity_type VARCHAR(40) NOT NULL,
  source_entity_id INT NOT NULL,
  title VARCHAR(190) NOT NULL,
  caption TEXT DEFAULT NULL,
  trim_start_seconds DECIMAL(10,3) NOT NULL DEFAULT 0,
  trim_end_seconds DECIMAL(10,3) NOT NULL,
  duration_seconds SMALLINT UNSIGNED NOT NULL,
  poster_at_seconds DECIMAL(10,3) NOT NULL DEFAULT 1,
  aspect_ratio ENUM('9:16','1:1','4:5','16:9') NOT NULL DEFAULT '9:16',
  destination_url VARCHAR(1000) NOT NULL,
  destination_label VARCHAR(80) NOT NULL DEFAULT 'Watch more',
  rights_owner_name VARCHAR(190) NOT NULL,
  rights_confirmed TINYINT(1) NOT NULL DEFAULT 0,
  rights_expires_at DATETIME DEFAULT NULL,
  scheduled_at DATETIME DEFAULT NULL,
  rendered_video_path VARCHAR(700) DEFAULT NULL,
  rendered_poster_path VARCHAR(700) DEFAULT NULL,
  local_status ENUM('draft','render_queued','rendering','ready','publishing','pending','scheduled','published','held','failed','withdrawn') NOT NULL DEFAULT 'draft',
  central_publication_uuid CHAR(36) DEFAULT NULL,
  central_publication_status VARCHAR(40) DEFAULT NULL,
  central_moderation_status VARCHAR(40) DEFAULT NULL,
  central_rights_status VARCHAR(40) DEFAULT NULL,
  central_feed_eligible TINYINT(1) NOT NULL DEFAULT 0,
  central_analytics_json JSON DEFAULT NULL,
  last_error VARCHAR(1000) DEFAULT NULL,
  source_updated_at DATETIME NOT NULL,
  last_synced_at DATETIME DEFAULT NULL,
  created_by_user_id INT DEFAULT NULL,
  updated_by_user_id INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_vp3_clip_uuid (clip_uuid),
  UNIQUE KEY uq_vp3_clip_public_token (public_token),
  INDEX idx_vp3_clips_status (local_status,scheduled_at,updated_at),
  INDEX idx_vp3_clips_source (source_media_object_id,created_at),
  INDEX idx_vp3_clips_publication (central_publication_uuid),
  FOREIGN KEY (source_media_object_id) REFERENCES media_objects(id) ON DELETE RESTRICT,
  FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vp3_clip_jobs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  job_uuid CHAR(36) NOT NULL,
  clip_id BIGINT NOT NULL,
  job_type ENUM('render','publish','status','analytics','withdraw') NOT NULL,
  status ENUM('queued','running','completed','retry','failed','canceled') NOT NULL DEFAULT 'queued',
  attempts INT NOT NULL DEFAULT 0,
  max_attempts INT NOT NULL DEFAULT 4,
  run_after DATETIME NOT NULL,
  locked_until DATETIME DEFAULT NULL,
  lock_token CHAR(64) DEFAULT NULL,
  request_uuid CHAR(36) DEFAULT NULL,
  response_json JSON DEFAULT NULL,
  error_message VARCHAR(1000) DEFAULT NULL,
  started_at DATETIME DEFAULT NULL,
  completed_at DATETIME DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_vp3_clip_job_uuid (job_uuid),
  INDEX idx_vp3_clip_jobs_queue (status,run_after,id),
  INDEX idx_vp3_clip_jobs_clip (clip_id,job_type,status),
  FOREIGN KEY (clip_id) REFERENCES vp3_clips(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vp3_clip_sync_events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  clip_id BIGINT NOT NULL,
  job_id BIGINT DEFAULT NULL,
  event_type VARCHAR(60) NOT NULL,
  event_status ENUM('success','failed','ignored') NOT NULL,
  request_uuid CHAR(36) DEFAULT NULL,
  http_status SMALLINT DEFAULT NULL,
  metadata_json JSON DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_vp3_clip_events_clip (clip_id,created_at),
  INDEX idx_vp3_clip_events_status (event_status,created_at),
  FOREIGN KEY (clip_id) REFERENCES vp3_clips(id) ON DELETE CASCADE,
  FOREIGN KEY (job_id) REFERENCES vp3_clip_jobs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
