<?php
$pageTitle='AI Execution Router';
$pageDescription='Run approved AI platform actions through audited allowlisted routes.';
$pageClass='membership-page admin-catalog-page ai-execution-router-page';
require_once __DIR__.'/../includes/admin_catalog.php';
require_once __DIR__.'/../includes/ai_platform_execution.php';
require_once __DIR__.'/../includes/ai_governance.php';
sf_agentic_require_permission('admin.ops.manage');

function sf_aier_ready_actions(): array { return sf_ai_exec_registry_ready()?sf_admin_fetch_all("SELECT * FROM ai_platform_actions WHERE approval_status='ready_for_execution' AND execution_status='ready' ORDER BY updated_at DESC,id DESC LIMIT 80"):[]; }
function sf_aier_recent_logs(): array { return sf_ai_exec_log_ready()?sf_admin_fetch_all('SELECT e.*,a.title,a.action_area,a.action_type FROM ai_platform_action_executions e LEFT JOIN ai_platform_actions a ON a.id=e.platform_action_id ORDER BY e.created_at DESC,e.id DESC LIMIT 100'):[]; }
function sf_aier_counts(): array { $counts=['ready'=>0,'completed'=>0,'failed'=>0,'blocked'=>0,'started'=>0];if(sf_ai_exec_registry_ready())$counts['ready']=(int)(sf_admin_fetch_one("SELECT COUNT(*) total FROM ai_platform_actions WHERE approval_status='ready_for_execution' AND execution_status='ready'")['total']??0);if(sf_ai_exec_log_ready())foreach(sf_admin_fetch_all('SELECT execution_status,COUNT(*) total FROM ai_platform_action_executions GROUP BY execution_status')as$row){$key=(string)($row['execution_status']??'');if(isset($counts[$key]))$counts[$key]=(int)$row['total'];}return$counts; }

if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'&&($_POST['action']??'')==='run_route'){
    $id=sf_admin_int($_POST['platform_action_id']??null,0)??0;$result=['ok'=>false,'message'=>'Missing platform action id.'];
    if($id>0){$action=sf_admin_fetch_one('SELECT * FROM ai_platform_actions WHERE id=? LIMIT 1',[$id]);$allowed=$action?sf_agentic_action_execution_allowed($action):['ok'=>false,'error'=>'invalid_action_payload'];if(empty($allowed['ok']))$result=['ok'=>false,'status'=>'blocked','message'=>sf_agentic_error_message((string)$allowed['error'])];elseif(!sf_agentic_acquire_lock('action|'.$id,0))$result=['ok'=>false,'status'=>'blocked','message'=>'Another worker is executing this action.'];else$result=sf_ai_exec_route_action($id);}
    sf_admin_flash(!empty($result['ok'])?'success':'error',(string)($result['message']??'Execution route finished.'));sf_admin_redirect(sf_url('admin/ai-execution-router.php'));
}
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'&&($_POST['action']??'')==='block_route'){
    $id=sf_admin_int($_POST['platform_action_id']??null,0)??0;if(!sf_ai_exec_registry_ready()||$id<=0)sf_admin_flash('error','Invalid platform action block request.');else{$before=sf_admin_fetch_one('SELECT * FROM ai_platform_actions WHERE id=? LIMIT 1',[$id]);$stmt=sf_admin_db()->prepare("UPDATE ai_platform_actions SET approval_status='blocked',execution_status='cancelled' WHERE id=? AND execution_status='ready'");$stmt->execute([$id]);$ok=$stmt->rowCount()===1;$after=sf_admin_fetch_one('SELECT * FROM ai_platform_actions WHERE id=? LIMIT 1',[$id]);if($ok){sf_ai_exec_log($id,(string)($before['action_type']??'unknown'),'blocked','Admin blocked this action before execution.');sf_admin_audit('ai_platform_action_blocked_before_execution','ai_platform_action',$id,$before,$after);}sf_admin_flash($ok?'success':'error',$ok?'AI platform action blocked.':'AI platform action was already changed or could not be blocked.');}sf_admin_redirect(sf_url('admin/ai-execution-router.php'));
}

$counts=sf_aier_counts();$readyActions=sf_aier_ready_actions();$logs=sf_aier_recent_logs();$routes=sf_ai_exec_routes();
require __DIR__.'/../includes/header.php';
sf_admin_shell_start('AI Operations','AI Execution Router','Run approved AI actions through explicit routes with policy checks, immutable approval validation, execution locks, and audit logs.','ai-execution-router');
?>
<style>.sf-agent-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.sf-agent-card{padding:18px;border:1px solid rgba(255,255,255,.1);border-radius:18px;background:rgba(255,255,255,.035)}.sf-agent-card h3{color:#fff;margin:8px 0}.sf-agent-card p,.sf-agent-card small{color:rgba(255,255,255,.68);line-height:1.5}.sf-agent-card code{display:block;white-space:normal;overflow-wrap:anywhere;padding:8px;border-radius:10px;background:rgba(0,0,0,.24)}@media(max-width:1000px){.sf-agent-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:680px){.sf-agent-grid{grid-template-columns:1fr}}</style>
<section class="sf-admin-card-grid"><div class="sf-admin-action-card"><span>Ready</span><strong><?= (int)$counts['ready'] ?></strong><small>Approved and unlocked actions.</small></div><div class="sf-admin-action-card"><span>Started</span><strong><?= (int)$counts['started'] ?></strong><small>Execution attempts logged.</small></div><div class="sf-admin-action-card"><span>Completed</span><strong><?= (int)$counts['completed'] ?></strong><small>Successfully routed actions.</small></div><div class="sf-admin-action-card"><span>Blocked</span><strong><?= (int)$counts['blocked'] ?></strong><small>Policy or admin blocks.</small></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Allowlist</span><h2><?= count($routes) ?> coded routes</h2></div></div><div class="sf-agent-grid"><?php foreach($routes as$key=>$route): ?><article class="sf-agent-card"><span class="sf-admin-mini-pill"><?= sf_admin_h($key) ?> · <?= sf_admin_h($route['side_effect']) ?></span><h3><?= sf_admin_h($route['label']) ?></h3><p><?= sf_admin_h($route['description']) ?></p><?php if(!empty($route['payload_hint'])): ?><code><?= sf_admin_h($route['payload_hint']) ?></code><?php endif; ?></article><?php endforeach; ?></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Approved Queue</span><h2><?= count($readyActions) ?> ready action(s)</h2></div></div><?php if(!$readyActions): ?><p>No actions are ready for execution.</p><?php else: ?><div class="sf-agent-grid"><?php foreach($readyActions as$action): ?><article class="sf-agent-card"><?= sf_admin_status_badge((string)$action['execution_status']) ?><h3><?= sf_admin_h($action['title']??'AI Action') ?></h3><p><?= sf_admin_h($action['action_type']??'route') ?> · Risk <?= sf_admin_h($action['risk_level']??'low') ?></p><p><?= sf_admin_h($action['description']??'') ?></p><form method="post" class="sf-admin-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="run_route"><input type="hidden" name="platform_action_id" value="<?= (int)$action['id'] ?>"><button type="submit">Run Routed Action</button></form><form method="post" class="sf-admin-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="block_route"><input type="hidden" name="platform_action_id" value="<?= (int)$action['id'] ?>"><button type="submit">Block Action</button></form></article><?php endforeach; ?></div><?php endif; ?></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Audit Trail</span><h2><?= count($logs) ?> recent event(s)</h2></div></div><div class="sf-agent-grid"><?php foreach($logs as$log): ?><article class="sf-agent-card"><?= sf_admin_status_badge((string)($log['execution_status']??'started')) ?><h3><?= sf_admin_h($log['title']??('Action #'.(int)$log['platform_action_id'])) ?></h3><small><?= sf_admin_h($log['route_key']??'route') ?> · <?= sf_admin_h($log['created_at']??'') ?></small><p><?= sf_admin_h($log['result_message']??'') ?></p></article><?php endforeach; ?></div></section>
<?php sf_admin_shell_end();require __DIR__.'/../includes/footer.php'; ?>
