<?php
$pageTitle = 'AI Mission Execution Console';
$pageDescription = 'Run approved AI operation missions one routed item at a time.';
$pageClass = 'membership-page admin-catalog-page ai-mission-execution-page';
require_once __DIR__ . '/../includes/admin_catalog.php';
require_once __DIR__ . '/../includes/ai_platform_execution.php';
require_once __DIR__ . '/../includes/ai_autonomy_policies.php';
require_once __DIR__ . '/../includes/ai_mission_execution.php';

if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST' && ($_POST['action'] ?? '') === 'run_next_item') {
  $result = sf_ai_mission_run_next(sf_admin_int($_POST['mission_id'] ?? null, 0) ?? 0);
  sf_admin_flash(!empty($result['ok']) ? 'success' : 'error', (string)($result['message'] ?? 'Mission execution action finished.'));
  sf_admin_redirect(sf_url('admin/ai-mission-execution.php'));
}

if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST' && ($_POST['action'] ?? '') === 'skip_item') {
  $result = sf_ai_mission_skip_item(sf_admin_int($_POST['item_id'] ?? null, 0) ?? 0);
  sf_admin_flash(!empty($result['ok']) ? 'success' : 'error', (string)($result['message'] ?? 'Mission skip action finished.'));
  sf_admin_redirect(sf_url('admin/ai-mission-execution.php'));
}

if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST' && ($_POST['action'] ?? '') === 'recover_running') {
  $result = sf_ai_mission_recover_running(sf_admin_int($_POST['mission_id'] ?? null, 0) ?? 0);
  sf_admin_flash(!empty($result['ok']) ? 'success' : 'error', (string)($result['message'] ?? 'Mission recovery action finished.'));
  sf_admin_redirect(sf_url('admin/ai-mission-execution.php'));
}

$missions = sf_ai_mission_missions();
$counts = sf_ai_mission_counts();
require __DIR__ . '/../includes/header.php';
sf_admin_shell_start('AI Operations', 'AI Mission Execution', 'Run approved AI missions one routed item at a time.', 'ai-mission-execution');
?>
<style>.ai-mission-execution-page .sf-exe-hero,.ai-mission-execution-page .sf-exe-stats,.ai-mission-execution-page .sf-exe-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:18px}.ai-mission-execution-page .sf-exe-panel{padding:20px;border:1px solid rgba(232,198,127,.16);border-radius:22px;background:linear-gradient(180deg,rgba(255,255,255,.06),rgba(255,255,255,.025));box-shadow:0 20px 56px rgba(0,0,0,.22)}.ai-mission-execution-page .sf-exe-panel h2{margin:8px 0;color:#fff;font-size:clamp(30px,4vw,56px);letter-spacing:-.05em;line-height:.98}.ai-mission-execution-page .sf-exe-copy,.ai-mission-execution-page .sf-exe-panel p{color:rgba(255,255,255,.68);line-height:1.55}.ai-mission-execution-page .sf-exe-card{padding:16px;border:1px solid rgba(255,255,255,.08);border-radius:18px;background:rgba(0,0,0,.15)}.ai-mission-execution-page .sf-exe-card h3{color:#fff;margin:10px 0 8px}.ai-mission-execution-page .sf-exe-pill{display:inline-block;margin-top:8px;border:1px solid rgba(232,198,127,.18);border-radius:999px;padding:4px 8px;color:#f5d98d;font-size:11px;font-weight:900}.ai-mission-execution-page .sf-exe-item{border-top:1px solid rgba(255,255,255,.08);padding:10px 0}@media(max-width:1080px){.ai-mission-execution-page .sf-exe-hero,.ai-mission-execution-page .sf-exe-stats,.ai-mission-execution-page .sf-exe-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:720px){.ai-mission-execution-page .sf-exe-hero,.ai-mission-execution-page .sf-exe-stats,.ai-mission-execution-page .sf-exe-grid{grid-template-columns:1fr}}</style>
<section class="sf-exe-hero"><div class="sf-exe-panel" style="grid-column:span 3"><span class="sf-panel-eyebrow">Phase 20</span><h2>Mission execution</h2><p>Approved missions can run exactly one eligible action card at a time through the existing AI Execution Router.</p></div><div class="sf-exe-panel"><span class="sf-panel-eyebrow">Guardrail</span><h2>Step by step</h2><p>No mission runs freeform or in bulk. The console stops when an item fails or is blocked.</p></div></section>
<?php if (!sf_ai_mission_ready()): ?><section class="sf-story-v1-warning"><strong>SQL required:</strong> Import <code>database/ai_operation_missions.sql</code> before executing missions.</section><?php endif; ?>
<?php if (!sf_ai_mission_actions_ready()): ?><section class="sf-story-v1-warning"><strong>SQL required:</strong> Import Phase 13 action registry SQL before executing missions.</section><?php endif; ?>
<?php if (!sf_ai_mission_logs_ready()): ?><section class="sf-story-v1-warning"><strong>SQL required:</strong> Import Phase 14 execution log SQL before executing missions.</section><?php endif; ?>
<section class="sf-exe-stats"><div class="sf-exe-panel"><span class="sf-panel-eyebrow">Approved</span><h2><?= (int)$counts['approved'] ?></h2></div><div class="sf-exe-panel"><span class="sf-panel-eyebrow">In Progress</span><h2><?= (int)$counts['in_progress'] ?></h2></div><div class="sf-exe-panel"><span class="sf-panel-eyebrow">Completed</span><h2><?= (int)$counts['completed'] ?></h2></div><div class="sf-exe-panel"><span class="sf-panel-eyebrow">Blocked</span><h2><?= (int)$counts['blocked'] ?></h2></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Execution Board</span><h2><?= count($missions) ?> executable mission(s)</h2></div><div><a href="<?= sf_url('admin/ai-operations-missions.php') ?>">Mission Planner</a> · <a href="<?= sf_url('admin/ai-execution-router.php') ?>">Execution Router</a></div></div><?php if (!$missions): ?><p class="sf-exe-copy">No approved or active missions are ready for the execution console.</p><?php else: ?><div class="sf-exe-grid"><?php foreach ($missions as $mission): $items = sf_ai_mission_items((int)$mission['id']); $next = sf_ai_mission_next_item((int)$mission['id']); ?><article class="sf-exe-card"><?= sf_admin_status_badge((string)($mission['mission_status'] ?? 'approved')) ?><h3><?= sf_admin_h($mission['mission_title'] ?? 'Mission') ?></h3><p class="sf-exe-copy"><strong><?= sf_admin_h($mission['mission_area'] ?? 'ops') ?></strong> · Risk <?= sf_admin_h($mission['risk_level'] ?? 'medium') ?><br><?= (int)($mission['item_count'] ?? 0) ?> items · <?= (int)($mission['completed_count'] ?? 0) ?> complete · <?= (int)($mission['blocked_count'] ?? 0) ?> blocked</p><form method="post" class="sf-admin-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="run_next_item"><input type="hidden" name="mission_id" value="<?= (int)$mission['id'] ?>"><div class="sf-admin-form-actions"><button type="submit"<?= ($next && in_array((string)($mission['mission_status'] ?? ''), ['approved','in_progress'], true)) ? '' : ' disabled' ?>>Run Next Eligible Item</button></div></form><form method="post" class="sf-admin-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="recover_running"><input type="hidden" name="mission_id" value="<?= (int)$mission['id'] ?>"><div class="sf-admin-form-actions"><button type="submit"<?= in_array((string)($mission['mission_status'] ?? ''), ['approved','in_progress','blocked'], true) ? '' : ' disabled' ?>>Recover Running Items</button></div></form><?php foreach ($items as $item): ?><div class="sf-exe-item"><span class="sf-exe-pill">#<?= (int)$item['item_order'] ?> · <?= sf_admin_h($item['item_status'] ?? 'pending') ?> · <?= sf_admin_h($item['action_type'] ?? 'route') ?></span><p class="sf-exe-copy"><strong><?= sf_admin_h($item['title'] ?? 'Action') ?></strong><br>Action: <?= sf_admin_h(($item['approval_status'] ?? 'missing') . ' / ' . ($item['execution_status'] ?? 'missing')) ?><br><?= sf_admin_h($item['last_result_message'] ?? '') ?></p><?php if (!in_array((string)($item['item_status'] ?? ''), ['completed','skipped','running'], true)): ?><form method="post" class="sf-admin-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="skip_item"><input type="hidden" name="item_id" value="<?= (int)$item['id'] ?>"><div class="sf-admin-form-actions"><button type="submit">Skip Item</button></div></form><?php endif; ?></div><?php endforeach; ?></article><?php endforeach; ?></div><?php endif; ?></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Safety</span><h2>Router-controlled mission execution</h2></div></div><p class="sf-exe-copy">This console only calls the existing AI Execution Router for one approved and ready action at a time. Router policies still block disallowed, critical, unknown, publishing, payment, billing, subscription, provider, sending, or destructive actions.</p></section>
<?php sf_admin_shell_end(); require __DIR__ . '/../includes/footer.php'; ?>
