<?php
$pageTitle = 'AI Operations Watchtower';
$pageDescription = 'Policy-aware AI operations dashboard for supervised platform recommendations.';
$pageClass = 'membership-page admin-catalog-page ai-operations-watchtower-page';
require_once __DIR__ . '/../includes/admin_catalog.php';
require_once __DIR__ . '/../includes/ai_platform_execution.php';
require_once __DIR__ . '/../includes/ai_autonomy_policies.php';

function sf_aiow_ready(): bool { return sf_admin_table_exists('ai_platform_actions'); }
function sf_aiow_text($value, string $fallback = 'Not set'): string { $text = trim((string)($value ?? '')); return $text === '' ? $fallback : $text; }
function sf_aiow_json(array $payload): string { return json_encode($payload, JSON_UNESCAPED_SLASHES); }
function sf_aiow_payload_key(array $payload): string { foreach (['source','created_from','created_at','requested_at','suggested_next_step'] as $k) unset($payload[$k]); ksort($payload); return sha1(sf_aiow_json($payload)); }
function sf_aiow_count(string $table): int { return sf_admin_table_exists($table) ? sf_admin_count_table($table) : 0; }
function sf_aiow_active_action_keys(): array { $keys = []; if (!sf_aiow_ready()) return $keys; foreach (sf_admin_fetch_all("SELECT action_type, target_table, target_id, payload_json FROM ai_platform_actions WHERE approval_status IN ('draft','proposed','approved','ready_for_execution') ORDER BY id DESC LIMIT 800") as $row) { $payload = json_decode((string)($row['payload_json'] ?? ''), true); $keys[(string)($row['action_type'] ?? '') . '|' . (string)($row['target_table'] ?? '') . '|' . (int)($row['target_id'] ?? 0) . '|' . (is_array($payload) ? sf_aiow_payload_key($payload) : 'none')] = true; } return $keys; }
function sf_aiow_route_allowed(string $route, array $routes): bool { return isset($routes[$route]) && (!function_exists('sf_ai_policy_can_propose') || sf_ai_policy_can_propose($route, $routes[$route])); }
function sf_aiow_signal(string $area, string $severity, string $title, string $description, string $route, array $payload, string $targetTable = '', int $targetId = 0, string $risk = 'medium'): array { return compact('area','severity','title','description','route','payload','targetTable','targetId','risk'); }
function sf_aiow_recent_storyboards(): array { return sf_admin_table_exists('storyboards') ? sf_admin_fetch_all('SELECT * FROM storyboards ORDER BY COALESCE(updated_at, created_at) DESC, id DESC LIMIT 60') : []; }
function sf_aiow_status(array $row): string { foreach (['producer_scene_status','status','storyboard_status','generation_status'] as $key) { $value = trim((string)($row[$key] ?? '')); if ($value !== '') return $value; } return 'outline'; }
function sf_aiow_signals(): array {
  $signals = []; $routes = sf_ai_exec_routes();
  if (sf_aiow_route_allowed('review', $routes)) foreach ([['table'=>'members','label'=>'Members'],['table'=>'orders','label'=>'Orders'],['table'=>'media_assets','label'=>'Media Assets'],['table'=>'ai_platform_actions','label'=>'AI Action Registry']] as $item) if (!sf_admin_table_exists($item['table'])) $signals[] = sf_aiow_signal('system','gap',$item['label'] . ' table missing',$item['label'] . ' table was not detected. Review install/database readiness before expanding AI automation.','review',['watchtower_scope'=>$item['table'] . '_missing'],'',0,'medium');
  $openActions = sf_aiow_ready() ? (int)(sf_admin_fetch_one("SELECT COUNT(*) total FROM ai_platform_actions WHERE approval_status IN ('proposed','approved','ready_for_execution')")['total'] ?? 0) : 0;
  if ($openActions > 20 && sf_aiow_route_allowed('review', $routes)) $signals[] = sf_aiow_signal('ops','review','High AI action backlog','There are ' . $openActions . ' active AI actions. Review and clear stale proposals before enabling more autonomy.','review',['watchtower_scope'=>'ai_action_backlog','active_actions'=>$openActions],'ai_platform_actions',0,'medium');
  foreach (sf_aiow_recent_storyboards() as $row) {
    $id = (int)($row['id'] ?? 0); if ($id <= 0) continue; $title = sf_aiow_text($row['title'] ?? $row['project_title'] ?? '', 'Storyboard #' . $id); $status = sf_aiow_status($row);
    if (in_array($status, ['draft','outline','in_progress'], true) && sf_aiow_route_allowed('mark_scene_needs_review', $routes)) $signals[] = sf_aiow_signal('story','review','Scene needs review: ' . $title,'Watchtower detected a scene shell that has not reached review status.','mark_scene_needs_review',['storyboard_id'=>$id],'storyboards',$id,'medium');
    if ($status === 'ready' && sf_aiow_route_allowed('create_team_briefing_draft', $routes)) $signals[] = sf_aiow_signal('ops','briefing','Ready scene needs briefing: ' . $title,'Watchtower detected a ready scene that may need a draft team briefing.','create_team_briefing_draft',['title'=>'Watchtower briefing — ' . $title,'subject'=>'Ready scene follow-up: ' . $title,'body'=>'AI Operations Watchtower detected this scene as ready and recommends a draft production briefing for review. Scene #' . $id . ': ' . $title,'action_url'=>'admin/ai-operations-watchtower.php'],'storyboards',$id,'medium');
  }
  if (sf_admin_table_exists('story_ai_media_prompts') && sf_admin_table_exists('story_ai_media_generation_jobs') && sf_aiow_route_allowed('queue_media_generation', $routes)) foreach (sf_admin_fetch_all("SELECT p.* FROM story_ai_media_prompts p LEFT JOIN story_ai_media_generation_jobs j ON j.media_prompt_id = p.id AND j.generation_status IN ('queued','blocked','needs_review') WHERE p.status IN ('approved','ready_for_generation') AND j.id IS NULL ORDER BY p.updated_at DESC, p.id DESC LIMIT 30") as $prompt) $signals[] = sf_aiow_signal('media','gap','Approved prompt not queued: ' . sf_aiow_text($prompt['prompt_title'] ?? '', 'Prompt #' . (int)$prompt['id']),'Watchtower found an approved prompt that is not yet in the generation queue.','queue_media_generation',['media_prompt_id'=>(int)$prompt['id']],'story_ai_media_prompts',(int)$prompt['id'],'high');
  if (sf_ai_policy_ready() && sf_admin_table_exists('ai_autonomy_policies') && sf_aiow_route_allowed('review', $routes)) { $blocked = (int)(sf_admin_fetch_one('SELECT COUNT(*) total FROM ai_autonomy_policies WHERE is_blocked = 1 OR autonomy_level = \'blocked\'')['total'] ?? 0); if ($blocked > 0) $signals[] = sf_aiow_signal('policy','review','Blocked autonomy routes present','There are ' . $blocked . ' blocked autonomy route policies. Review whether this is intentional before broader AI operations.','review',['watchtower_scope'=>'blocked_autonomy_policies','blocked_routes'=>$blocked],'ai_autonomy_policies',0,'low'); }
  return $signals;
}
function sf_aiow_counts(array $signals): array { $out = ['total'=>count($signals),'gap'=>0,'review'=>0,'briefing'=>0,'policy'=>0]; foreach ($signals as $s) { $sev = (string)($s['severity'] ?? 'gap'); if (!isset($out[$sev])) $out[$sev] = 0; $out[$sev]++; if (($s['area'] ?? '') === 'policy') $out['policy']++; } return $out; }

if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST' && ($_POST['action'] ?? '') === 'create_watchtower_proposal') {
  $routes = sf_ai_exec_routes(); $route = trim((string)($_POST['route'] ?? '')); $payload = json_decode((string)($_POST['payload_json'] ?? ''), true); $risk = trim((string)($_POST['risk_level'] ?? 'medium'));
  if (!sf_aiow_route_allowed($route, $routes)) sf_admin_flash('error', 'Route is not allowlisted or is blocked by autonomy policy.');
  elseif (!is_array($payload)) sf_admin_flash('error', 'Watchtower payload JSON is invalid.');
  elseif (!sf_aiow_ready()) sf_admin_flash('error', 'AI action registry is not ready.');
  else { if (!in_array($risk, ['low','medium','high','critical'], true)) $risk = 'medium'; $targetTable = sf_aiow_text($_POST['target_table'] ?? '', ''); $targetId = (int)($_POST['target_id'] ?? 0); $key = $route . '|' . $targetTable . '|' . $targetId . '|' . sf_aiow_payload_key($payload); if (!empty(sf_aiow_active_action_keys()[$key])) { sf_admin_flash('error', 'An active Watchtower proposal already exists for this route, target, and payload.'); sf_admin_redirect(sf_url('admin/ai-operations-watchtower.php')); } $payload = $payload + ['source'=>'ai_operations_watchtower','created_at'=>date('c')]; $ok = sf_admin_execute('INSERT INTO ai_platform_actions (action_area, action_type, target_table, target_id, title, description, payload_json, risk_level, approval_status, execution_status, created_by_ai) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)', [sf_aiow_text($_POST['action_area'] ?? '', 'ops'), $route, $targetTable ?: null, $targetId ?: null, sf_aiow_text($_POST['title'] ?? '', $routes[$route]['label'] ?? 'Watchtower Proposal'), sf_aiow_text($_POST['description'] ?? '', $routes[$route]['description'] ?? 'Watchtower proposal.'), sf_aiow_json($payload), $risk, 'proposed', 'not_ready']); if ($ok) sf_admin_audit('ai_watchtower_proposal_created', 'ai_platform_action', null, null, ['route'=>$route,'target_table'=>$targetTable,'target_id'=>$targetId]); sf_admin_flash($ok ? 'success' : 'error', $ok ? 'Watchtower proposal created.' : 'Watchtower proposal could not be created.'); }
  sf_admin_redirect(sf_url('admin/ai-operations-watchtower.php'));
}

$signals = sf_aiow_signals(); $counts = sf_aiow_counts($signals); $activeKeys = sf_aiow_active_action_keys();
require __DIR__ . '/../includes/header.php';
sf_admin_shell_start('AI Operations', 'AI Operations Watchtower', 'Policy-aware operational signals and supervised proposal creation.', 'ai-operations-watchtower');
?>
<style>.ai-operations-watchtower-page .sf-watch-hero,.ai-operations-watchtower-page .sf-watch-stats,.ai-operations-watchtower-page .sf-watch-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:18px}.ai-operations-watchtower-page .sf-watch-panel{padding:20px;border:1px solid rgba(232,198,127,.16);border-radius:22px;background:linear-gradient(180deg,rgba(255,255,255,.06),rgba(255,255,255,.025));box-shadow:0 20px 56px rgba(0,0,0,.22)}.ai-operations-watchtower-page .sf-watch-panel h2{margin:8px 0;color:#fff;font-size:clamp(30px,4vw,56px);letter-spacing:-.05em;line-height:.98}.ai-operations-watchtower-page .sf-watch-copy,.ai-operations-watchtower-page .sf-watch-panel p{color:rgba(255,255,255,.68);line-height:1.55}.ai-operations-watchtower-page .sf-watch-card{padding:16px;border:1px solid rgba(255,255,255,.08);border-radius:18px;background:rgba(0,0,0,.15)}.ai-operations-watchtower-page .sf-watch-card h3{color:#fff;margin:10px 0 8px}.ai-operations-watchtower-page .sf-watch-pill{display:inline-block;margin-top:8px;border:1px solid rgba(232,198,127,.18);border-radius:999px;padding:4px 8px;color:#f5d98d;font-size:11px;font-weight:900}.ai-operations-watchtower-page code{display:block;white-space:normal;overflow-wrap:anywhere;margin-top:8px;color:#d7e6ff;background:rgba(0,0,0,.22);border:1px solid rgba(255,255,255,.08);border-radius:12px;padding:8px;font-size:12px}@media(max-width:1080px){.ai-operations-watchtower-page .sf-watch-hero,.ai-operations-watchtower-page .sf-watch-stats,.ai-operations-watchtower-page .sf-watch-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:720px){.ai-operations-watchtower-page .sf-watch-hero,.ai-operations-watchtower-page .sf-watch-stats,.ai-operations-watchtower-page .sf-watch-grid{grid-template-columns:1fr}}</style>
<section class="sf-watch-hero"><div class="sf-watch-panel" style="grid-column:span 3"><span class="sf-panel-eyebrow">Phase 18</span><h2>Operations Watchtower</h2><p>AI reviews operational signals and creates policy-compliant action proposals for admin approval.</p></div><div class="sf-watch-panel"><span class="sf-panel-eyebrow">Guardrail</span><h2>No background work</h2><p>This page runs only when opened and creates proposals only. It does not execute, publish, send, bill, or generate.</p></div></section>
<?php if (!sf_aiow_ready()): ?><section class="sf-story-v1-warning"><strong>SQL required:</strong> Import Phase 13 <code>database/ai_platform_actions.sql</code> before creating Watchtower proposals.</section><?php endif; ?>
<?php if (!sf_ai_policy_ready()): ?><section class="sf-story-v1-warning"><strong>Policy warning:</strong> Import Phase 17 <code>database/ai_autonomy_policies.sql</code> and seed policies for full policy-backed behavior. Defaults are used until then.</section><?php endif; ?>
<section class="sf-watch-stats"><div class="sf-watch-panel"><span class="sf-panel-eyebrow">Signals</span><h2><?= (int)$counts['total'] ?></h2></div><div class="sf-watch-panel"><span class="sf-panel-eyebrow">Gaps</span><h2><?= (int)$counts['gap'] ?></h2></div><div class="sf-watch-panel"><span class="sf-panel-eyebrow">Reviews</span><h2><?= (int)$counts['review'] ?></h2></div><div class="sf-watch-panel"><span class="sf-panel-eyebrow">Policy</span><h2><?= (int)$counts['policy'] ?></h2></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Watchtower Signals</span><h2><?= count($signals) ?> policy-compliant signal(s)</h2></div><div><a href="<?= sf_url('admin/ai-autonomy-policies.php') ?>">Autonomy Policies</a> · <a href="<?= sf_url('admin/ai-platform-control.php') ?>">AI Control Center</a></div></div><?php if (!$signals): ?><p class="sf-watch-copy">No policy-compliant Watchtower signals were detected.</p><?php else: ?><div class="sf-watch-grid"><?php foreach ($signals as $signal): $key = (string)$signal['route'] . '|' . (string)$signal['targetTable'] . '|' . (int)$signal['targetId'] . '|' . sf_aiow_payload_key($signal['payload']); $exists = !empty($activeKeys[$key]); ?><article class="sf-watch-card"><span class="sf-watch-pill"><?= sf_admin_h($signal['area']) ?> · <?= sf_admin_h($signal['severity']) ?> · <?= sf_admin_h($signal['route']) ?></span><h3><?= sf_admin_h($signal['title']) ?></h3><p class="sf-watch-copy">Risk <?= sf_admin_h($signal['risk']) ?><?php if ($exists): ?><br>Existing active proposal already found.<?php endif; ?></p><p class="sf-watch-copy"><?= sf_admin_h($signal['description']) ?></p><code><?= sf_admin_h(sf_aiow_json($signal['payload'])) ?></code><form method="post" class="sf-admin-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="create_watchtower_proposal"><input type="hidden" name="route" value="<?= sf_admin_h($signal['route']) ?>"><input type="hidden" name="action_area" value="<?= sf_admin_h($signal['area']) ?>"><input type="hidden" name="risk_level" value="<?= sf_admin_h($signal['risk']) ?>"><input type="hidden" name="target_table" value="<?= sf_admin_h($signal['targetTable']) ?>"><input type="hidden" name="target_id" value="<?= (int)$signal['targetId'] ?>"><input type="hidden" name="title" value="<?= sf_admin_h($signal['title']) ?>"><input type="hidden" name="description" value="<?= sf_admin_h($signal['description']) ?>"><input type="hidden" name="payload_json" value="<?= sf_admin_h(sf_aiow_json($signal['payload'])) ?>"><div class="sf-admin-form-actions"><button type="submit"<?= (sf_aiow_ready() && !$exists) ? '' : ' disabled' ?>><?= $exists ? 'Proposal Exists' : 'Create Proposal' ?></button></div></form></article><?php endforeach; ?></div><?php endif; ?></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Safety</span><h2>Central watch, supervised action</h2></div></div><p class="sf-watch-copy">The Watchtower is not a daemon and performs no background automation. It surfaces signals and creates AI action cards that still pass through Control Center approval, Autonomy Policies, and the Execution Router.</p></section>
<?php sf_admin_shell_end(); require __DIR__ . '/../includes/footer.php'; ?>
