<?php
$pageTitle = 'AI Operations Missions';
$pageDescription = 'Group approved AI action cards into supervised operation missions.';
$pageClass = 'membership-page admin-catalog-page ai-operations-missions-page';
require_once __DIR__ . '/../includes/admin_catalog.php';
require_once __DIR__ . '/../includes/ai_platform_execution.php';
require_once __DIR__ . '/../includes/ai_autonomy_policies.php';

function sf_aiom_ready(): bool { return sf_admin_table_exists('ai_operation_missions') && sf_admin_table_exists('ai_operation_mission_items'); }
function sf_aiom_actions_ready(): bool { return sf_admin_table_exists('ai_platform_actions'); }
function sf_aiom_user_id(): ?int { return function_exists('sf_current_user_id') ? sf_current_user_id() : null; }
function sf_aiom_text($value, string $fallback = 'Not set'): string { $text = trim((string)($value ?? '')); return $text === '' ? $fallback : $text; }
function sf_aiom_statuses(): array { return ['draft'=>'Draft','reviewing'=>'Reviewing','approved'=>'Approved','in_progress'=>'In Progress','completed'=>'Completed','blocked'=>'Blocked','cancelled'=>'Cancelled']; }
function sf_aiom_risks(): array { return ['low'=>'Low','medium'=>'Medium','high'=>'High','critical'=>'Critical']; }
function sf_aiom_candidate_actions(): array { if (!sf_aiom_actions_ready()) return []; return sf_admin_fetch_all("SELECT * FROM ai_platform_actions WHERE approval_status IN ('proposed','approved','ready_for_execution') AND execution_status IN ('not_ready','ready') ORDER BY FIELD(risk_level,'critical','high','medium','low'), updated_at DESC, id DESC LIMIT 120"); }
function sf_aiom_missions(): array { return sf_aiom_ready() ? sf_admin_fetch_all('SELECT m.*, COUNT(i.id) item_count, SUM(i.item_status IN (\'completed\')) completed_count, SUM(i.item_status IN (\'blocked\',\'failed\')) blocked_count FROM ai_operation_missions m LEFT JOIN ai_operation_mission_items i ON i.mission_id = m.id GROUP BY m.id ORDER BY m.updated_at DESC, m.id DESC LIMIT 80') : []; }
function sf_aiom_items(int $missionId): array { return sf_aiom_ready() && $missionId > 0 ? sf_admin_fetch_all('SELECT i.*, a.title, a.action_type, a.action_area, a.risk_level, a.approval_status, a.execution_status FROM ai_operation_mission_items i LEFT JOIN ai_platform_actions a ON a.id = i.platform_action_id WHERE i.mission_id = ? ORDER BY i.item_order ASC, i.id ASC', [$missionId]) : []; }
function sf_aiom_counts(): array { return ['missions'=>sf_admin_table_exists('ai_operation_missions') ? sf_admin_count_table('ai_operation_missions') : 0,'candidates'=>count(sf_aiom_candidate_actions()),'active'=>sf_aiom_ready() ? (int)(sf_admin_fetch_one("SELECT COUNT(*) total FROM ai_operation_missions WHERE mission_status IN ('draft','reviewing','approved','in_progress')")['total'] ?? 0) : 0,'blocked'=>sf_aiom_ready() ? (int)(sf_admin_fetch_one("SELECT COUNT(*) total FROM ai_operation_missions WHERE mission_status = 'blocked'")['total'] ?? 0) : 0]; }
function sf_aiom_selected_ids($value): array { return array_values(array_unique(array_filter(array_map('intval', is_array($value) ? $value : [])))); }

if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST' && ($_POST['action'] ?? '') === 'create_mission') {
  $selected = sf_aiom_selected_ids($_POST['platform_action_ids'] ?? []);
  $title = sf_aiom_text($_POST['mission_title'] ?? '', 'AI Operations Mission');
  $area = sf_aiom_text($_POST['mission_area'] ?? '', 'ops');
  $risk = sf_aiom_text($_POST['risk_level'] ?? '', 'medium');
  if (!sf_aiom_ready()) sf_admin_flash('error', 'Mission planner SQL is not ready. Import database/ai_operation_missions.sql first.');
  elseif (!$selected) sf_admin_flash('error', 'Select at least one AI action card for this mission.');
  elseif (!array_key_exists($risk, sf_aiom_risks())) sf_admin_flash('error', 'Invalid mission risk level.');
  else {
    $ok = sf_admin_execute('INSERT INTO ai_operation_missions (mission_title, mission_area, mission_status, risk_level, objective, source_context, created_by_ai, created_by_user_id) VALUES (?, ?, ?, ?, ?, ?, 1, ?)', [$title, $area, 'draft', $risk, sf_aiom_text($_POST['objective'] ?? '', 'Mission grouped from existing AI action cards.'), 'ai_operations_missions', sf_aiom_user_id()]);
    $missionId = (int)(sf_admin_db()?->lastInsertId() ?: 0);
    $order = 10;
    if ($ok && $missionId > 0) foreach ($selected as $actionId) { sf_admin_execute('INSERT IGNORE INTO ai_operation_mission_items (mission_id, platform_action_id, item_order, item_status, stop_on_failure) VALUES (?, ?, ?, ?, 1)', [$missionId, $actionId, $order, 'pending']); $order += 10; }
    if ($ok) sf_admin_audit('ai_operation_mission_created', 'ai_operation_mission', $missionId, null, ['selected_actions'=>$selected]);
    sf_admin_flash($ok ? 'success' : 'error', $ok ? 'AI operation mission created.' : 'AI operation mission could not be created.');
  }
  sf_admin_redirect(sf_url('admin/ai-operations-missions.php'));
}

if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST' && ($_POST['action'] ?? '') === 'update_mission_status') {
  $missionId = sf_admin_int($_POST['mission_id'] ?? null, 0) ?? 0;
  $status = sf_aiom_text($_POST['mission_status'] ?? '', 'draft');
  if (!sf_aiom_ready() || $missionId <= 0 || !array_key_exists($status, sf_aiom_statuses())) sf_admin_flash('error', 'Invalid mission status update.');
  else {
    $before = sf_admin_fetch_one('SELECT * FROM ai_operation_missions WHERE id = ? LIMIT 1', [$missionId]);
    $ok = sf_admin_execute('UPDATE ai_operation_missions SET mission_status = ?, approved_by_user_id = CASE WHEN ? = \'approved\' THEN ? ELSE approved_by_user_id END, approved_at = CASE WHEN ? = \'approved\' THEN NOW() ELSE approved_at END, completed_at = CASE WHEN ? = \'completed\' THEN NOW() ELSE completed_at END WHERE id = ?', [$status, $status, sf_aiom_user_id(), $status, $status, $missionId]);
    $after = sf_admin_fetch_one('SELECT * FROM ai_operation_missions WHERE id = ? LIMIT 1', [$missionId]);
    if ($ok) sf_admin_audit('ai_operation_mission_status_update', 'ai_operation_mission', $missionId, $before, $after);
    sf_admin_flash($ok ? 'success' : 'error', $ok ? 'Mission status updated.' : 'Mission status could not be updated.');
  }
  sf_admin_redirect(sf_url('admin/ai-operations-missions.php'));
}

$candidates = sf_aiom_candidate_actions();
$missions = sf_aiom_missions();
$counts = sf_aiom_counts();
require __DIR__ . '/../includes/header.php';
sf_admin_shell_start('AI Operations', 'AI Operations Missions', 'Plan grouped AI management work before execution.', 'ai-operations-missions');
?>
<style>.ai-operations-missions-page .sf-mis-hero,.ai-operations-missions-page .sf-mis-stats,.ai-operations-missions-page .sf-mis-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:18px}.ai-operations-missions-page .sf-mis-panel{padding:20px;border:1px solid rgba(232,198,127,.16);border-radius:22px;background:linear-gradient(180deg,rgba(255,255,255,.06),rgba(255,255,255,.025));box-shadow:0 20px 56px rgba(0,0,0,.22)}.ai-operations-missions-page .sf-mis-panel h2{margin:8px 0;color:#fff;font-size:clamp(30px,4vw,56px);letter-spacing:-.05em;line-height:.98}.ai-operations-missions-page .sf-mis-copy,.ai-operations-missions-page .sf-mis-panel p{color:rgba(255,255,255,.68);line-height:1.55}.ai-operations-missions-page .sf-mis-card{padding:16px;border:1px solid rgba(255,255,255,.08);border-radius:18px;background:rgba(0,0,0,.15)}.ai-operations-missions-page .sf-mis-card h3{color:#fff;margin:10px 0 8px}.ai-operations-missions-page .sf-mis-pill{display:inline-block;margin-top:8px;border:1px solid rgba(232,198,127,.18);border-radius:999px;padding:4px 8px;color:#f5d98d;font-size:11px;font-weight:900}.ai-operations-missions-page textarea{width:100%;min-height:70px;resize:vertical}.ai-operations-missions-page .sf-mis-actions{max-height:440px;overflow:auto;border:1px solid rgba(255,255,255,.08);border-radius:18px;padding:8px;background:rgba(0,0,0,.14)}.ai-operations-missions-page .sf-mis-check{display:block;padding:10px;border-bottom:1px solid rgba(255,255,255,.06);color:rgba(255,255,255,.78)}@media(max-width:1080px){.ai-operations-missions-page .sf-mis-hero,.ai-operations-missions-page .sf-mis-stats,.ai-operations-missions-page .sf-mis-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:720px){.ai-operations-missions-page .sf-mis-hero,.ai-operations-missions-page .sf-mis-stats,.ai-operations-missions-page .sf-mis-grid{grid-template-columns:1fr}}</style>
<section class="sf-mis-hero"><div class="sf-mis-panel" style="grid-column:span 3"><span class="sf-panel-eyebrow">Phase 19</span><h2>Mission planner</h2><p>Group individual AI action cards into reviewable operation missions before mission execution exists.</p></div><div class="sf-mis-panel"><span class="sf-panel-eyebrow">Guardrail</span><h2>No execution</h2><p>This planner groups and statuses missions only. Phase 20 will add step-through execution.</p></div></section>
<?php if (!sf_aiom_ready()): ?><section class="sf-story-v1-warning"><strong>SQL required:</strong> Import <code>database/ai_operation_missions.sql</code> before creating missions.</section><?php endif; ?>
<section class="sf-mis-stats"><div class="sf-mis-panel"><span class="sf-panel-eyebrow">Missions</span><h2><?= (int)$counts['missions'] ?></h2></div><div class="sf-mis-panel"><span class="sf-panel-eyebrow">Candidate Actions</span><h2><?= (int)$counts['candidates'] ?></h2></div><div class="sf-mis-panel"><span class="sf-panel-eyebrow">Active</span><h2><?= (int)$counts['active'] ?></h2></div><div class="sf-mis-panel"><span class="sf-panel-eyebrow">Blocked</span><h2><?= (int)$counts['blocked'] ?></h2></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Create Mission</span><h2>Group AI action cards</h2></div><div><a href="<?= sf_url('admin/ai-operations-watchtower.php') ?>">Watchtower</a> · <a href="<?= sf_url('admin/ai-platform-control.php') ?>">AI Control Center</a></div></div><form method="post" class="sf-admin-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="create_mission"><div class="sf-admin-form-grid"><label>Mission Title<input name="mission_title" value="Prepare selected AI operations"></label><label>Mission Area<input name="mission_area" value="ops"></label><label>Risk<select name="risk_level"><?php foreach (sf_aiom_risks() as $key => $label): ?><option value="<?= sf_admin_h($key) ?>"><?= sf_admin_h($label) ?></option><?php endforeach; ?></select></label></div><label>Objective<textarea name="objective">Group selected AI action cards into a supervised mission for review.</textarea></label><div class="sf-mis-actions"><?php if (!$candidates): ?><p class="sf-mis-copy">No candidate AI action cards available. Create proposals from Watchtower, Publishing Readiness, or AI Control Center first.</p><?php else: foreach ($candidates as $action): ?><label class="sf-mis-check"><input type="checkbox" name="platform_action_ids[]" value="<?= (int)$action['id'] ?>"> <strong><?= sf_admin_h($action['title'] ?? 'AI Action') ?></strong><br><?= sf_admin_h(($action['action_area'] ?? 'area') . ' · ' . ($action['action_type'] ?? 'route') . ' · ' . ($action['approval_status'] ?? 'status') . ' · risk ' . ($action['risk_level'] ?? 'medium')) ?></label><?php endforeach; endif; ?></div><div class="sf-admin-form-actions"><button type="submit"<?= (sf_aiom_ready() && $candidates) ? '' : ' disabled' ?>>Create Mission</button></div></form></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Mission Board</span><h2><?= count($missions) ?> mission(s)</h2></div></div><?php if (!$missions): ?><p class="sf-mis-copy">No missions created yet.</p><?php else: ?><div class="sf-mis-grid"><?php foreach ($missions as $mission): $items = sf_aiom_items((int)$mission['id']); ?><article class="sf-mis-card"><?= sf_admin_status_badge((string)($mission['mission_status'] ?? 'draft')) ?><h3><?= sf_admin_h($mission['mission_title'] ?? 'Mission') ?></h3><p class="sf-mis-copy"><strong><?= sf_admin_h($mission['mission_area'] ?? 'ops') ?></strong> · Risk <?= sf_admin_h($mission['risk_level'] ?? 'medium') ?><br><?= (int)($mission['item_count'] ?? 0) ?> items · <?= (int)($mission['completed_count'] ?? 0) ?> complete · <?= (int)($mission['blocked_count'] ?? 0) ?> blocked</p><p class="sf-mis-copy"><?= sf_admin_h($mission['objective'] ?? '') ?></p><?php foreach ($items as $item): ?><p class="sf-mis-copy">#<?= (int)$item['item_order'] ?> · <?= sf_admin_h($item['item_status'] ?? 'pending') ?> · <?= sf_admin_h($item['action_type'] ?? 'route') ?><br><?= sf_admin_h($item['title'] ?? 'Action') ?></p><?php endforeach; ?><form method="post" class="sf-admin-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="update_mission_status"><input type="hidden" name="mission_id" value="<?= (int)$mission['id'] ?>"><label>Mission Status<select name="mission_status"><?php foreach (sf_aiom_statuses() as $key => $label): ?><option value="<?= sf_admin_h($key) ?>"<?= (string)($mission['mission_status'] ?? '') === $key ? ' selected' : '' ?>><?= sf_admin_h($label) ?></option><?php endforeach; ?></select></label><div class="sf-admin-form-actions"><button type="submit">Update Mission</button></div></form></article><?php endforeach; ?></div><?php endif; ?></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Safety</span><h2>Planning only</h2></div></div><p class="sf-mis-copy">Phase 19 does not run mission items. It only groups existing AI action cards and tracks mission status. Step-through mission execution should be added separately in Phase 20.</p></section>
<?php sf_admin_shell_end(); require __DIR__ . '/../includes/footer.php'; ?>
