<?php

declare(strict_types=1);

$pageTitle='Launch Catalog Operations';
$pageDescription='Unified launch readiness, publication, SEO, sample cleanup, and reversible catalog operations.';
$pageClass='membership-page admin-catalog-page';
require __DIR__.'/../includes/catalog_operations.php';

if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
  $action=(string)($_POST['action']??'');
  if(!sf_lco_ready()){sf_admin_flash('warning','Import migration 024 before using launch catalog operations.');sf_admin_redirect(sf_url('admin/catalog-operations.php'));}
  if($action==='snapshot'){$scan=sf_lco_scan(true,trim((string)($_POST['target_commit_sha']??getenv('SF_RELEASE_COMMIT_SHA')?:'')));sf_admin_flash(!empty($scan['snapshot_id'])?'success':'error',!empty($scan['snapshot_id'])?'Readiness snapshot created.':'Snapshot could not be created.');}
  elseif($action==='save_series'){$id=sf_lco_save_series($_POST,sf_admin_int($_POST['id']??null,0)??0);sf_admin_flash($id?'success':'error',$id?'Series record saved.':'Series record could not be saved.');}
  elseif($action==='save_seo'){$ok=sf_lco_save_seo((string)($_POST['entity_type']??''),sf_admin_int($_POST['entity_id']??null,0)??0,$_POST);sf_admin_flash($ok?'success':'error',$ok?'SEO metadata saved.':'SEO metadata failed validation.');}
  elseif($action==='scan_samples'){$flags=sf_lco_scan_samples(true);sf_admin_flash('success',count($flags).' sample-content signal(s) recorded.');}
  elseif($action==='publish_ready'){$r=sf_lco_publish_ready((string)($_POST['confirmation']??''));sf_admin_flash(!empty($r['ok'])?'success':'error',!empty($r['ok'])?'Ready catalog items published in batch #'.(int)$r['batch_id'].'.':(string)($r['message']??'Publishing completed with errors.'));}
  elseif($action==='archive_samples'){$r=sf_lco_archive_samples((string)($_POST['confirmation']??''));sf_admin_flash(!empty($r['ok'])?'success':'error',!empty($r['ok'])?'High-confidence samples archived in batch #'.(int)$r['batch_id'].'.':(string)($r['message']??'Sample archive completed with errors.'));}
  elseif($action==='rollback'){$r=sf_lco_rollback_batch(sf_admin_int($_POST['batch_id']??null,0)??0,(string)($_POST['confirmation']??''));sf_admin_flash(!empty($r['ok'])?'success':'error',!empty($r['ok'])?'Batch rolled back.':(string)($r['message']??'Rollback failed.'));}
  sf_admin_redirect(sf_url('admin/catalog-operations.php'));
}

$scan=sf_lco_scan();
$latest=sf_lco_latest_snapshot();
$series=sf_lco_rows('series');
$seoTargetType=array_key_exists($_GET['seo_type']??'',sf_lco_types())?(string)$_GET['seo_type']:'series';
$seoTargetId=sf_admin_int($_GET['seo_id']??null,0)??0;
$seoRow=$seoTargetId>0?sf_lco_seo($seoTargetType,$seoTargetId):null;
$batches=sf_admin_table_exists('catalog_publication_batches')?sf_admin_fetch_all('SELECT * FROM catalog_publication_batches ORDER BY created_at DESC,id DESC LIMIT 20'):[];
$sampleFlags=sf_admin_table_exists('catalog_sample_flags')?sf_admin_fetch_all('SELECT * FROM catalog_sample_flags WHERE flag_status="open" ORDER BY confidence_percent DESC,id DESC LIMIT 50'):[];
$assets=sf_admin_assets('image');
require __DIR__.'/../includes/header.php';
sf_admin_shell_start('Launch Catalog','Content + Catalog Operations','Score every launch record, fix blockers, publish only ready content, and roll back every batch.','catalog-operations');
?>
<?php if(!sf_lco_ready()): ?><section class="sf-admin-alert sf-admin-alert-warning"><strong>SQL required:</strong> import <code>database/migrations/024_launch_content_catalog_operations.sql</code>.</section><?php endif; ?>
<section class="sf-admin-metrics-grid"><article><span>Live Readiness</span><strong><?= (int)$scan['overall_score'] ?>%</strong><small><?= (int)$scan['ready_count'] ?> of <?= (int)$scan['item_count'] ?> items ready</small></article><article><span>Blockers</span><strong><?= (int)$scan['blocker_count'] ?></strong><small>Across all launch catalog types</small></article><article><span>Last Snapshot</span><strong><?= $latest?(int)$latest['overall_score'].'%':'—' ?></strong><small><?= sf_admin_h($latest['created_at']??'No saved snapshot') ?></small></article><article><span>Sample Flags</span><strong><?= count($sampleFlags) ?></strong><small>Open high-confidence review items</small></article></section>
<section class="sf-admin-card-grid"><a class="sf-admin-action-card" href="<?= sf_url('admin/catalog-transfer.php') ?>"><span>Transfer</span><strong>Import / Export</strong><small>Draft-first CSV and JSON operations.</small></a><a class="sf-admin-action-card" href="<?= sf_url('admin/release-schedule.php') ?>"><span>Schedule</span><strong>Release Calendar</strong><small>Timezone-safe publishing windows.</small></a><a class="sf-admin-action-card" href="<?= sf_url('admin/media-pipeline.php') ?>"><span>Media</span><strong>Processing Pipeline</strong><small>Audio, waveform, poster, and HLS readiness.</small></a><a class="sf-admin-action-card" href="<?= sf_url('admin/payment-gateways.php') ?>"><span>Commerce</span><strong>Payment Readiness</strong><small>Stripe Connect onboarding and settlement.</small></a></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Readiness by Type</span><h2>Launch catalog scorecard</h2></div><form method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="snapshot"><input type="hidden" name="target_commit_sha" value="<?= sf_admin_h(getenv('SF_RELEASE_COMMIT_SHA')?:'') ?>"><button type="submit">Save Snapshot</button></form></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Catalog</th><th>Records</th><th>Ready</th><th>Blocked</th><th>Score</th></tr></thead><tbody><?php foreach($scan['types'] as$type=>$sum): ?><tr><td><strong><?= sf_admin_h($sum['label']) ?></strong></td><td><?= (int)$sum['total'] ?></td><td><?= (int)$sum['ready'] ?></td><td><?= (int)$sum['blocked'] ?></td><td><?= (int)$sum['score'] ?>%</td></tr><?php endforeach; ?></tbody></table></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Blockers</span><h2>Items requiring work</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Item</th><th>Type</th><th>Score</th><th>Blockers</th><th>Actions</th></tr></thead><tbody><?php $blocked=array_values(array_filter($scan['items'],fn($i)=>$i['status']!=='ready'));foreach(array_slice($blocked,0,150) as$item): ?><tr><td><strong><?= sf_admin_h($item['label']) ?></strong><small>#<?= (int)$item['entity_id'] ?></small></td><td><?= sf_admin_h($scan['types'][$item['entity_type']]['label']??$item['entity_type']) ?></td><td><?= (int)$item['score'] ?>%</td><td><?= sf_admin_h(implode(', ',$item['blockers'])) ?><?php if($item['warnings']): ?><small>Warnings: <?= sf_admin_h(implode(', ',$item['warnings'])) ?></small><?php endif; ?></td><td><a href="<?= sf_url($item['edit_url']) ?>">Edit</a> · <a href="<?= sf_url('admin/catalog-operations.php?seo_type='.urlencode($item['entity_type']).'&seo_id='.(int)$item['entity_id'].'#seo') ?>">SEO</a> · <a href="<?= sf_url($item['public_url']) ?>">Preview</a></td></tr><?php endforeach; ?><?php if(!$blocked): ?><tr><td colspan="5">Every catalog item is launch-ready.</td></tr><?php endif; ?></tbody></table></div></section>
<section class="sf-admin-two-col sf-admin-two-col-wide"><article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Series Source</span><h2>Main series record</h2></div></div><?php $editSeries=$series[0]??[]; ?><form class="sf-admin-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="save_series"><input type="hidden" name="id" value="<?= (int)($editSeries['id']??0) ?>"><label>Series Title<input name="title" required value="<?= sf_admin_h($editSeries['title']??'Stonefellow') ?>"></label><label>Slug<input name="slug" value="<?= sf_admin_h($editSeries['slug']??'stonefellow') ?>"></label><label>Description<textarea name="description" rows="5"><?= sf_admin_h($editSeries['description']??'') ?></textarea></label><div class="sf-admin-form-grid"><label>Release Time<input type="datetime-local" name="release_at" value=""></label><label>Timezone<input name="release_timezone" value="<?= sf_admin_h($editSeries['release_timezone']??sf_lco_timezone()) ?>"></label></div><label>Primary Image<?= sf_admin_asset_select('primary_image_asset_id',$assets,$editSeries['primary_image_asset_id']??'','image') ?></label><label>Status<?= sf_admin_select('status',['draft'=>'Draft','scheduled'=>'Scheduled','published'=>'Published','archived'=>'Archived'],$editSeries['status']??'draft') ?></label><div class="sf-admin-form-actions"><button type="submit">Save Series</button></div></form></article><article class="sf-admin-panel" id="seo"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">SEO</span><h2>Explicit metadata</h2></div></div><form class="sf-admin-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="save_seo"><div class="sf-admin-form-grid"><label>Entity Type<?= sf_admin_select('entity_type',array_map(fn($c)=>$c['label'],sf_lco_types()),$seoTargetType) ?></label><label>Entity ID<input type="number" name="entity_id" min="1" required value="<?= $seoTargetId?:'' ?>"></label></div><label>SEO Title<input name="seo_title" maxlength="190" required value="<?= sf_admin_h($seoRow['seo_title']??'') ?>"></label><label>Meta Description<textarea name="meta_description" maxlength="320" rows="4" required><?= sf_admin_h($seoRow['meta_description']??'') ?></textarea></label><label>Canonical Path<input name="canonical_path" required placeholder="/series.php" value="<?= sf_admin_h($seoRow['canonical_path']??'') ?>"></label><label>Social Image<?= sf_admin_asset_select('social_image_asset_id',$assets,$seoRow['social_image_asset_id']??'','image') ?></label><label><input type="checkbox" name="robots_noindex" value="1"<?= !empty($seoRow['robots_noindex'])?' checked':'' ?>> Keep this record out of search engines</label><div class="sf-admin-form-actions"><button type="submit">Save SEO Metadata</button></div></form></article></section>
<section class="sf-admin-two-col sf-admin-two-col-wide"><article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Controlled Launch</span><h2>Publication batches</h2></div></div><form class="sf-admin-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="publish_ready"><label>Confirmation<input name="confirmation" autocomplete="off" placeholder="Type PUBLISH"></label><p class="sf-admin-copy">Only records currently scoring 100% are changed. Every before/after state is recorded for rollback.</p><button type="submit" onclick="return confirm('Publish every currently ready catalog item?')">Publish Ready Items</button></form><hr><form class="sf-admin-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="scan_samples"><button type="submit">Scan for Sample Content</button></form><form class="sf-admin-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="archive_samples"><label>Confirmation<input name="confirmation" autocomplete="off" placeholder="Type ARCHIVE"></label><button type="submit" onclick="return confirm('Archive open sample flags at 90% confidence or higher?')">Archive High-Confidence Samples</button></form></article><article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Recovery</span><h2>Recent reversible batches</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Batch</th><th>Action</th><th>Status</th><th>Items</th><th>Rollback</th></tr></thead><tbody><?php foreach($batches as$b): ?><tr><td>#<?= (int)$b['id'] ?><small><?= sf_admin_h($b['created_at']) ?></small></td><td><?= sf_admin_h($b['action_type']) ?></td><td><?= sf_admin_status_badge((string)$b['batch_status']) ?></td><td><?= (int)$b['success_count'] ?>/<?= (int)$b['item_count'] ?></td><td><?php if(!in_array($b['batch_status'],['rolled_back','rolling_back'],true)): ?><form method="post" class="sf-inline-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="rollback"><input type="hidden" name="batch_id" value="<?= (int)$b['id'] ?>"><input name="confirmation" placeholder="ROLLBACK" size="10"><button type="submit">Rollback</button></form><?php else: ?>—<?php endif; ?></td></tr><?php endforeach; ?><?php if(!$batches): ?><tr><td colspan="5">No catalog operation batches yet.</td></tr><?php endif; ?></tbody></table></div></article></section>
<?php sf_admin_shell_end();require __DIR__.'/../includes/footer.php'; ?>
