<?php

declare(strict_types=1);
$pageTitle='Catalog Import / Export';$pageDescription='Draft-first CSV and JSON transfer for every launch catalog type.';$pageClass='membership-page admin-catalog-page';
require __DIR__.'/../includes/catalog_operations.php';
$types=sf_lco_transfer_configs();$selected=array_key_exists($_GET['type']??'',$types)?(string)$_GET['type']:array_key_first($types);$preview=null;$rows=[];
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){$selected=array_key_exists($_POST['entity_type']??'',$types)?(string)$_POST['entity_type']:$selected;try{$rows=sf_lco_parse_transfer($_FILES['catalog_file']??null,(string)($_POST['pasted_json']??''));$preview=sf_lco_transfer_preview($selected,$rows);if(($_POST['action']??'preview')==='commit'){$result=sf_lco_transfer_commit($selected,$rows,(string)($_POST['confirmation']??''));sf_admin_flash(!empty($result['ok'])?'success':'error',!empty($result['ok'])?'Import committed in reversible batch #'.(int)$result['batch_id'].'.':(string)($result['message']??'Import failed.'));if(!empty($result['ok']))sf_admin_redirect(sf_url('admin/catalog-operations.php'));}}catch(Throwable $e){sf_admin_flash('error','Transfer parsing failed: '.$e->getMessage());}}
require __DIR__.'/../includes/header.php';sf_admin_shell_start('Catalog Transfer','Import + Export','Move launch data through bounded, validated, draft-first CSV or JSON operations.','catalog-transfer');
?>
<section class="sf-admin-card-grid"><a class="sf-admin-action-card" href="<?= sf_url('admin/catalog-operations.php') ?>"><span>Readiness</span><strong>Catalog Operations</strong><small>Score imported records before launch.</small></a><a class="sf-admin-action-card" href="<?= sf_url('admin/import.php') ?>"><span>Legacy</span><strong>Content Import</strong><small>Existing specialized import workflows.</small></a><div class="sf-admin-action-card"><span>Safety</span><strong>Draft First</strong><small>Imports never publish records automatically.</small></div></section>
<section class="sf-admin-two-col sf-admin-two-col-wide"><article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Import</span><h2>CSV or JSON</h2></div></div><form class="sf-admin-form" method="post" enctype="multipart/form-data"><?= sf_csrf_field() ?><label>Catalog Type<select name="entity_type"><?php foreach($types as$t=>$cfg): ?><option value="<?= sf_admin_h($t) ?>"<?= $t===$selected?' selected':'' ?>><?= sf_admin_h($cfg['label']) ?></option><?php endforeach; ?></select></label><label>CSV or JSON File<input type="file" name="catalog_file" accept=".csv,.json,text/csv,application/json"></label><label>Or Paste JSON<textarea name="pasted_json" rows="10" maxlength="2097152"><?= sf_admin_h((string)($_POST['pasted_json']??'')) ?></textarea></label><label>Commit Confirmation<input name="confirmation" placeholder="Type IMPORT" autocomplete="off"></label><p class="sf-admin-copy">Maximum 2 MB and 1,000 rows. Unknown columns are ignored. Status is forced to draft or inactive unless reviewed later.</p><div class="sf-admin-form-actions"><button name="action" value="preview">Preview</button><button name="action" value="commit" onclick="return confirm('Commit this validated draft-first import?')">Commit Import</button></div></form></article><article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Export</span><h2>Catalog backups</h2></div></div><div class="sf-admin-list"><?php foreach($types as$t=>$cfg): ?><div class="sf-admin-list-row"><strong><?= sf_admin_h($cfg['label']) ?></strong><span><a href="<?= sf_url('api/catalog-export.php?type='.urlencode($t)) ?>">Download CSV</a></span></div><?php endforeach; ?></div></article></section>
<?php if($preview): ?><section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Preview</span><h2><?= count($preview['rows']??[]) ?> rows · <?= (int)($preview['errors']??0) ?> errors</h2></div><small><?= sf_admin_h(substr((string)($preview['digest']??''),0,16)) ?>…</small></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Row</th><th>Status</th><th>Payload</th><th>Errors</th></tr></thead><tbody><?php foreach($preview['rows']??[] as$r): ?><tr><td>#<?= (int)$r['row_number'] ?></td><td><?= !empty($r['ok'])?'Ready':'Fix' ?></td><td><pre class="sf-admin-table-pre"><?= sf_admin_h(sf_lco_json($r['payload'])) ?></pre></td><td><?= sf_admin_h(implode('; ',$r['errors'])) ?></td></tr><?php endforeach; ?></tbody></table></div></section><?php endif; ?>
<?php sf_admin_shell_end();require __DIR__.'/../includes/footer.php'; ?>
