<?php
$pageTitle='Content Import';$pageDescription='Preview and commit bounded, draft-first CSV/JSON imports for Stonefellow content records.';$pageClass='membership-page admin-catalog-page';
require __DIR__.'/../includes/importer.php';
$types=sf_importer_types();$selectedType=array_key_exists($_GET['type']??'',$types)?(string)$_GET['type']:array_key_first($types);$preview=null;$rawRows=[];
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
  $action=(string)($_POST['action']??'preview');$selectedType=array_key_exists($_POST['import_type']??'',$types)?(string)$_POST['import_type']:$selectedType;
  if(!sf_importer_tables_ready()){sf_admin_flash('warning','Import tables are not ready. Run migration 011.');sf_admin_redirect(sf_url('admin/import.php?type='.urlencode($selectedType)));}
  try{$rawRows=sf_importer_parse_payload($_FILES['import_file']??null,(string)($_POST['pasted_json']??''));if(!$rawRows){sf_admin_flash('error','No import rows were found.');sf_admin_redirect(sf_url('admin/import.php?type='.urlencode($selectedType)));}$preview=sf_importer_preview($selectedType,$rawRows);
    if($action==='commit'){if(!hash_equals('IMPORT',strtoupper(trim((string)($_POST['confirm_import']??'')))))sf_admin_flash('error','Type IMPORT exactly before committing.');elseif(!$preview['ok'])sf_admin_flash('error','Import has validation errors. Fix the rows before committing.');else{$source=trim((string)($_FILES['import_file']['name']??''))?:'pasted-json';$result=sf_importer_run($selectedType,$rawRows,$source);sf_admin_flash(!empty($result['ok'])?'success':'error',($result['message']??'Import completed.').(!empty($result['batch_id'])?' Batch #'.(int)$result['batch_id'].'.':''));if(!empty($result['ok']))sf_admin_redirect(sf_url('admin/seed-manager.php'));}}
  }catch(Throwable $e){error_log('Stonefellow import parse failed: '.$e->getMessage());sf_admin_flash('error','Import could not be parsed or exceeded a safety limit.');}
}
$samples=sf_importer_sample_rows($selectedType);require __DIR__.'/../includes/header.php';sf_admin_shell_start('Content Import','Import CSV or JSON content','Preview and validate bounded rows, then commit every content change in one transaction.','import');
?>
<section class="sf-admin-card-grid"><a class="sf-admin-action-card" href="<?= sf_url('admin/seed-manager.php') ?>"><span>Seeds</span><strong>Seed Manager</strong><small>Review batches and rollbacks.</small></a><a class="sf-admin-action-card" href="<?= sf_url('admin/demo-content.php') ?>"><span>Samples</span><strong>Demo Content</strong><small>View starter JSON examples.</small></a><div class="sf-admin-action-card"><span>Safety</span><strong>Draft First</strong><small>Imported content does not become public automatically.</small></div></section>
<section class="sf-admin-two-col sf-admin-two-col-wide"><article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Upload + Preview</span><h2><?= sf_admin_h($types[$selectedType]??'Import') ?></h2></div></div><form class="sf-admin-form" method="post" enctype="multipart/form-data"><?= sf_csrf_field() ?><label>Import Type<select name="import_type"><?php foreach($types as $type=>$label): ?><option value="<?= sf_admin_h($type) ?>" <?= $type===$selectedType?'selected':'' ?>><?= sf_admin_h($label) ?></option><?php endforeach; ?></select></label><label>CSV or JSON File<input type="file" name="import_file" accept=".csv,.json,text/csv,application/json"></label><label>Or Paste JSON Rows<textarea name="pasted_json" rows="10" maxlength="2097152" placeholder='[{"title":"The Road Is Calling","slug":"the-road-is-calling"}]'><?= sf_admin_h((string)($_POST['pasted_json']??'')) ?></textarea></label><label>Commit Confirmation<input name="confirm_import" autocomplete="off" placeholder="Type IMPORT to commit" value="<?= sf_admin_h((string)($_POST['confirm_import']??'')) ?>"></label><p class="sf-admin-copy">Maximum defaults: 2 MB, 500 rows, 100 columns. File type and MIME are validated. Every commit is atomic.</p><div class="sf-admin-form-actions"><button type="submit" name="action" value="preview">Preview Import</button><button type="submit" name="action" value="commit" onclick="return confirm('Commit this validated import as one transaction?')">Commit Import</button></div></form></article><article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Sample</span><h2>Starter row</h2></div></div><pre class="sf-admin-code"><code><?= sf_admin_h(json_encode($samples,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)) ?></code></pre><p class="sf-admin-copy">CSV headers use the same field names as JSON keys. Status defaults are draft or inactive.</p></article></section>
<?php if($preview): ?><section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Preview Result</span><h2><?= (int)$preview['total'] ?> rows / <?= (int)$preview['errors'] ?> errors</h2></div><small>Digest <?= sf_admin_h(substr((string)($preview['digest']??''),0,16)) ?>…</small></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Row</th><th>Status</th><th>Unique Key</th><th>Payload</th><th>Errors</th></tr></thead><tbody><?php foreach($preview['rows'] as $item): ?><tr><td>#<?= (int)$item['row_number'] ?></td><td><?= !empty($item['ok'])?'<span class="sf-admin-status sf-admin-status-published">Ready</span>':'<span class="sf-admin-status sf-admin-status-draft">Fix</span>' ?></td><td><small><?= sf_admin_h($item['unique_key']??'') ?></small></td><td><pre class="sf-admin-table-pre"><?= sf_admin_h(json_encode($item['payload']??[],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)) ?></pre></td><td><?= sf_admin_h(implode('; ',$item['errors']??[])) ?></td></tr><?php endforeach; ?></tbody></table></div></section><?php endif; ?>
<?php sf_admin_shell_end();require __DIR__.'/../includes/footer.php'; ?>
