<?php
$pageTitle = 'Incidents & Alerts';
$pageDescription = 'Stonefellow incident response center for alerts, severity workflow, notification routing, and incident event history.';
$pageClass = 'membership-page admin-catalog-page';
require __DIR__ . '/../includes/admin_catalog.php';
require_once __DIR__ . '/../includes/monitoring_alerts.php';
sf_sec_require('admin.ops.manage');
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST') {
  $action=(string)($_POST['action']??'');
  if($action==='create_incident'){ $id=sf_mon_create_incident((string)($_POST['title']??''),(string)($_POST['summary']??''),(string)($_POST['severity']??'medium'),'manual'); sf_admin_flash($id?'success':'error',$id?'Incident opened and alerts routed.':'Incident was not created.'); sf_admin_redirect($id?sf_url('admin/incidents.php?incident_id='.$id):null); }
  if($action==='update_incident'){ sf_mon_update_incident((int)($_POST['incident_id']??0),(string)($_POST['status']??'investigating'),(string)($_POST['severity']??''),(string)($_POST['resolution_notes']??'')); sf_admin_flash('success','Incident updated.'); }
  if($action==='event'){ sf_mon_incident_event((int)($_POST['incident_id']??0),(string)($_POST['event_type']??'manual_update'),(string)($_POST['event_status']??'info'),(string)($_POST['message']??'')); sf_admin_flash('success','Incident event added.'); }
  if($action==='route_alert'){ $r=sf_mon_route_alert((int)($_POST['incident_id']??0)); sf_admin_flash('success','Alerts routed: '.(int)$r['created'].' created, '.(int)$r['sent'].' sent.'); }
  if($action==='mark_alert'){ sf_mon_mark_alert((int)($_POST['alert_id']??0),(string)($_POST['status']??'read')); sf_admin_flash('success','Alert updated.'); }
  sf_admin_redirect(sf_url('admin/incidents.php'.(!empty($_POST['incident_id'])?'?incident_id='.(int)$_POST['incident_id']:'')));
}
require __DIR__ . '/../includes/header.php';
$summary=sf_mon_summary();
$incidents=sf_mon_incidents(150);
$alerts=sf_mon_alerts(150);
$rules=sf_mon_rules();
$selectedId=(int)($_GET['incident_id']??($incidents[0]['id']??0));
$selected=$selectedId?sf_mon_incident($selectedId):null;
$events=$selectedId?sf_mon_incident_events($selectedId):[];
sf_admin_shell_start('Incidents & Alerts', 'Incident response v1', 'Track incident severity, status workflow, admin alerts, alert rules, event history, and operational response after failed checks.', 'incidents');
?>
<section class="sf-admin-card-grid">
  <div class="sf-admin-action-card"><span>Open</span><strong><?= (int)$summary['open_incidents'] ?></strong><small>Active incidents.</small></div>
  <div class="sf-admin-action-card"><span>Critical</span><strong><?= (int)$summary['critical_incidents'] ?></strong><small>Immediate attention.</small></div>
  <div class="sf-admin-action-card"><span>Queued Alerts</span><strong><?= (int)$summary['alerts_queued'] ?></strong><small>Dashboard/email/in-app alerts.</small></div>
  <div class="sf-admin-action-card"><span>Rules</span><strong><?= count($rules) ?></strong><small>Alert routing rules.</small></div>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/monitoring.php') ?>"><span>Monitoring</span><strong>Dashboard</strong><small>Health and errors.</small></a>
</section>
<section class="sf-admin-two-col sf-admin-two-col-wide">
  <article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Incidents</span><h2><?= count($incidents) ?> records</h2></div><a href="<?= sf_url('api/incidents.php') ?>">JSON API</a></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Incident</th><th>Severity</th><th>Status</th><th>Source</th><th>Detected</th></tr></thead><tbody><?php foreach($incidents as $inc): ?><tr><td><strong><a href="<?= sf_url('admin/incidents.php?incident_id='.(int)$inc['id']) ?>"><?= sf_admin_h($inc['title']) ?></a></strong><small><?= sf_admin_h($inc['incident_key']) ?></small></td><td><?= sf_admin_status_badge($inc['severity']) ?></td><td><?= sf_admin_h($inc['status']) ?></td><td><?= sf_admin_h($inc['source']) ?></td><td><?= sf_admin_h($inc['detected_at']) ?></td></tr><?php endforeach; ?><?php if(!$incidents): ?><tr><td colspan="5">No incidents yet.</td></tr><?php endif; ?></tbody></table></div></article>
  <aside class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow"><?= $selected?'Selected':'Create' ?></span><h2><?= $selected?sf_admin_h($selected['title']):'Manual incident' ?></h2></div></div><?php if($selected): ?><div class="sf-admin-detail-list"><div><span>Key</span><strong><?= sf_admin_h($selected['incident_key']) ?></strong></div><div><span>Status</span><strong><?= sf_admin_h($selected['status']) ?></strong></div><div><span>Severity</span><strong><?= sf_admin_h($selected['severity']) ?></strong></div><div><span>Detected</span><strong><?= sf_admin_h($selected['detected_at']) ?></strong></div></div><form class="sf-admin-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="update_incident"><input type="hidden" name="incident_id" value="<?= (int)$selected['id'] ?>"><div class="sf-admin-form-grid"><label>Status<?= sf_admin_select('status',['open'=>'Open','investigating'=>'Investigating','monitoring'=>'Monitoring','resolved'=>'Resolved','closed'=>'Closed'],$selected['status']) ?></label><label>Severity<?= sf_admin_select('severity',['low'=>'Low','medium'=>'Medium','high'=>'High','critical'=>'Critical'],$selected['severity']) ?></label></div><label>Resolution Notes<textarea name="resolution_notes" rows="4"<?= sf_admin_form_disabled_attr() ?>><?= sf_admin_h($selected['resolution_notes']??'') ?></textarea></label><div class="sf-admin-form-actions"><button type="submit"<?= sf_admin_form_disabled_attr() ?>>Update Incident</button></div></form><form class="sf-admin-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="route_alert"><input type="hidden" name="incident_id" value="<?= (int)$selected['id'] ?>"><div class="sf-admin-form-actions"><button type="submit"<?= sf_admin_form_disabled_attr() ?>>Route Admin Alert</button></div></form><?php endif; ?><form class="sf-admin-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="create_incident"><label>Title<input name="title" required<?= sf_admin_form_disabled_attr() ?>></label><label>Severity<?= sf_admin_select('severity',['low'=>'Low','medium'=>'Medium','high'=>'High','critical'=>'Critical'],'medium') ?></label><label>Summary<textarea name="summary" rows="4"<?= sf_admin_form_disabled_attr() ?>></textarea></label><div class="sf-admin-form-actions"><button type="submit"<?= sf_admin_form_disabled_attr() ?>>Create Incident</button></div></form></aside>
</section>
<?php if($selected): ?><section class="sf-admin-two-col sf-admin-two-col-wide"><article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Incident Timeline</span><h2><?= count($events) ?> events</h2></div></div><div class="sf-admin-list"><?php foreach($events as $ev): ?><article class="sf-admin-list-row"><strong><?= sf_admin_h($ev['event_type']) ?></strong><span><?= sf_admin_h($ev['event_status']) ?> · <?= sf_admin_h($ev['created_at']) ?> · <?= sf_admin_h($ev['display_name'] ?: $ev['email'] ?: 'System') ?></span><p><?= nl2br(sf_admin_h($ev['message'])) ?></p></article><?php endforeach; ?><?php if(!$events): ?><article class="sf-admin-list-row"><strong>No events yet.</strong><p>Incident events will appear here.</p></article><?php endif; ?></div></article><aside class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Add Timeline Event</span><h2>Response note</h2></div></div><form class="sf-admin-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="event"><input type="hidden" name="incident_id" value="<?= (int)$selected['id'] ?>"><div class="sf-admin-form-grid"><label>Type<input name="event_type" value="manual_update"<?= sf_admin_form_disabled_attr() ?>></label><label>Status<?= sf_admin_select('event_status',['info'=>'Info','success'=>'Success','warning'=>'Warning','error'=>'Error'],'info') ?></label></div><label>Message<textarea name="message" rows="5" required<?= sf_admin_form_disabled_attr() ?>></textarea></label><div class="sf-admin-form-actions"><button type="submit"<?= sf_admin_form_disabled_attr() ?>>Add Event</button></div></form></aside></section><?php endif; ?>
<section class="sf-admin-two-col sf-admin-two-col-wide"><article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Admin Alerts</span><h2><?= count($alerts) ?> alerts</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Alert</th><th>Recipient</th><th>Severity</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach($alerts as $alert): ?><tr><td><strong><?= sf_admin_h($alert['title']) ?></strong><small><?= sf_admin_h($alert['alert_key']) ?></small></td><td><?= sf_admin_h($alert['user_email'] ?: $alert['recipient_email']) ?></td><td><?= sf_admin_status_badge($alert['severity']) ?></td><td><?= sf_admin_h($alert['delivery_status']) ?></td><td><form method="post" class="sf-admin-inline-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="mark_alert"><input type="hidden" name="alert_id" value="<?= (int)$alert['id'] ?>"><input type="hidden" name="incident_id" value="<?= (int)($alert['incident_id']??0) ?>"><button name="status" value="read" type="submit">Read</button><button name="status" value="dismissed" type="submit">Dismiss</button></form></td></tr><?php endforeach; ?><?php if(!$alerts): ?><tr><td colspan="5">No admin alerts yet.</td></tr><?php endif; ?></tbody></table></div></article><aside class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Alert Rules</span><h2><?= count($rules) ?> rules</h2></div></div><div class="sf-admin-list"><?php foreach($rules as $rule): ?><article class="sf-admin-list-row"><strong><?= sf_admin_h($rule['rule_label']) ?></strong><span><?= sf_admin_h($rule['trigger_source']) ?> · <?= sf_admin_h($rule['min_severity']) ?> · <?= sf_admin_h($rule['status']) ?></span><p><?= sf_admin_h($rule['description']??'') ?></p></article><?php endforeach; ?><?php if(!$rules): ?><article class="sf-admin-list-row"><strong>No alert rules found.</strong><p>Run migration 020.</p></article><?php endif; ?></div></aside></section>
<?php sf_admin_shell_end(); require __DIR__ . '/../includes/footer.php'; ?>
