<?php
$pageTitle = 'Admin Foundation';
$pageDescription = 'Stonefellow admin foundation for membership tiers, revenue dashboard, personalized feed, engagement analytics, creator posts, comments, notifications, catalog, analytics, deployment, payments, publishing, activity, content ops, PWA, upload UX, library, and discovery.';
$pageClass = 'membership-page admin-catalog-page';
require __DIR__ . '/../includes/admin_catalog.php';
require __DIR__ . '/../includes/header.php';
sf_admin_shell_start('Admin Foundation', 'Operational build control', 'Manage membership tiers, revenue, personalized feed, follow system, engagement analytics, creator posts, inline comments, notifications, catalog, content ops, payments, publishing, library, search, and delivery.', 'index');
?>
<section class="sf-admin-card-grid">
  <a class="sf-admin-action-card" href="<?= sf_url('admin/tier-manager.php') ?>"><span>Tiers</span><strong>Access Packaging</strong><small>Plans, benefit matrix, access labels, upgrade paths.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/revenue-dashboard.php') ?>"><span>Revenue</span><strong>Launch Dashboard</strong><small>MRR, ARR, checkout conversion, merch, churn risk.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/engagement-analytics.php') ?>"><span>Analytics v2</span><strong>Engagement</strong><small>Feed saves, hides, follows, comments, reactions, top members.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('feed.php') ?>"><span>Personalized</span><strong>Member Feed</strong><small>Follow system, preferences, saved and hidden feed items.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/posts.php') ?>"><span>Creator</span><strong>Posts Manager</strong><small>News, updates, media-linked posts, and publish states.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/engagement.php') ?>"><span>Engagement</span><strong>Fan Dashboard</strong><small>Comments, reactions, member notifications, moderation.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/payment-gateways.php') ?>"><span>Payments</span><strong>Gateways</strong><small>Stripe/PayPal readiness and checkout production pass.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('notifications.php') ?>"><span>Member</span><strong>Notifications</strong><small>Unread/read/dismissed member notification center.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/activity-feed.php') ?>"><span>Activity</span><strong>Member Feed</strong><small>Signups, streams, saves, orders, payments, notifications.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/content-ops.php') ?>"><span>Ops</span><strong>Content Command</strong><small>Tasks, missing media, drafts, orders, notification failures.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/streaming-analytics.php') ?>"><span>Streaming</span><strong>Analytics</strong><small>Engagement, conversion, library, and revenue signals.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('library.php') ?>"><span>Library</span><strong>Member Library</strong><small>Saved, liked, watchlist, and completed content.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/search-discovery.php') ?>"><span>Discovery</span><strong>Search Index</strong><small>Search coverage and discovery diagnostics.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/music.php') ?>"><span>Catalog</span><strong>Media Dashboard</strong><small>Counts, flow, and next controls.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/qa.php') ?>"><span>QA</span><strong>Production Readiness</strong><small>Launch scoring, route checks, security checks, and content audit.</small></a>
</section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Streaming Platform Foundation</span><h2>What is now built</h2></div></div><div class="sf-admin-roadmap"><div><span>✓</span><strong>Membership Tiers / Access Packaging v2</strong><p>Clear public packages, tier manager, benefit matrix, access labels, and account upgrade path.</p></div><div><span>✓</span><strong>Launch Revenue Dashboard v1</strong><p>MRR, ARR, paid members, subscription revenue, merch revenue, checkout conversion, churn risk, and snapshots.</p></div><div><span>✓</span><strong>Feed Personalization / Follow System</strong><p>Follow creators/content types, tune preferences, save/hide feed items, and rank posts per member.</p></div><div><span>✓</span><strong>Member Engagement Analytics v2</strong><p>Track feed saves/hides, comments, reactions, follows, top content, and top engaged members.</p></div><div><span>✓</span><strong>Creator Posts / News Feed</strong><p>Public feed, post detail pages, admin post manager, media links, publish states, and APIs.</p></div><div><span>✓</span><strong>Installer + QA</strong><p>Web installer, SQL migrations, system health, route checks, security checks, and deployment runbook.</p></div></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Database Mode</span><h2>Runtime notes</h2></div><a href="<?= sf_url('docs/SQL_FILE_MAP.md') ?>">SQL Map</a></div><p class="sf-admin-copy">The installer runs the base schema plus migrations 001 through 015. Migration 015 adds membership tier packaging, benefit matrix tables, launch revenue snapshots, and checkout conversion events.</p></section>
<?php sf_admin_shell_end(); require __DIR__ . '/../includes/footer.php'; ?>
