<?php
$pageTitle = 'Admin Foundation';
$pageDescription = 'Stonefellow admin foundation for backup restore, release management, roles, permissions, security audit, automation scheduler, member messaging, lifecycle, retention, support help desk, membership tiers, revenue dashboard, personalized feed, engagement analytics, creator posts, comments, notifications, catalog, analytics, payments, publishing, activity, content ops, PWA, upload UX, library, and discovery.';
$pageClass = 'membership-page admin-catalog-page';
require __DIR__ . '/../includes/admin_catalog.php';
require __DIR__ . '/../includes/header.php';
sf_admin_shell_start('Admin Foundation', 'Operational build control', 'Manage backups, releases, deployment readiness, security, roles, permissions, audits, automation, member messaging, lifecycle, support, revenue, content, payments, publishing, library, search, and delivery.', 'index');
?>
<section class="sf-admin-card-grid">
  <a class="sf-admin-action-card" href="<?= sf_url('admin/backups.php') ?>"><span>Backup</span><strong>Restore Manager</strong><small>Backup records, readiness checks, manifests, storage coverage.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/releases.php') ?>"><span>Release</span><strong>Deploy Manager</strong><small>Release records, checklist, migration range, rollback notes.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('deploy/preflight.php') ?>"><span>Deploy</span><strong>Preflight</strong><small>Production readiness command/check output.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/security-dashboard.php') ?>"><span>Security</span><strong>Dashboard</strong><small>Roles, sessions, audit events, route protection, hardening.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/roles.php') ?>"><span>Roles</span><strong>Permissions</strong><small>Admin role matrix and user role assignments.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/audit-log.php') ?>"><span>Audit</span><strong>Event Log</strong><small>Permission denials, role changes, sensitive admin actions.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/ops-scheduler.php') ?>"><span>Automation</span><strong>Ops Scheduler</strong><small>Due jobs, lifecycle checks, SLA reminders, snapshots, reports.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/member-messaging.php') ?>"><span>Messaging</span><strong>Member Campaigns</strong><small>Segmented member notices, in-app inbox, email queue.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/member-lifecycle.php') ?>"><span>Lifecycle</span><strong>Retention Ops</strong><small>Subscriber segments, churn risk, notes, and follow-up tasks.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/support.php') ?>"><span>Support</span><strong>Help Desk</strong><small>Member tickets, replies, priority workflow, linked context.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/tier-manager.php') ?>"><span>Tiers</span><strong>Access Packaging</strong><small>Plans, benefit matrix, access labels, upgrade paths.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/revenue-dashboard.php') ?>"><span>Revenue</span><strong>Launch Dashboard</strong><small>MRR, ARR, checkout conversion, merch, churn risk.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/engagement-analytics.php') ?>"><span>Analytics v2</span><strong>Engagement</strong><small>Feed saves, hides, follows, comments, reactions, top members.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/posts.php') ?>"><span>Creator</span><strong>Posts Manager</strong><small>News, updates, media-linked posts, and publish states.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/qa.php') ?>"><span>QA</span><strong>Production Readiness</strong><small>Launch scoring, route checks, security checks, and content audit.</small></a>
</section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Streaming Platform Foundation</span><h2>What is now built</h2></div></div><div class="sf-admin-roadmap"><div><span>✓</span><strong>Production Backup / Restore Manager v1</strong><p>Backup profiles, run records, schema manifests, storage coverage, restore readiness checks, and verified-run tracking.</p></div><div><span>✓</span><strong>Deployment Release Manager v1</strong><p>Release records, deployment checklist, migration range, backup links, preflight link, release events, and rollback notes.</p></div><div><span>✓</span><strong>Admin Roles / Permissions v1</strong><p>Role matrix, module permissions, role assignments, sensitive-module helpers, and permission-aware admin security pages.</p></div><div><span>✓</span><strong>Security Hardening + Audit Log v1</strong><p>Security dashboard, audit events, permission denials, sensitive action logging, session tracking, and production hardening review.</p></div><div><span>✓</span><strong>Admin Automation / Ops Scheduler v1</strong><p>Scheduled operations, due-run controls, job history, notification dispatch, lifecycle scans, SLA reminders, revenue snapshots, and engagement refreshes.</p></div><div><span>✓</span><strong>Installer + QA</strong><p>Web installer, SQL migrations, system health, route checks, security checks, and deployment runbook.</p></div></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Database Mode</span><h2>Runtime notes</h2></div><a href="<?= sf_url('docs/SQL_FILE_MAP.md') ?>">SQL Map</a></div><p class="sf-admin-copy">The installer runs the base schema plus migrations 001 through 019. Migration 019 adds backup profiles, backup records, restore readiness checks, deployment releases, release checklist tasks, and deployment event history.</p></section>
<?php sf_admin_shell_end(); require __DIR__ . '/../includes/footer.php'; ?>
