<?php
$pageTitle = 'Admin Foundation';
$pageDescription = 'Stonefellow admin foundation for automation scheduler, member messaging, lifecycle, retention, support help desk, membership tiers, revenue dashboard, personalized feed, engagement analytics, creator posts, comments, notifications, catalog, analytics, payments, publishing, activity, content ops, PWA, upload UX, library, and discovery.';
$pageClass = 'membership-page admin-catalog-page';
require __DIR__ . '/../includes/admin_catalog.php';
require __DIR__ . '/../includes/header.php';
sf_admin_shell_start('Admin Foundation', 'Operational build control', 'Manage automation, member messaging, lifecycle, retention, support tickets, membership tiers, revenue, personalized feed, engagement analytics, creator posts, notifications, catalog, content ops, payments, publishing, library, search, and delivery.', 'index');
?>
<section class="sf-admin-card-grid">
  <a class="sf-admin-action-card" href="<?= sf_url('admin/ops-scheduler.php') ?>"><span>Automation</span><strong>Ops Scheduler</strong><small>Due jobs, lifecycle checks, SLA reminders, snapshots, reports.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/member-messaging.php') ?>"><span>Messaging</span><strong>Member Campaigns</strong><small>Segmented member notices, in-app inbox, email queue.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('messages.php') ?>"><span>Member</span><strong>Messages</strong><small>Member-facing message inbox.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/member-lifecycle.php') ?>"><span>Lifecycle</span><strong>Retention Ops</strong><small>Subscriber segments, churn risk, notes, and follow-up tasks.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/support.php') ?>"><span>Support</span><strong>Help Desk</strong><small>Member tickets, replies, priority workflow, linked context.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/tier-manager.php') ?>"><span>Tiers</span><strong>Access Packaging</strong><small>Plans, benefit matrix, access labels, upgrade paths.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/revenue-dashboard.php') ?>"><span>Revenue</span><strong>Launch Dashboard</strong><small>MRR, ARR, checkout conversion, merch, churn risk.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/engagement-analytics.php') ?>"><span>Analytics v2</span><strong>Engagement</strong><small>Feed saves, hides, follows, comments, reactions, top members.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/posts.php') ?>"><span>Creator</span><strong>Posts Manager</strong><small>News, updates, media-linked posts, and publish states.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/payment-gateways.php') ?>"><span>Payments</span><strong>Gateways</strong><small>Stripe/PayPal readiness and checkout production pass.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('notifications.php') ?>"><span>Member</span><strong>Notifications</strong><small>Unread/read/dismissed member notification center.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/activity-feed.php') ?>"><span>Activity</span><strong>Member Feed</strong><small>Signups, streams, saves, orders, payments, notifications.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/content-ops.php') ?>"><span>Ops</span><strong>Content Command</strong><small>Tasks, missing media, drafts, orders, notification failures.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('library.php') ?>"><span>Library</span><strong>Member Library</strong><small>Saved, liked, watchlist, and completed content.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/qa.php') ?>"><span>QA</span><strong>Production Readiness</strong><small>Launch scoring, route checks, security checks, and content audit.</small></a>
</section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Streaming Platform Foundation</span><h2>What is now built</h2></div></div><div class="sf-admin-roadmap"><div><span>✓</span><strong>Admin Automation / Ops Scheduler v1</strong><p>Scheduled operations, due-run controls, job history, notification dispatch, lifecycle scans, SLA reminders, revenue snapshots, and engagement refreshes.</p></div><div><span>✓</span><strong>Member Messaging + Campaign Broadcasts v1</strong><p>Segmented member notices, message composer, in-app inbox, email queue integration, recipient tracking, and campaign history.</p></div><div><span>✓</span><strong>Admin Member Lifecycle / Retention v1</strong><p>Subscriber segments, churn-risk lists, lifecycle notes, retention tasks, and admin follow-up workflow.</p></div><div><span>✓</span><strong>Customer Support + Help Desk v1</strong><p>Member support center, admin inbox, ticket statuses, replies, priorities, and member-linked context.</p></div><div><span>✓</span><strong>Membership Tiers / Access Packaging v2</strong><p>Clear public packages, tier manager, benefit matrix, access labels, and account upgrade path.</p></div><div><span>✓</span><strong>Installer + QA</strong><p>Web installer, SQL migrations, system health, route checks, security checks, and deployment runbook.</p></div></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Database Mode</span><h2>Runtime notes</h2></div><a href="<?= sf_url('docs/SQL_FILE_MAP.md') ?>">SQL Map</a></div><p class="sf-admin-copy">The installer runs the base schema plus migrations 001 through 017. Migration 017 adds ops scheduled jobs, job runs, member message threads, member messages, message campaigns, and recipient tracking.</p></section>
<?php sf_admin_shell_end(); require __DIR__ . '/../includes/footer.php'; ?>
