<?php

declare(strict_types=1);

$pageTitle='Media Pipeline';
$pageDescription='Protected storage, resumable ingestion, processing jobs, HLS delivery, waveform generation, CDN readiness, and media health.';
$pageClass='membership-page admin-catalog-page media-pipeline-page';
require_once __DIR__.'/../includes/admin_catalog.php';
require_once __DIR__.'/../includes/media_pipeline.php';

if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!sf_verify_csrf($_POST['csrf_token']??null)){sf_admin_flash('error','Security check failed.');sf_admin_redirect();}
    $action=(string)($_POST['action']??'');
    if($action==='enqueue_job'){
        $objectId=sf_admin_int($_POST['object_id']??null,0)??0;$jobType=trim((string)($_POST['job_type']??''));$result=sf_mp_enqueue_job($objectId,$jobType,50);
        sf_admin_flash(!empty($result['ok'])?'success':'error',!empty($result['ok'])?'Processing job queued.':'Processing job could not be queued: '.($result['error']??'unknown error'));
    }elseif($action==='retry_job'){
        $jobId=sf_admin_int($_POST['job_id']??null,0)??0;
        $ok=$jobId>0&&sf_admin_execute("UPDATE media_processing_jobs SET status='retry',run_after=NOW(),locked_until=NULL,lock_token=NULL,error_message=NULL WHERE id=? AND status='failed'",[$jobId]);
        sf_admin_flash($ok?'success':'error',$ok?'Failed job returned to the queue.':'Job could not be retried.');
    }elseif($action==='set_primary'){
        $ok=sf_mp_set_primary(sf_admin_int($_POST['object_id']??null,0)??0);sf_admin_flash($ok?'success':'error',$ok?'Primary media object updated.':'Object could not be updated.');
    }elseif($action==='delete_object'){
        $objectId=sf_admin_int($_POST['object_id']??null,0)??0;$confirmation=trim((string)($_POST['confirmation']??''));$object=sf_mp_object_by_id($objectId);
        $ok=$object&&hash_equals((string)$object['object_key'],$confirmation)&&sf_mp_mark_object($objectId,'deleted',['deleted_by'=>sf_current_user_id()]);
        sf_admin_flash($ok?'success':'error',$ok?'Media object retired from delivery.':'Enter the exact object key to retire it.');
    }elseif($action==='expire_sessions'){
        $count=sf_mp_expire_upload_sessions(1000);sf_admin_flash('success',$count.' expired upload session(s) cleaned.');
    }elseif($action==='run_health'){
        $result=sf_mp_run_storage_health_check();sf_admin_flash(!empty($result['ok'])?'success':'error','Storage health: '.($result['status']??$result['error']??'unknown').'.');
    }
    sf_admin_redirect(sf_url('admin/media-pipeline.php'));
}

$provider=sf_mp_provider_summary();$usage=sf_mp_storage_usage_summary();$queue=sf_mp_queue_summary();$delivery=sf_mp_delivery_summary();
$objects=sf_admin_table_exists('media_objects')?sf_admin_fetch_all('SELECT mo.*,msp.driver,msp.provider_key FROM media_objects mo JOIN media_storage_providers msp ON msp.id=mo.provider_id ORDER BY mo.id DESC LIMIT 100'):[];
$jobs=sf_admin_table_exists('media_processing_jobs')?sf_admin_fetch_all('SELECT mpj.*,mo.entity_type,mo.entity_id,mo.role FROM media_processing_jobs mpj JOIN media_objects mo ON mo.id=mpj.object_id ORDER BY mpj.id DESC LIMIT 100'):[];
$uploads=sf_admin_table_exists('media_upload_sessions')?sf_admin_fetch_all('SELECT * FROM media_upload_sessions ORDER BY id DESC LIMIT 50'):[];
$health=sf_admin_table_exists('media_storage_health_runs')?sf_admin_fetch_all('SELECT msh.*,msp.provider_key FROM media_storage_health_runs msh JOIN media_storage_providers msp ON msp.id=msh.provider_id ORDER BY msh.id DESC LIMIT 20'):[];
$songs=sf_admin_songs();$videos=sf_admin_videos();$csrf=sf_csrf_token();
require __DIR__.'/../includes/header.php';
sf_admin_shell_start('Secure Media','Protected Media Storage, CDN & Transcoding','Upload protected masters, create previews and waveforms, package adaptive HLS video, monitor storage, and audit member delivery.','media-pipeline');
?>
<style>
.mp-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px}.mp-card{padding:18px;border:1px solid rgba(255,255,255,.1);border-radius:18px;background:rgba(255,255,255,.035)}.mp-card strong{display:block;font-size:26px;margin:7px 0}.mp-muted{color:rgba(255,255,255,.65);line-height:1.5}.mp-progress{height:9px;border-radius:99px;background:rgba(255,255,255,.1);overflow:hidden}.mp-progress span{display:block;height:100%;background:currentColor}.mp-upload-status{white-space:pre-wrap;padding:12px;border-radius:12px;background:rgba(255,255,255,.04);min-height:44px}.mp-actions{display:flex;gap:8px;flex-wrap:wrap}.mp-actions form{display:flex;gap:6px;align-items:center;margin:0}.mp-code{font-family:ui-monospace,monospace;font-size:12px;word-break:break-all}@media(max-width:1050px){.mp-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.mp-grid{grid-template-columns:1fr}}
</style>
<section class="mp-grid">
 <article class="mp-card"><span class="sf-panel-eyebrow">Storage</span><strong><?= sf_admin_h(strtoupper((string)$provider['driver'])) ?></strong><small class="mp-muted"><?= !empty($provider['storage_ready'])?'Provider ready':'Provider configuration incomplete' ?></small></article>
 <article class="mp-card"><span class="sf-panel-eyebrow">Objects</span><strong><?= number_format((int)($usage['objects']??0)) ?></strong><small class="mp-muted"><?= sf_admin_format_bytes((int)($usage['bytes']??0)) ?> registered</small></article>
 <article class="mp-card"><span class="sf-panel-eyebrow">Processing</span><strong><?= number_format((int)(($queue['queued']??0)+($queue['retry']??0)+($queue['running']??0))) ?></strong><small class="mp-muted"><?= (int)($queue['failed']??0) ?> failed</small></article>
 <article class="mp-card"><span class="sf-panel-eyebrow">Delivery</span><strong><?= number_format((int)($delivery['active_sessions']??0)) ?></strong><small class="mp-muted"><?= number_format((int)($delivery['today_segments']??0)) ?> segments today</small></article>
 <article class="mp-card"><span class="sf-panel-eyebrow">Binaries</span><strong><?= !empty($provider['ffmpeg_ready'])&&!empty($provider['ffprobe_ready'])?'READY':'CHECK' ?></strong><small class="mp-muted">FFmpeg <?= !empty($provider['ffmpeg_ready'])?'yes':'no' ?> · FFprobe <?= !empty($provider['ffprobe_ready'])?'yes':'no' ?></small></article>
</section>
<section class="sf-admin-two-col sf-admin-two-col-wide">
 <article class="sf-admin-panel">
  <div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Resumable Ingestion</span><h2>Upload a protected media master</h2></div><small>Chunked, resumable, checksummed</small></div>
  <form class="sf-admin-form" id="mediaPipelineUpload">
   <div class="sf-admin-form-grid"><label>Content Type<select name="entity_type"><option value="song">Song</option><option value="video">Video</option><option value="episode">Episode</option><option value="asset">Standalone Asset</option></select></label><label>Content ID<input type="number" name="entity_id" min="1" required></label><label>Target Role<select name="target_role"><option value="original">Original Master</option><option value="poster">Poster</option><option value="thumbnail">Thumbnail</option><option value="caption">Caption</option></select></label></div>
   <label>Media File<input type="file" name="media_file" accept="audio/*,video/*,image/jpeg,image/png,image/webp,.vtt,.srt" required></label>
   <button type="submit">Start Protected Upload</button>
  </form>
  <div class="mp-progress" aria-label="Upload progress"><span id="mediaUploadBar" style="width:0%"></span></div><pre id="mediaUploadStatus" class="mp-upload-status">Choose a song, video, or asset master to begin.</pre>
 </article>
 <article class="sf-admin-panel">
  <div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Operations</span><h2>Storage and queue controls</h2></div></div>
  <div class="mp-actions"><form method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="run_health"><button>Run Storage Health</button></form><form method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="expire_sessions"><button>Clean Expired Uploads</button></form><a href="<?= sf_url('admin/media-delivery.php') ?>">Delivery Diagnostics</a></div>
  <div class="sf-admin-detail-list"><div><span>Mode</span><strong><?= sf_admin_h((string)$provider['mode']) ?></strong></div><div><span>Schema</span><strong><?= !empty($provider['schema_ready'])?'Installed':'Missing: '.sf_admin_h(implode(', ',$provider['missing_tables']??[])) ?></strong></div><div><span>Worker</span><strong class="mp-code">POST /api/media-processing-worker.php</strong></div><div><span>Security</span><strong>Timestamped HMAC worker requests</strong></div></div>
 </article>
</section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Media Objects</span><h2><?= count($objects) ?> recent objects</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Object</th><th>Entity</th><th>Role</th><th>Provider</th><th>Size</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($objects as $object): ?><tr><td><strong>#<?= (int)$object['id'] ?></strong><small class="mp-code"><?= sf_admin_h($object['object_key']) ?></small></td><td><?= sf_admin_h($object['entity_type'].' #'.$object['entity_id']) ?></td><td><?= sf_admin_h($object['role']) ?><?= !empty($object['is_primary'])?' · primary':'' ?></td><td><?= sf_admin_h($object['provider_key'].' / '.$object['driver']) ?></td><td><?= sf_admin_format_bytes((int)$object['size_bytes']) ?></td><td><?= sf_admin_status_badge((string)$object['status']) ?></td><td><div class="mp-actions"><?php if(($object['status']??'')!=='deleted'): ?><form method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="set_primary"><input type="hidden" name="object_id" value="<?= (int)$object['id'] ?>"><button>Primary</button></form><form method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="enqueue_job"><input type="hidden" name="object_id" value="<?= (int)$object['id'] ?>"><select name="job_type"><?php foreach(array_keys(sf_mp_job_catalog()) as $jobType): ?><option value="<?= sf_admin_h($jobType) ?>"><?= sf_admin_h($jobType) ?></option><?php endforeach; ?></select><button>Queue</button></form><?php endif; ?></div></td></tr><?php endforeach; ?><?php if(!$objects): ?><tr><td colspan="7">No media objects yet. Import migration 023 and upload a master.</td></tr><?php endif; ?></tbody></table></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Processing Queue</span><h2><?= count($jobs) ?> recent jobs</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Job</th><th>Object</th><th>Type</th><th>Progress</th><th>Attempts</th><th>Status</th><th>Error</th><th></th></tr></thead><tbody><?php foreach($jobs as $job): ?><tr><td><strong>#<?= (int)$job['id'] ?></strong><small class="mp-code"><?= sf_admin_h($job['job_key']) ?></small></td><td><?= sf_admin_h($job['entity_type'].' #'.$job['entity_id'].' · '.$job['role']) ?></td><td><?= sf_admin_h($job['job_type']) ?></td><td><?= (int)$job['progress_percent'] ?>%</td><td><?= (int)$job['attempts'] ?>/<?= (int)$job['max_attempts'] ?></td><td><?= sf_admin_status_badge((string)$job['status']) ?></td><td><?= sf_admin_h($job['error_message']??'—') ?></td><td><?php if(($job['status']??'')==='failed'): ?><form method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="retry_job"><input type="hidden" name="job_id" value="<?= (int)$job['id'] ?>"><button>Retry</button></form><?php endif; ?></td></tr><?php endforeach; ?><?php if(!$jobs): ?><tr><td colspan="8">No processing jobs yet.</td></tr><?php endif; ?></tbody></table></div></section>
<section class="sf-admin-two-col sf-admin-two-col-wide"><article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Upload Sessions</span><h2>Recent ingestion</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>File</th><th>Entity</th><th>Chunks</th><th>Bytes</th><th>Status</th></tr></thead><tbody><?php foreach($uploads as $upload): ?><tr><td><strong><?= sf_admin_h($upload['original_filename']) ?></strong></td><td><?= sf_admin_h($upload['entity_type'].' #'.$upload['entity_id']) ?></td><td><?= (int)$upload['received_chunks'] ?>/<?= (int)$upload['expected_chunks'] ?></td><td><?= sf_admin_format_bytes((int)$upload['received_size_bytes']) ?> / <?= sf_admin_format_bytes((int)$upload['expected_size_bytes']) ?></td><td><?= sf_admin_status_badge((string)$upload['status']) ?></td></tr><?php endforeach; ?><?php if(!$uploads): ?><tr><td colspan="5">No upload sessions yet.</td></tr><?php endif; ?></tbody></table></div></article><article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Provider Health</span><h2>Read/write/delete evidence</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Provider</th><th>Status</th><th>R/W/D</th><th>Latency</th><th>Completed</th></tr></thead><tbody><?php foreach($health as $run): ?><tr><td><?= sf_admin_h($run['provider_key']) ?></td><td><?= sf_admin_status_badge((string)$run['status']) ?></td><td><?= sf_admin_h($run['read_test_status'].' / '.$run['write_test_status'].' / '.$run['delete_test_status']) ?></td><td><?= (int)$run['latency_ms'] ?> ms</td><td><?= sf_admin_h($run['completed_at']??'—') ?></td></tr><?php endforeach; ?><?php if(!$health): ?><tr><td colspan="5">No health run recorded.</td></tr><?php endif; ?></tbody></table></div></article></section>
<script>
(()=>{const form=document.getElementById('mediaPipelineUpload');if(!form)return;const status=document.getElementById('mediaUploadStatus');const bar=document.getElementById('mediaUploadBar');const csrf=<?= json_encode($csrf) ?>;const sha=async blob=>{const buf=await blob.arrayBuffer();const hash=await crypto.subtle.digest('SHA-256',buf);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')};form.addEventListener('submit',async e=>{e.preventDefault();const file=form.media_file.files[0];if(!file)return;try{status.textContent='Creating protected upload session…';const init=await fetch(<?= json_encode(sf_url('api/media-upload-init.php')) ?>,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csrf_token:csrf,entity_type:form.entity_type.value,entity_id:Number(form.entity_id.value),target_role:form.target_role.value,filename:file.name,mime_type:file.type||'application/octet-stream',size_bytes:file.size})}).then(r=>r.json());if(!init.ok)throw new Error(init.error||'Session failed');for(let part=0;part<init.expected_chunks;part++){const start=part*init.chunk_size_bytes,end=Math.min(file.size,start+init.chunk_size_bytes),chunk=file.slice(start,end),digest=await sha(chunk);status.textContent=`Uploading chunk ${part+1} of ${init.expected_chunks}…`;const response=await fetch(<?= json_encode(sf_url('api/media-upload-chunk.php')) ?>+`?session=${encodeURIComponent(init.session_token)}&part=${part}`,{method:'PUT',headers:{'X-Stonefellow-CSRF':csrf,'X-Chunk-SHA256':digest,'Content-Type':'application/octet-stream'},body:chunk}).then(r=>r.json());if(!response.ok)throw new Error(response.error||'Chunk failed');bar.style.width=Math.round(((part+1)/init.expected_chunks)*90)+'%'}status.textContent='Verifying checksum, registering master, and creating processing jobs…';const complete=await fetch(<?= json_encode(sf_url('api/media-upload-complete.php')) ?>,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csrf_token:csrf,session_token:init.session_token})}).then(r=>r.json());if(!complete.ok)throw new Error(complete.error||'Completion failed');bar.style.width='100%';status.textContent=`Upload complete. Media object #${complete.object_id}. Jobs: ${(complete.queued_jobs||[]).join(', ')||'none'}.`;setTimeout(()=>location.reload(),1500)}catch(error){status.textContent='Upload failed: '+error.message;bar.style.width='0%'}})})();
</script>
<?php sf_admin_shell_end();require __DIR__.'/../includes/footer.php'; ?>
