<?php
$pageTitle = 'Member Lifecycle';
$pageDescription = 'Manage Stonefellow member lifecycle, subscriber health, retention tasks, churn risk, and admin follow-up notes.';
$pageClass = 'membership-page admin-catalog-page';
require __DIR__ . '/../includes/admin_catalog.php';
require_once __DIR__ . '/../includes/member_lifecycle_support.php';
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST') {
  $action = $_POST['action'] ?? '';
  $userId = (int)($_POST['user_id'] ?? 0);
  if ($action === 'add_note') { sf_lifecycle_create_note($userId,(string)($_POST['note'] ?? ''),(string)($_POST['note_type'] ?? 'general')); sf_admin_flash('success','Lifecycle note saved.'); }
  if ($action === 'add_task') { sf_lifecycle_create_task($userId,(string)($_POST['title'] ?? ''),(string)($_POST['detail'] ?? ''),(string)($_POST['task_type'] ?? 'manual'),(string)($_POST['priority'] ?? 'medium'),(string)($_POST['due_at'] ?? '')); sf_admin_flash('success','Retention task created.'); }
  if ($action === 'task_status') { sf_lifecycle_update_task((int)($_POST['task_id'] ?? 0),(string)($_POST['status'] ?? 'open')); sf_admin_flash('success','Task updated.'); }
  sf_admin_redirect($userId ? sf_url('admin/member-lifecycle.php?user_id=' . $userId) : null);
}
require __DIR__ . '/../includes/header.php';
$summary = sf_lifecycle_summary();
$members = sf_lifecycle_segments();
$selectedId = (int)($_GET['user_id'] ?? ($members[0]['id'] ?? 0));
$selected = $selectedId ? sf_ops_fetch_one("SELECT u.*, sp.name plan_name, us.status subscription_status, us.current_period_end, us.cancel_at_period_end FROM users u LEFT JOIN user_subscriptions us ON us.id=(SELECT us2.id FROM user_subscriptions us2 WHERE us2.user_id=u.id ORDER BY FIELD(us2.status,'active','trialing','past_due','unpaid','canceled','expired'), us2.current_period_end DESC, us2.id DESC LIMIT 1) LEFT JOIN subscription_plans sp ON sp.id=us.plan_id WHERE u.id=? LIMIT 1",[$selectedId]) : null;
$notes = $selectedId ? sf_lifecycle_notes($selectedId,30) : [];
$tasks = $selectedId ? sf_lifecycle_tasks($selectedId,60) : [];
$allTasks = sf_lifecycle_tasks(0,80);
sf_admin_shell_start('Member Lifecycle', 'Retention operations v1', 'Segment subscribers, spot churn risk, add lifecycle notes, and create admin follow-up tasks for launch operations.', 'member-lifecycle');
?>
<section class="sf-admin-card-grid">
  <div class="sf-admin-action-card"><span>Members</span><strong><?= (int)$summary['members'] ?></strong><small><?= (int)$summary['new_signups_7d'] ?> new in 7 days.</small></div>
  <div class="sf-admin-action-card"><span>Active</span><strong><?= (int)($summary['active'] + $summary['trialing']) ?></strong><small>Active/trialing subscriptions.</small></div>
  <div class="sf-admin-action-card"><span>Churn Risk</span><strong><?= (int)$summary['churn_risk'] ?></strong><small>Past due, canceling, or ending soon.</small></div>
  <div class="sf-admin-action-card"><span>Open Tasks</span><strong><?= (int)$summary['open_tasks'] ?></strong><small>Retention follow-ups.</small></div>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/support.php') ?>"><span>Support</span><strong><?= (int)$summary['support_open'] ?></strong><small>Open help desk tickets.</small></a>
</section>
<section class="sf-admin-two-col sf-admin-two-col-wide">
  <article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Subscriber Segments</span><h2><?= count($members) ?> members</h2></div><a href="<?= sf_url('api/member-lifecycle.php') ?>">JSON API</a></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Member</th><th>Plan</th><th>Status</th><th>Period End</th><th>Ops</th></tr></thead><tbody><?php foreach($members as $m): $risk=($m['subscription_status']??'')==='past_due'||!empty($m['cancel_at_period_end'])||(!empty($m['current_period_end'])&&strtotime((string)$m['current_period_end'])<time()+864000); ?><tr><td><strong><?= sf_admin_h($m['display_name'] ?: $m['email']) ?></strong><small><?= sf_admin_h($m['email'] ?? '') ?></small></td><td><?= sf_admin_h($m['plan_name'] ?: 'Free') ?></td><td><?= $risk ? sf_admin_status_badge('warning') : sf_admin_status_badge($m['subscription_status'] ?: 'free') ?></td><td><?= sf_admin_h($m['current_period_end'] ?? '—') ?></td><td><a href="<?= sf_url('admin/member-lifecycle.php?user_id=' . (int)$m['id']) ?>">Open</a> · <?= (int)($m['open_tasks'] ?? 0) ?> tasks · <?= (int)($m['open_tickets'] ?? 0) ?> tickets</td></tr><?php endforeach; ?><?php if(!$members): ?><tr><td colspan="5">No members found yet.</td></tr><?php endif; ?></tbody></table></div></article>
  <aside class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Selected Member</span><h2><?= $selected ? sf_admin_h($selected['display_name'] ?: $selected['email']) : 'No member selected' ?></h2></div></div><?php if($selected): ?><div class="sf-admin-detail-list"><div><span>Email</span><strong><?= sf_admin_h($selected['email']) ?></strong></div><div><span>Plan</span><strong><?= sf_admin_h($selected['plan_name'] ?: 'Free') ?></strong></div><div><span>Status</span><strong><?= sf_admin_h($selected['subscription_status'] ?: $selected['status']) ?></strong></div><div><span>Last Login</span><strong><?= sf_admin_h($selected['last_login_at'] ?? '—') ?></strong></div></div><form class="sf-admin-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="add_note"><input type="hidden" name="user_id" value="<?= (int)$selectedId ?>"><label>Note Type<?= sf_admin_select('note_type',['retention'=>'Retention','billing'=>'Billing','support'=>'Support','access'=>'Access','churn_risk'=>'Churn Risk','general'=>'General'],'retention') ?></label><label>Admin Note<textarea name="note" rows="4" required<?= sf_admin_form_disabled_attr() ?>></textarea></label><div class="sf-admin-form-actions"><button type="submit"<?= sf_admin_form_disabled_attr() ?>>Save Note</button></div></form><form class="sf-admin-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="add_task"><input type="hidden" name="user_id" value="<?= (int)$selectedId ?>"><label>Task Title<input name="title" placeholder="Follow up before renewal" required<?= sf_admin_form_disabled_attr() ?>></label><div class="sf-admin-form-grid"><label>Type<?= sf_admin_select('task_type',['welcome'=>'Welcome','renewal'=>'Renewal','past_due'=>'Past Due','cancel_save'=>'Cancel Save','upgrade'=>'Upgrade','support_followup'=>'Support Follow-up','manual'=>'Manual'],'manual') ?></label><label>Priority<?= sf_admin_select('priority',['low'=>'Low','medium'=>'Medium','high'=>'High','critical'=>'Critical'],'medium') ?></label></div><label>Due At<input type="datetime-local" name="due_at"<?= sf_admin_form_disabled_attr() ?>></label><label>Detail<textarea name="detail" rows="3"<?= sf_admin_form_disabled_attr() ?>></textarea></label><div class="sf-admin-form-actions"><button type="submit"<?= sf_admin_form_disabled_attr() ?>>Create Task</button></div></form><?php endif; ?></aside>
</section>
<section class="sf-admin-two-col sf-admin-two-col-wide"><article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Member Notes</span><h2><?= count($notes) ?> notes</h2></div></div><div class="sf-admin-list"><?php foreach($notes as $note): ?><article class="sf-admin-list-row"><strong><?= sf_admin_h(ucfirst(str_replace('_',' ',(string)$note['note_type']))) ?></strong><span><?= sf_admin_h($note['created_at']) ?> · <?= sf_admin_h($note['admin_name'] ?: $note['admin_email'] ?: 'Admin') ?></span><p><?= nl2br(sf_admin_h($note['note'])) ?></p></article><?php endforeach; ?><?php if(!$notes): ?><article class="sf-admin-list-row"><strong>No notes yet.</strong><p>Create the first retention or support note.</p></article><?php endif; ?></div></article><aside class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Retention Tasks</span><h2><?= count($allTasks) ?> active/recent tasks</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Task</th><th>Member</th><th>Priority</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($allTasks as $task): ?><tr><td><strong><?= sf_admin_h($task['title']) ?></strong><small><?= sf_admin_h($task['due_at'] ?? '') ?></small></td><td><?= sf_admin_h($task['display_name'] ?: $task['email'] ?: '') ?></td><td><?= sf_admin_h($task['priority']) ?></td><td><?= sf_admin_status_badge($task['status']) ?></td><td><form method="post" class="sf-admin-inline-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="task_status"><input type="hidden" name="task_id" value="<?= (int)$task['id'] ?>"><input type="hidden" name="user_id" value="<?= (int)($task['user_id'] ?? 0) ?>"><button name="status" value="done" type="submit">Done</button><button name="status" value="dismissed" type="submit">Dismiss</button></form></td></tr><?php endforeach; ?><?php if(!$allTasks): ?><tr><td colspan="5">No retention tasks yet.</td></tr><?php endif; ?></tbody></table></div></aside></section>
<?php sf_admin_shell_end(); require __DIR__ . '/../includes/footer.php'; ?>
