<?php
$pageTitle='Member Messaging';$pageDescription='Stonefellow in-app and email member campaign console.';$pageClass='membership-page admin-catalog-page';
require __DIR__.'/../includes/admin_catalog.php';require_once __DIR__.'/../includes/ops_scheduler_messaging.php';sf_sec_require('admin.members.manage');
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
 $action=(string)($_POST['action']??'');
 if($action==='save_campaign'){$id=sf_msg_save_campaign($_POST,(int)($_POST['campaign_id']??0));sf_admin_flash($id?'success':'error',$id?'Campaign saved.':'Campaign was rejected. Confirm title, subject, body, channel, schedule, URL, and editable status.');sf_admin_redirect($id?sf_url('admin/member-messaging.php?campaign_id='.$id):null);}
 if($action==='seed_recipients'){$id=(int)($_POST['campaign_id']??0);$n=sf_msg_seed_recipients($id);sf_admin_flash($id>0?'success':'error',$id>0?$n.' recipients added to the audience snapshot.':'Campaign not found.');}
 if($action==='send_campaign'){$id=(int)($_POST['campaign_id']??0);$campaign=sf_msg_campaign($id);if(!$campaign)sf_admin_flash('error','Campaign not found.');elseif(in_array((string)$campaign['status'],['sent','archived'],true))sf_admin_flash('error','Sent or archived campaigns cannot be sent again.');else{sf_sched_execute("UPDATE member_message_campaigns SET status='queued',scheduled_at=COALESCE(scheduled_at,NOW()),updated_at=NOW() WHERE id=?",[$id]);$r=sf_msg_send_campaign($id,500);sf_admin_flash((int)$r['failed']>0?'warning':'success','Campaign delivery: '.(int)$r['sent'].' sent, '.(int)$r['failed'].' failed, '.(int)$r['skipped'].' preference-skipped.');}}
 if($action==='send_due'){$r=sf_msg_send_due(20);sf_admin_flash((int)$r['failed']>0?'warning':'success','Due campaigns: '.(int)$r['campaigns'].' campaigns, '.(int)$r['sent'].' sent, '.(int)$r['failed'].' failed, '.(int)$r['skipped'].' skipped.');}
 sf_admin_redirect(sf_url('admin/member-messaging.php'.(!empty($_POST['campaign_id'])?'?campaign_id='.(int)$_POST['campaign_id']:'')));
}
require __DIR__.'/../includes/header.php';$summary=sf_msg_summary();$campaigns=sf_msg_campaigns(120);$selectedId=(int)($_GET['campaign_id']??($campaigns[0]['id']??0));$selected=$selectedId?sf_msg_campaign($selectedId):null;$recipients=$selectedId?sf_sched_fetch_all('SELECT r.*,u.display_name FROM member_message_recipients r LEFT JOIN users u ON u.id=r.user_id WHERE r.campaign_id=? ORDER BY r.id DESC LIMIT 200',[$selectedId]):[];
sf_admin_shell_start('Member Messaging','Campaigns and member notices','Create audience snapshots, honor channel preferences, and deliver duplicate-safe in-app/email messages.','member-messaging');
?>
<section class="sf-admin-card-grid"><div class="sf-admin-action-card"><span>Campaigns</span><strong><?= (int)$summary['campaigns'] ?></strong><small><?= (int)$summary['scheduled'] ?> scheduled.</small></div><div class="sf-admin-action-card"><span>Recipients</span><strong><?= (int)$summary['recipients'] ?></strong><small>Audience snapshots.</small></div><div class="sf-admin-action-card"><span>Unread In-App</span><strong><?= (int)$summary['in_app_unread'] ?></strong><small>Member inbox notices.</small></div><a class="sf-admin-action-card" href="<?= sf_url('admin/ops-scheduler.php') ?>"><span>Automation</span><strong>Scheduler</strong><small>Queue and campaign dispatch.</small></a></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Due Delivery</span><h2>Process scheduled and queued campaigns</h2></div><small>Campaign and notification queues use separate exclusive locks.</small></div><form method="post" class="sf-admin-form" onsubmit="return confirm('Process all due campaigns now?')"><?= sf_csrf_field() ?><input type="hidden" name="action" value="send_due"><div class="sf-admin-form-actions"><button type="submit">Send Due Campaigns</button></div></form></section>
<section class="sf-admin-two-col sf-admin-two-col-wide"><article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Campaigns</span><h2><?= count($campaigns) ?> records</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Campaign</th><th>Audience</th><th>Channels</th><th>Status</th><th>Delivery</th><th>Actions</th></tr></thead><tbody><?php foreach($campaigns as $c): ?><tr><td><strong><a href="<?= sf_url('admin/member-messaging.php?campaign_id='.(int)$c['id']) ?>"><?= sf_admin_h($c['title']) ?></a></strong><small><?= sf_admin_h($c['subject']) ?></small></td><td><?= sf_admin_h($c['audience_filter']) ?><small><?= !empty($c['honors_preferences'])?'Preferences honored':'Transactional/override' ?></small></td><td><?= !empty($c['channel_email'])?'Email ':'' ?><?= !empty($c['channel_in_app'])?'In-app':'' ?></td><td><?= sf_admin_status_badge($c['status']) ?></td><td><?= (int)$c['sent_count'] ?> / <?= (int)$c['recipients'] ?></td><td><div class="sf-admin-inline-form"><?php if(in_array((string)$c['status'],['draft','scheduled','queued','paused'],true)): ?><form method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="seed_recipients"><input type="hidden" name="campaign_id" value="<?= (int)$c['id'] ?>"><button type="submit">Snapshot Audience</button></form><form method="post" onsubmit="return confirm('Queue and send this campaign now?')"><?= sf_csrf_field() ?><input type="hidden" name="action" value="send_campaign"><input type="hidden" name="campaign_id" value="<?= (int)$c['id'] ?>"><button type="submit">Send</button></form><?php endif; ?></div></td></tr><?php endforeach; ?><?php if(!$campaigns): ?><tr><td colspan="6">No campaigns yet. Run migration 017.</td></tr><?php endif; ?></tbody></table></div></article>
<aside class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow"><?= $selected?'Edit':'Create' ?></span><h2><?= $selected?sf_admin_h($selected['title']):'Member campaign' ?></h2></div></div><?php if(!$selected||in_array((string)$selected['status'],['draft','scheduled','queued','paused'],true)): ?><form class="sf-admin-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="save_campaign"><input type="hidden" name="campaign_id" value="<?= (int)($selected['id']??0) ?>"><label>Title<input name="title" maxlength="190" required value="<?= sf_admin_h($selected['title']??'') ?>"></label><label>Subject<input name="subject" maxlength="190" required value="<?= sf_admin_h($selected['subject']??'') ?>"></label><label>Message<textarea name="body" maxlength="20000" rows="7" required><?= sf_admin_h($selected['body']??'') ?></textarea></label><div class="sf-admin-form-grid"><label>Audience<?= sf_admin_select('audience_filter',['all_members'=>'All Members','active_subscribers'=>'Active Subscribers','free_members'=>'Free Members','churn_risk'=>'Churn Risk','engaged_members'=>'Engaged Members','support_open'=>'Open Support','manual'=>'Manual'],(string)($selected['audience_filter']??'all_members')) ?></label><label>Status<?= sf_admin_select('status',['draft'=>'Draft','scheduled'=>'Scheduled','queued'=>'Queued','paused'=>'Paused','archived'=>'Archived'],(string)($selected['status']??'draft')) ?></label></div><div class="sf-admin-form-grid"><label>Scheduled At<input type="datetime-local" name="scheduled_at" value="<?= !empty($selected['scheduled_at'])?sf_admin_h(str_replace(' ','T',substr((string)$selected['scheduled_at'],0,16))):'' ?>"></label><label>Action URL<input name="action_url" maxlength="255" value="<?= sf_admin_h($selected['action_url']??sf_url('messages.php')) ?>"></label></div><label class="sf-admin-check"><input type="checkbox" name="channel_email" value="1"<?= !empty($selected['channel_email'])||!$selected?' checked':'' ?>> Email</label><label class="sf-admin-check"><input type="checkbox" name="channel_in_app" value="1"<?= !empty($selected['channel_in_app'])||!$selected?' checked':'' ?>> In-app</label><label class="sf-admin-check"><input type="checkbox" name="honors_preferences" value="1"<?= !isset($selected['honors_preferences'])||!empty($selected['honors_preferences'])?' checked':'' ?>> Honor member channel preferences</label><p class="sf-admin-copy">Broad marketing audiences always honor preferences. Transactional campaigns should use a narrowly selected audience and documented purpose.</p><div class="sf-admin-form-actions"><button type="submit">Save Campaign</button></div></form><?php else: ?><p class="sf-admin-copy">This campaign is immutable because delivery has completed or it has been archived.</p><?php endif; ?></aside></section>
<?php if($selected): ?><section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Recipients</span><h2><?= count($recipients) ?> recent rows</h2></div><small>Masked addresses; per-channel IDs retained for retry integrity.</small></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Member</th><th>Status</th><th>Email Log</th><th>In-App</th><th>Sent</th><th>Error</th></tr></thead><tbody><?php foreach($recipients as $r): $email=(string)($r['email']??'');$p=explode('@',$email,2);$masked=count($p)===2?substr($p[0],0,1).'***@'.$p[1]:''; ?><tr><td><?= sf_admin_h($r['display_name']?:$masked) ?><small><?= sf_admin_h($masked) ?></small></td><td><?= sf_admin_status_badge($r['delivery_status']) ?></td><td><?= sf_admin_h((string)($r['email_log_id']??'—')) ?></td><td><?= sf_admin_h((string)($r['member_message_id']??'—')) ?></td><td><?= sf_admin_h($r['sent_at']??'—') ?></td><td><?= sf_admin_h($r['error_message']??'') ?></td></tr><?php endforeach; ?><?php if(!$recipients): ?><tr><td colspan="6">No audience snapshot yet.</td></tr><?php endif; ?></tbody></table></div></section><?php endif; ?>
<?php sf_admin_shell_end();require __DIR__.'/../includes/footer.php'; ?>
