<?php
$pageTitle = 'Member Messaging';
$pageDescription = 'Stonefellow member messaging and segmented campaign composer for email and in-app notices.';
$pageClass = 'membership-page admin-catalog-page';
require __DIR__ . '/../includes/admin_catalog.php';
require_once __DIR__ . '/../includes/ops_scheduler_messaging.php';
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST') {
  if (!sf_verify_csrf($_POST['csrf_token'] ?? null)) { sf_admin_flash('error','Security check failed.'); sf_admin_redirect(); }
  $action=(string)($_POST['action']??'');
  if($action==='save_campaign'){ $id=sf_msg_save_campaign($_POST,(int)($_POST['id']??0)); sf_admin_flash($id?'success':'error',$id?'Message campaign saved.':'Campaign was not saved. Run migration 017.'); sf_admin_redirect($id?sf_url('admin/member-messaging.php?campaign_id='.$id):null); }
  if($action==='seed_recipients'){ $count=sf_msg_seed_recipients((int)($_POST['campaign_id']??0)); sf_admin_flash('success','Recipient queue prepared: '.$count.' added/confirmed.'); }
  if($action==='send_campaign'){ $r=sf_msg_send_campaign((int)($_POST['campaign_id']??0),500); sf_admin_flash('success','Send complete: '.(int)$r['processed'].' processed, '.(int)$r['sent'].' sent, '.(int)$r['failed'].' failed.'); }
  if($action==='send_due'){ $r=sf_msg_send_due(20); sf_admin_flash('success','Due message campaigns complete: '.(int)$r['campaigns'].' campaigns, '.(int)$r['sent'].' sent.'); }
  sf_admin_redirect(sf_url('admin/member-messaging.php'));
}
require __DIR__ . '/../includes/header.php';
$summary=sf_msg_summary();
$campaigns=sf_msg_campaigns(120);
$editId=(int)($_GET['campaign_id']??0);
$edit=$editId?sf_msg_campaign($editId):null;
$recipients=$editId&&sf_sched_table_exists('member_message_recipients')?sf_sched_fetch_all('SELECT r.*, u.email, u.display_name FROM member_message_recipients r LEFT JOIN users u ON u.id=r.user_id WHERE r.campaign_id=? ORDER BY r.created_at DESC LIMIT 120',[$editId]):[];
sf_admin_shell_start('Member Messaging', 'Campaign broadcasts v1', 'Compose member notices, choose safe audience filters, create in-app messages, queue email delivery, and track message performance.', 'member-messaging');
?>
<section class="sf-admin-card-grid">
  <div class="sf-admin-action-card"><span>Campaigns</span><strong><?= (int)$summary['campaigns'] ?></strong><small><?= (int)$summary['draft'] ?> drafts · <?= (int)$summary['scheduled'] ?> scheduled.</small></div>
  <div class="sf-admin-action-card"><span>Queued</span><strong><?= (int)$summary['queued'] ?></strong><small>Ready for delivery.</small></div>
  <div class="sf-admin-action-card"><span>Sent</span><strong><?= (int)$summary['sent'] ?></strong><small>Completed campaigns.</small></div>
  <div class="sf-admin-action-card"><span>Recipients</span><strong><?= (int)$summary['recipients'] ?></strong><small>Queued/processed audience records.</small></div>
  <a class="sf-admin-action-card" href="<?= sf_url('messages.php') ?>"><span>Member</span><strong>Inbox</strong><small>Open member-facing messages.</small></a>
</section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Delivery Controls</span><h2>Due campaigns</h2></div><a href="<?= sf_url('api/member-messaging.php') ?>">JSON API</a></div><form class="sf-admin-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="send_due"><p class="sf-admin-copy">Send campaigns whose status is scheduled or queued and whose scheduled time has arrived. Delivery can create in-app messages, email logs, or both.</p><div class="sf-admin-form-actions"><button type="submit"<?= sf_msg_ready()?'':' disabled' ?>>Send Due Campaigns</button></div></form></section>
<section class="sf-admin-two-col sf-admin-two-col-wide">
  <article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Campaigns</span><h2><?= count($campaigns) ?> message campaigns</h2></div><a href="<?= sf_url('admin/member-messaging.php') ?>">New</a></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Campaign</th><th>Audience</th><th>Status</th><th>Recipients</th><th>Actions</th></tr></thead><tbody><?php foreach($campaigns as $c): ?><tr><td><strong><?= sf_admin_h($c['title']) ?></strong><small><?= sf_admin_h($c['subject']) ?></small></td><td><?= sf_admin_h(str_replace('_',' ',$c['audience_filter'])) ?></td><td><?= sf_admin_status_badge($c['status']) ?></td><td><?= (int)($c['sent_count']??0) ?> / <?= (int)($c['recipients']??0) ?></td><td><a href="<?= sf_url('admin/member-messaging.php?campaign_id='.(int)$c['id']) ?>">Edit</a><form method="post" class="sf-admin-inline-form"><?= sf_csrf_field() ?><input type="hidden" name="campaign_id" value="<?= (int)$c['id'] ?>"><button name="action" value="seed_recipients" type="submit">Queue</button><button name="action" value="send_campaign" type="submit">Send</button></form></td></tr><?php endforeach; ?><?php if(!$campaigns): ?><tr><td colspan="5">No message campaigns yet.</td></tr><?php endif; ?></tbody></table></div></article>
  <aside class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow"><?= $edit?'Edit':'Create' ?></span><h2><?= $edit?sf_admin_h($edit['title']):'Member message' ?></h2></div></div><form class="sf-admin-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="save_campaign"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><label>Title<input name="title" value="<?= sf_admin_h($edit['title']??'') ?>" required<?= sf_admin_form_disabled_attr() ?>></label><label>Subject<input name="subject" value="<?= sf_admin_h($edit['subject']??'') ?>" required<?= sf_admin_form_disabled_attr() ?>></label><label>Body<textarea name="body" rows="7" required<?= sf_admin_form_disabled_attr() ?>><?= sf_admin_h($edit['body']??'') ?></textarea></label><label>Action URL<input name="action_url" value="<?= sf_admin_h($edit['action_url']??'') ?>" placeholder="<?= sf_url('member.php') ?>"<?= sf_admin_form_disabled_attr() ?>></label><div class="sf-admin-form-grid"><label>Audience<?= sf_admin_select('audience_filter',['all_members'=>'All Members','active_subscribers'=>'Active Subscribers','free_members'=>'Free Members','churn_risk'=>'Churn Risk','engaged_members'=>'Engaged Members','support_open'=>'Open Support Tickets','manual'=>'Manual Queue'],$edit['audience_filter']??'all_members') ?></label><label>Status<?= sf_admin_select('status',['draft'=>'Draft','scheduled'=>'Scheduled','queued'=>'Queued','paused'=>'Paused','archived'=>'Archived'],$edit['status']??'draft') ?></label></div><label>Scheduled At<input type="datetime-local" name="scheduled_at" value="<?= !empty($edit['scheduled_at'])?sf_admin_h(str_replace(' ','T',substr((string)$edit['scheduled_at'],0,16))):'' ?>"<?= sf_admin_form_disabled_attr() ?>></label><label class="sf-admin-check"><input type="checkbox" name="channel_email" value="1"<?= !isset($edit['channel_email'])||!empty($edit['channel_email'])?' checked':'' ?><?= sf_admin_form_disabled_attr() ?>> Queue email notification</label><label class="sf-admin-check"><input type="checkbox" name="channel_in_app" value="1"<?= !isset($edit['channel_in_app'])||!empty($edit['channel_in_app'])?' checked':'' ?><?= sf_admin_form_disabled_attr() ?>> Create in-app message</label><label class="sf-admin-check"><input type="checkbox" name="honors_preferences" value="1"<?= !isset($edit['honors_preferences'])||!empty($edit['honors_preferences'])?' checked':'' ?><?= sf_admin_form_disabled_attr() ?>> Honor member preferences where available</label><div class="sf-admin-form-actions"><button type="submit"<?= sf_admin_form_disabled_attr() ?>>Save Campaign</button></div></form></aside>
</section>
<?php if($edit): ?><section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Recipients</span><h2><?= count($recipients) ?> recent records</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Member</th><th>Status</th><th>Email Log</th><th>Message</th><th>Sent</th></tr></thead><tbody><?php foreach($recipients as $r): ?><tr><td><strong><?= sf_admin_h($r['display_name'] ?: $r['email']) ?></strong><small><?= sf_admin_h($r['email']) ?></small></td><td><?= sf_admin_status_badge($r['delivery_status']) ?></td><td><?= (int)($r['email_log_id']??0) ?></td><td><?= (int)($r['member_message_id']??0) ?></td><td><?= sf_admin_h($r['sent_at']??'') ?></td></tr><?php endforeach; ?><?php if(!$recipients): ?><tr><td colspan="5">No recipients queued yet. Use Queue or Send.</td></tr><?php endif; ?></tbody></table></div></section><?php endif; ?>
<?php sf_admin_shell_end(); require __DIR__ . '/../includes/footer.php'; ?>
