<?php
$pageTitle = 'Monitoring';
$pageDescription = 'Stonefellow production monitoring dashboard for health snapshots, service checks, errors, failed jobs, payments, media, email, and incident creation.';
$pageClass = 'membership-page admin-catalog-page';
require __DIR__ . '/../includes/admin_catalog.php';
require_once __DIR__ . '/../includes/monitoring_alerts.php';
sf_sec_require('admin.ops.manage');
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST') {
  $action=(string)($_POST['action']??'');
  if($action==='snapshot'){ $id=sf_mon_take_snapshot(); sf_admin_flash($id?'success':'error',$id?'Monitoring snapshot recorded.':'Snapshot failed. Run migration 020.'); }
  if($action==='capture_error'){ $id=sf_mon_capture_error((string)($_POST['source']??'manual'),(string)($_POST['severity']??'error'),(string)($_POST['message']??''),['manual'=>true]); sf_admin_flash($id?'success':'error',$id?'Error event recorded.':'Error event was not recorded.'); }
  if($action==='error_status'){ sf_mon_update_error((int)($_POST['error_id']??0),(string)($_POST['status']??'triaged')); sf_admin_flash('success','Error status updated.'); }
  if($action==='open_incident'){ $id=sf_mon_create_incident((string)($_POST['title']??'Manual incident'),(string)($_POST['summary']??''),(string)($_POST['severity']??'medium'),'manual',(int)($_POST['error_id']??0)); sf_admin_flash($id?'success':'error',$id?'Incident opened and alerts routed.':'Incident was not created.'); sf_admin_redirect($id?sf_url('admin/incidents.php?incident_id='.$id):null); }
  sf_admin_redirect(sf_url('admin/monitoring.php'));
}
require __DIR__ . '/../includes/header.php';
$summary=sf_mon_summary();
$checks=sf_mon_service_checks();
$snapshots=sf_mon_snapshots(40);
$errors=sf_mon_recent_errors(100);
$metrics=sf_mon_metrics();
sf_admin_shell_start('Monitoring', 'Error log center v1', 'Track health snapshots, failed jobs, failed notifications, failed payments, service checks, application errors, and incident triggers after launch.', 'monitoring');
?>
<section class="sf-admin-card-grid">
  <div class="sf-admin-action-card"><span>Health</span><strong><?= (int)$summary['health_score'] ?>%</strong><small><?= sf_admin_h($summary['health_status']) ?></small></div>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/incidents.php') ?>"><span>Open Incidents</span><strong><?= (int)$summary['open_incidents'] ?></strong><small><?= (int)$summary['critical_incidents'] ?> critical.</small></a>
  <div class="sf-admin-action-card"><span>New Errors</span><strong><?= (int)$summary['new_errors'] ?></strong><small>Untriaged records.</small></div>
  <div class="sf-admin-action-card"><span>Critical Checks</span><strong><?= (int)$summary['checks_critical'] ?></strong><small>Service checks needing action.</small></div>
  <a class="sf-admin-action-card" href="<?= sf_url('api/monitoring.php') ?>"><span>API</span><strong>Monitoring</strong><small>JSON health and metrics.</small></a>
</section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Run Monitoring</span><h2>Health snapshot</h2></div><a href="<?= sf_url('admin/system-health.php') ?>">System Health</a></div><form class="sf-admin-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="snapshot"><p class="sf-admin-copy">Capture current system health, failed notification/job/payment counters, incident counts, and service check status. Critical health snapshots can create incidents automatically.</p><div class="sf-admin-form-actions"><button type="submit"<?= sf_mon_ready()?'':' disabled' ?>>Run Snapshot</button></div></form></section>
<section class="sf-admin-two-col sf-admin-two-col-wide"><article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Service Checks</span><h2><?= count($checks) ?> checks</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Check</th><th>Group</th><th>Status</th><th>Value</th><th>Detail</th></tr></thead><tbody><?php foreach($checks as $check): ?><tr><td><strong><?= sf_admin_h($check['check_label']) ?></strong><small><?= sf_admin_h($check['check_key']) ?></small></td><td><?= sf_admin_h($check['check_group']) ?></td><td><?= sf_admin_status_badge($check['status']) ?></td><td><?= sf_admin_h($check['last_value'] ?? '—') ?></td><td><?= sf_admin_h($check['detail'] ?? '') ?></td></tr><?php endforeach; ?><?php if(!$checks): ?><tr><td colspan="5">No service checks found. Run migration 020.</td></tr><?php endif; ?></tbody></table></div></article><aside class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">24h Metrics</span><h2>Runtime counters</h2></div></div><div class="sf-admin-detail-list"><div><span>Failed Notifications</span><strong><?= (int)$metrics['failed_notifications_24h'] ?></strong></div><div><span>Failed Jobs</span><strong><?= (int)$metrics['failed_jobs_24h'] ?></strong></div><div><span>Failed Payments</span><strong><?= (int)$metrics['failed_payments_24h'] ?></strong></div><div><span>Open Incidents</span><strong><?= (int)$metrics['open_incidents'] ?></strong></div><div><span>PHP Log Size</span><strong><?= number_format((int)$metrics['php_log_size']) ?> bytes</strong></div></div><form class="sf-admin-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="capture_error"><label>Source<?= sf_admin_select('source',['manual'=>'Manual','php'=>'PHP','application'=>'Application','database'=>'Database','payment'=>'Payment','media'=>'Media','email'=>'Email','job'=>'Job','security'=>'Security'],'manual') ?></label><label>Severity<?= sf_admin_select('severity',['info'=>'Info','notice'=>'Notice','warning'=>'Warning','error'=>'Error','critical'=>'Critical'],'error') ?></label><label>Message<textarea name="message" rows="4" required<?= sf_admin_form_disabled_attr() ?>></textarea></label><div class="sf-admin-form-actions"><button type="submit"<?= sf_admin_form_disabled_attr() ?>>Record Error</button></div></form></aside></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Error Center</span><h2><?= count($errors) ?> recent errors</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Error</th><th>Source</th><th>Severity</th><th>Status</th><th>Seen</th><th>Action</th></tr></thead><tbody><?php foreach($errors as $err): ?><tr><td><strong><?= sf_admin_h(substr((string)$err['message'],0,110)) ?></strong><small><?= sf_admin_h($err['event_key']) ?> · <?= (int)$err['occurrence_count'] ?>x</small></td><td><?= sf_admin_h($err['source']) ?></td><td><?= sf_admin_status_badge($err['severity']) ?></td><td><?= sf_admin_h($err['status']) ?></td><td><?= sf_admin_h($err['last_seen_at']) ?></td><td><form method="post" class="sf-admin-inline-form"><?= sf_csrf_field() ?><input type="hidden" name="error_id" value="<?= (int)$err['id'] ?>"><button name="action" value="error_status" type="submit">Triage</button><button name="action" value="open_incident" type="submit">Incident</button><input type="hidden" name="title" value="<?= sf_admin_h(substr((string)$err['message'],0,120)) ?>"><input type="hidden" name="summary" value="<?= sf_admin_h($err['message']) ?>"><input type="hidden" name="severity" value="<?= sf_admin_h(sf_mon_incident_severity((string)$err['severity'])) ?>"></form></td></tr><?php endforeach; ?><?php if(!$errors): ?><tr><td colspan="6">No monitoring error events yet.</td></tr><?php endif; ?></tbody></table></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Health Snapshots</span><h2><?= count($snapshots) ?> recent snapshots</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Snapshot</th><th>Score</th><th>Status</th><th>Passed</th><th>Failed</th><th>Created</th></tr></thead><tbody><?php foreach($snapshots as $s): ?><tr><td><?= sf_admin_h($s['snapshot_key']) ?></td><td><?= (int)$s['health_score'] ?>%</td><td><?= sf_admin_status_badge($s['status']) ?></td><td><?= (int)$s['checks_passed'] ?></td><td><?= (int)$s['checks_failed'] ?></td><td><?= sf_admin_h($s['created_at']) ?></td></tr><?php endforeach; ?><?php if(!$snapshots): ?><tr><td colspan="6">No snapshots yet.</td></tr><?php endif; ?></tbody></table></div></section>
<?php sf_admin_shell_end(); require __DIR__ . '/../includes/footer.php'; ?>
