<?php
$pageTitle='Ops Scheduler';$pageDescription='Stonefellow scheduled jobs, run history, queue dispatch, lifecycle scans, support SLA checks, revenue snapshots, and engagement refresh.';$pageClass='membership-page admin-catalog-page';
require __DIR__.'/../includes/admin_catalog.php';require_once __DIR__.'/../includes/ops_scheduler_messaging.php';sf_sec_require('admin.ops.manage');
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
 $action=(string)($_POST['action']??'');
 if($action==='save_job'){$id=sf_sched_save_job($_POST,(int)($_POST['job_id']??0));sf_admin_flash($id?'success':'error',$id?'Scheduled job saved.':'Job was rejected. Confirm its key, title, frequency, time, and status.');sf_admin_redirect($id?sf_url('admin/ops-scheduler.php?job_id='.$id):null);}
 if($action==='run_job'){$job=sf_sched_fetch_one('SELECT * FROM ops_scheduled_jobs WHERE id=? LIMIT 1',[(int)($_POST['job_id']??0)]);$r=$job?sf_sched_run_job($job,true):['ok'=>false,'summary'=>'Job not found.'];sf_admin_flash(!empty($r['ok'])?'success':'error',$r['summary']??'Job completed.');}
 if($action==='run_due'){$r=sf_sched_run_due(20);sf_admin_flash((int)$r['failed']>0?'warning':'success','Due jobs: '.(int)$r['success'].' successful, '.(int)$r['failed'].' failed, '.(int)$r['processed'].' processed.');}
 sf_admin_redirect(sf_url('admin/ops-scheduler.php'));
}
require __DIR__.'/../includes/header.php';$summary=sf_sched_summary();$jobs=sf_sched_jobs();$runs=sf_sched_runs(120);$editId=(int)($_GET['job_id']??($jobs[0]['id']??0));$editing=$editId?sf_sched_fetch_one('SELECT * FROM ops_scheduled_jobs WHERE id=? LIMIT 1',[$editId]):null;
sf_admin_shell_start('Ops Scheduler','Scheduled jobs v1','Run bounded, lease-protected operational jobs without overlapping executions.','ops-scheduler');
?>
<section class="sf-admin-card-grid"><div class="sf-admin-action-card"><span>Jobs</span><strong><?= (int)$summary['jobs'] ?></strong><small><?= (int)$summary['active'] ?> active.</small></div><div class="sf-admin-action-card"><span>Due</span><strong><?= (int)$summary['due'] ?></strong><small>Automatic jobs only.</small></div><div class="sf-admin-action-card"><span>Running</span><strong><?= (int)$summary['running'] ?></strong><small>Started in past 30 minutes.</small></div><div class="sf-admin-action-card"><span>Failed Runs</span><strong><?= (int)$summary['failed'] ?></strong><small>Past seven days.</small></div><a class="sf-admin-action-card" href="<?= sf_url('admin/member-messaging.php') ?>"><span>Messages</span><strong>Campaigns</strong><small>Member communication.</small></a></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Process Due</span><h2>Run eligible automatic jobs</h2></div><small>Manual-frequency jobs are never automatically due.</small></div><form method="post" class="sf-admin-form" onsubmit="return confirm('Run all currently due jobs?')"><?= sf_csrf_field() ?><input type="hidden" name="action" value="run_due"><div class="sf-admin-form-actions"><button type="submit">Run Due Jobs</button></div></form></section>
<section class="sf-admin-two-col sf-admin-two-col-wide"><article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Job Registry</span><h2><?= count($jobs) ?> jobs</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Job</th><th>Type</th><th>Frequency</th><th>Status</th><th>Next</th><th>Run</th></tr></thead><tbody><?php foreach($jobs as $j): ?><tr><td><strong><a href="<?= sf_url('admin/ops-scheduler.php?job_id='.(int)$j['id']) ?>"><?= sf_admin_h($j['title']) ?></a></strong><small><?= sf_admin_h($j['job_key']) ?></small></td><td><?= sf_admin_h($j['job_type']) ?></td><td><?= sf_admin_h($j['frequency']) ?><small><?= sf_admin_h($j['schedule_time']??'') ?></small></td><td><?= sf_admin_status_badge($j['status']) ?></td><td><?= sf_admin_h($j['next_run_at']?:'Manual') ?></td><td><form method="post" onsubmit="return confirm('Run this job now under an exclusive lease?')"><?= sf_csrf_field() ?><input type="hidden" name="action" value="run_job"><input type="hidden" name="job_id" value="<?= (int)$j['id'] ?>"><button type="submit">Run</button></form></td></tr><?php endforeach; ?><?php if(!$jobs): ?><tr><td colspan="6">No scheduled jobs found. Run migration 017.</td></tr><?php endif; ?></tbody></table></div></article>
<aside class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow"><?= $editing?'Edit':'Create' ?></span><h2><?= $editing?sf_admin_h($editing['title']):'Scheduled Job' ?></h2></div></div><form class="sf-admin-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="save_job"><input type="hidden" name="job_id" value="<?= (int)($editing['id']??0) ?>"><label>Job Key<input name="job_key" maxlength="120" required value="<?= sf_admin_h($editing['job_key']??'') ?>"></label><label>Title<input name="title" maxlength="190" required value="<?= sf_admin_h($editing['title']??'') ?>"></label><label>Description<textarea name="description" maxlength="5000" rows="3"><?= sf_admin_h($editing['description']??'') ?></textarea></label><div class="sf-admin-form-grid"><label>Type<?= sf_admin_select('job_type',['dispatch_notifications'=>'Dispatch Notifications','lifecycle_churn_scan'=>'Lifecycle Churn Scan','support_sla_scan'=>'Support SLA Scan','revenue_snapshot'=>'Revenue Snapshot','engagement_score_refresh'=>'Engagement Score Refresh','custom'=>'Custom'],(string)($editing['job_type']??'custom')) ?></label><label>Frequency<?= sf_admin_select('frequency',['hourly'=>'Hourly','daily'=>'Daily','weekly'=>'Weekly','monthly'=>'Monthly','manual'=>'Manual'],(string)($editing['frequency']??'daily')) ?></label></div><div class="sf-admin-form-grid"><label>Schedule Time<input type="time" step="1" name="schedule_time" value="<?= sf_admin_h($editing['schedule_time']??'08:00:00') ?>"></label><label>Status<?= sf_admin_select('status',['active'=>'Active','paused'=>'Paused','archived'=>'Archived'],(string)($editing['status']??'paused')) ?></label></div><label>Next Run Override<input type="datetime-local" name="next_run_at" value="<?= !empty($editing['next_run_at'])?sf_admin_h(str_replace(' ','T',substr((string)$editing['next_run_at'],0,16))):'' ?>"></label><p class="sf-admin-copy">Manual jobs always store a null next-run time. Other jobs calculate the next future occurrence when no override is provided.</p><div class="sf-admin-form-actions"><button type="submit">Save Job</button></div></form></aside></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Run History</span><h2><?= count($runs) ?> recent runs</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Job</th><th>Status</th><th>Processed</th><th>Success</th><th>Failed</th><th>Started</th><th>Summary</th></tr></thead><tbody><?php foreach($runs as $r): ?><tr><td><strong><?= sf_admin_h($r['title']?:$r['job_key']) ?></strong><small><?= sf_admin_h($r['job_key']) ?></small></td><td><?= sf_admin_status_badge($r['run_status']) ?></td><td><?= (int)$r['processed_count'] ?></td><td><?= (int)$r['success_count'] ?></td><td><?= (int)$r['failed_count'] ?></td><td><?= sf_admin_h($r['started_at']) ?></td><td><?= sf_admin_h($r['result_summary']??$r['error_message']??'') ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php sf_admin_shell_end();require __DIR__.'/../includes/footer.php'; ?>
