<?php
$pageTitle='Platform Certification';
$pageDescription='Stonefellow whole-codebase source score and deployed operational certification status.';
$pageClass='membership-page admin-catalog-page platform-certification-page';
require_once __DIR__.'/../includes/platform_certification.php';
if(function_exists('sf_agentic_require_permission'))sf_agentic_require_permission('admin.ops.manage');
$summary=sf_pc_summary();
require __DIR__.'/../includes/header.php';
sf_admin_shell_start('Operations','Stonefellow Platform Certification','One source of truth for the codebase audit score, deployed evidence score, launch certification, integration matrix, production promotion, backup, release, and preflight.','platform-certification');
?>
<style>.pc-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.pc-card{padding:18px;border:1px solid rgba(255,255,255,.1);border-radius:18px;background:rgba(255,255,255,.035)}.pc-card strong{display:block;font-size:28px;color:#fff;margin:6px 0}.pc-muted{color:rgba(255,255,255,.68);line-height:1.5}.pc-links{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.pc-links a{display:block;padding:18px;border:1px solid rgba(255,255,255,.1);border-radius:18px;background:rgba(255,255,255,.035);color:#fff}.pc-links strong{display:block;margin:5px 0}.pc-pass{color:#9ee6b2}.pc-pending{color:#f5d98d}@media(max-width:950px){.pc-grid,.pc-links{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.pc-grid,.pc-links{grid-template-columns:1fr}}</style>
<section class="pc-grid">
  <article class="pc-card"><span class="sf-panel-eyebrow">Source / CI Score</span><strong class="<?= $summary['static_score']===100?'pc-pass':'pc-pending' ?>"><?= (int)$summary['static_score'] ?>%</strong><small class="pc-muted"><?= $summary['static_score']===100?'10/10 cumulative source certification':'Resolve missing code or audit gates' ?></small></article>
  <article class="pc-card"><span class="sf-panel-eyebrow">Operational Score</span><strong class="<?= $summary['operational_score']===100?'pc-pass':'pc-pending' ?>"><?= (int)$summary['operational_score'] ?>%</strong><small class="pc-muted"><?= sf_admin_h(str_replace('_',' ',$summary['operational_status'])) ?></small></article>
  <article class="pc-card"><span class="sf-panel-eyebrow">Staging Certificate</span><strong><?= $summary['latest_certificate']?'PASS':'PENDING' ?></strong><small class="pc-muted"><?= sf_admin_h($summary['latest_certificate']['target_commit_sha']??'No passed certificate') ?></small></article>
  <article class="pc-card"><span class="sf-panel-eyebrow">Production Promotion</span><strong><?= $summary['latest_promotion']?'VERIFIED':'PENDING' ?></strong><small class="pc-muted"><?= sf_admin_h($summary['latest_promotion']['target_commit_sha']??'No verified promotion') ?></small></article>
</section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Certification Workflow</span><h2>Open each launch stage</h2></div><a href="<?= sf_url('deploy/preflight.php') ?>">Run Preflight</a></div><div class="pc-links">
<a href="<?= sf_url('admin/ai-staging-certification.php') ?>"><span>AI</span><strong>AI Staging Certification</strong><small>Provider, budget, restore, moderation, and cost evidence.</small></a>
<a href="<?= sf_url('admin/staging-launch-certification.php') ?>"><span>Staging</span><strong>Launch Certification</strong><small>Whole-platform required check and evidence ledger.</small></a>
<a href="<?= sf_url('admin/staging-integration-matrix.php') ?>"><span>Integration</span><strong>Scenario Matrix</strong><small>Authentication, billing, media, delivery, content, AI, recovery, and browser tests.</small></a>
<a href="<?= sf_url('admin/production-launch.php') ?>"><span>Production</span><strong>Launch Promotion</strong><small>Approvals, artifact, deployment, verification, and rollback.</small></a>
<a href="<?= sf_url('admin/operations-recovery.php') ?>"><span>Recovery</span><strong>Operations & Recovery</strong><small>Migrations, backup, restore, monitoring, and release gates.</small></a>
<a href="<?= sf_url('admin/releases.php') ?>"><span>Release</span><strong>Deployment Release</strong><small>Exact commit, tasks, backup, migration range, and rollback plan.</small></a>
</div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Source Certification</span><h2>Ten cumulative codebase sections</h2></div><small>All sections must score 100% in CI.</small></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Section</th><th>Score</th><th>Passed</th><th>Failed</th></tr></thead><tbody><?php foreach($summary['static_sections'] as $section): ?><tr><td><strong><?= sf_admin_h($section['section']) ?></strong></td><td><?= (int)$section['score'] ?>%</td><td><?= (int)$section['passed'] ?> / <?= (int)$section['total'] ?></td><td><?= (int)$section['failed'] ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Operational Certification</span><h2>Deployed evidence gates</h2></div><small>These cannot be satisfied by static code alone.</small></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Area</th><th>Gate</th><th>Status</th><th>Detail</th><th>Open</th></tr></thead><tbody><?php foreach($summary['operational_checks'] as $check): ?><tr><td><?= sf_admin_h($check['section']) ?></td><td><strong><?= sf_admin_h($check['label']) ?></strong></td><td><?= sf_admin_status_badge($check['status']) ?></td><td><?= sf_admin_h($check['detail']) ?></td><td><?= !empty($check['url'])?'<a href="'.sf_admin_h(sf_url($check['url'])).'">Open</a>':'—' ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Certification Boundary</span><h2>What 10/10 means</h2></div></div><p class="pc-muted"><strong>Source 10/10</strong> means every committed PHP file passes lint and every cumulative smoke/static audit is enforced by GitHub Actions. <strong>Operational 10/10</strong> additionally requires the deployed SQL, real provider tests, complete staging scenarios, verified backup/restore evidence, independent launch approvals, an exact production commit, post-deploy checks, and a verified production promotion.</p></section>
<?php sf_admin_shell_end();require __DIR__.'/../includes/footer.php'; ?>
