<?php
$pageTitle='Production Launch';
$pageDescription='Promote a certified Stonefellow release through independent approval, deployment, post-deploy verification, and rollback gates.';
$pageClass='membership-page admin-catalog-page production-launch-page';
require_once __DIR__.'/../includes/production_launch.php';
if(function_exists('sf_agentic_require_permission'))sf_agentic_require_permission('admin.ops.manage');

if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
  $action=(string)($_POST['action']??'');$promotionId=(int)($_POST['promotion_id']??0);
  if($action==='create'){$promotionId=sf_prod_create($_POST);sf_admin_flash($promotionId?'success':'error',$promotionId?'Production launch promotion created.':'Promotion was blocked. Confirm the release gate, 100% certificate, full scenario coverage, matching verified backup, freeze time, and rollback plan.');}
  elseif($action==='artifact'&&$promotionId>0){$ok=sf_prod_update_artifact($promotionId,(string)($_POST['artifact_reference']??''),(string)($_POST['artifact_sha256']??''));sf_admin_flash($ok?'success':'error',$ok?'Deployment artifact saved.':'Artifact reference and valid SHA-256 are required.');}
  elseif($action==='approval'&&$promotionId>0){$ok=sf_prod_record_approval($promotionId,(string)($_POST['approval_type']??''),(string)($_POST['approval_status']??'pending'),(string)($_POST['decision_note']??''),(string)($_POST['evidence_reference']??''),(string)($_POST['evidence_sha256']??''));sf_admin_flash($ok?'success':'error',$ok?'Approval decision saved.':'Approval was rejected. Approved decisions require an independent authenticated user, meaningful note, and evidence reference.');}
  elseif($action==='check'&&$promotionId>0){$ok=sf_prod_record_check($promotionId,(string)($_POST['check_key']??''),(string)($_POST['check_status']??'pending'),(string)($_POST['result_message']??''),(string)($_POST['evidence_reference']??''),(string)($_POST['evidence_sha256']??''));sf_admin_flash($ok?'success':'error',$ok?'Launch check saved.':'Check was rejected for this promotion phase or lacks required evidence.');}
  elseif($action==='transition'&&$promotionId>0){$r=sf_prod_transition($promotionId,(string)($_POST['requested_status']??''),(string)($_POST['transition_note']??''));sf_admin_flash(!empty($r['ok'])?'success':'warning',(string)$r['message']);}
  sf_admin_redirect(sf_url('admin/production-launch.php'.($promotionId>0?'?promotion_id='.$promotionId:'')));
}
$promotions=sf_prod_promotions();$promotionId=(int)($_GET['promotion_id']??($promotions[0]['id']??0));$promotion=sf_prod_promotion($promotionId);$checks=$promotion?sf_prod_checks($promotionId):[];$approvals=$promotion?sf_prod_approvals($promotionId):[];$events=$promotion?sf_prod_events($promotionId):[];$releases=sf_rel_releases(100);$certificates=array_values(array_filter(sf_slc_runs(100),static fn($r)=>($r['run_status']??'')==='passed'&&(float)($r['overall_score']??0)===100.0));$backups=array_values(array_filter(sf_br_runs(100),static fn($b)=>($b['run_status']??'')==='verified'));
require __DIR__.'/../includes/header.php';
sf_admin_shell_start('Operations','Production Launch Promotion','Bind the exact release commit to its passed certificate, integration evidence, backup, approvals, deployment artifact, and post-deploy proof.','production-launch');
?>
<style>.prod-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.prod-two{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.prod-card,.prod-check{padding:16px;border:1px solid rgba(255,255,255,.1);border-radius:18px;background:rgba(255,255,255,.035)}.prod-card strong{display:block;font-size:24px;color:#fff;margin:6px 0}.prod-muted{color:rgba(255,255,255,.68);line-height:1.5}.prod-phase{margin:18px 0 8px;color:#f5d98d;text-transform:uppercase;letter-spacing:.1em;font-size:12px}.prod-list{display:flex;gap:8px;flex-wrap:wrap}.prod-list a{padding:8px 12px;border:1px solid rgba(255,255,255,.12);border-radius:999px;color:#fff}.prod-list a.is-active{border-color:#e8c67f;color:#f5d98d}@media(max-width:950px){.prod-grid,.prod-two{grid-template-columns:1fr 1fr}}@media(max-width:700px){.prod-grid,.prod-two{grid-template-columns:1fr}}</style>
<?php if(!sf_prod_ready()): ?><div class="sf-admin-alert sf-admin-alert-warning"><strong>SQL required:</strong> import <code>database/production_launch_promotion_v1.sql</code>.</div><?php endif; ?>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">New Promotion</span><h2>Bind a certified release candidate</h2></div><a href="<?= sf_url('admin/staging-integration-matrix.php') ?>">Integration Matrix</a></div><form method="post" class="sf-admin-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="create"><div class="sf-admin-form-grid"><label>Promotion label<input name="promotion_label" maxlength="190" placeholder="Stonefellow production launch"></label><label>Release<select name="release_id" required><?php foreach($releases as $r): ?><option value="<?= (int)$r['id'] ?>"><?= sf_admin_h($r['release_label'].' · '.$r['git_sha']) ?></option><?php endforeach; ?></select></label><label>Passed certificate<select name="certification_run_id" required><?php foreach($certificates as $c): ?><option value="<?= (int)$c['id'] ?>"><?= sf_admin_h($c['run_label'].' · '.$c['target_commit_sha']) ?></option><?php endforeach; ?></select></label><label>Verified backup<select name="backup_run_id" required><?php foreach($backups as $b): ?><option value="<?= (int)$b['id'] ?>"><?= sf_admin_h($b['run_key'].' · '.($b['verified_at']??'')) ?></option><?php endforeach; ?></select></label><label>Freeze time<input type="datetime-local" name="freeze_at" required></label></div><label>Rollback trigger<textarea name="rollback_trigger" rows="3" required placeholder="Define measurable error, payment, queue, latency, or integrity thresholds that trigger rollback."></textarea></label><label>Rollback procedure<textarea name="rollback_procedure" rows="6" required placeholder="Record owner, package/ref, commands, database decision, restore path, validation, and communications."></textarea></label><label>Release notes<textarea name="release_notes" rows="4"></textarea></label><div class="sf-admin-form-actions"><button type="submit"<?= sf_prod_ready()?'':' disabled' ?>>Create Promotion</button></div></form><?php if($promotions): ?><div class="prod-list"><?php foreach($promotions as $p): ?><a class="<?= (int)$p['id']===$promotionId?'is-active':'' ?>" href="<?= sf_url('admin/production-launch.php?promotion_id='.(int)$p['id']) ?>"><?= sf_admin_h($p['promotion_label'].' · '.$p['promotion_status']) ?></a><?php endforeach; ?></div><?php endif; ?></section>
<?php if($promotion): $approvalGate=sf_prod_approval_gate($promotionId);$artifactGate=sf_prod_artifact_gate($promotion); ?>
<section class="prod-grid"><article class="prod-card"><span class="sf-panel-eyebrow">Status</span><strong><?= sf_admin_h(strtoupper($promotion['promotion_status'])) ?></strong><small class="prod-muted"><?= sf_admin_h($promotion['target_branch']) ?></small></article><article class="prod-card"><span class="sf-panel-eyebrow">Commit</span><strong style="font-size:14px"><code><?= sf_admin_h($promotion['target_commit_sha']) ?></code></strong><small class="prod-muted">Exact certified revision</small></article><article class="prod-card"><span class="sf-panel-eyebrow">Approvals</span><strong><?= count(array_filter($approvals,static fn($a)=>$a['approval_status']==='approved')) ?> / 4</strong><small class="prod-muted"><?= $approvalGate['ok']?'Complete':'Independent decisions required' ?></small></article><article class="prod-card"><span class="sf-panel-eyebrow">Artifact</span><strong><?= $artifactGate['ok']?'VERIFIED':'PENDING' ?></strong><small class="prod-muted"><?= sf_admin_h($promotion['artifact_reference']??'No artifact') ?></small></article></section>
<section class="prod-two"><article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Deployment Artifact</span><h2>Approved package evidence</h2></div></div><form method="post" class="sf-admin-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="artifact"><input type="hidden" name="promotion_id" value="<?= $promotionId ?>"><label>Artifact reference<input name="artifact_reference" maxlength="1000" value="<?= sf_admin_h($promotion['artifact_reference']??'') ?>" required></label><label>Artifact SHA-256<input name="artifact_sha256" maxlength="64" pattern="[a-fA-F0-9]{64}" value="<?= sf_admin_h($promotion['artifact_sha256']??'') ?>" required></label><button type="submit"<?= in_array($promotion['promotion_status'],['draft','approved'],true)?'':' disabled' ?>>Save Artifact</button></form></article><article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">State Transition</span><h2>Fail-closed promotion</h2></div></div><form method="post" class="sf-admin-form" onsubmit="return confirm('Evaluate and apply this production launch state transition?')"><?= sf_csrf_field() ?><input type="hidden" name="action" value="transition"><input type="hidden" name="promotion_id" value="<?= $promotionId ?>"><label>Requested status<?= sf_admin_select('requested_status',array_combine(sf_prod_statuses(),array_map(static fn($s)=>ucwords(str_replace('_',' ',$s)),sf_prod_statuses())),$promotion['promotion_status']) ?></label><label>Transition note<textarea name="transition_note" rows="3" required></textarea></label><button type="submit"<?= sf_prod_locked($promotion)?' disabled':'' ?>>Evaluate Transition</button></form></article></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Independent Approval</span><h2>Technical, operations, security, and business decisions</h2></div><small>Distinct approvers are required by default.</small></div><div class="prod-two"><?php foreach($approvals as $a): ?><article class="prod-check"><h3><?= sf_admin_h(ucfirst($a['approval_type']).' approval') ?></h3><?= sf_admin_status_badge($a['approval_status']) ?><p class="prod-muted"><?= sf_admin_h($a['decision_note']?:'No decision recorded.') ?></p><form method="post" class="sf-admin-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="approval"><input type="hidden" name="promotion_id" value="<?= $promotionId ?>"><input type="hidden" name="approval_type" value="<?= sf_admin_h($a['approval_type']) ?>"><label>Decision<?= sf_admin_select('approval_status',['approved'=>'Approved','rejected'=>'Rejected','pending'=>'Pending','revoked'=>'Revoked'],$a['approval_status']) ?></label><label>Decision note<textarea name="decision_note" rows="3" required><?= sf_admin_h($a['decision_note']??'') ?></textarea></label><label>Evidence reference<input name="evidence_reference" maxlength="1000" value="<?= sf_admin_h($a['evidence_reference']??'') ?>"></label><label>Evidence SHA-256<input name="evidence_sha256" maxlength="64" pattern="[a-fA-F0-9]{64}" value="<?= sf_admin_h($a['evidence_sha256']??'') ?>"></label><button type="submit"<?= $promotion['promotion_status']==='draft'?'':' disabled' ?>>Save Decision</button></form></article><?php endforeach; ?></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Launch Checks</span><h2>Pre-deploy, deploy, post-deploy, and rollback proof</h2></div></div><?php $phase='';foreach($checks as $check): if($phase!==$check['phase_key']):$phase=$check['phase_key'];?><h3 class="prod-phase"><?= sf_admin_h(str_replace('_',' ',$phase)) ?></h3><?php endif; ?><article class="prod-check"><h3><?= sf_admin_h($check['check_label']) ?></h3><?= sf_admin_status_badge($check['check_status']) ?><p class="prod-muted"><?= sf_admin_h($check['result_message']?:'No evidence recorded.') ?></p><form method="post" class="sf-admin-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="check"><input type="hidden" name="promotion_id" value="<?= $promotionId ?>"><input type="hidden" name="check_key" value="<?= sf_admin_h($check['check_key']) ?>"><label>Status<?= sf_admin_select('check_status',['passed'=>'Passed','failed'=>'Failed','running'=>'Running','pending'=>'Pending','skipped'=>'Skipped'],$check['check_status']) ?></label><label>Result<textarea name="result_message" rows="3" required><?= sf_admin_h($check['result_message']??'') ?></textarea></label><label>Evidence reference<input name="evidence_reference" maxlength="1000" value="<?= sf_admin_h($check['evidence_reference']??'') ?>"></label><label>Evidence SHA-256<input name="evidence_sha256" maxlength="64" pattern="[a-fA-F0-9]{64}" value="<?= sf_admin_h($check['evidence_sha256']??'') ?>"></label><button type="submit"<?= sf_prod_locked($promotion)?' disabled':'' ?>>Save Check</button></form></article><?php endforeach; ?></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Event Ledger</span><h2><?= count($events) ?> production launch events</h2></div><small>Signed deployment automation posts to <code>/api/production-deployment-event.php</code>.</small></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Event</th><th>Status</th><th>Message</th><th>Hash</th><th>Time</th></tr></thead><tbody><?php foreach($events as $event): ?><tr><td><?= sf_admin_h($event['event_type']) ?><small><?= sf_admin_h($event['source_event_id']??'') ?></small></td><td><?= sf_admin_status_badge($event['event_status']) ?></td><td><?= sf_admin_h($event['event_message']) ?></td><td><code><?= sf_admin_h(substr((string)$event['payload_hash'],0,16)) ?><?= $event['payload_hash']?'…':'' ?></code></td><td><?= sf_admin_h($event['created_at']) ?></td></tr><?php endforeach; ?><?php if(!$events): ?><tr><td colspan="5">No launch events recorded yet.</td></tr><?php endif; ?></tbody></table></div></section>
<?php endif; ?>
<?php sf_admin_shell_end();require __DIR__.'/../includes/footer.php'; ?>
