<?php
$pageTitle='Publishing Workflow';$pageDescription='Draft, scheduled, published, archived, and early-access publishing controls.';$pageClass='membership-page admin-catalog-page';
require __DIR__.'/../includes/admin_catalog.php';require_once __DIR__.'/../includes/publishing.php';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
  $action=(string)($_POST['action']??'save');
  if($action==='run_due'){$result=sf_publish_run_due();sf_admin_flash(!empty($result['ok'])?'success':'error',!empty($result['ok'])?'Due publishing completed: '.(int)$result['changed'].' changes across '.(int)$result['checked'].' checked records.':($result['message']??'Due publishing failed.'));sf_admin_redirect();}
  $type=(string)($_POST['content_type']??'');$id=(int)($_POST['content_id']??0);$data=['status'=>(string)($_POST['status']??'draft'),'release_at'=>sf_admin_datetime_or_null('release_at'),'publish_window_start'=>sf_admin_datetime_or_null('publish_window_start'),'publish_window_end'=>sf_admin_datetime_or_null('publish_window_end'),'access_level'=>(string)($_POST['access_level']??'subscriber'),'is_featured'=>isset($_POST['is_featured'])?1:0];
  if($id>0&&sf_publish_apply($type,$id,$data))sf_admin_flash('success','Publishing settings updated transactionally.');else sf_admin_flash('warning','Publishing settings were rejected. Confirm the state, release time, access level, and database schema.');sf_admin_redirect();
}
require __DIR__.'/../includes/header.php';$items=sf_publish_items();$stats=['draft'=>0,'scheduled'=>0,'published'=>0,'archived'=>0,'expired'=>0];foreach($items as $item){$state=$item['computed_state']??'draft';$stats[$state]=($stats[$state]??0)+1;}
sf_admin_shell_start('Publishing','Release workflow v1','Manage validated, atomic release transitions across music, video, episodes, albums, products, and creator posts.','publishing');
?>
<section class="sf-admin-card-grid"><div class="sf-admin-action-card"><span>Published</span><strong><?= (int)($stats['published']??0) ?></strong><small>Live now.</small></div><div class="sf-admin-action-card"><span>Scheduled</span><strong><?= (int)($stats['scheduled']??0) ?></strong><small>Future release.</small></div><div class="sf-admin-action-card"><span>Drafts</span><strong><?= (int)($stats['draft']??0) ?></strong><small>Not public.</small></div><a class="sf-admin-action-card" href="<?= sf_url('admin/release-schedule.php') ?>"><span>Calendar</span><strong>Release Schedule</strong><small>Review scheduled content.</small></a></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Due Runner</span><h2>Promote scheduled releases</h2></div></div><p class="sf-admin-copy">This action is never run during a page view. It acquires a database advisory lock, promotes due scheduled records, archives expired windows, refreshes search entries, and records an event.</p><form method="post" class="sf-admin-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="run_due"><div class="sf-admin-form-actions"><button type="submit" onclick="return confirm('Run the due publishing process now?')">Run Due Publishing</button></div></form></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Content Registry</span><h2><?= count($items) ?> items</h2></div><small>Draft-first, access-aware, and search-indexed.</small></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Content</th><th>State</th><th>Release</th><th>Access</th><th>Update</th></tr></thead><tbody>
<?php foreach($items as $item): ?><tr><td><strong><?= sf_admin_h($item['display_title']??'') ?></strong><small><?= sf_admin_h(($item['content_type']??'').' · '.($item['slug']??'')) ?></small></td><td><?= sf_admin_status_badge((string)($item['computed_state']??'draft')) ?></td><td><?= sf_admin_h($item['release_at']??$item['published_at']??$item['publish_window_start']??'Unscheduled') ?></td><td><?= sf_admin_h(sf_access_label((string)($item['access_level']??'public'))) ?></td><td><form class="sf-admin-inline-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="save"><input type="hidden" name="content_type" value="<?= sf_admin_h($item['content_type']??'') ?>"><input type="hidden" name="content_id" value="<?= (int)($item['id']??0) ?>"><?= sf_admin_select('status',sf_publish_statuses(),(string)($item['computed_state']??'draft')) ?><?= sf_admin_select('access_level',sf_publish_access_levels(),(string)($item['access_level']??'subscriber')) ?><input type="datetime-local" name="release_at" value="<?= !empty($item['release_at']??$item['published_at']??null)?sf_admin_h(str_replace(' ','T',substr((string)($item['release_at']??$item['published_at']),0,16))):'' ?>"><label class="sf-admin-check"><input type="checkbox" name="is_featured" <?= !empty($item['is_featured'])?'checked':'' ?>> Featured</label><button type="submit"<?= sf_admin_form_disabled_attr() ?>>Save</button></form></td></tr><?php endforeach; ?>
<?php if(!$items): ?><tr><td colspan="5">No publishable database content found yet.</td></tr><?php endif; ?></tbody></table></div></section>
<?php sf_admin_shell_end();require __DIR__.'/../includes/footer.php'; ?>
