<?php
$pageTitle = 'Release Manager';
$pageDescription = 'Stonefellow deployment release manager for release records, deployment checklist, migration status, rollback notes, and release events.';
$pageClass = 'membership-page admin-catalog-page';
require __DIR__ . '/../includes/admin_catalog.php';
require_once __DIR__ . '/../includes/backup_release.php';
sf_sec_require('admin.ops.manage');
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST') {
  $action=(string)($_POST['action']??'');
  if($action==='save_release'){ $id=sf_rel_create_or_update($_POST,(int)($_POST['release_id']??0)); sf_admin_flash($id?'success':'error',$id?'Release saved.':'Release was not saved. Run migration 019.'); sf_admin_redirect($id?sf_url('admin/releases.php?release_id='.$id):null); }
  if($action==='update_task'){ sf_rel_update_task((int)($_POST['task_id']??0),(string)($_POST['status']??'pending'),(string)($_POST['detail']??'')); sf_admin_flash('success','Release task updated.'); }
  if($action==='event'){ sf_rel_event((int)($_POST['release_id']??0),(string)($_POST['event_type']??'manual_event'),(string)($_POST['event_status']??'info'),(string)($_POST['title']??'Release event'),(string)($_POST['detail']??'')); sf_admin_flash('success','Release event added.'); }
  sf_admin_redirect(sf_url('admin/releases.php'.(!empty($_POST['release_id'])?'?release_id='.(int)$_POST['release_id']:'')));
}
require __DIR__ . '/../includes/header.php';
$summary=sf_br_summary();
$releases=sf_rel_releases(120);
$backups=sf_br_runs(80);
$selectedId=(int)($_GET['release_id']??($releases[0]['id']??0));
$selected=$selectedId?sf_rel_release($selectedId):null;
$tasks=$selectedId?sf_rel_tasks($selectedId):[];
$events=$selectedId?sf_rel_events($selectedId,100):sf_rel_events(0,80);
$migrations=sf_br_schema_status();
sf_admin_shell_start('Release Manager', 'Deployment release manager v1', 'Track release versions, deployment checklists, migration ranges, backup links, release events, smoke-test status, and rollback notes.', 'releases');
?>
<section class="sf-admin-card-grid">
  <div class="sf-admin-action-card"><span>Draft/Ready</span><strong><?= (int)$summary['ready_releases'] ?></strong><small>Pending releases.</small></div>
  <div class="sf-admin-action-card"><span>Deployed</span><strong><?= (int)$summary['deployed_releases'] ?></strong><small>Completed releases.</small></div>
  <div class="sf-admin-action-card"><span>Backups</span><strong><?= (int)$summary['runs'] ?></strong><small>Available backup records.</small></div>
  <a class="sf-admin-action-card" href="<?= sf_url('deploy/preflight.php') ?>"><span>Preflight</span><strong>Run</strong><small>Deployment CLI/browser preflight.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/backups.php') ?>"><span>Backup</span><strong>Manager</strong><small>Create backup record.</small></a>
</section>
<section class="sf-admin-two-col sf-admin-two-col-wide">
  <article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Releases</span><h2><?= count($releases) ?> records</h2></div><a href="<?= sf_url('api/release-manager.php') ?>">JSON API</a></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Release</th><th>Env</th><th>Status</th><th>Migration</th><th>Tasks</th></tr></thead><tbody><?php foreach($releases as $release): ?><tr><td><strong><a href="<?= sf_url('admin/releases.php?release_id='.(int)$release['id']) ?>"><?= sf_admin_h($release['release_label']) ?></a></strong><small><?= sf_admin_h($release['release_version'] ?: $release['release_key']) ?></small></td><td><?= sf_admin_h($release['deployment_environment']) ?></td><td><?= sf_admin_status_badge($release['release_status']) ?></td><td><?= sf_admin_h(($release['migration_from']?:'—').' → '.($release['migration_to']?:'—')) ?></td><td><?= (int)$release['passed_tasks'] ?> / <?= (int)$release['tasks'] ?></td></tr><?php endforeach; ?><?php if(!$releases): ?><tr><td colspan="5">No release records yet.</td></tr><?php endif; ?></tbody></table></div></article>
  <aside class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow"><?= $selected?'Edit':'Create' ?></span><h2><?= $selected?sf_admin_h($selected['release_label']):'Deployment release' ?></h2></div></div><form class="sf-admin-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="save_release"><input type="hidden" name="release_id" value="<?= (int)($selected['id']??0) ?>"><label>Release Label<input name="release_label" required value="<?= sf_admin_h($selected['release_label']??'') ?>"<?= sf_admin_form_disabled_attr() ?>></label><div class="sf-admin-form-grid"><label>Version<input name="release_version" value="<?= sf_admin_h($selected['release_version']??'') ?>" placeholder="v1.0.0"<?= sf_admin_form_disabled_attr() ?>></label><label>Status<?= sf_admin_select('release_status',['draft'=>'Draft','ready'=>'Ready','deploying'=>'Deploying','deployed'=>'Deployed','rolled_back'=>'Rolled Back','failed'=>'Failed','archived'=>'Archived'],$selected['release_status']??'draft') ?></label></div><div class="sf-admin-form-grid"><label>Environment<?= sf_admin_select('deployment_environment',['local'=>'Local','staging'=>'Staging','production'=>'Production'],$selected['deployment_environment']??'production') ?></label><label>Backup<select name="backup_run_id"><option value="0">No linked backup</option><?php foreach($backups as $b): ?><option value="<?= (int)$b['id'] ?>"<?= !empty($selected['backup_run_id'])&&(int)$selected['backup_run_id']===(int)$b['id']?' selected':'' ?>><?= sf_admin_h($b['run_key']) ?></option><?php endforeach; ?></select></label></div><div class="sf-admin-form-grid"><label>Git Branch<input name="git_branch" value="<?= sf_admin_h($selected['git_branch']??'main') ?>"<?= sf_admin_form_disabled_attr() ?>></label><label>Git SHA<input name="git_sha" value="<?= sf_admin_h($selected['git_sha']??'') ?>"<?= sf_admin_form_disabled_attr() ?>></label></div><div class="sf-admin-form-grid"><label>Migration From<input name="migration_from" value="<?= sf_admin_h($selected['migration_from']??'018') ?>"<?= sf_admin_form_disabled_attr() ?>></label><label>Migration To<input name="migration_to" value="<?= sf_admin_h($selected['migration_to']??'019') ?>"<?= sf_admin_form_disabled_attr() ?>></label></div><label>Deploy Notes<textarea name="deploy_notes" rows="4"<?= sf_admin_form_disabled_attr() ?>><?= sf_admin_h($selected['deploy_notes']??'') ?></textarea></label><label>Rollback Notes<textarea name="rollback_notes" rows="4"<?= sf_admin_form_disabled_attr() ?>><?= sf_admin_h($selected['rollback_notes']??'') ?></textarea></label><div class="sf-admin-form-actions"><button type="submit"<?= sf_admin_form_disabled_attr() ?>>Save Release</button></div></form></aside>
</section>
<?php if($selected): ?><section class="sf-admin-two-col sf-admin-two-col-wide"><article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Deployment Checklist</span><h2><?= count($tasks) ?> tasks</h2></div></div><div class="sf-admin-list"><?php foreach($tasks as $task): ?><article class="sf-admin-list-row"><strong><?= sf_admin_h($task['task_label']) ?></strong><span><?= sf_admin_h($task['task_group']) ?> · <?= sf_admin_h($task['status']) ?></span><form method="post" class="sf-admin-inline-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="update_task"><input type="hidden" name="release_id" value="<?= (int)$selected['id'] ?>"><input type="hidden" name="task_id" value="<?= (int)$task['id'] ?>"><button name="status" value="passed" type="submit">Pass</button><button name="status" value="failed" type="submit">Fail</button><button name="status" value="waived" type="submit">Waive</button></form></article><?php endforeach; ?></div></article><aside class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Add Event</span><h2>Release event</h2></div></div><form class="sf-admin-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="event"><input type="hidden" name="release_id" value="<?= (int)$selected['id'] ?>"><div class="sf-admin-form-grid"><label>Type<input name="event_type" value="manual_event"<?= sf_admin_form_disabled_attr() ?>></label><label>Status<?= sf_admin_select('event_status',['info'=>'Info','success'=>'Success','warning'=>'Warning','error'=>'Error'],'info') ?></label></div><label>Title<input name="title" required<?= sf_admin_form_disabled_attr() ?>></label><label>Detail<textarea name="detail" rows="4"<?= sf_admin_form_disabled_attr() ?>></textarea></label><div class="sf-admin-form-actions"><button type="submit"<?= sf_admin_form_disabled_attr() ?>>Add Event</button></div></form></aside></section><?php endif; ?>
<section class="sf-admin-two-col sf-admin-two-col-wide"><article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Release Events</span><h2><?= count($events) ?> events</h2></div></div><div class="sf-admin-list"><?php foreach($events as $event): ?><article class="sf-admin-list-row"><strong><?= sf_admin_h($event['title']) ?></strong><span><?= sf_admin_h($event['event_type']) ?> · <?= sf_admin_h($event['event_status']) ?> · <?= sf_admin_h($event['created_at']) ?></span><p><?= sf_admin_h($event['detail']??'') ?></p></article><?php endforeach; ?><?php if(!$events): ?><article class="sf-admin-list-row"><strong>No release events yet.</strong><p>Deployment events will appear here.</p></article><?php endif; ?></div></article><aside class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Migration Status</span><h2><?= count($migrations) ?> applied</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Key</th><th>File</th><th>Applied</th></tr></thead><tbody><?php foreach(array_slice($migrations,-12) as $m): ?><tr><td><?= sf_admin_h($m['migration_key']) ?></td><td><?= sf_admin_h($m['file_path']) ?></td><td><?= sf_admin_h($m['applied_at']) ?></td></tr><?php endforeach; ?><?php if(!$migrations): ?><tr><td colspan="3">Migration table not available.</td></tr><?php endif; ?></tbody></table></div></aside></section>
<?php sf_admin_shell_end(); require __DIR__ . '/../includes/footer.php'; ?>
