<?php
$pageTitle = 'Scene Backgrounds';
$pageDescription = 'Reusable Stonefellow scene background catalog for consistent locations, interiors, stages, and environments.';
$pageClass = 'membership-page admin-catalog-page storyboarding-system-page scene-backgrounds-page';
require __DIR__ . '/../includes/story_scene_backgrounds.php';

if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST') {
  if (!sf_verify_csrf($_POST['csrf_token'] ?? null)) { sf_admin_flash('error', 'Security check failed.'); sf_admin_redirect(); }
  if (!sf_scene_backgrounds_ready()) { sf_admin_flash('warning', 'Import database/story_scene_backgrounds_v1.sql before saving scene backgrounds.'); sf_admin_redirect(); }
  $action = (string)($_POST['action'] ?? 'save_background');
  $id = sf_admin_int($_POST['id'] ?? null, 0) ?? 0;
  if ($action === 'save_background') {
    $name = trim((string)($_POST['background_name'] ?? ''));
    if ($name === '') { sf_admin_flash('error', 'Background name is required.'); sf_admin_redirect(); }
    $imagePath = sf_admin_nullable_string($_POST['image_path'] ?? '') ?: '';
    if (isset($_FILES['background_image']) && is_array($_FILES['background_image']) && (int)($_FILES['background_image']['error'] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_NO_FILE) {
      $upload = sf_admin_handle_upload('background_image', 'image', 'story_scene_background', 'Scene Background - ' . $name, $name . ' background reference image');
      if (empty($upload['ok'])) { sf_admin_flash('error', $upload['message'] ?? 'Background image upload failed.'); sf_admin_redirect(sf_url('admin/scene-backgrounds.php' . ($id > 0 ? '?edit=' . $id : '?new=1'))); }
      $imagePath = (string)($upload['path'] ?? $imagePath);
    }
    $payload = ['background_name'=>$name,'slug'=>trim((string)($_POST['slug'] ?? '')) ?: sf_story_v1_unique_slug('story_scene_backgrounds', $name, $id),'background_type'=>$_POST['background_type'] ?? 'location','location_label'=>sf_admin_nullable_string($_POST['location_label'] ?? '') ?: '','time_of_day'=>sf_admin_nullable_string($_POST['time_of_day'] ?? '') ?: '','short_description'=>sf_admin_nullable_string($_POST['short_description'] ?? ''),'continuity_notes'=>sf_admin_nullable_string($_POST['continuity_notes'] ?? ''),'image_path'=>$imagePath,'status'=>$_POST['status'] ?? 'active','sort_order'=>sf_admin_int($_POST['sort_order'] ?? null, 10) ?? 10];
    $newId = sf_scene_backgrounds_save($payload, $id);
    sf_admin_flash($newId ? 'success' : 'error', $newId ? 'Scene background saved.' : 'Scene background could not be saved.');
    sf_admin_redirect(sf_url('admin/scene-backgrounds.php' . ($newId ? '?edit=' . $newId : '')));
  }
  sf_admin_redirect();
}

$backgrounds = sf_scene_backgrounds_all();
$activeBackgrounds = array_values(array_filter($backgrounds, static fn($row) => (string)($row['status'] ?? 'active') === 'active'));
$editId = sf_admin_int($_GET['edit'] ?? null, 0) ?? 0;
$edit = sf_scene_backgrounds_find($backgrounds, $editId) ?: [];
$showForm = isset($_GET['new']) || $edit;
$disabled = sf_scene_backgrounds_disabled_attr();
require __DIR__ . '/../includes/header.php';
sf_admin_shell_start('Scene Backgrounds', 'Scene Backgrounds Catalog', 'Manage reusable backgrounds and locations that scene cards can select for visual continuity.', 'scene-backgrounds');
?>
<style>.scene-backgrounds-page .sf-bg-thumb{width:72px;height:54px;border-radius:14px;border:1px solid rgba(232,198,127,.22);background:rgba(255,255,255,.04);background-size:cover;background-position:center;display:grid;place-items:center;color:rgba(255,255,255,.42);font-weight:950}.scene-backgrounds-page .sf-bg-image-field{display:grid;grid-template-columns:160px minmax(0,1fr);gap:14px;align-items:center;padding:14px;border:1px solid rgba(255,255,255,.08);border-radius:18px;background:rgba(0,0,0,.15)}.scene-backgrounds-page .sf-bg-image-field .sf-bg-thumb{width:160px;height:100px}@media(max-width:760px){.scene-backgrounds-page .sf-bg-image-field{grid-template-columns:1fr}.scene-backgrounds-page .sf-bg-image-field .sf-bg-thumb{width:100%;height:190px}}</style>
<?php if (!sf_scene_backgrounds_ready()): ?><section class="sf-story-v1-warning"><strong>SQL required:</strong> Import <code>database/story_scene_backgrounds_v1.sql</code> after the existing storyboarding SQL to enable Scene Backgrounds.</section><?php endif; ?>
<section class="sf-admin-card-grid sf-character-catalog-stats"><div class="sf-admin-action-card"><span>Total Backgrounds</span><strong><?= count($backgrounds) ?></strong><small>Reusable scene environments.</small></div><div class="sf-admin-action-card"><span>Active</span><strong><?= count($activeBackgrounds) ?></strong><small>Available for scene cards.</small></div><div class="sf-admin-action-card"><span>Scene Uses</span><strong><?= array_sum(array_map(static fn($row)=>(int)($row['scene_count'] ?? 0), $backgrounds)) ?></strong><small>Assigned scene cards.</small></div></section>
<?php if (!$showForm): ?>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Catalog</span><h2>Scene Backgrounds</h2></div><a href="<?= sf_url('admin/scene-backgrounds.php?new=1') ?>">Add Background</a></div><p class="sf-admin-copy">Create reusable backgrounds like green rooms, stages, desert roads, bars, homes, vehicles, and studio interiors that scene cards can select for consistency.</p><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Image</th><th>Background</th><th>Type</th><th>Location / Time</th><th>Description</th><th>Scenes</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach ($backgrounds as $background): $image = trim((string)($background['image_path'] ?? '')); ?><tr><td><div class="sf-bg-thumb"<?= $image !== '' ? ' style="background-image:url(' . sf_admin_h(sf_asset($image)) . ')"' : '' ?>><?= $image === '' ? 'BG' : '' ?></div></td><td><strong><?= sf_admin_h($background['background_name'] ?? '') ?></strong><small><?= sf_admin_h($background['slug'] ?? '') ?></small></td><td><?= sf_admin_h(sf_story_v1_status_label((string)($background['background_type'] ?? 'location'))) ?></td><td><strong><?= sf_admin_h($background['location_label'] ?? '') ?></strong><small><?= sf_admin_h($background['time_of_day'] ?? '') ?></small></td><td><strong><?= sf_admin_h($background['short_description'] ?? '') ?></strong><small><?= sf_admin_h($background['continuity_notes'] ?? '') ?></small></td><td><?= (int)($background['scene_count'] ?? 0) ?></td><td><?= sf_admin_status_badge((string)($background['status'] ?? 'active')) ?></td><td><a href="<?= sf_url('admin/scene-backgrounds.php?edit=' . (int)$background['id']) ?>">Edit</a></td></tr><?php endforeach; ?><?php if (!$backgrounds): ?><tr><td colspan="8">No scene backgrounds yet.</td></tr><?php endif; ?></tbody></table></div></section>
<?php else: ?>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow"><?= $edit ? 'Edit Background' : 'Add Background' ?></span><h2><?= $edit ? sf_admin_h($edit['background_name'] ?? '') : 'New Scene Background' ?></h2></div><a href="<?= sf_url('admin/scene-backgrounds.php') ?>">Back to Backgrounds</a></div><form class="sf-admin-form" method="post" enctype="multipart/form-data"><?= sf_csrf_field() ?><input type="hidden" name="action" value="save_background"><input type="hidden" name="id" value="<?= (int)($edit['id'] ?? 0) ?>"><div class="sf-story-v1-form-grid"><label>Background Name<input name="background_name" value="<?= sf_admin_h($edit['background_name'] ?? '') ?>" required<?= $disabled ?>></label><label>Type<?= sf_admin_select('background_type', sf_scene_background_type_options(), $edit['background_type'] ?? 'location') ?></label><label>Status<?= sf_admin_select('status', sf_scene_background_status_options(), $edit['status'] ?? 'active') ?></label></div><div class="sf-story-v1-form-grid"><label>Slug<input name="slug" value="<?= sf_admin_h($edit['slug'] ?? '') ?>" placeholder="auto-generated"<?= $disabled ?>></label><label>Location Label<input name="location_label" value="<?= sf_admin_h($edit['location_label'] ?? '') ?>" placeholder="Backstage green room"<?= $disabled ?>></label><label>Time of Day<input name="time_of_day" value="<?= sf_admin_h($edit['time_of_day'] ?? '') ?>" placeholder="night"<?= $disabled ?>></label><label>Sort<input type="number" name="sort_order" value="<?= sf_admin_h($edit['sort_order'] ?? 10) ?>"<?= $disabled ?>></label></div><?php $editImage = trim((string)($edit['image_path'] ?? '')); ?><div class="sf-bg-image-field"><div class="sf-bg-thumb"<?= $editImage !== '' ? ' style="background-image:url(' . sf_admin_h(sf_asset($editImage)) . ')"' : '' ?>><?= $editImage === '' ? 'BG' : '' ?></div><div><label>Upload Reference Image<input type="file" name="background_image" accept="image/*"<?= $disabled ?>></label><label>Image Path<input name="image_path" value="<?= sf_admin_h($editImage) ?>" placeholder="images/backgrounds/green-room.png"<?= $disabled ?>></label></div></div><label>Short Description<textarea name="short_description" rows="3"<?= $disabled ?>><?= sf_admin_h($edit['short_description'] ?? '') ?></textarea></label><label>Continuity Notes<textarea name="continuity_notes" rows="4"<?= $disabled ?>><?= sf_admin_h($edit['continuity_notes'] ?? '') ?></textarea></label><div class="sf-admin-form-actions"><button type="submit"<?= $disabled ?>>Save Background</button></div></form></section>
<?php endif; ?>
<?php sf_admin_shell_end(); require __DIR__ . '/../includes/footer.php'; ?>
