<?php
$pageTitle='Staging Launch Certification';
$pageDescription='Run the complete deployed integration matrix, attach evidence, and block launch until every required stage passes.';
$pageClass='membership-page admin-catalog-page staging-launch-certification-page';
require_once __DIR__.'/../includes/staging_launch_certification.php';
if(function_exists('sf_agentic_require_permission'))sf_agentic_require_permission('admin.ops.manage');

if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
  $action=(string)($_POST['action']??'');$runId=(int)($_POST['run_id']??0);
  if($action==='create_run'){$runId=sf_slc_create_run((string)($_POST['run_label']??''),(string)($_POST['target_branch']??'main'),(string)($_POST['target_commit_sha']??''));sf_admin_flash($runId?'success':'error',$runId?'Certification run created.':'Run was not created. Import the SQL and provide a valid 40-character commit SHA.');}
  elseif($action==='run_automated'&&$runId>0){$r=sf_slc_run_automated($runId);sf_admin_flash(!empty($r['ok'])?'success':'error','Automated checks: '.(int)$r['passed'].' passed, '.(int)$r['failed'].' failed.');}
  elseif($action==='manual_check'&&$runId>0){$ok=sf_slc_manual_check($runId,(string)($_POST['check_key']??''),(string)($_POST['check_status']??'pending'),(string)($_POST['result_message']??''),(string)($_POST['evidence_type']??'note'),(string)($_POST['source_reference']??''),(string)($_POST['artifact_sha256']??''));sf_admin_flash($ok?'success':'error',$ok?'Check evidence saved.':'Evidence was rejected. Passed checks require a meaningful note and source reference.');}
  elseif($action==='complete_run'&&$runId>0){$r=sf_slc_complete($runId,(string)($_POST['notes']??''));sf_admin_flash(!empty($r['ok'])?'success':'warning',(string)$r['message']);}
  sf_admin_redirect(sf_url('admin/staging-launch-certification.php'.($runId>0?'?run_id='.$runId:'')));
}
$runs=sf_slc_runs();$selected=(int)($_GET['run_id']??($runs[0]['id']??0));$run=sf_slc_run($selected);$checks=$run?sf_slc_checks($selected):[];$stages=$run?sf_slc_stage_summary($selected):[];$evidence=$run?sf_slc_evidence($selected):[];
require __DIR__.'/../includes/header.php';
sf_admin_shell_start('Operations','Staging & Launch Certification','Complete the real payment, media, email, publishing, AI, browser, backup, concurrency, and release gates before production promotion.','staging-launch-certification');
?>
<style>.slc-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.slc-card,.slc-check{padding:16px;border:1px solid rgba(255,255,255,.1);border-radius:18px;background:rgba(255,255,255,.035)}.slc-card strong{display:block;font-size:28px;color:#fff;margin:6px 0}.slc-muted{color:rgba(255,255,255,.68);line-height:1.5}.slc-stage-grid,.slc-check-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.slc-run-list{display:flex;gap:8px;flex-wrap:wrap}.slc-run-list a{padding:8px 12px;border:1px solid rgba(255,255,255,.12);border-radius:999px;color:#fff}.slc-run-list a.is-active{border-color:#e8c67f;color:#f5d98d}.slc-check h3{margin:8px 0}.slc-meta{display:flex;gap:6px;flex-wrap:wrap}.slc-pill{font-size:11px;border:1px solid rgba(232,198,127,.25);padding:4px 8px;border-radius:999px;color:#f5d98d}@media(max-width:900px){.slc-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:700px){.slc-grid,.slc-stage-grid,.slc-check-grid{grid-template-columns:1fr}}</style>
<?php if(!sf_slc_ready()): ?><div class="sf-admin-alert sf-admin-alert-warning"><strong>SQL required:</strong> import <code>database/staging_launch_certification_v1.sql</code>.</div><?php endif; ?>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Certification Run</span><h2>Create or select a run</h2></div><a href="<?= sf_url('deploy/preflight.php') ?>">Deployment Preflight</a></div>
<form class="sf-admin-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="create_run"><div class="sf-admin-form-grid"><label>Run label<input name="run_label" placeholder="Release candidate staging certification"></label><label>Target branch<input name="target_branch" value="main" required></label><label>Target commit SHA<input name="target_commit_sha" pattern="[a-fA-F0-9]{40}" maxlength="40" required placeholder="40-character Git SHA"></label></div><div class="sf-admin-form-actions"><button type="submit"<?= sf_slc_ready()?'':' disabled' ?>>Create Run</button></div></form>
<?php if($runs): ?><div class="slc-run-list"><?php foreach($runs as $r): ?><a class="<?= (int)$r['id']===$selected?'is-active':'' ?>" href="<?= sf_url('admin/staging-launch-certification.php?run_id='.(int)$r['id']) ?>"><?= sf_admin_h($r['run_label']) ?> · <?= sf_admin_h($r['run_status']) ?></a><?php endforeach; ?></div><?php endif; ?></section>
<?php if($run): ?>
<section class="slc-grid"><article class="slc-card"><span class="sf-panel-eyebrow">Score</span><strong><?= number_format((float)$run['overall_score'],1) ?>%</strong><small class="slc-muted"><?= (int)$run['passed_checks'] ?> / <?= (int)$run['required_checks'] ?> passed</small></article><article class="slc-card"><span class="sf-panel-eyebrow">Failures</span><strong><?= (int)$run['failed_checks'] ?></strong><small class="slc-muted"><?= (int)$run['pending_checks'] ?> pending</small></article><article class="slc-card"><span class="sf-panel-eyebrow">Environment</span><strong><?= sf_admin_h($run['environment_key']) ?></strong><small class="slc-muted"><?= sf_admin_h($run['target_branch']) ?></small></article><article class="slc-card"><span class="sf-panel-eyebrow">Status</span><strong><?= sf_admin_h(strtoupper($run['run_status'])) ?></strong><small class="slc-muted"><?= sf_admin_h($run['target_commit_sha']??'commit missing') ?></small></article></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Automated Foundation</span><h2>Environment, secrets, database, payment, email, and AI gates</h2></div></div><form method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="run_automated"><input type="hidden" name="run_id" value="<?= $selected ?>"><button type="submit"<?= sf_slc_locked($run)?' disabled':'' ?>>Run Automated Checks</button></form></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Stage Scores</span><h2>Operational certification matrix</h2></div></div><div class="slc-stage-grid"><?php foreach($stages as $s): ?><article class="slc-card"><span class="sf-panel-eyebrow"><?= sf_admin_h($s['stage_key']) ?></span><strong><?= number_format((float)$s['score'],1) ?>%</strong><small class="slc-muted"><?= (int)$s['passed'] ?> passed · <?= (int)$s['failed'] ?> failed · <?= (int)$s['pending'] ?> pending</small></article><?php endforeach; ?></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Checks & Evidence</span><h2><?= count($checks) ?> required launch controls</h2></div></div><div class="slc-check-grid"><?php foreach($checks as $c): ?><article class="slc-check"><div class="slc-meta"><span class="slc-pill"><?= sf_admin_h($c['stage_key']) ?></span><span class="slc-pill"><?= sf_admin_h($c['severity']) ?></span><span class="slc-pill"><?= !empty($c['is_automated'])?'automated':'manual' ?></span></div><h3><?= sf_admin_h($c['check_label']) ?></h3><?= sf_admin_status_badge((string)$c['check_status']) ?><p class="slc-muted"><?= sf_admin_h($c['result_message']?:'Not tested yet.') ?></p><?php if(empty($c['is_automated'])&&!sf_slc_locked($run)): ?><form method="post" class="sf-admin-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="manual_check"><input type="hidden" name="run_id" value="<?= $selected ?>"><input type="hidden" name="check_key" value="<?= sf_admin_h($c['check_key']) ?>"><label>Status<?= sf_admin_select('check_status',['passed'=>'Passed','failed'=>'Failed','pending'=>'Pending','skipped'=>'Skipped'],$c['check_status']) ?></label><label>Evidence type<?= sf_admin_select('evidence_type',['note'=>'Note','url'=>'URL','file_hash'=>'File hash','provider_event'=>'Provider event','browser_test'=>'Browser test','database_test'=>'Database test','backup'=>'Backup','restore'=>'Restore','approval'=>'Approval'],'note') ?></label><label>Evidence / result<textarea name="result_message" rows="3" required><?= sf_admin_h($c['result_message']??'') ?></textarea></label><label>Source reference<input name="source_reference" placeholder="Ticket, provider event, test URL, artifact location, or signed note"></label><label>Artifact SHA-256 (optional)<input name="artifact_sha256" pattern="[a-fA-F0-9]{64}" maxlength="64"></label><button type="submit">Save Evidence</button></form><?php endif; ?></article><?php endforeach; ?></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Evidence Ledger</span><h2><?= count($evidence) ?> verified records</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Check</th><th>Type</th><th>Evidence</th><th>Status</th><th>Submitted</th></tr></thead><tbody><?php foreach($evidence as $e): ?><tr><td><?= sf_admin_h($e['check_key']) ?></td><td><?= sf_admin_h($e['evidence_type']) ?></td><td><strong><?= sf_admin_h($e['evidence_label']) ?></strong><small><?= sf_admin_h($e['source_reference']??'') ?></small></td><td><?= sf_admin_status_badge((string)$e['verification_status']) ?></td><td><?= sf_admin_h($e['submitted_at']) ?></td></tr><?php endforeach; ?><?php if(!$evidence): ?><tr><td colspan="5">No evidence recorded yet.</td></tr><?php endif; ?></tbody></table></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Final Gate</span><h2>Complete certification</h2></div></div><form method="post" class="sf-admin-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="complete_run"><input type="hidden" name="run_id" value="<?= $selected ?>"><label>Certification notes<textarea name="notes" rows="5" required><?= sf_admin_h($run['certification_notes']??'') ?></textarea></label><div class="sf-admin-form-actions"><button type="submit"<?= sf_slc_locked($run)?' disabled':'' ?>>Evaluate 100% Launch Gate</button></div></form></section>
<?php else: ?><section class="sf-admin-panel"><p class="slc-muted">Create a run to begin the deployed certification program.</p></section><?php endif; ?>
<?php sf_admin_shell_end();require __DIR__.'/../includes/footer.php'; ?>
