<?php

declare(strict_types=1);

$pageTitle='Staging Activation';
$pageDescription='Bind real catalog, media, commerce, delivery, recovery, certification, and a frozen release candidate to one exact commit.';
$pageClass='membership-page admin-catalog-page staging-activation-page';
require __DIR__.'/../includes/staging_activation.php';

if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    $action=(string)($_POST['action']??'');$runId=(int)($_POST['run_id']??0);
    if(!sf_sa_ready()){sf_admin_flash('warning','Import migration 025 before using staging activation.');sf_admin_redirect(sf_url('admin/staging-activation.php'));}
    if($action==='create_run'){$id=sf_sa_create_run((string)($_POST['run_label']??''),(string)($_POST['target_branch']??'main'),(string)($_POST['target_commit_sha']??''));sf_admin_flash($id?'success':'error',$id?'Activation run created.':'Activation run could not be created. Use an exact 40-character commit.');sf_admin_redirect(sf_url('admin/staging-activation.php'.($id?'?run='.$id:'')));}
    if($action==='run_automated'&&$runId>0){$r=sf_sa_run_automated($runId);sf_admin_flash(!empty($r['ok'])?'success':'error','Automated checks: '.(int)($r['passed']??0).' passed, '.(int)($r['failed']??0).' failed.');sf_admin_redirect(sf_url('admin/staging-activation.php?run='.$runId));}
    if($action==='manual_check'&&$runId>0){$ok=sf_sa_manual_check($runId,(string)($_POST['check_key']??''),(string)($_POST['check_status']??'failed'),(string)($_POST['result_message']??''),(string)($_POST['evidence_type']??'note'),(string)($_POST['source_reference']??''),(string)($_POST['artifact_sha256']??''));sf_admin_flash($ok?'success':'error',$ok?'Manual evidence recorded.':'Manual evidence was rejected. Passed checks require a detailed result and source reference.');sf_admin_redirect(sf_url('admin/staging-activation.php?run='.$runId));}
    if($action==='complete_run'&&$runId>0){$r=sf_sa_complete($runId,(string)($_POST['activation_notes']??''));sf_admin_flash(!empty($r['ok'])?'success':'error',(string)$r['message']);sf_admin_redirect(sf_url('admin/staging-activation.php?run='.$runId));}
    if($action==='create_candidate'&&$runId>0){$id=sf_sa_create_candidate($runId,(string)($_POST['candidate_label']??''),(string)($_POST['artifact_url']??''),(string)($_POST['artifact_sha256']??''),(string)($_POST['release_notes']??''));sf_admin_flash($id?'success':'error',$id?'Release candidate created and ready to freeze.':'Candidate gate failed. Confirm activation, catalog, certification, scenarios, backup, release, artifact URL, and SHA-256.');sf_admin_redirect(sf_url('admin/staging-activation.php?run='.$runId));}
    if($action==='freeze_candidate'){$candidateId=(int)($_POST['candidate_id']??0);$r=sf_sa_freeze_candidate($candidateId,(string)($_POST['freeze_notes']??''));sf_admin_flash(!empty($r['ok'])?'success':'error',(string)$r['message']);sf_admin_redirect(sf_url('admin/staging-activation.php'.($runId?'?run='.$runId:'')));}
}

$runs=sf_sa_runs();$selectedId=(int)($_GET['run']??($runs[0]['id']??0));$run=$selectedId?sf_sa_run($selectedId):null;$checks=$run?sf_sa_checks($selectedId):[];$sections=$run?sf_sa_section_summary($selectedId):[];$candidates=sf_sa_candidates();$summary=sf_sa_activation_summary();
require __DIR__.'/../includes/header.php';
sf_admin_shell_start('Staging Activation','Activation + Release Candidate','Clear one consolidated blocker board, certify real staging behavior, and freeze an artifact against an exact commit.','staging-activation');
?>
<?php if(!sf_sa_ready()): ?><section class="sf-admin-alert sf-admin-alert-warning"><strong>SQL required:</strong> Import <code>database/migrations/025_staging_activation_release_candidate.sql</code>.</section><?php endif; ?>
<section class="sf-admin-metrics-grid">
  <article><span>Schema</span><strong><?= !empty($summary['schema_ready'])?'Ready':'Missing' ?></strong><small>Activation persistence</small></article>
  <article><span>Latest Activation</span><strong><?= sf_admin_h($summary['latest_run']['overall_score']??0) ?>%</strong><small><?= sf_admin_h($summary['latest_run']['run_status']??'none') ?></small></article>
  <article><span>Frozen Candidate</span><strong><?= !empty($summary['latest_candidate'])?'Yes':'No' ?></strong><small><?= sf_admin_h(substr((string)($summary['latest_candidate']['target_commit_sha']??''),0,12)) ?></small></article>
  <article><span>Commit Match</span><strong><?= !empty($summary['candidate_matches_release'])?'Yes':'No' ?></strong><small>SF_RELEASE_COMMIT_SHA</small></article>
</section>
<section class="sf-admin-card-grid">
  <a class="sf-admin-action-card" href="<?= sf_url('admin/catalog-operations.php') ?>"><span>Catalog</span><strong>Readiness</strong><small>Real records, SEO, media, pricing, and samples.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/media-pipeline.php') ?>"><span>Media</span><strong>Processing</strong><small>Storage health, audio, waveforms, and HLS.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/staging-integration-matrix.php') ?>"><span>Scenarios</span><strong>Integration Matrix</strong><small>Record end-to-end account, payment, media, and delivery evidence.</small></a>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/releases.php') ?>"><span>Release</span><strong>Deployment Record</strong><small>Bind migration, backup, tasks, and rollback.</small></a>
</section>
<section class="sf-admin-two-col sf-admin-two-col-wide">
  <article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">New Run</span><h2>Exact-commit activation</h2></div></div><form class="sf-admin-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="create_run"><label>Run Label<input name="run_label" placeholder="Stonefellow staging activation"></label><label>Branch<input name="target_branch" value="main" required></label><label>Commit SHA<input name="target_commit_sha" pattern="[a-fA-F0-9]{40}" maxlength="40" value="<?= sf_admin_h((string)(getenv('SF_RELEASE_COMMIT_SHA')?:'')) ?>" required></label><button type="submit"<?= sf_sa_ready()?'':' disabled' ?>>Create Activation Run</button></form></article>
  <article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Runs</span><h2><?= count($runs) ?> activation runs</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Run</th><th>Commit</th><th>Score</th><th>Status</th></tr></thead><tbody><?php foreach($runs as$item): ?><tr><td><a href="<?= sf_url('admin/staging-activation.php?run='.(int)$item['id']) ?>"><?= sf_admin_h($item['run_label']) ?></a></td><td><code><?= sf_admin_h(substr((string)$item['target_commit_sha'],0,12)) ?></code></td><td><?= sf_admin_h($item['overall_score']) ?>%</td><td><?= sf_admin_status_badge((string)$item['run_status']) ?></td></tr><?php endforeach; ?><?php if(!$runs): ?><tr><td colspan="4">No activation runs yet.</td></tr><?php endif; ?></tbody></table></div></article>
</section>
<?php if($run): ?>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Selected Run</span><h2><?= sf_admin_h($run['run_label']) ?></h2></div><strong><?= sf_admin_h($run['overall_score']) ?>%</strong></div><p class="sf-admin-copy"><code><?= sf_admin_h($run['target_commit_sha']) ?></code> · <?= sf_admin_h($run['environment_key']) ?> · <?= sf_admin_h($run['run_status']) ?></p><div class="sf-admin-form-actions"><form method="post" class="sf-inline-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="run_automated"><input type="hidden" name="run_id" value="<?= (int)$run['id'] ?>"><button type="submit">Run Automated Checks</button></form><form method="post" class="sf-inline-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="complete_run"><input type="hidden" name="run_id" value="<?= (int)$run['id'] ?>"><input name="activation_notes" placeholder="Completion notes"><button type="submit">Complete Run</button></form></div></section>
<section class="sf-admin-card-grid"><?php foreach($sections as$section): ?><div class="sf-admin-action-card"><span><?= sf_admin_h(ucwords(str_replace('_',' ',$section['section_key']))) ?></span><strong><?= sf_admin_h($section['score']) ?>%</strong><small><?= (int)$section['passed'] ?> passed · <?= (int)$section['failed'] ?> failed · <?= (int)$section['pending'] ?> pending</small></div><?php endforeach; ?></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Blocker Board</span><h2><?= count($checks) ?> activation checks</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Section</th><th>Check</th><th>Status</th><th>Result</th><th>Evidence</th></tr></thead><tbody><?php foreach($checks as$check): ?><tr><td><?= sf_admin_h(ucwords(str_replace('_',' ',$check['section_key']))) ?></td><td><strong><?= sf_admin_h($check['check_label']) ?></strong><small><?= sf_admin_h($check['check_key']) ?> · <?= !empty($check['is_automated'])?'automated':'manual' ?></small></td><td><?= sf_admin_status_badge((string)$check['check_status']) ?></td><td><?= sf_admin_h($check['result_message']??'Pending') ?></td><td><?php if(empty($check['is_automated'])&&!sf_sa_locked($run)): ?><form method="post" class="sf-admin-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="manual_check"><input type="hidden" name="run_id" value="<?= (int)$run['id'] ?>"><input type="hidden" name="check_key" value="<?= sf_admin_h($check['check_key']) ?>"><select name="check_status"><option value="passed">Passed</option><option value="failed">Failed</option><option value="running">Running</option></select><select name="evidence_type"><option value="browser_test">Browser test</option><option value="transaction">Transaction</option><option value="provider_event">Provider event</option><option value="restore">Restore</option><option value="approval">Approval</option><option value="artifact">Artifact</option><option value="note">Note</option></select><input name="source_reference" placeholder="Ticket, URL, provider event, or artifact" required><input name="artifact_sha256" pattern="[a-fA-F0-9]{64}" maxlength="64" placeholder="Optional SHA-256"><textarea name="result_message" rows="2" placeholder="What passed, account/browser used, expected result, and actual result" required></textarea><button type="submit">Record</button></form><?php else: ?><?= !empty($check['evidence_hash'])?'<code>'.sf_admin_h(substr((string)$check['evidence_hash'],0,12)).'</code>':'—' ?><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php if(($run['run_status']??'')==='passed'): ?><section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Release Candidate</span><h2>Create exact artifact binding</h2></div></div><form class="sf-admin-form" method="post"><?= sf_csrf_field() ?><input type="hidden" name="action" value="create_candidate"><input type="hidden" name="run_id" value="<?= (int)$run['id'] ?>"><label>Candidate Label<input name="candidate_label" placeholder="Stonefellow RC <?= sf_admin_h(substr((string)$run['target_commit_sha'],0,12)) ?>"></label><label>Artifact URL<input type="url" name="artifact_url" value="https://github.com/bigriversocial74/stonefellow-membership-platform/archive/refs/heads/main.zip" required></label><label>Artifact SHA-256<input name="artifact_sha256" pattern="[a-fA-F0-9]{64}" maxlength="64" required></label><label>Release Notes<textarea name="release_notes" rows="4"></textarea></label><button type="submit">Create Ready Candidate</button></form></section><?php endif; ?>
<?php endif; ?>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Candidates</span><h2><?= count($candidates) ?> release candidates</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Candidate</th><th>Commit</th><th>Artifact</th><th>Status</th><th>Freeze</th></tr></thead><tbody><?php foreach($candidates as$candidate): ?><tr><td><strong><?= sf_admin_h($candidate['candidate_label']) ?></strong><small><?= sf_admin_h($candidate['candidate_key']) ?></small></td><td><code><?= sf_admin_h(substr((string)$candidate['target_commit_sha'],0,12)) ?></code></td><td><a href="<?= sf_admin_h($candidate['artifact_url']) ?>">Open</a><small><?= sf_admin_h(substr((string)$candidate['artifact_sha256'],0,12)) ?>…</small></td><td><?= sf_admin_status_badge((string)$candidate['candidate_status']) ?></td><td><?php if(($candidate['candidate_status']??'')==='ready'): ?><form method="post" class="sf-admin-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="freeze_candidate"><input type="hidden" name="candidate_id" value="<?= (int)$candidate['id'] ?>"><input type="hidden" name="run_id" value="<?= (int)$candidate['activation_run_id'] ?>"><textarea name="freeze_notes" rows="2" placeholder="Document frozen scope, owners, rollback threshold, and approval boundary" required></textarea><button type="submit">Freeze Candidate</button></form><?php else: ?><?= sf_admin_h($candidate['frozen_at']??'—') ?><?php endif; ?></td></tr><?php endforeach; ?><?php if(!$candidates): ?><tr><td colspan="5">No release candidates yet.</td></tr><?php endif; ?></tbody></table></div></section>
<?php sf_admin_shell_end();require __DIR__.'/../includes/footer.php'; ?>
