<?php
$pageTitle='Staging Integration Matrix';
$pageDescription='Execute structured staging scenarios, record assertion evidence, correlate provider events, and promote passed results into launch certification.';
$pageClass='membership-page admin-catalog-page staging-integration-matrix-page';
require_once __DIR__.'/../includes/staging_integration_matrix.php';
if(function_exists('sf_agentic_require_permission'))sf_agentic_require_permission('admin.ops.manage');

if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
  $action=(string)($_POST['action']??'');$executionId=(int)($_POST['execution_id']??0);
  if($action==='create_execution'){$executionId=sf_sim_create_execution((int)($_POST['run_id']??0),(string)($_POST['scenario_key']??''),(string)($_POST['test_account_reference']??''));sf_admin_flash($executionId?'success':'error',$executionId?'Integration execution created.':'Execution was not created. Import the SQL, select an active run, and choose a valid scenario.');}
  elseif($action==='record_assertion'&&$executionId>0){$ok=sf_sim_record_assertion($executionId,(string)($_POST['assertion_key']??''),(string)($_POST['assertion_status']??'pending'),(string)($_POST['result_message']??''),(string)($_POST['source_reference']??''),(string)($_POST['evidence_sha256']??''));sf_admin_flash($ok?'success':'error',$ok?'Assertion evidence saved.':'Assertion evidence was rejected. Passed assertions require a meaningful result and source reference.');}
  elseif($action==='complete_execution'&&$executionId>0){$r=sf_sim_complete_execution($executionId,(string)($_POST['summary']??''));sf_admin_flash(!empty($r['ok'])?'success':'warning',(string)$r['message']);}
  sf_admin_redirect(sf_url('admin/staging-integration-matrix.php'.($executionId>0?'?execution_id='.$executionId:'')));
}
$runs=sf_slc_runs();$runId=(int)($_GET['run_id']??($runs[0]['id']??0));$executions=sf_sim_executions($runId,150);$executionId=(int)($_GET['execution_id']??($executions[0]['id']??0));$execution=sf_sim_execution($executionId);if($execution)$runId=(int)$execution['certification_run_id'];$assertions=$execution?sf_sim_assertions($executionId):[];$events=$execution?sf_sim_events($executionId):[];$catalog=sf_sim_catalog();
require __DIR__.'/../includes/header.php';
sf_admin_shell_start('Operations','Staging Integration Matrix','Execute repeatable, evidence-backed scenarios against a deployed staging release.','staging-integration-matrix');
?>
<style>.sim-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.sim-card,.sim-assertion{padding:16px;border:1px solid rgba(255,255,255,.1);border-radius:18px;background:rgba(255,255,255,.035)}.sim-card strong{display:block;font-size:24px;color:#fff;margin:6px 0}.sim-assertion h3{margin:8px 0}.sim-meta{display:flex;gap:6px;flex-wrap:wrap}.sim-pill{font-size:11px;border:1px solid rgba(232,198,127,.25);padding:4px 8px;border-radius:999px;color:#f5d98d}.sim-muted{color:rgba(255,255,255,.68);line-height:1.5}.sim-scenarios{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}@media(max-width:900px){.sim-grid,.sim-scenarios{grid-template-columns:1fr}}</style>
<?php if(!sf_sim_ready()): ?><div class="sf-admin-alert sf-admin-alert-warning"><strong>SQL required:</strong> import <code>database/staging_integration_matrix_v1.sql</code> after the launch-certification SQL.</div><?php endif; ?>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Scenario Execution</span><h2>Create a structured staging test</h2></div><a href="<?= sf_url('admin/staging-launch-certification.php?run_id='.$runId) ?>">Launch Certification</a></div>
<form method="post" class="sf-admin-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="create_execution"><div class="sf-admin-form-grid"><label>Certification run<select name="run_id" required><?php foreach($runs as $r): ?><option value="<?= (int)$r['id'] ?>"<?= (int)$r['id']===$runId?' selected':'' ?><?= sf_slc_locked($r)?' disabled':'' ?>><?= sf_admin_h($r['run_label'].' · '.$r['run_status']) ?></option><?php endforeach; ?></select></label><label>Scenario<select name="scenario_key" required><?php foreach($catalog as $key=>$scenario): ?><option value="<?= sf_admin_h($key) ?>"><?= sf_admin_h($scenario['label']) ?></option><?php endforeach; ?></select></label><label>Test account reference<input name="test_account_reference" maxlength="255" placeholder="Account ID or privacy-safe test alias"></label></div><div class="sf-admin-form-actions"><button type="submit"<?= sf_sim_ready()?'':' disabled' ?>>Create Execution</button></div></form></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Scenario Library</span><h2><?= count($catalog) ?> integration scenarios</h2></div></div><div class="sim-scenarios"><?php foreach($catalog as $key=>$scenario): ?><article class="sim-card"><span class="sim-pill"><?= sf_admin_h($scenario['stage']) ?></span><strong><?= sf_admin_h($scenario['label']) ?></strong><small class="sim-muted"><?= count($scenario['assertions']) ?> required assertions · promotes <?= count($scenario['checks']) ?> certification check<?= count($scenario['checks'])===1?'':'s' ?></small></article><?php endforeach; ?></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Execution History</span><h2><?= count($executions) ?> runs</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Scenario</th><th>Status</th><th>Correlation</th><th>Account</th><th>Started</th></tr></thead><tbody><?php foreach($executions as $e): ?><tr><td><a href="<?= sf_url('admin/staging-integration-matrix.php?execution_id='.(int)$e['id']) ?>"><strong><?= sf_admin_h($e['scenario_label']) ?></strong></a><small><?= sf_admin_h($e['run_label']) ?></small></td><td><?= sf_admin_status_badge($e['execution_status']) ?></td><td><code><?= sf_admin_h($e['correlation_id']) ?></code></td><td><?= sf_admin_h($e['test_account_reference']??'—') ?></td><td><?= sf_admin_h($e['started_at']) ?></td></tr><?php endforeach; ?><?php if(!$executions): ?><tr><td colspan="5">No integration executions for this run yet.</td></tr><?php endif; ?></tbody></table></div></section>
<?php if($execution): $counts=sf_sim_assertion_counts($executionId); ?>
<section class="sim-grid"><article class="sim-card"><span class="sf-panel-eyebrow">Scenario</span><strong><?= sf_admin_h($execution['scenario_label']) ?></strong><small class="sim-muted"><?= sf_admin_h($execution['execution_status']) ?></small></article><article class="sim-card"><span class="sf-panel-eyebrow">Assertions</span><strong><?= (int)$counts['passed_count'] ?> / <?= (int)$counts['required_count'] ?></strong><small class="sim-muted"><?= (int)$counts['failed_count'] ?> failed · <?= (int)$counts['pending_count'] ?> pending</small></article><article class="sim-card"><span class="sf-panel-eyebrow">Correlation ID</span><strong style="font-size:15px"><code><?= sf_admin_h($execution['correlation_id']) ?></code></strong><small class="sim-muted">Use in provider metadata and test logs.</small></article></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Assertions</span><h2>Required scenario proof</h2></div><small>Passed executions are immutable.</small></div><div class="sim-scenarios"><?php foreach($assertions as $a): ?><article class="sim-assertion"><div class="sim-meta"><span class="sim-pill"><?= sf_admin_h($a['assertion_key']) ?></span><?= sf_admin_status_badge($a['assertion_status']) ?></div><h3><?= sf_admin_h($a['assertion_label']) ?></h3><p class="sim-muted"><?= sf_admin_h($a['result_message']?:'No result recorded.') ?></p><?php if(!sf_sim_locked($execution)): ?><form method="post" class="sf-admin-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="record_assertion"><input type="hidden" name="execution_id" value="<?= $executionId ?>"><input type="hidden" name="assertion_key" value="<?= sf_admin_h($a['assertion_key']) ?>"><label>Status<?= sf_admin_select('assertion_status',['passed'=>'Passed','failed'=>'Failed','pending'=>'Pending','running'=>'Running','skipped'=>'Skipped'],$a['assertion_status']) ?></label><label>Result<textarea name="result_message" rows="3" required><?= sf_admin_h($a['result_message']??'') ?></textarea></label><label>Source reference<input name="source_reference" maxlength="1000" value="<?= sf_admin_h($a['source_reference']??'') ?>" placeholder="Provider event, test log, screenshot ID, query result, or artifact location"></label><label>Evidence SHA-256<input name="evidence_sha256" maxlength="64" pattern="[a-fA-F0-9]{64}" value="<?= sf_admin_h($a['evidence_sha256']??'') ?>"></label><button type="submit">Save Assertion</button></form><?php endif; ?></article><?php endforeach; ?></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Provider Events</span><h2><?= count($events) ?> correlated events</h2></div><small>POST signed events to <code>/api/staging-integration-event.php</code>.</small></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Event</th><th>Provider</th><th>Assertion</th><th>Status</th><th>Hash</th><th>Time</th></tr></thead><tbody><?php foreach($events as $event): ?><tr><td><?= sf_admin_h($event['event_type']) ?><small><?= sf_admin_h($event['source_event_id']??'') ?></small></td><td><?= sf_admin_h($event['provider']??'') ?></td><td><?= sf_admin_h($event['assertion_key']??'') ?></td><td><?= sf_admin_status_badge($event['event_status']) ?></td><td><code><?= sf_admin_h(substr($event['payload_hash'],0,16)) ?>…</code></td><td><?= sf_admin_h($event['created_at']) ?></td></tr><?php endforeach; ?><?php if(!$events): ?><tr><td colspan="6">No signed provider events correlated yet.</td></tr><?php endif; ?></tbody></table></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Complete Scenario</span><h2>Promote passed results</h2></div></div><form method="post" class="sf-admin-form"><?= sf_csrf_field() ?><input type="hidden" name="action" value="complete_execution"><input type="hidden" name="execution_id" value="<?= $executionId ?>"><label>Execution summary<textarea name="summary" rows="5" required><?= sf_admin_h($execution['summary']??'') ?></textarea></label><div class="sf-admin-form-actions"><button type="submit"<?= sf_sim_locked($execution)?' disabled':'' ?>>Evaluate Scenario</button></div></form></section>
<?php endif; ?>
<?php sf_admin_shell_end();require __DIR__.'/../includes/footer.php'; ?>
