<?php
$pageTitle = 'Storyboard Builder';
$pageDescription = 'AI-assisted 9-scene storyboard builder with character management, UX modals, scene actions, and job tracking.';
$pageClass = 'membership-page admin-catalog-page storyboards-page storyboard-builder-page';
require __DIR__ . '/../includes/storyboard_character_actions.php';
$project = sf_storyboard_project((int)($_GET['project_id'] ?? 1));
$projectId = (int)($project['id'] ?? 0);
$settings = sf_storyboard_settings($project);
$characters = sf_storyboard_characters($projectId);
$scenes = sf_storyboard_scenes($projectId);
$jobs = function_exists('sf_sbc_recent_jobs') ? sf_sbc_recent_jobs($projectId, 8) : [];
$returnUrl = sf_url('admin/storyboard-builder.php?project_id=' . $projectId);
$disabledAttr = sf_storyboard_ready() ? '' : ' disabled';
require __DIR__ . '/../includes/header.php';
sf_admin_shell_start('Storyboarding', 'Storyboard builder workspace', 'Create 9-scene storyboards, manage character references, assign characters to scenes, and run scene-level AI actions from one workspace.', 'storyboards');
?>
<section class="sf-admin-card-grid">
  <div class="sf-admin-action-card"><span>Storyboard</span><strong><?= sf_storyboard_h($project['title']) ?></strong><small><?= sf_storyboard_h($project['genre']) ?></small></div>
  <div class="sf-admin-action-card"><span>Scenes</span><strong><?= count($scenes) ?></strong><small><?= sf_storyboard_ready() ? 'Database-backed scene cards.' : 'Static shell scene cards.' ?></small></div>
  <div class="sf-admin-action-card"><span>Characters</span><strong><?= count($characters) ?></strong><small>Reference profiles for likeness consistency.</small></div>
  <a class="sf-admin-action-card" href="<?= sf_url('admin/ai-settings.php') ?>"><span>AI Provider</span><strong>Admin Managed</strong><small>No API key fields in the creator workspace.</small></a>
</section>

<section class="sf-admin-two-col sf-admin-two-col-wide">
  <article class="sf-admin-panel">
    <div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Script Prompt</span><h2><?= sf_storyboard_h($project['title']) ?></h2></div><span class="sf-admin-mini-pill"><?= strlen((string)($project['prompt'] ?? '')) ?> / 1000</span></div>
    <form class="sf-admin-form" method="post" action="<?= sf_url('api/storyboard-generate.php') ?>">
      <?= sf_csrf_field() ?><input type="hidden" name="storyboard_id" value="<?= (int)$projectId ?>"><input type="hidden" name="return_url" value="<?= sf_storyboard_h($returnUrl) ?>">
      <label>Prompt<textarea rows="7" name="story_prompt"<?= sf_admin_form_disabled_attr() ?>><?= sf_storyboard_h($project['prompt']) ?></textarea></label>
      <div class="sf-admin-form-actions"><button type="button"<?= sf_admin_form_disabled_attr() ?>>Enhance Prompt</button><button type="submit"<?= sf_admin_form_disabled_attr() ?>>Generate 9-Scene Storyboard</button></div>
    </form>
  </article>
  <aside class="sf-admin-panel">
    <div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Storyboard Settings</span><h2>Creator workflow</h2></div><a href="<?= sf_url('admin/ai-settings.php') ?>">AI Settings</a></div>
    <div class="sf-admin-list"><?php foreach ($settings as $label => $value): ?><article class="sf-admin-list-row"><strong><?= sf_storyboard_h(ucwords(str_replace('_',' ', $label))) ?></strong><span><?= sf_storyboard_h($value) ?></span></article><?php endforeach; ?></div>
    <form class="sf-admin-form" method="post" action="<?= sf_url('api/storyboard-character-action.php') ?>">
      <?= sf_csrf_field() ?><input type="hidden" name="action" value="bulk_regenerate_images"><input type="hidden" name="storyboard_id" value="<?= (int)$projectId ?>"><input type="hidden" name="return_url" value="<?= sf_storyboard_h($returnUrl) ?>">
      <div class="sf-admin-form-actions"><button type="submit"<?= $disabledAttr ?>>Bulk Regenerate All Scene Images</button></div>
    </form>
  </aside>
</section>

<section class="sf-admin-panel">
  <div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Characters</span><h2>Reference library + management</h2></div><span class="sf-admin-mini-pill">Phase 44</span></div>
  <p class="sf-admin-copy">Add characters, upload reference images, maintain likeness notes, and assign/remove characters from individual scenes.</p>
  <details class="sf-storyboard-modal-card"><summary>Add Character</summary>
    <form class="sf-admin-form" method="post" action="<?= sf_url('api/storyboard-character-action.php') ?>">
      <?= sf_csrf_field() ?><input type="hidden" name="action" value="add_character"><input type="hidden" name="storyboard_id" value="<?= (int)$projectId ?>"><input type="hidden" name="return_url" value="<?= sf_storyboard_h($returnUrl) ?>">
      <div class="sf-admin-form-grid"><label>Name<input name="character_name" placeholder="Lead Musician"<?= $disabledAttr ?>></label><label>Role<input name="role_label" placeholder="Primary"<?= $disabledAttr ?>></label><label>Likeness Strength<select name="likeness_strength"<?= $disabledAttr ?>><option value="loose">Loose</option><option value="medium" selected>Medium</option><option value="strong">Strong</option></select></label></div>
      <label>Appearance Notes<textarea rows="2" name="appearance_notes"<?= $disabledAttr ?>></textarea></label><label>Wardrobe Notes<textarea rows="2" name="wardrobe_notes"<?= $disabledAttr ?>></textarea></label><label>Consistency Prompt<textarea rows="3" name="consistency_prompt"<?= $disabledAttr ?>></textarea></label>
      <div class="sf-admin-form-actions"><button type="submit"<?= $disabledAttr ?>>Save Character</button></div>
    </form>
  </details>
  <div class="sf-storyboard-character-grid">
    <?php foreach ($characters as $character): $characterId = (int)($character['id'] ?? 0); $charDisabled = ($characterId > 0 && sf_storyboard_ready()) ? '' : ' disabled'; ?>
      <article class="sf-storyboard-character-card"><div class="sf-storyboard-thumb sf-storyboard-character-thumb" style="background-image:url('<?= sf_storyboard_h(sf_url($character['image'])) ?>')"></div><div class="sf-storyboard-character-body"><span><?= sf_storyboard_h($character['role']) ?></span><strong><?= sf_storyboard_h($character['name']) ?></strong><small><?= sf_storyboard_h($character['summary']) ?></small><small><strong>Consistency:</strong> <?= sf_storyboard_h($character['notes']) ?></small><details><summary>Manage Character</summary><form class="sf-admin-form" method="post" action="<?= sf_url('api/storyboard-character-action.php') ?>"><?= sf_csrf_field() ?><input type="hidden" name="action" value="update_character"><input type="hidden" name="character_id" value="<?= $characterId ?>"><input type="hidden" name="return_url" value="<?= sf_storyboard_h($returnUrl) ?>"><label>Name<input name="character_name" value="<?= sf_storyboard_h($character['name']) ?>"<?= $charDisabled ?>></label><label>Role<input name="role_label" value="<?= sf_storyboard_h($character['role']) ?>"<?= $charDisabled ?>></label><label>Appearance<textarea rows="2" name="appearance_notes"<?= $charDisabled ?>><?= sf_storyboard_h($character['summary']) ?></textarea></label><label>Consistency<textarea rows="3" name="consistency_prompt"<?= $charDisabled ?>><?= sf_storyboard_h($character['notes']) ?></textarea></label><div class="sf-admin-form-actions"><button type="submit"<?= $charDisabled ?>>Update</button></div></form><form class="sf-admin-form" method="post" enctype="multipart/form-data" action="<?= sf_url('api/storyboard-character-action.php') ?>"><?= sf_csrf_field() ?><input type="hidden" name="action" value="upload_reference"><input type="hidden" name="character_id" value="<?= $characterId ?>"><input type="hidden" name="return_url" value="<?= sf_storyboard_h($returnUrl) ?>"><label>Reference Image<input type="file" name="reference_image" accept="image/*"<?= $charDisabled ?>></label><div class="sf-admin-form-actions"><button type="submit"<?= $charDisabled ?>>Upload Reference</button></div></form></details></div></article>
    <?php endforeach; ?>
  </div>
</section>

<section class="sf-admin-panel">
  <div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Storyboard</span><h2>9-scene screenplay grid</h2></div><div class="sf-admin-inline-form"><button type="button">View 3x3</button><button type="button">Expand All</button></div></div>
  <p class="sf-admin-copy">Scene cards now use expandable modal-style panels for editing, rewriting, image actions, and character assignment.</p>
  <div class="sf-storyboard-scene-grid">
    <?php foreach ($scenes as $scene): $sceneId = (int)($scene['id'] ?? 0); $sceneDisabled = ($sceneId > 0 && sf_storyboard_ready()) ? '' : ' disabled'; $currentSceneStatus = strtolower(str_replace(' ', '_', (string)($scene['status'] ?? 'draft'))); ?>
      <article id="scene-<?= (int)$scene['number'] ?>" class="sf-storyboard-scene-card">
        <div class="sf-storyboard-thumb sf-storyboard-scene-thumb" style="background-image:url('<?= sf_storyboard_h(sf_url($scene['image'])) ?>')"><span><?= (int)$scene['number'] ?></span></div>
        <div class="sf-storyboard-scene-body"><span>Scene <?= (int)$scene['number'] ?> · <?= sf_storyboard_h($scene['status']) ?> · Image <?= sf_storyboard_h($scene['image_status'] ?? 'none') ?> · Rewrite <?= sf_storyboard_h($scene['rewrite_status'] ?? 'none') ?></span><strong><?= sf_storyboard_h($scene['title']) ?></strong><small><strong>Prompt:</strong> <?= sf_storyboard_h($scene['prompt']) ?></small><small><strong>Dialog:</strong> “<?= sf_storyboard_h($scene['dialog']) ?>”</small><small><strong>Characters:</strong> <?php foreach ($scene['characters'] as $characterName) echo sf_storyboard_render_character_chip($characterName) . ' '; ?></small>
          <details class="sf-storyboard-scene-editor"><summary>Scene Actions</summary>
            <form class="sf-admin-form" method="post" action="<?= sf_url('api/storyboard-scene-action.php') ?>"><?= sf_csrf_field() ?><input type="hidden" name="action" value="edit_scene"><input type="hidden" name="scene_id" value="<?= $sceneId ?>"><input type="hidden" name="return_url" value="<?= sf_storyboard_h($returnUrl . '#scene-' . (int)$scene['number']) ?>"><label>Title<input name="scene_title" value="<?= sf_storyboard_h($scene['title']) ?>"<?= $sceneDisabled ?>></label><label>Summary<textarea rows="2" name="scene_summary"<?= $sceneDisabled ?>><?= sf_storyboard_h($scene['summary'] ?? '') ?></textarea></label><label>Scene Prompt<textarea rows="3" name="scene_prompt"<?= $sceneDisabled ?>><?= sf_storyboard_h($scene['prompt']) ?></textarea></label><label>Image Prompt<textarea rows="3" name="image_prompt"<?= $sceneDisabled ?>><?= sf_storyboard_h($scene['image_prompt'] ?? '') ?></textarea></label><label>Dialog<textarea rows="3" name="dialog_text"<?= $sceneDisabled ?>><?= sf_storyboard_h($scene['dialog']) ?></textarea></label><label>Action Notes<textarea rows="2" name="action_notes"<?= $sceneDisabled ?>><?= sf_storyboard_h($scene['action_notes'] ?? '') ?></textarea></label><div class="sf-admin-form-grid"><label>Location<input name="location_label" value="<?= sf_storyboard_h($scene['location_label'] ?? '') ?>"<?= $sceneDisabled ?>></label><label>Time<input name="time_of_day" value="<?= sf_storyboard_h($scene['time_of_day'] ?? '') ?>"<?= $sceneDisabled ?>></label><label>Status<select name="scene_status"<?= $sceneDisabled ?>><option value="draft"<?= $currentSceneStatus==='draft'?' selected':'' ?>>Draft</option><option value="needs_review"<?= $currentSceneStatus==='needs_review'?' selected':'' ?>>Needs Review</option><option value="ready"<?= $currentSceneStatus==='ready'?' selected':'' ?>>Ready</option><option value="archived"<?= $currentSceneStatus==='archived'?' selected':'' ?>>Archived</option></select></label></div><div class="sf-admin-form-actions"><button type="submit"<?= $sceneDisabled ?>>Save Scene</button></div></form>
            <form class="sf-admin-form" method="post" action="<?= sf_url('api/storyboard-scene-action.php') ?>"><?= sf_csrf_field() ?><input type="hidden" name="action" value="rewrite_scene"><input type="hidden" name="scene_id" value="<?= $sceneId ?>"><input type="hidden" name="return_url" value="<?= sf_storyboard_h($returnUrl . '#scene-' . (int)$scene['number']) ?>"><label>Rewrite Instruction<input name="rewrite_instruction" placeholder="Make this scene tighter, funnier, more cinematic..."<?= $sceneDisabled ?>></label><div class="sf-admin-form-actions"><button type="submit"<?= $sceneDisabled ?>>Rewrite Scene</button></div></form>
            <form class="sf-admin-form" method="post" action="<?= sf_url('api/storyboard-scene-action.php') ?>"><?= sf_csrf_field() ?><input type="hidden" name="action" value="regenerate_image"><input type="hidden" name="scene_id" value="<?= $sceneId ?>"><input type="hidden" name="return_url" value="<?= sf_storyboard_h($returnUrl . '#scene-' . (int)$scene['number']) ?>"><div class="sf-admin-form-actions"><button type="submit"<?= $sceneDisabled ?>>Regenerate Image</button></div></form>
            <form class="sf-admin-form" method="post" enctype="multipart/form-data" action="<?= sf_url('api/storyboard-scene-action.php') ?>"><?= sf_csrf_field() ?><input type="hidden" name="action" value="upload_image"><input type="hidden" name="scene_id" value="<?= $sceneId ?>"><input type="hidden" name="return_url" value="<?= sf_storyboard_h($returnUrl . '#scene-' . (int)$scene['number']) ?>"><label>Upload Replacement Image<input type="file" name="scene_image" accept="image/*"<?= $sceneDisabled ?>></label><div class="sf-admin-form-actions"><button type="submit"<?= $sceneDisabled ?>>Upload Image</button></div></form>
            <form class="sf-admin-form" method="post" action="<?= sf_url('api/storyboard-character-action.php') ?>"><?= sf_csrf_field() ?><input type="hidden" name="action" value="assign_scene_character"><input type="hidden" name="storyboard_id" value="<?= (int)$projectId ?>"><input type="hidden" name="scene_id" value="<?= $sceneId ?>"><input type="hidden" name="return_url" value="<?= sf_storyboard_h($returnUrl . '#scene-' . (int)$scene['number']) ?>"><label>Assign Character<select name="character_id"<?= $sceneDisabled ?>><?php foreach ($characters as $character): ?><option value="<?= (int)$character['id'] ?>"><?= sf_storyboard_h($character['name']) ?></option><?php endforeach; ?></select></label><div class="sf-admin-form-actions"><button type="submit"<?= $sceneDisabled ?>>Assign Character</button></div></form>
            <form class="sf-admin-form" method="post" action="<?= sf_url('api/storyboard-character-action.php') ?>"><?= sf_csrf_field() ?><input type="hidden" name="action" value="remove_scene_character"><input type="hidden" name="scene_id" value="<?= $sceneId ?>"><input type="hidden" name="return_url" value="<?= sf_storyboard_h($returnUrl . '#scene-' . (int)$scene['number']) ?>"><label>Remove Character<select name="character_id"<?= $sceneDisabled ?>><?php foreach ($characters as $character): ?><option value="<?= (int)$character['id'] ?>"><?= sf_storyboard_h($character['name']) ?></option><?php endforeach; ?></select></label><div class="sf-admin-form-actions"><button type="submit"<?= $sceneDisabled ?>>Remove Character</button></div></form>
          </details>
        </div>
      </article>
    <?php endforeach; ?>
  </div>
</section>

<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Jobs</span><h2>Recent storyboard jobs</h2></div><span class="sf-admin-mini-pill">Retry Ready</span></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Job</th><th>Scene</th><th>Status</th><th>Updated</th><th>Retry</th></tr></thead><tbody><?php foreach ($jobs as $job): ?><tr><td><strong><?= sf_storyboard_h($job['job_type']) ?></strong><small><?= sf_storyboard_h($job['provider_key'] ?? '') ?></small></td><td><?= !empty($job['scene_number']) ? 'Scene ' . (int)$job['scene_number'] . ' — ' . sf_storyboard_h($job['scene_title']) : 'Storyboard' ?></td><td><?= sf_admin_status_badge($job['job_status'] ?? 'queued') ?></td><td><?= sf_storyboard_h($job['updated_at'] ?? $job['created_at'] ?? '') ?></td><td><form method="post" action="<?= sf_url('api/storyboard-scene-action.php') ?>"><?= sf_csrf_field() ?><input type="hidden" name="action" value="retry_job"><input type="hidden" name="job_id" value="<?= (int)$job['id'] ?>"><input type="hidden" name="return_url" value="<?= sf_storyboard_h($returnUrl) ?>"><button type="submit">Retry</button></form></td></tr><?php endforeach; ?><?php if (!$jobs): ?><tr><td colspan="5">No storyboard jobs yet.</td></tr><?php endif; ?></tbody></table></div></section>

<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Implementation Notes</span><h2>What Phase 44 adds</h2></div><a href="<?= sf_url('docs/PHASE_44_CHARACTER_MANAGEMENT_UX.md') ?>">Phase Docs</a></div><div class="sf-admin-roadmap"><div><span>Cast</span><strong>Character management</strong><p>Add/update characters, upload references, and maintain consistency notes.</p></div><div><span>Scenes</span><strong>Assignments</strong><p>Assign or remove characters from scenes for stronger rewrite/image context.</p></div><div><span>UX</span><strong>Modal-style panels</strong><p>Expandable action panels replace flat inline controls.</p></div><div><span>Jobs</span><strong>Retry controls</strong><p>Recent job table exposes status badges and retry actions.</p></div></div></section>
<?php sf_admin_shell_end(); require __DIR__ . '/../includes/footer.php'; ?>
