<?php
declare(strict_types=1);
$pageTitle='VP3 Clips';$pageDescription='Create vertical clip renditions from your protected media, publish them to VP3 Clips, and reconcile moderation and network analytics.';$pageClass='membership-page admin-catalog-page';require_once __DIR__.'/../includes/admin_catalog.php';require_once __DIR__.'/../includes/vp3_clips.php';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){$action=(string)($_POST['action']??'');try{if($action==='run_next'){$result=sf_vp3_clip_process_next();sf_admin_flash(!empty($result['ok'])?'success':'error',!empty($result['idle'])?'No clip jobs are waiting.':(!empty($result['ok'])?'Clip job completed.':'Clip job failed: '.($result['error']??'unknown error')));}elseif($action==='queue_sync'){sf_vp3_clip_queue((int)$_POST['clip_id'],'status');sf_admin_flash('success','Status and analytics sync queued.');}}catch(Throwable $e){sf_admin_flash('error',$e->getMessage());}sf_admin_redirect(sf_url('admin/vp3-clips.php'));}
$ready=sf_vp3_clip_tables_ready();$clips=sf_vp3_clip_list();$counts=[];foreach($clips as $c)$counts[$c['local_status']]=($counts[$c['local_status']]??0)+1;require __DIR__.'/../includes/header.php';sf_admin_shell_start('VP3 Network','Clip Creator & Publishing Bridge','Stonefellow owns the source, trim, rendition, rights, schedule, and destination. VP3 owns verification, moderation, feed distribution, and network analytics.','vp3-clips');
?>
<section class="sf-admin-card-grid"><a class="sf-admin-action-card" href="<?=sf_url('admin/vp3-clip-editor.php')?>"><span>Create</span><strong>New Clip</strong><small>Select a ready video, trim it, render a vertical rendition, and publish.</small></a><a class="sf-admin-action-card" href="<?=sf_url('admin/vp3-clips-settings.php')?>"><span>Connection</span><strong>VP3 Bridge</strong><small>Private credential and creator/show identities.</small></a><div class="sf-admin-action-card"><span>Clips</span><strong><?=count($clips)?></strong><small><?=number_format((int)($counts['published']??0))?> published · <?=number_format((int)($counts['pending']??0))?> pending</small></div><div class="sf-admin-action-card"><span>Schema</span><strong><?=$ready?'READY':'IMPORT 027'?></strong><small>Local clips and sync ledger.</small></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Worker</span><h2>Render and synchronization queue</h2></div><form method="post"><?=sf_csrf_field()?><input type="hidden" name="action" value="run_next"><button type="submit">Run next job</button></form></div><p>Production should run <code>php jobs/vp3-clips-worker.php</code> from cron or a supervised worker. The admin action processes one bounded job for setup and QA.</p></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Source-owned catalog</span><h2>Clip publications</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Clip</th><th>Source</th><th>Duration</th><th>Local</th><th>VP3 moderation</th><th>Feed</th><th>Updated</th><th></th></tr></thead><tbody><?php foreach($clips as $clip):?><tr><td><strong><?=sf_admin_h($clip['title'])?></strong><small><?=sf_admin_h($clip['clip_uuid'])?></small></td><td><?=sf_admin_h($clip['source_type'].' #'.$clip['source_id'])?></td><td><?=(int)$clip['duration_seconds']?> sec · <?=sf_admin_h($clip['aspect_ratio'])?></td><td><?=sf_admin_status_badge($clip['local_status'])?></td><td><?=sf_admin_h(($clip['central_moderation_status']?:'not submitted').' / '.($clip['central_rights_status']?:'local'))?></td><td><?=!empty($clip['central_feed_eligible'])?'Eligible':'Held'?></td><td><?=sf_admin_h($clip['updated_at']??$clip['created_at'])?></td><td><a href="<?=sf_url('admin/vp3-clip-editor.php?id='.(int)$clip['id'])?>">Open</a></td></tr><?php endforeach;?><?php if(!$clips):?><tr><td colspan="8">No clips yet. Import migration 027, configure the bridge, and create the first source-owned clip.</td></tr><?php endif;?></tbody></table></div></section>
<?php sf_admin_shell_end();require __DIR__.'/../includes/footer.php';?>
