<?php
declare(strict_types=1);
$pageTitle='VP3 Clips Certification';$pageDescription='Run non-destructive environment checks, a synthetic FFmpeg render probe, signed central authentication, and live publishing approval reconciliation.';$pageClass='membership-page admin-catalog-page';
require_once __DIR__.'/../includes/admin_catalog.php';require_once __DIR__.'/../includes/vp3_clips.php';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    $action=(string)($_POST['action']??'');
    try{
        if($action==='run'){$result=sf_vp3_clip_certification_submit(sf_current_user_id());sf_admin_flash(!empty($result['ok'])?'success':'error',!empty($result['ok'])?'Certification report submitted. Current status: '.($result['data']['certification_status']??'unknown').'.':'Certification failed: '.($result['error']??'unknown error'));}
        elseif($action==='refresh'){$result=sf_vp3_clip_certification_refresh();sf_admin_flash(!empty($result['ok'])?'success':'error',!empty($result['ok'])?'Central certification status refreshed: '.($result['data']['certification_status']??'unknown').'.':'Status refresh failed: '.($result['error']??'unknown error'));}
    }catch(Throwable $e){sf_admin_flash('error',$e->getMessage());}
    sf_admin_redirect(sf_url('admin/vp3-clips-certification.php'));
}
$latest=sf_vp3_clip_certification_latest();$history=sf_vp3_clip_certification_history();$checks=$latest?json_decode((string)$latest['checks_json'],true):[];
require __DIR__.'/../includes/header.php';sf_admin_shell_start('VP3 Network','Live Clips Integration Certification','Prove this licensed installation can render, host, authenticate, and reconcile clips before central VP3 live publishing is enabled.','vp3-clips-settings');
?>
<style>.cert-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.cert-card{padding:18px;border:1px solid rgba(255,255,255,.1);border-radius:18px;background:rgba(255,255,255,.035)}.cert-card strong{display:block;font-size:1.25rem;margin-top:7px}.cert-actions{display:flex;gap:10px;flex-wrap:wrap}.cert-checks{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.cert-check{padding:14px;border:1px solid rgba(255,255,255,.1);border-radius:14px}.cert-check small{display:block;color:rgba(255,255,255,.65);margin-top:5px}@media(max-width:900px){.cert-grid,.cert-checks{grid-template-columns:1fr 1fr}}@media(max-width:620px){.cert-grid,.cert-checks{grid-template-columns:1fr}}</style>
<section class="cert-grid"><article class="cert-card"><span class="sf-panel-eyebrow">Local status</span><strong><?=sf_admin_h($latest['status']??'not_started')?></strong></article><article class="cert-card"><span class="sf-panel-eyebrow">Publishing mode</span><strong><?=sf_admin_h($latest['publishing_mode']??'certification')?></strong></article><article class="cert-card"><span class="sf-panel-eyebrow">Certification</span><strong><?=sf_admin_h($latest['certification_uuid']??'Not submitted')?></strong></article><article class="cert-card"><span class="sf-panel-eyebrow">Expires</span><strong><?=sf_admin_h($latest['expires_at']??'—')?></strong></article></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Certification run</span><h2>Non-destructive live readiness test</h2></div></div><p>The test validates migrations 027–028, the license receipt, encrypted bridge settings, TLS, OpenSSL, FFmpeg/FFprobe, private storage, public HTTPS identity, signed VP3 context authentication, and a two-second synthetic render. The generated probe files are deleted immediately and no feed publication is created.</p><div class="cert-actions"><form method="post"><?=sf_csrf_field()?><input type="hidden" name="action" value="run"><button type="submit">Run full certification</button></form><form method="post"><?=sf_csrf_field()?><input type="hidden" name="action" value="refresh"><button type="submit">Refresh VP3 approval</button></form><a href="<?=sf_url('admin/vp3-clips-settings.php')?>">Connection settings</a><a href="<?=sf_url('admin/vp3-clips.php')?>">Clip workspace</a></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Latest evidence</span><h2><?=count((array)$checks)?> checks</h2></div></div><div class="cert-checks"><?php foreach((array)$checks as $name=>$check):?><article class="cert-check"><strong><?=sf_admin_h(ucwords(str_replace('_',' ',$name)))?> · <?=sf_admin_h($check['status']??'unknown')?></strong><small><?=sf_admin_h($check['detail']??'')?></small></article><?php endforeach;?><?php if(!$checks):?><p>No certification evidence has been recorded yet.</p><?php endif;?></div></section>
<section class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">History</span><h2><?=count($history)?> certification runs</h2></div></div><div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr><th>Certification</th><th>Bridge</th><th>Status</th><th>Mode</th><th>Failure</th><th>Started</th><th>Approval / expiry</th></tr></thead><tbody><?php foreach($history as $row):?><tr><td><code><?=sf_admin_h($row['certification_uuid']??'—')?></code></td><td><code><?=sf_admin_h($row['bridge_uuid'])?></code></td><td><?=sf_admin_status_badge((string)$row['status'])?></td><td><?=sf_admin_h($row['publishing_mode'])?></td><td><?=sf_admin_h($row['failure_summary']??'—')?></td><td><?=sf_admin_h($row['started_at'])?></td><td><?=sf_admin_h($row['approved_at']??'—')?><br><small><?=sf_admin_h($row['expires_at']??'')?></small></td></tr><?php endforeach;?><?php if(!$history):?><tr><td colspan="7">No certification runs yet. Import migration 028, save bridge settings, then run the certification.</td></tr><?php endif;?></tbody></table></div></section>
<?php sf_admin_shell_end();require __DIR__.'/../includes/footer.php';?>
