<?php
declare(strict_types=1);
$pageTitle='VP3 Clips Connection';$pageDescription='Connect this licensed Stonefellow installation to its verified VP3 Network listing without storing the product license key.';$pageClass='membership-page admin-catalog-page';
require_once __DIR__.'/../includes/admin_catalog.php';require_once __DIR__.'/../includes/vp3_clips.php';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){$action=(string)($_POST['action']??'save');try{if($action==='save'){sf_vp3_clip_save_settings($_POST);sf_admin_flash('success','Private VP3 Clips bridge settings saved. Run a fresh certification for this credential.');}elseif($action==='test'){$result=sf_vp3_clip_context();sf_admin_flash(!empty($result['ok'])?'success':'error',!empty($result['ok'])?'VP3 bridge authenticated. Publishing mode: '.($result['data']['publishing_mode']??'certification').'.':'VP3 bridge test failed: '.($result['error']??'unknown error'));}}catch(Throwable $e){sf_admin_flash('error',$e->getMessage());}sf_admin_redirect(sf_url('admin/vp3-clips-settings.php'));}
$settings=sf_vp3_clip_settings();$receipt=sf_license_receipt();$latest=sf_vp3_clip_certification_latest();require __DIR__.'/../includes/header.php';sf_admin_shell_start('VP3 Network','Clips Publishing Connection','Store the one-time bridge credential privately, verify the licensed installation, and complete live integration certification.','vp3-clips-settings');
?>
<section class="sf-admin-two-col sf-admin-two-col-wide"><article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Private configuration</span><h2>VP3 bridge credential</h2></div></div><form method="post" class="sf-admin-form" autocomplete="off"><?=sf_csrf_field()?><input type="hidden" name="action" value="save"><label>VP3 API base URL<input type="url" name="api_base" required placeholder="https://vp3media.com" value="<?=sf_admin_h($settings['api_base']??'')?>"></label><label>Bridge ID<input name="bridge_uuid" required value="<?=sf_admin_h($settings['bridge_uuid']??'')?>"></label><label>Bridge secret<input type="password" name="bridge_secret" autocomplete="new-password" placeholder="<?=!empty($settings['bridge_secret'])?'Configured — leave blank to keep current secret':'Paste the one-time secret from VP3'?>"></label><div class="sf-admin-form-grid"><label>Creator UUID<input name="source_creator_uuid" value="<?=sf_admin_h($settings['source_creator_uuid']??'')?>"></label><label>Show UUID<input name="source_show_uuid" value="<?=sf_admin_h($settings['source_show_uuid']??'')?>"></label></div><button type="submit">Save private connection</button></form><div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:12px"><form method="post"><?=sf_csrf_field()?><input type="hidden" name="action" value="test"><button type="submit">Test signed connection</button></form><a href="<?=sf_url('admin/vp3-clips-certification.php')?>">Open live certification</a></div></article><article class="sf-admin-panel"><div class="sf-admin-panel-head"><div><span class="sf-panel-eyebrow">Installed product</span><h2>License and certification boundary</h2></div></div><?php if($receipt):?><div class="sf-admin-detail-list"><div><span>Product</span><strong><?=sf_admin_h($receipt['product_id']??'')?></strong></div><div><span>Installation</span><strong><?=sf_admin_h($receipt['installation_id']??'')?></strong></div><div><span>Domain</span><strong><?=sf_admin_h($receipt['activated_domain']??'')?></strong></div><div><span>Base URL</span><strong><?=sf_admin_h($receipt['base_url']??'')?></strong></div><div><span>Certification</span><strong><?=sf_admin_h($latest['status']??'not_started')?></strong></div><div><span>Publishing mode</span><strong><?=sf_admin_h($latest['publishing_mode']??'certification')?></strong></div></div><?php else:?><p>No private product-license receipt is installed. Activate the installation before connecting VP3 Clips.</p><?php endif;?><p>The complete product key is never requested or stored here. Real clip publication remains blocked until the current bridge credential has a passing report and explicit VP3 approval.</p></article></section>
<?php sf_admin_shell_end();require __DIR__.'/../includes/footer.php';?>
