<?php
require_once __DIR__ . '/ai_governance.php';

function sf_ai_mission_ready(): bool { return function_exists('sf_admin_table_exists')&&sf_admin_table_exists('ai_operation_missions')&&sf_admin_table_exists('ai_operation_mission_items'); }
function sf_ai_mission_actions_ready(): bool { return function_exists('sf_admin_table_exists')&&sf_admin_table_exists('ai_platform_actions'); }
function sf_ai_mission_logs_ready(): bool { return function_exists('sf_admin_table_exists')&&sf_admin_table_exists('ai_platform_action_executions'); }
function sf_ai_mission_text($value,string $fallback='Not set'): string { $text=trim((string)($value??''));return$text===''?$fallback:$text; }
function sf_ai_mission_missions(): array { return sf_ai_mission_ready()?sf_admin_fetch_all("SELECT m.*,COUNT(i.id) item_count,SUM(i.item_status='completed') completed_count,SUM(i.item_status IN ('blocked','failed')) blocked_count FROM ai_operation_missions m LEFT JOIN ai_operation_mission_items i ON i.mission_id=m.id WHERE m.mission_status IN ('approved','in_progress','blocked','completed') GROUP BY m.id ORDER BY FIELD(m.mission_status,'in_progress','approved','blocked','completed'),m.updated_at DESC,m.id DESC LIMIT 80"):[]; }
function sf_ai_mission_items(int $missionId): array { return sf_ai_mission_ready()&&$missionId>0?sf_admin_fetch_all('SELECT i.*,a.title,a.action_type,a.action_area,a.risk_level,a.approval_status,a.execution_status FROM ai_operation_mission_items i LEFT JOIN ai_platform_actions a ON a.id=i.platform_action_id WHERE i.mission_id=? ORDER BY i.item_order,i.id',[$missionId]):[]; }
function sf_ai_mission_counts(): array { $out=[];foreach(['approved','in_progress','completed','blocked']as$status)$out[$status]=sf_ai_mission_ready()?(int)(sf_admin_fetch_one('SELECT COUNT(*) total FROM ai_operation_missions WHERE mission_status=?',[$status])['total']??0):0;return$out; }
function sf_ai_mission_remaining_count(int $missionId): int { return sf_ai_mission_ready()&&$missionId>0?(int)(sf_admin_fetch_one("SELECT COUNT(*) total FROM ai_operation_mission_items WHERE mission_id=? AND item_status NOT IN ('completed','skipped')",[$missionId])['total']??0):0; }
function sf_ai_mission_blocked_item_count(int $missionId): int { return sf_ai_mission_ready()&&$missionId>0?(int)(sf_admin_fetch_one("SELECT COUNT(*) total FROM ai_operation_mission_items WHERE mission_id=? AND item_status IN ('blocked','failed','running')",[$missionId])['total']??0):0; }
function sf_ai_mission_mark_terminal_if_done(int $missionId): void { if(sf_ai_mission_remaining_count($missionId)===0)sf_admin_execute("UPDATE ai_operation_missions SET mission_status='completed',completed_at=NOW() WHERE id=?",[$missionId]); }
function sf_ai_mission_resume_if_unblocked(int $missionId): void { if(sf_ai_mission_remaining_count($missionId)>0&&sf_ai_mission_blocked_item_count($missionId)===0)sf_admin_execute("UPDATE ai_operation_missions SET mission_status='approved' WHERE id=? AND mission_status='blocked'",[$missionId]); }
function sf_ai_mission_item_message(array $result): string { return sf_ai_mission_text($result['message']??'','Execution route finished.'); }
function sf_ai_mission_claim_next(int $missionId): ?array
{
    $pdo=sf_admin_db();if(!$pdo)return null;try{$pdo->beginTransaction();$stmt=$pdo->prepare('SELECT * FROM ai_operation_missions WHERE id=? FOR UPDATE');$stmt->execute([$missionId]);$mission=$stmt->fetch();if(!$mission||!in_array((string)$mission['mission_status'],['approved','in_progress'],true)){$pdo->rollBack();return null;}$itemStmt=$pdo->prepare("SELECT i.*,a.approval_status,a.execution_status,a.action_type,a.risk_level,a.title,a.payload_json,a.approved_by_user_id,a.approved_at,a.updated_at action_updated_at FROM ai_operation_mission_items i INNER JOIN ai_platform_actions a ON a.id=i.platform_action_id WHERE i.mission_id=? AND i.item_status IN ('pending','ready') AND a.approval_status='ready_for_execution' AND a.execution_status='ready' ORDER BY i.item_order,i.id LIMIT 1 FOR UPDATE");$itemStmt->execute([$missionId]);$item=$itemStmt->fetch();if(!$item){$pdo->rollBack();return null;}$update=$pdo->prepare("UPDATE ai_operation_mission_items SET item_status='running',last_result_message='Execution started.' WHERE id=? AND item_status IN ('pending','ready')");$update->execute([(int)$item['id']]);if($update->rowCount()!==1){$pdo->rollBack();return null;}$pdo->prepare("UPDATE ai_operation_missions SET mission_status='in_progress' WHERE id=?")->execute([$missionId]);$pdo->commit();return$item;}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();error_log('Stonefellow mission claim failed: '.$e->getMessage());return null;}
}
function sf_ai_mission_run_next(int $missionId): array
{
    if(!sf_ai_mission_ready())return['ok'=>false,'message'=>'Mission SQL is not ready. Import database/ai_operation_missions.sql first.'];if(!sf_ai_mission_actions_ready()||!sf_ai_mission_logs_ready())return['ok'=>false,'message'=>'AI action registry or execution log SQL is not ready.'];if($missionId<=0)return['ok'=>false,'message'=>'Missing mission id.'];sf_agentic_require_permission('admin.ops.manage');$item=sf_ai_mission_claim_next($missionId);if(!$item)return['ok'=>false,'message'=>'No executable mission item is ready, or another worker already claimed it.'];$action=sf_admin_fetch_one('SELECT * FROM ai_platform_actions WHERE id=? LIMIT 1',[(int)$item['platform_action_id']]);$allowed=$action?sf_agentic_action_execution_allowed($action):['ok'=>false,'error'=>'invalid_action_payload'];if(empty($allowed['ok'])){$message=sf_agentic_error_message((string)$allowed['error']);sf_admin_execute("UPDATE ai_operation_mission_items SET item_status='blocked',last_result_message=? WHERE id=?",[$message,(int)$item['id']]);sf_admin_execute("UPDATE ai_operation_missions SET mission_status='blocked' WHERE id=?",[$missionId]);return['ok'=>false,'status'=>'blocked','message'=>$message];}$lockKey='action|'.(int)$item['platform_action_id'];if(!sf_agentic_acquire_lock($lockKey,0)){sf_admin_execute("UPDATE ai_operation_mission_items SET item_status='ready',last_result_message='Another worker is executing this action.' WHERE id=?",[(int)$item['id']]);return['ok'=>false,'status'=>'blocked','message'=>'Another worker is executing this action.'];}
    $beforeItem=$item;$result=sf_ai_exec_route_action((int)$item['platform_action_id']);$message=sf_ai_mission_item_message($result);$itemStatus=!empty($result['ok'])?'completed':(((string)($result['status']??'')==='blocked')?'blocked':'failed');sf_admin_execute('UPDATE ai_operation_mission_items SET item_status=?,last_result_message=? WHERE id=?',[$itemStatus,substr($message,0,2000),(int)$item['id']]);$after=sf_admin_fetch_one('SELECT * FROM ai_operation_mission_items WHERE id=? LIMIT 1',[(int)$item['id']]);sf_admin_audit('ai_mission_item_routed_execution','ai_operation_mission_item',(int)$item['id'],$beforeItem,$after);if($itemStatus==='completed'){sf_ai_mission_mark_terminal_if_done($missionId);return['ok'=>true,'message'=>$message,'item_status'=>$itemStatus];}if(!empty($item['stop_on_failure']))sf_admin_execute("UPDATE ai_operation_missions SET mission_status='blocked' WHERE id=?",[$missionId]);return['ok'=>false,'message'=>$message,'item_status'=>$itemStatus];
}
function sf_ai_mission_skip_item(int $itemId): array
{
    if(!sf_ai_mission_ready()||$itemId<=0)return['ok'=>false,'message'=>'Invalid item skip request.'];sf_agentic_require_permission('admin.ops.manage');$before=sf_admin_fetch_one('SELECT * FROM ai_operation_mission_items WHERE id=? LIMIT 1',[$itemId]);$mission=$before?sf_admin_fetch_one('SELECT * FROM ai_operation_missions WHERE id=? LIMIT 1',[(int)$before['mission_id']]):null;if(!$before||!$mission||!in_array((string)$mission['mission_status'],['approved','in_progress','blocked'],true))return['ok'=>false,'message'=>'Only approved, in-progress, or blocked mission items can be skipped.'];$stmt=sf_admin_db()->prepare("UPDATE ai_operation_mission_items SET item_status='skipped',last_result_message='Skipped manually by admin.' WHERE id=? AND item_status NOT IN ('completed','running')");$stmt->execute([$itemId]);$ok=$stmt->rowCount()===1;$after=sf_admin_fetch_one('SELECT * FROM ai_operation_mission_items WHERE id=? LIMIT 1',[$itemId]);if($ok){sf_admin_audit('ai_mission_item_skipped','ai_operation_mission_item',$itemId,$before,$after);sf_ai_mission_mark_terminal_if_done((int)$before['mission_id']);sf_ai_mission_resume_if_unblocked((int)$before['mission_id']);}return['ok'=>$ok,'message'=>$ok?'Mission item skipped. Mission was resumed if no blocked items remain.':'Mission item could not be skipped.'];
}
function sf_ai_mission_recover_running(int $missionId): array
{
    if(!sf_ai_mission_ready()||$missionId<=0)return['ok'=>false,'message'=>'Invalid mission recovery request.'];sf_agentic_require_permission('admin.ops.manage');$mission=sf_admin_fetch_one('SELECT * FROM ai_operation_missions WHERE id=? LIMIT 1',[$missionId]);if(!$mission||!in_array((string)$mission['mission_status'],['approved','in_progress','blocked'],true))return['ok'=>false,'message'=>'Mission cannot be recovered in its current state.'];$lease=max(300,min(86400,(int)(getenv('SF_AI_RUNNING_LEASE_SECONDS')?:1800)));$stmt=sf_admin_db()->prepare("UPDATE ai_operation_mission_items SET item_status='ready',last_result_message='Recovered from an expired execution lease by admin.' WHERE mission_id=? AND item_status='running' AND updated_at<DATE_SUB(NOW(),INTERVAL ? SECOND)");$stmt->execute([$missionId,$lease]);$count=$stmt->rowCount();if($count>0){sf_ai_mission_resume_if_unblocked($missionId);sf_admin_audit('ai_mission_running_items_recovered','ai_operation_mission',$missionId,null,['mission_id'=>$missionId,'lease_seconds'=>$lease,'recovered'=>$count]);}return['ok'=>$count>0,'message'=>$count>0?($count.' expired running item(s) recovered to ready state.'):'No expired running mission items were eligible for recovery.'];
}
?>
