<?php
require_once __DIR__ . '/media_delivery.php';
require_once __DIR__ . '/media_pipeline.php';
require_once __DIR__ . '/revenue_access_governance.php';
function sf_audio_clean_asset_path(?string $path): string { $path=trim((string)$path);if($path==='')return'';if(preg_match('~^(https?:)?//|^data:~i',$path))return$path;$path=ltrim($path,'/');if(strpos($path,'assets/')===0)$path=substr($path,7);return$path; }
function sf_audio_duration_label(int $seconds): string { $seconds=max(0,$seconds);return floor($seconds/60).':'.str_pad((string)($seconds%60),2,'0',STR_PAD_LEFT); }
function sf_audio_member_can_play_full(array $song,array $member): bool { $songId=(int)($song['id']??0);$required=(string)($song['access']??$song['access_level']??'subscriber');if($required==='public')return true;if(!empty($member['can_stream_full_music']))return true;return$songId>0&&sf_user_has_direct_grant('song',$songId,null,$required); }
function sf_audio_file_type(array $song,array $member): string { $songId=(int)($song['id']??0);$pipeline=$songId>0?sf_mp_ready_object('song',$songId,'stream'):null;$hasFull=$pipeline||($songId>0&&sf_media_song_file($song,'full'))||!empty($song['full_src']);return$hasFull&&sf_audio_member_can_play_full($song,$member)?'full':'preview'; }
function sf_audio_track_payload(array $song,array $member): array { $fileType=sf_audio_file_type($song,$member);$songId=(int)($song['id']??0);$pipelineRole=$fileType==='full'?'stream':'preview';$pipelineObject=$songId>0?sf_mp_ready_object('song',$songId,$pipelineRole):null;$waveformObject=$songId>0?sf_mp_ready_object('song',$songId,'waveform'):null;$file=$songId>0?sf_media_song_file($song,$fileType):null;$rawPath=sf_audio_clean_asset_path((string)($file['file_path']??''));if($rawPath==='')$rawPath=sf_audio_clean_asset_path((string)($song[$fileType==='full'?'full_src':'preview_src']??''));if($rawPath===''&&$fileType==='full'&&!$pipelineObject){$fileType='preview';$pipelineRole='preview';$pipelineObject=$songId>0?sf_mp_ready_object('song',$songId,'preview'):null;$file=$songId>0?sf_media_song_file($song,'preview'):null;$rawPath=sf_audio_clean_asset_path((string)($file['file_path']??$song['preview_src']??''));}$src='';if($pipelineObject)$src=sf_mp_object_url($pipelineObject,900,'inline',sf_current_user_id());elseif($songId>0&&$rawPath!==''&&sf_revenue_media_signing_ready())$src=sf_media_signed_url('song',$songId,$fileType,'stream',900);elseif(!sf_revenue_is_production()&&$rawPath!=='')$src=preg_match('~^(https?:)?//|^data:~i',$rawPath)?$rawPath:sf_asset($rawPath);$durationSeconds=(int)($song['duration_seconds']??0);if($durationSeconds<=0)$durationSeconds=(int)($pipelineObject['duration_seconds']??$file['duration_seconds']??0);$durationLabel=$durationSeconds>0?sf_audio_duration_label($durationSeconds):(string)($song['duration']??'0:00');return ['id'=>$songId,'title'=>(string)($song['title']??'Stonefellow'),'artist'=>(string)($song['artist']??'Stonefellow'),'src'=>$src,'source_mode'=>$pipelineObject?'pipeline_'.$pipelineRole:$fileType,'waveform_url'=>$waveformObject?sf_mp_object_url($waveformObject,900,'inline',sf_current_user_id()):'','cover'=>sf_asset(sf_audio_clean_asset_path((string)($song['cover']??'images/music/soundtrack-cover.png'))),'url'=>sf_url('song.php?slug='.urlencode((string)($song['slug']??''))),'duration'=>$durationLabel,'duration_seconds'=>$durationSeconds,'preview_seconds'=>(int)($song['preview_seconds']??30),'access'=>(string)($song['access']??$song['access_level']??'free_preview')]; }
function sf_audio_tracks_payload(array $songs,array $member): array { return array_values(array_map(static fn($song)=>sf_audio_track_payload($song,$member),$songs)); }
function sf_audio_track_map(array $songs,array $member): array { $map=[];foreach($songs as$song){$payload=sf_audio_track_payload($song,$member);$map[(int)$payload['id']]=$payload;}return$map; }
function sf_audio_player_state(?int $userId=null): array { $userId=$userId?:sf_current_user_id();$default=['queue'=>[],'current_song_id'=>null,'position_seconds'=>0,'shuffle'=>false,'repeat_mode'=>'off','updated_at'=>null];$pdo=sf_db();if(!$pdo||!$userId)return$default;try{$stmt=$pdo->prepare("SELECT state_json FROM user_player_state WHERE user_id=? AND player_type='audio' LIMIT 1");$stmt->execute([$userId]);$json=$stmt->fetchColumn();$state=$json?json_decode((string)$json,true):[];return is_array($state)?array_merge($default,$state):$default;}catch(Throwable$e){return$default;} }
function sf_audio_save_player_state(int $userId,array $state): bool { $pdo=sf_db();if(!$pdo||!$userId)return false;$queue=array_slice(array_values(array_unique(array_filter(array_map('intval',$state['queue']??[]),static fn($id)=>$id>0))),0,200);$safe=['queue'=>$queue,'current_song_id'=>isset($state['current_song_id'])&&(int)$state['current_song_id']>0?(int)$state['current_song_id']:null,'position_seconds'=>max(0,min(43200,(int)($state['position_seconds']??0))),'shuffle'=>!empty($state['shuffle']),'repeat_mode'=>in_array(($state['repeat_mode']??'off'),['off','one','all'],true)?$state['repeat_mode']:'off','updated_at'=>date('c')];try{$stmt=$pdo->prepare("INSERT INTO user_player_state (user_id,player_type,state_json,updated_at) VALUES (?,'audio',?,NOW()) ON DUPLICATE KEY UPDATE state_json=VALUES(state_json),updated_at=NOW()");return$stmt->execute([$userId,json_encode($safe,JSON_UNESCAPED_SLASHES)]);}catch(Throwable$e){error_log('Stonefellow audio player state save failed: '.$e->getMessage());return false;} }
?>
