<?php
require_once __DIR__ . '/db.php';
require_once __DIR__ . '/admin_security.php';

function sf_br_db(): ?PDO { return sf_db(); }
function sf_br_table_exists(string $table): bool { $pdo=sf_br_db(); if(!$pdo)return false; try{$s=$pdo->prepare('SHOW TABLES LIKE ?');$s->execute([$table]);return (bool)$s->fetchColumn();}catch(Throwable $e){return false;} }
function sf_br_fetch_all(string $sql,array $params=[]): array { $pdo=sf_br_db(); if(!$pdo)return []; try{$s=$pdo->prepare($sql);$s->execute($params);return $s->fetchAll()?:[];}catch(Throwable $e){error_log('Stonefellow backup/release fetch failed: '.$e->getMessage());return [];} }
function sf_br_fetch_one(string $sql,array $params=[]): ?array { $rows=sf_br_fetch_all($sql,$params); return $rows[0]??null; }
function sf_br_execute(string $sql,array $params=[]): bool { $pdo=sf_br_db(); if(!$pdo)return false; try{$s=$pdo->prepare($sql);return $s->execute($params);}catch(Throwable $e){error_log('Stonefellow backup/release execute failed: '.$e->getMessage());return false;} }
function sf_br_h($value): string { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
function sf_br_key(string $prefix): string { return $prefix.'-'.date('Ymd-His').'-'.strtolower(substr(bin2hex(random_bytes(3)),0,6)); }
function sf_br_ready(): bool { return sf_br_table_exists('backup_runs') && sf_br_table_exists('deployment_releases'); }
function sf_br_storage_paths(): array { $root=realpath(__DIR__.'/..') ?: dirname(__DIR__); return ['database'=>'database/','uploads'=>'assets/images/uploads, assets/audio/uploads, assets/video/uploads, assets/documents/uploads','config'=>'config/local.php, storage/install.lock','docs'=>'docs/','logs'=>'storage/logs/']; }
function sf_br_schema_status(): array { $out=[]; if(!sf_br_table_exists('schema_migrations'))return $out; foreach(sf_br_fetch_all('SELECT migration_key,file_path,applied_at FROM schema_migrations ORDER BY migration_key') as $r)$out[]=$r; return $out; }
function sf_br_manifest(): array { $tables=[]; $pdo=sf_br_db(); if($pdo){try{$q=$pdo->query('SHOW TABLES');foreach($q->fetchAll(PDO::FETCH_NUM) as $row){$t=$row[0];$c=sf_br_fetch_one('SELECT COUNT(*) total FROM `'.str_replace('`','',$t).'`');$tables[]=['table'=>$t,'rows'=>(int)($c['total']??0)];}}catch(Throwable $e){$tables[]=['table'=>'error','rows'=>0,'detail'=>$e->getMessage()];}} return ['generated_at'=>date('c'),'database_tables'=>$tables,'migrations'=>sf_br_schema_status(),'storage_paths'=>sf_br_storage_paths(),'app'=>'Stonefellow']; }
function sf_br_profiles(): array { return sf_br_table_exists('backup_profiles')?sf_br_fetch_all('SELECT * FROM backup_profiles ORDER BY status, profile_label'):[]; }
function sf_br_runs(int $limit=100): array { return sf_br_table_exists('backup_runs')?sf_br_fetch_all('SELECT b.*, p.profile_label, u.email admin_email FROM backup_runs b LEFT JOIN backup_profiles p ON p.id=b.profile_id LEFT JOIN users u ON u.id=b.created_by_user_id ORDER BY b.created_at DESC LIMIT '.max(1,min(300,$limit))):[]; }
function sf_br_run(int $id): ?array { return $id&&sf_br_table_exists('backup_runs')?sf_br_fetch_one('SELECT b.*, p.profile_label FROM backup_runs b LEFT JOIN backup_profiles p ON p.id=b.profile_id WHERE b.id=? LIMIT 1',[$id]):null; }
function sf_br_summary(): array { $out=['profiles'=>0,'runs'=>0,'completed'=>0,'verified'=>0,'failed'=>0,'ready_releases'=>0,'deployed_releases'=>0]; if(sf_br_table_exists('backup_profiles'))$out['profiles']=(int)(sf_br_fetch_one('SELECT COUNT(*) total FROM backup_profiles')['total']??0); if(sf_br_table_exists('backup_runs')){foreach(sf_br_fetch_all('SELECT run_status, COUNT(*) total FROM backup_runs GROUP BY run_status') as $r){$out[(string)$r['run_status']]=(int)$r['total'];$out['runs']+=(int)$r['total'];}} if(sf_br_table_exists('deployment_releases')){$out['ready_releases']=(int)(sf_br_fetch_one("SELECT COUNT(*) total FROM deployment_releases WHERE release_status IN ('draft','ready','deploying')")['total']??0);$out['deployed_releases']=(int)(sf_br_fetch_one("SELECT COUNT(*) total FROM deployment_releases WHERE release_status='deployed'")['total']??0);} return $out; }
function sf_br_create_run(array $data): int { if(!sf_br_table_exists('backup_runs'))return 0; $profile=(int)($data['profile_id']??0); $key=trim((string)($data['run_key']??''))?:sf_br_key('backup'); $type=in_array(($data['run_type']??'manual'),['manual','scheduled','pre_release','post_release'],true)?$data['run_type']:'manual'; $status=in_array(($data['run_status']??'planned'),['planned','running','completed','failed','verified','archived'],true)?$data['run_status']:'planned'; $manifest=json_encode(sf_br_manifest(),JSON_UNESCAPED_SLASHES); $ok=sf_br_execute('INSERT INTO backup_runs (profile_id,run_key,run_type,run_status,database_status,uploads_status,config_status,manifest_json,storage_location,notes,started_at,finished_at,verified_at,created_by_user_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[$profile?:null,$key,$type,$status,$data['database_status']??'not_started',$data['uploads_status']??'not_started',$data['config_status']??'not_started',$manifest,$data['storage_location']??null,$data['notes']??null,$status==='running'?date('Y-m-d H:i:s'):null,in_array($status,['completed','verified'],true)?date('Y-m-d H:i:s'):null,$status==='verified'?date('Y-m-d H:i:s'):null,sf_current_user_id()?:null]); $id=$ok?(int)(sf_br_db()?->lastInsertId()?:0):0; if($id){sf_br_seed_restore_checks($id); sf_sec_audit('backup_run_created','notice','backup_run',$id,['run_key'=>$key]);} return $id; }
function sf_br_update_run(int $id,array $data): bool { if(!$id||!sf_br_table_exists('backup_runs'))return false; $status=in_array(($data['run_status']??'planned'),['planned','running','completed','failed','verified','archived'],true)?$data['run_status']:'planned'; $ok=sf_br_execute('UPDATE backup_runs SET run_status=?, database_status=?, uploads_status=?, config_status=?, storage_location=?, notes=?, finished_at=CASE WHEN ? IN ("completed","verified","failed") THEN COALESCE(finished_at,NOW()) ELSE finished_at END, verified_at=CASE WHEN ?="verified" THEN COALESCE(verified_at,NOW()) ELSE verified_at END, updated_at=NOW() WHERE id=?',[$status,$data['database_status']??'not_started',$data['uploads_status']??'not_started',$data['config_status']??'not_started',$data['storage_location']??null,$data['notes']??null,$status,$status,$id]); if($ok)sf_sec_audit('backup_run_updated','notice','backup_run',$id,['status'=>$status]); return $ok; }
function sf_br_seed_restore_checks(int $backupId): void { if(!$backupId||!sf_br_table_exists('restore_readiness_checks'))return; $checks=[['db_import','Database import tested','database'],['uploads_present','Uploads archive present','uploads'],['config_safe','Config secrets backed up securely','config'],['migration_map','Migration map recorded','release'],['restore_window','Restore window approved','manual'],['admin_access','Admin access verified after restore','security']]; foreach($checks as $i=>$c)sf_br_execute('INSERT IGNORE INTO restore_readiness_checks (backup_run_id,check_key,check_label,check_group) VALUES (?,?,?,?)',[$backupId,$c[0],$c[1],$c[2]]); }
function sf_br_restore_checks(int $backupId): array { return $backupId&&sf_br_table_exists('restore_readiness_checks')?sf_br_fetch_all('SELECT * FROM restore_readiness_checks WHERE backup_run_id=? ORDER BY FIELD(status,"failed","pending","passed","waived"), id',[$backupId]):[]; }
function sf_br_update_check(int $id,string $status,string $detail=''): bool { if(!$id||!sf_br_table_exists('restore_readiness_checks'))return false; if(!in_array($status,['pending','passed','failed','waived'],true))$status='pending'; return sf_br_execute('UPDATE restore_readiness_checks SET status=?, detail=?, checked_by_user_id=?, checked_at=NOW(), updated_at=NOW() WHERE id=?',[$status,$detail?:null,sf_current_user_id()?:null,$id]); }

function sf_rel_releases(int $limit=100): array { return sf_br_table_exists('deployment_releases')?sf_br_fetch_all('SELECT r.*, b.run_key backup_key, u.email admin_email, (SELECT COUNT(*) FROM deployment_release_tasks t WHERE t.release_id=r.id) tasks, (SELECT COUNT(*) FROM deployment_release_tasks t WHERE t.release_id=r.id AND t.status="passed") passed_tasks FROM deployment_releases r LEFT JOIN backup_runs b ON b.id=r.backup_run_id LEFT JOIN users u ON u.id=r.created_by_user_id ORDER BY r.created_at DESC LIMIT '.max(1,min(300,$limit))):[]; }
function sf_rel_release(int $id): ?array { return $id&&sf_br_table_exists('deployment_releases')?sf_br_fetch_one('SELECT * FROM deployment_releases WHERE id=? LIMIT 1',[$id]):null; }
function sf_rel_create_or_update(array $data,int $id=0): int { if(!sf_br_table_exists('deployment_releases'))return 0; $label=trim((string)($data['release_label']??'')); if($label==='')return 0; $key=trim((string)($data['release_key']??''))?:sf_br_key('release'); $status=in_array(($data['release_status']??'draft'),['draft','ready','deploying','deployed','rolled_back','failed','archived'],true)?$data['release_status']:'draft'; $env=in_array(($data['deployment_environment']??'production'),['local','staging','production'],true)?$data['deployment_environment']:'production'; $scheduled=trim((string)($data['scheduled_at']??'')); $scheduled=$scheduled?str_replace('T',' ',$scheduled).(strlen($scheduled)===16?':00':''):null; $vals=[$key,$label,$data['release_version']??null,$data['git_branch']??null,$data['git_sha']??null,$env,$status,(int)($data['backup_run_id']??0)?:null,$data['migration_from']??null,$data['migration_to']??null,$data['deploy_notes']??null,$data['rollback_notes']??null,$scheduled,$status==='deployed'?date('Y-m-d H:i:s'):null,$status==='rolled_back'?date('Y-m-d H:i:s'):null,sf_current_user_id()?:null]; if($id>0){sf_br_execute('UPDATE deployment_releases SET release_key=?, release_label=?, release_version=?, git_branch=?, git_sha=?, deployment_environment=?, release_status=?, backup_run_id=?, migration_from=?, migration_to=?, deploy_notes=?, rollback_notes=?, scheduled_at=?, deployed_at=COALESCE(deployed_at,?), rolled_back_at=COALESCE(rolled_back_at,?), created_by_user_id=COALESCE(created_by_user_id,?), updated_at=NOW() WHERE id=?',array_merge($vals,[$id]));} else {sf_br_execute('INSERT INTO deployment_releases (release_key,release_label,release_version,git_branch,git_sha,deployment_environment,release_status,backup_run_id,migration_from,migration_to,deploy_notes,rollback_notes,scheduled_at,deployed_at,rolled_back_at,created_by_user_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',$vals);$id=(int)(sf_br_db()?->lastInsertId()?:0);sf_rel_seed_tasks($id);} if($id){sf_rel_event($id,'release_saved','success','Release saved',$label);sf_sec_audit('deployment_release_saved','notice','deployment_release',$id,['status'=>$status]);} return $id; }
function sf_rel_seed_tasks(int $releaseId): void { if(!$releaseId||!sf_br_table_exists('deployment_release_tasks'))return; $tasks=[['preflight_score','Deployment preflight passes','preflight',10],['fresh_backup','Fresh backup recorded','backup',20],['migration_plan','Migration range reviewed','migrations',30],['deploy_zip','Deploy package/branch confirmed','deploy',40],['smoke_tests','Smoke tests complete','verify',50],['rollback_ready','Rollback notes reviewed','rollback',60]]; foreach($tasks as $t)sf_br_execute('INSERT IGNORE INTO deployment_release_tasks (release_id,task_key,task_label,task_group,sort_order) VALUES (?,?,?,?,?)',[$releaseId,$t[0],$t[1],$t[2],$t[3]]); }
function sf_rel_tasks(int $releaseId): array { return $releaseId&&sf_br_table_exists('deployment_release_tasks')?sf_br_fetch_all('SELECT * FROM deployment_release_tasks WHERE release_id=? ORDER BY sort_order,id',[$releaseId]):[]; }
function sf_rel_update_task(int $taskId,string $status,string $detail=''): bool { if(!$taskId||!sf_br_table_exists('deployment_release_tasks'))return false; if(!in_array($status,['pending','passed','failed','waived'],true))$status='pending'; $ok=sf_br_execute('UPDATE deployment_release_tasks SET status=?, detail=?, checked_by_user_id=?, checked_at=NOW(), updated_at=NOW() WHERE id=?',[$status,$detail?:null,sf_current_user_id()?:null,$taskId]); if($ok)sf_sec_audit('deployment_task_updated','notice','deployment_task',$taskId,['status'=>$status]); return $ok; }
function sf_rel_event(?int $releaseId,string $type,string $status,string $title,string $detail=''): bool { if(!sf_br_table_exists('deployment_events'))return false; return sf_br_execute('INSERT INTO deployment_events (release_id,event_type,event_status,title,detail,actor_user_id) VALUES (?,?,?,?,?,?)',[$releaseId?:null,$type,$status,$title,$detail?:null,sf_current_user_id()?:null]); }
function sf_rel_events(int $releaseId=0,int $limit=100): array { if(!sf_br_table_exists('deployment_events'))return []; $where=$releaseId?'WHERE e.release_id=?':''; $params=$releaseId?[$releaseId]:[]; return sf_br_fetch_all("SELECT e.*, r.release_label FROM deployment_events e LEFT JOIN deployment_releases r ON r.id=e.release_id {$where} ORDER BY e.created_at DESC,e.id DESC LIMIT ".max(1,min(300,$limit)),$params); }
?>
