<?php

declare(strict_types=1);

function sf_lco_item_checks(string $type,array $row): array {
    $c=sf_lco_type($type);$id=(int)($row['id']??0);$title=sf_lco_title($type,$row);$slug=sf_lco_slug($type,$row);$description=sf_lco_description($type,$row);$status=(string)($row[$c['status']??'status']??'draft');$checks=[];
    $checks[]=sf_lco_check('title','Title / name',$title!=='', $title!==''?'Present.':'Missing title or name.',2);
    $checks[]=sf_lco_check('slug','Unique slug',$slug!==''&&!sf_lco_duplicate_slug($c['table'],$slug),$slug===''?'Missing slug.':(sf_lco_duplicate_slug($c['table'],$slug)?'Slug is duplicated.':'Unique slug present.'),2);
    $checks[]=sf_lco_check('description','Description',sf_lco_len($description)>=20,sf_lco_len($description)>=20?'Description is launch-ready.':'Description needs at least 20 characters.',2);
    $checks[]=sf_lco_check('status','Publication state',in_array($status,['draft','scheduled','published','active','archived','inactive','sold_out'],true),'Current state: '.$status.'.',1);
    $imageFields=$c['image']??[];$imageOk=!$imageFields;foreach($imageFields as$f)if(isset($row[$f])&&sf_lco_asset_ready($row[$f])){$imageOk=true;break;}$checks[]=sf_lco_check('image','Primary image',$imageOk,$imageOk?'Image requirement satisfied.':'Primary image or artwork is missing.',2);
    $seo=sf_lco_seo($type,$id);$seoOk=$seo&&sf_lco_len((string)$seo['seo_title'])>=10&&sf_lco_len((string)$seo['meta_description'])>=50&&str_starts_with((string)$seo['canonical_path'],'/');$checks[]=sf_lco_check('seo','SEO metadata',(bool)$seoOk,$seoOk?'SEO title, description, and canonical path are configured.':'Explicit SEO metadata is incomplete.',2);
    if($type==='series'){$checks[]=sf_lco_check('timezone','Release timezone',in_array((string)($row['release_timezone']??''),timezone_identifiers_list(),true),'Timezone must be an IANA identifier.',1);}
    if($type==='season'){$checks[]=sf_lco_check('season_number','Season number',(int)($row['season_number']??0)>0,'Season number must be positive.',2);}
    if($type==='episode'){$season=(int)($row['season_number']??0);$ep=(int)($row['episode_number']??0);$checks[]=sf_lco_check('ordering','Season / episode order',$season>0&&$ep>0,'Both season and episode numbers are required.',2);$seasonOk=!sf_admin_table_exists('seasons')||($season>0&&(bool)sf_admin_fetch_one('SELECT id FROM seasons WHERE season_number=? LIMIT 1',[$season]));$checks[]=sf_lco_check('season_relation','Season relationship',$seasonOk,$seasonOk?'Season relationship resolves.':'No matching season record.',2);$videoCount=sf_admin_table_exists('videos')?(int)(sf_admin_fetch_one('SELECT COUNT(*) AS total FROM videos WHERE episode_id=?',[$id])['total']??0):0;$checks[]=sf_lco_check('episode_video','Episode video',$videoCount>0,$videoCount>0?$videoCount.' video record(s) attached.':'No video is attached.',3);}
    if($type==='video'){$episodeId=(int)($row['episode_id']??0);$relation=$episodeId===0||sf_lco_row_exists('episodes',$episodeId);$checks[]=sf_lco_check('episode_relation','Episode relationship',$relation,$relation?'Relationship resolves.':'Attached episode does not exist.',2);$roles=sf_lco_media_roles('video',$id);$hls=!empty($roles['manifest']['ready'])&&!empty($roles['segment']['ready']);$legacy=sf_lco_file_count('video_files','video_id',$id)>0;$checks[]=sf_lco_check('video_media','Processed video',$hls||$legacy,$hls?'Ready adaptive HLS manifest and segments exist.':($legacy?'Legacy video source exists.':'No ready HLS or video source.'),4);$checks[]=sf_lco_check('access','Access level',in_array((string)($row['access_level']??''),['public','free','subscriber','founding_fan','supporter','vip','admin'],true),'Access policy must be explicit.',1);}
    if($type==='album'){$checks[]=sf_lco_check('artist','Artist',trim((string)($row['artist']??''))!=='','Artist is required.',1);$songCount=sf_admin_table_exists('songs')?(int)(sf_admin_fetch_one('SELECT COUNT(*) AS total FROM songs WHERE album_id=?',[$id])['total']??0):0;$checks[]=sf_lco_check('album_tracks','Album tracks',$songCount>0,$songCount.' track(s) attached.',3);}
    if($type==='song'){$albumId=(int)($row['album_id']??0);$checks[]=sf_lco_check('album_relation','Album relationship',$albumId>0&&sf_lco_row_exists('albums',$albumId),'Song must belong to an existing album.',2);$checks[]=sf_lco_check('track_order','Track order',(int)($row['track_number']??0)>0,'Track number must be positive.',1);$checks[]=sf_lco_check('duration','Duration',(int)($row['duration_seconds']??0)>0,'Duration must be known.',1);$roles=sf_lco_media_roles('song',$id);$full=!empty($roles['stream']['ready'])||sf_lco_file_count('song_files','song_id',$id,'full')>0;$preview=!empty($roles['preview']['ready'])||sf_lco_file_count('song_files','song_id',$id,'preview')>0;$wave=!empty($roles['waveform']['ready']);$checks[]=sf_lco_check('song_full','Full audio',$full,'A ready full/stream audio object is required.',3);$checks[]=sf_lco_check('song_preview','30-second preview',$preview,'A public preview is required.',3);$checks[]=sf_lco_check('waveform','Waveform',$wave,'Processed waveform data is required.',1,'warning');}
    if($type==='character'){$checks[]=sf_lco_check('role','Role type',trim((string)($row['role_type']??''))!=='','Role type is required.',1);$checks[]=sf_lco_check('bio','Cast biography',sf_lco_len((string)($row['short_bio']??''))>=20,'Cast biography needs detail.',2);}
    if($type==='product'){$price=(int)($row['price_cents']??0);$physical=(string)($row['product_type']??'physical')==='physical';$inventory=(int)($row['inventory_quantity']??0);$variantCount=sf_lco_file_count('product_variants','product_id',$id);$checks[]=sf_lco_check('price','Price',$price>0,'Price must be greater than zero.',3);$checks[]=sf_lco_check('inventory','Inventory',!$physical||$inventory>0||$variantCount>0,$physical?'Physical products need inventory or variants.':'Digital products do not require stock.',3);$checks[]=sf_lco_check('sku','SKU',trim((string)($row['sku']??''))!==''||$variantCount>0,'SKU or variant SKUs are required.',2);}
    if($type==='plan'){$checks[]=sf_lco_check('price','Plan price',(int)($row['price_cents']??0)>0,'Plan price must be greater than zero.',3);$checks[]=sf_lco_check('billing_interval','Billing interval',in_array((string)($row['billing_interval']??''),['month','year','monthly','yearly','one_time'],true),'Billing interval must be supported.',2);$featureCols=['allows_full_music','allows_video_streaming','allows_episode_tracking','allows_playlists'];$feature=false;foreach($featureCols as$f)if(!empty($row[$f])){$feature=true;break;}$checks[]=sf_lco_check('features','Plan entitlements',$feature,'At least one membership entitlement must be enabled.',3);}
    return$checks;
}
function sf_lco_score_checks(array $checks): array { $total=0;$earned=0;$blockers=[];$warnings=[];foreach($checks as$c){$w=max(1,(int)($c['weight']??1));$total+=$w;if(!empty($c['ok']))$earned+=$w;elseif(($c['severity']??'blocker')==='warning')$warnings[]=$c['label'];else$blockers[]=$c['label'];}$score=$total?(int)round($earned/$total*100):0;return['score'=>$score,'status'=>$score===100&&!$blockers?'ready':($score>=70?'needs_work':'blocked'),'blockers'=>$blockers,'warnings'=>$warnings]; }
function sf_lco_scan(bool $persist=false,string $targetSha=''): array { $items=[];$types=[];foreach(sf_lco_types() as$type=>$config){$tableReady=sf_admin_table_exists($config['table']);$rows=$tableReady?sf_lco_rows($type):[];$sum=['type'=>$type,'label'=>$config['label'],'total'=>count($rows),'ready'=>0,'blocked'=>0,'score'=>0];$scores=[];if(!$tableReady||!$rows){$reason=!$tableReady?'Required source table is missing.':'No launch records exist for this catalog type.';$synthetic=['entity_type'=>$type,'entity_id'=>0,'label'=>$config['label'].' catalog','score'=>0,'status'=>'blocked','checks'=>[sf_lco_check('catalog_presence','Catalog source',false,$reason,5)],'blockers'=>[$reason],'warnings'=>[],'edit_url'=>$config['edit'],'public_url'=>$config['public'],'row'=>[]];$items[]=$synthetic;$scores[] = 0;$sum['blocked']=1;}foreach($rows as$row){$checks=sf_lco_item_checks($type,$row);$s=sf_lco_score_checks($checks);$item=['entity_type'=>$type,'entity_id'=>(int)$row['id'],'label'=>sf_lco_title($type,$row),'score'=>$s['score'],'status'=>$s['status'],'checks'=>$checks,'blockers'=>$s['blockers'],'warnings'=>$s['warnings'],'edit_url'=>sf_lco_edit_url($type,$row),'public_url'=>sf_lco_public_url($type,$row),'row'=>$row];$items[]=$item;$scores[]=$s['score'];if($s['status']==='ready')$sum['ready']++;else$sum['blocked']++;}$sum['score']=$scores?(int)round(array_sum($scores)/count($scores)):0;$types[$type]=$sum;}$overall=$items?(int)round(array_sum(array_column($items,'score'))/count($items)):0;$result=['overall_score'=>$overall,'item_count'=>count($items),'ready_count'=>count(array_filter($items,fn($i)=>$i['status']==='ready')),'blocker_count'=>array_sum(array_map(fn($i)=>count($i['blockers']),$items)),'types'=>$types,'items'=>$items];if($persist&&sf_lco_ready())$result['snapshot_id']=sf_lco_store_snapshot($result,$targetSha);return$result; }
function sf_lco_store_snapshot(array $scan,string $targetSha=''): int { $pdo=sf_admin_db();if(!$pdo||!sf_lco_ready())return 0;$key=sf_lco_key('snapshot');$targetSha=preg_match('/^[a-f0-9]{40}$/i',$targetSha)?strtolower($targetSha):null;try{$pdo->beginTransaction();$s=$pdo->prepare('INSERT INTO catalog_readiness_snapshots (snapshot_key,target_commit_sha,overall_score,snapshot_status,item_count,ready_count,blocker_count,summary_json,created_by_user_id) VALUES (?,?,?,?,?,?,?,?,?)');$status=$scan['overall_score']===100?'passed':'needs_work';$s->execute([$key,$targetSha,$scan['overall_score'],$status,$scan['item_count'],$scan['ready_count'],$scan['blocker_count'],sf_lco_json($scan['types']),sf_current_user_id()?:null]);$id=(int)$pdo->lastInsertId();$itemStmt=$pdo->prepare('INSERT INTO catalog_readiness_items (snapshot_id,entity_type,entity_id,display_label,readiness_score,readiness_status,checks_json,blockers_json,warnings_json,source_updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)');foreach($scan['items'] as$item)$itemStmt->execute([$id,$item['entity_type'],$item['entity_id'],$item['label'],$item['score'],$item['status'],sf_lco_json($item['checks']),sf_lco_json($item['blockers']),sf_lco_json($item['warnings']),$item['row']['updated_at']??null]);$pdo->commit();return$id;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('Catalog snapshot failed: '.$e->getMessage());return 0;} }
function sf_lco_latest_snapshot(): ?array { return sf_admin_table_exists('catalog_readiness_snapshots')?sf_admin_fetch_one('SELECT * FROM catalog_readiness_snapshots ORDER BY created_at DESC,id DESC LIMIT 1'):null; }
