<?php
require_once __DIR__ . '/membership.php';
require_once __DIR__ . '/notifications.php';
require_once __DIR__ . '/data.php';
require_once __DIR__ . '/content_integrity.php';

function sf_eng_db(): ?PDO { return sf_db(); }
function sf_eng_table_exists(string $table): bool { $pdo=sf_eng_db();return $pdo instanceof PDO&&sf_content_table_exists($pdo,$table); }
function sf_eng_fetch_all(string $sql,array $params=[]): array { $pdo=sf_eng_db();if(!$pdo)return [];try{$s=$pdo->prepare($sql);$s->execute($params);return $s->fetchAll()?:[];}catch(Throwable $e){error_log('Stonefellow engagement fetch failed: '.$e->getMessage());return [];} }
function sf_eng_fetch_one(string $sql,array $params=[]): ?array { $rows=sf_eng_fetch_all($sql,$params);return $rows[0]??null; }
function sf_eng_execute(string $sql,array $params=[]): bool { $pdo=sf_eng_db();if(!$pdo)return false;try{$s=$pdo->prepare($sql);return $s->execute($params);}catch(Throwable $e){error_log('Stonefellow engagement execute failed: '.$e->getMessage());return false;} }
function sf_eng_h($value): string { return htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8'); }
function sf_eng_content_url(string $type,string $slug='',int $id=0): string { $slug=trim($slug);return match($type){'episode'=>sf_url('episode.php'.($slug?'?slug='.urlencode($slug):'')),'video'=>sf_url('watch.php'.($slug?'?slug='.urlencode($slug):'')),'song'=>sf_url('song.php'.($slug?'?slug='.urlencode($slug):'')),'album'=>sf_url('album.php'.($slug?'?slug='.urlencode($slug):'')),'post'=>sf_url('comments.php?content_type=post&content_id='.$id),'product'=>sf_url('product.php'.($slug?'?slug='.urlencode($slug):'')),default=>sf_url('comments.php')}; }
function sf_eng_is_admin(): bool { $user=function_exists('sf_auth_user')?sf_auth_user():null;return $user&&($user['role']??'')==='admin'; }

function sf_member_notification_static(): array { $logs=function_exists('sf_notify_recent_logs')?sf_notify_recent_logs(20):[];$rows=[];foreach($logs as $log)$rows[]=['id'=>(int)($log['id']??0),'title'=>$log['subject']??'Stonefellow notification','body'=>$log['body_preview']??($log['rendered_text']??''),'notification_type'=>$log['notification_type']??'system','status'=>($log['status']??'')==='sent'?'read':'unread','action_url'=>sf_url('notifications.php'),'created_at'=>$log['created_at']??date('Y-m-d H:i:s')];if($rows)return $rows;return [['id'=>1,'title'=>'Welcome to Stonefellow','body'=>'Your member dashboard, library, watchlist, comments, and streaming access are ready.','notification_type'=>'welcome','status'=>'unread','action_url'=>sf_url('member.php'),'created_at'=>date('Y-m-d H:i:s')],['id'=>2,'title'=>'Follow the soundtrack','body'=>'Open the player and save your favorite songs to your library.','notification_type'=>'music','status'=>'unread','action_url'=>sf_url('player.php'),'created_at'=>date('Y-m-d H:i:s')]]; }
function sf_member_notifications(int $userId,string $status='',int $limit=100): array { $limit=max(1,min(200,$limit));if(!$userId||!sf_eng_table_exists('member_notifications'))return sf_member_notification_static();$where='WHERE user_id=?';$params=[$userId];if($status!==''){$where.=' AND status=?';$params[]=$status;}return sf_eng_fetch_all("SELECT * FROM member_notifications {$where} ORDER BY created_at DESC,id DESC LIMIT {$limit}",$params); }
function sf_member_notification_summary(int $userId): array { $summary=['total'=>0,'unread'=>0,'read'=>0,'dismissed'=>0];if(!$userId||!sf_eng_table_exists('member_notifications')){$rows=sf_member_notification_static();foreach($rows as $row){$summary['total']++;$key=(string)($row['status']??'unread');$summary[$key]=($summary[$key]??0)+1;}return $summary;}$rows=sf_eng_fetch_all('SELECT status,COUNT(*) total FROM member_notifications WHERE user_id=? GROUP BY status',[$userId]);foreach($rows as $row){$status=(string)$row['status'];$summary[$status]=(int)$row['total'];$summary['total']+=(int)$row['total'];}return $summary; }
function sf_member_notification_create(int $userId,string $title,string $body='',string $type='system',string $url='',array $meta=[]): int { if(!$userId||!sf_eng_table_exists('member_notifications')||!sf_content_user_active($userId))return 0;$title=sf_content_clean_text($title,190);$body=sf_content_clean_text($body,5000);$url=str_starts_with($url,'/')?$url:'';$ok=sf_eng_execute('INSERT INTO member_notifications (user_id,notification_type,title,body,action_url,status,metadata_json) VALUES (?,?,?,?,?,"unread",?)',[$userId,sf_content_clean_text($type,80),$title,$body,$url,json_encode($meta,JSON_UNESCAPED_SLASHES)]);return $ok?(int)(sf_eng_db()?->lastInsertId()?:0):0; }
function sf_member_notification_update(int $userId,int $id,string $status): bool { if(!$userId||$id<=0||!in_array($status,['unread','read','dismissed'],true)||!sf_eng_table_exists('member_notifications'))return false;$readSql=$status==='read'?',read_at=COALESCE(read_at,NOW())':'';return sf_eng_execute("UPDATE member_notifications SET status=?{$readSql},updated_at=NOW() WHERE id=? AND user_id=?",[$status,$id,$userId]); }
function sf_member_notifications_mark_all_read(int $userId): bool { return $userId&&sf_eng_table_exists('member_notifications')?sf_eng_execute("UPDATE member_notifications SET status='read',read_at=COALESCE(read_at,NOW()),updated_at=NOW() WHERE user_id=? AND status='unread'",[$userId]):false; }

function sf_comment_static(string $type='episode',int $id=0): array { return [['id'=>1,'author_name'=>'Stonefellow Fan','body'=>'This chapter feels like the story and music are starting to collide.','status'=>'approved','reaction_count'=>8,'created_at'=>date('Y-m-d H:i:s',time()-3600)],['id'=>2,'author_name'=>'Member Preview','body'=>'The fan engagement layer is ready for database-backed comments after install.','status'=>'approved','reaction_count'=>3,'created_at'=>date('Y-m-d H:i:s',time()-7200)]]; }
function sf_comments_for(string $type,int $id=0,string $slug='',string $status='approved',int $limit=100): array {
  $type=in_array($type,sf_content_allowed_types(),true)?$type:'episode';$slug=sf_content_safe_slug($slug);$limit=max(1,min(100,$limit));if(!sf_eng_table_exists('fan_comments'))return $status==='approved'?sf_comment_static($type,$id):[];
  if($status!=='approved'&&!sf_eng_is_admin())$status='approved';$where='WHERE fc.content_type=?';$params=[$type];if($id>0){$where.=' AND fc.content_id=?';$params[]=$id;}if($slug!==''){$where.=' AND fc.content_slug=?';$params[]=$slug;}if($status!==''){$where.=' AND fc.status=?';$params[]=$status;}
  return sf_eng_fetch_all("SELECT fc.id,fc.user_id,fc.parent_comment_id,fc.content_type,fc.content_id,fc.content_slug,fc.body,fc.status,fc.is_pinned,fc.reaction_count,fc.created_at,fc.updated_at,u.display_name FROM fan_comments fc LEFT JOIN users u ON u.id=fc.user_id {$where} ORDER BY fc.is_pinned DESC,fc.created_at DESC,fc.id DESC LIMIT {$limit}",$params);
}
function sf_comment_create(int $userId,string $type,int $id,string $slug,string $body,?int $parentId=null): array {
  $type=strtolower(trim($type));$slug=sf_content_safe_slug($slug);if(!$userId||!sf_content_user_active($userId))return ['ok'=>false,'message'=>'Active login required.'];if(!in_array($type,sf_content_allowed_types(),true))return ['ok'=>false,'message'=>'Unsupported content type.'];if(!sf_eng_table_exists('fan_comments'))return ['ok'=>false,'message'=>'Comments are temporarily unavailable.'];if(!sf_content_exists($type,$id,$slug))return ['ok'=>false,'message'=>'Content target was not found.'];$validated=sf_content_comment_body($body);if(!$validated['ok'])return ['ok'=>false,'message'=>$validated['message']];$body=$validated['body'];
  if(!sf_content_rate_limit('comment-user-'.$userId,8,600)||!sf_content_rate_limit('comment-ip-'.sf_content_client_hash('ip',(string)($_SERVER['REMOTE_ADDR']??'')),20,600))return ['ok'=>false,'message'=>'Comment limit reached. Try again later.'];$pdo=sf_eng_db();
  try{$pdo->beginTransaction();$dup=$pdo->prepare('SELECT id FROM fan_comments WHERE user_id=? AND body=? AND created_at>=DATE_SUB(NOW(),INTERVAL 10 MINUTE) LIMIT 1');$dup->execute([$userId,$body]);if($dup->fetchColumn()){ $pdo->rollBack();return ['ok'=>false,'message'=>'Duplicate comment detected.']; }
    if($parentId){$p=$pdo->prepare('SELECT id FROM fan_comments WHERE id=? AND content_type=? AND content_id=? AND COALESCE(content_slug,"")=? AND status IN ("pending","approved") FOR UPDATE');$p->execute([$parentId,$type,$id,$slug]);if(!$p->fetchColumn()){ $pdo->rollBack();return ['ok'=>false,'message'=>'Reply target is invalid.']; }}
    $requiresApproval=(getenv('SF_COMMENTS_REQUIRE_APPROVAL')?:'1')!=='0';$status=sf_eng_is_admin()||!$requiresApproval?'approved':'pending';$s=$pdo->prepare('INSERT INTO fan_comments (user_id,parent_comment_id,content_type,content_id,content_slug,body,status,ip_address,user_agent) VALUES (?,?,?,?,?,?,?,?,?)');$s->execute([$userId,$parentId?:null,$type,$id,$slug?:null,$body,$status,sf_content_client_hash('ip',(string)($_SERVER['REMOTE_ADDR']??'')),sf_content_client_hash('ua',substr((string)($_SERVER['HTTP_USER_AGENT']??''),0,255))]);$commentId=(int)$pdo->lastInsertId();if(sf_eng_table_exists('member_activity_events'))$pdo->prepare('INSERT INTO member_activity_events (user_id,event_type,event_group,content_type,content_id,title,detail,action_url,severity) VALUES (?,"comment_created","activity",?,?,?,?,?,?)')->execute([$userId,$type,$id,'New comment posted',substr($body,0,160),sf_eng_content_url($type,$slug,$id),$status==='pending'?'warning':'info']);$pdo->commit();return ['ok'=>true,'message'=>$status==='pending'?'Comment submitted for moderation.':'Comment posted.','status'=>$status,'comment_id'=>$commentId];
  }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('Stonefellow comment create failed: '.$e->getMessage());return ['ok'=>false,'message'=>'Comment could not be saved.'];}
}
function sf_comment_update_status(int $commentId,string $status,string $note=''): bool {
  if($commentId<=0||!in_array($status,['pending','approved','rejected','hidden','spam'],true)||!sf_eng_table_exists('fan_comments')||!sf_eng_is_admin())return false;if(function_exists('sf_sec_can')&&!sf_sec_can('admin.content.manage'))return false;$pdo=sf_eng_db();
  try{$pdo->beginTransaction();$s=$pdo->prepare('SELECT status FROM fan_comments WHERE id=? FOR UPDATE');$s->execute([$commentId]);$before=$s->fetchColumn();if($before===false){$pdo->rollBack();return false;}$pdo->prepare('UPDATE fan_comments SET status=?,moderated_by_user_id=?,moderated_at=NOW(),updated_at=NOW() WHERE id=?')->execute([$status,sf_current_user_id(),$commentId]);if(sf_eng_table_exists('comment_moderation_events'))$pdo->prepare('INSERT INTO comment_moderation_events (comment_id,moderator_user_id,action,note,created_at) VALUES (?,?,?,?,NOW())')->execute([$commentId,sf_current_user_id(),$status,sf_content_clean_text($note,1000)]);$pdo->commit();return true;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();return false;}
}
function sf_comment_react(int $userId,string $type,int $targetId,string $reaction='like'): array {
  if(!$userId||!sf_content_user_active($userId))return ['ok'=>false,'message'=>'Active login required.'];if(!in_array($type,['comment','episode','video','song','album','post','product'],true)||$targetId<=0)return ['ok'=>false,'message'=>'Unsupported target.'];if(!in_array($reaction,['like','love','fire','laugh','wow'],true))return ['ok'=>false,'message'=>'Unsupported reaction.'];if(!sf_eng_table_exists('fan_reactions'))return ['ok'=>false,'message'=>'Reactions are temporarily unavailable.'];if(!sf_content_rate_limit('reaction-user-'.$userId,40,600))return ['ok'=>false,'message'=>'Reaction limit reached.'];$pdo=sf_eng_db();
  try{$pdo->beginTransaction();if($type==='comment'){$s=$pdo->prepare('SELECT id FROM fan_comments WHERE id=? AND status="approved" FOR UPDATE');$s->execute([$targetId]);if(!$s->fetchColumn()){ $pdo->rollBack();return ['ok'=>false,'message'=>'Comment target is unavailable.']; }}elseif(!sf_content_exists($type,$targetId,'')){ $pdo->rollBack();return ['ok'=>false,'message'=>'Content target is unavailable.']; }
    $existing=$pdo->prepare('SELECT id,reaction_type FROM fan_reactions WHERE user_id=? AND target_type=? AND target_id=? FOR UPDATE');$existing->execute([$userId,$type,$targetId]);$old=$existing->fetch();if($old)$pdo->prepare('UPDATE fan_reactions SET reaction_type=?,updated_at=NOW() WHERE id=?')->execute([$reaction,(int)$old['id']]);else{$pdo->prepare('INSERT INTO fan_reactions (user_id,target_type,target_id,reaction_type) VALUES (?,?,?,?)')->execute([$userId,$type,$targetId,$reaction]);if($type==='comment')$pdo->prepare('UPDATE fan_comments SET reaction_count=reaction_count+1 WHERE id=?')->execute([$targetId]);}$pdo->commit();return ['ok'=>true,'message'=>'Reaction saved.'];
  }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();return ['ok'=>false,'message'=>'Reaction failed.'];}
}
function sf_comment_summary(): array { $summary=['comments'=>0,'pending'=>0,'approved'=>0,'hidden'=>0,'reactions'=>0];if(sf_eng_table_exists('fan_comments')){$rows=sf_eng_fetch_all('SELECT status,COUNT(*) total FROM fan_comments GROUP BY status');foreach($rows as $row){$status=(string)$row['status'];$summary[$status]=(int)$row['total'];$summary['comments']+=(int)$row['total'];}}if(sf_eng_table_exists('fan_reactions'))$summary['reactions']=(int)(sf_eng_fetch_one('SELECT COUNT(*) total FROM fan_reactions')['total']??0);if(!$summary['comments'])$summary['comments']=count(sf_comment_static());if(!sf_eng_is_admin())unset($summary['pending'],$summary['hidden']);return $summary; }
function sf_comment_moderation_queue(int $limit=100): array { $limit=max(1,min(200,$limit));if(!sf_eng_is_admin()||!sf_eng_table_exists('fan_comments'))return [];return sf_eng_fetch_all("SELECT fc.*,u.display_name FROM fan_comments fc LEFT JOIN users u ON u.id=fc.user_id WHERE fc.status IN ('pending','hidden','spam') ORDER BY fc.created_at ASC,fc.id ASC LIMIT {$limit}"); }
function sf_engagement_dashboard(): array { return ['notifications'=>sf_member_notification_summary(sf_current_user_id()?:0),'comments'=>sf_comment_summary(),'queue'=>sf_comment_moderation_queue(20)]; }
?>
