<?php
require_once __DIR__ . '/billing.php';

function sf_tiers_db(): ?PDO { return sf_db(); }
function sf_tiers_table_exists(string $table): bool { $pdo=sf_tiers_db(); if(!$pdo)return false; try{$s=$pdo->prepare('SHOW TABLES LIKE ?');$s->execute([$table]);return (bool)$s->fetchColumn();}catch(Throwable $e){return false;} }
function sf_tiers_column_exists(string $table,string $column): bool { $pdo=sf_tiers_db(); if(!$pdo||!sf_tiers_table_exists($table))return false; try{$s=$pdo->prepare('SHOW COLUMNS FROM `'.str_replace('`','',$table).'` LIKE ?');$s->execute([$column]);return (bool)$s->fetchColumn();}catch(Throwable $e){return false;} }
function sf_tiers_fetch_all(string $sql,array $params=[]): array { $pdo=sf_tiers_db(); if(!$pdo)return []; try{$s=$pdo->prepare($sql);$s->execute($params);return $s->fetchAll()?:[];}catch(Throwable $e){error_log('Stonefellow tiers fetch failed: '.$e->getMessage());return [];} }
function sf_tiers_fetch_one(string $sql,array $params=[]): ?array { $rows=sf_tiers_fetch_all($sql,$params); return $rows[0]??null; }
function sf_tiers_execute(string $sql,array $params=[]): bool { $pdo=sf_tiers_db(); if(!$pdo)return false; try{$s=$pdo->prepare($sql);return $s->execute($params);}catch(Throwable $e){error_log('Stonefellow tiers execute failed: '.$e->getMessage());return false;} }
function sf_tiers_money(int $cents,string $currency='USD'): string { return function_exists('sf_billing_money') ? sf_billing_money($cents,$currency) : ('$'.number_format($cents/100,2)); }
function sf_tiers_fallback_plans(): array { return [
  ['id'=>0,'name'=>'Monthly Access','slug'=>'monthly-access','price_cents'=>799,'billing_interval'=>'month','description'=>'Core access for watching, listening, commenting, and following the story.','public_badge'=>'Start Here','access_label'=>'Core Member','launch_position'=>'entry','features'=>['Episode streaming','Full soundtrack streaming','Private playlists','Fan comments','Personalized feed']],
  ['id'=>0,'name'=>'Annual Access','slug'=>'annual-access','price_cents'=>7999,'billing_interval'=>'year','description'=>'Best-value annual membership with premium access and launch drops.','public_badge'=>'Most Popular','access_label'=>'Premium Member','launch_position'=>'premium','features'=>['Everything in Monthly','Early episode access','Live session archive','Subscriber merch drops','Priority fan feed']],
  ['id'=>0,'name'=>'Founding Fan','slug'=>'founding-fan','price_cents'=>14999,'billing_interval'=>'year','description'=>'Founder-level support with VIP recognition and collectible launch benefits.','public_badge'=>'Founder','access_label'=>'Founding Fan','launch_position'=>'founder','features'=>['Everything in Annual','Founder recognition','Supporter wall','Limited launch collectibles','VIP behind-the-scenes']],
]; }
function sf_tiers_plan_features(array $plan): array { if(!empty($plan['features'])&&is_array($plan['features']))return $plan['features']; if(sf_tiers_table_exists('membership_tier_benefit_map')){ $rows=sf_tiers_fetch_all('SELECT b.benefit_label,m.value_label,m.is_enabled FROM membership_tier_benefit_map m INNER JOIN membership_tier_benefits b ON b.benefit_key=m.benefit_key WHERE m.plan_id=? AND m.is_enabled=1 ORDER BY m.sort_order,b.sort_order',[(int)($plan['id']??0)]); if($rows)return array_map(fn($r)=>(string)($r['value_label']?:$r['benefit_label']),$rows); } $features=[]; if(!empty($plan['allows_video_streaming']))$features[]='Episode video access'; if(!empty($plan['allows_full_music']))$features[]='Full soundtrack streaming'; if(!empty($plan['allows_playlists']))$features[]='Private member playlists'; if(!empty($plan['allows_offline_downloads']))$features[]='Offline/download access'; if(!empty($plan['description']))$features[]=(string)$plan['description']; return $features ?: ['Member access','Fan comments','Personalized feed']; }
function sf_tiers_public_plans(): array { if(!sf_tiers_table_exists('subscription_plans'))return sf_tiers_fallback_plans(); $where="status='active'"; if(sf_tiers_column_exists('subscription_plans','is_public'))$where.=' AND is_public=1'; $order=sf_tiers_column_exists('subscription_plans','sort_order')?'sort_order, price_cents, id':'price_cents, id'; $plans=sf_tiers_fetch_all("SELECT * FROM subscription_plans WHERE {$where} ORDER BY {$order}"); if(!$plans)return sf_tiers_fallback_plans(); foreach($plans as &$plan){ $plan['access_label']=$plan['access_label']??($plan['name']??'Member'); $plan['public_badge']=$plan['public_badge']??(!empty($plan['is_featured'])?'Featured':''); $plan['features']=sf_tiers_plan_features($plan); } unset($plan); return $plans; }
function sf_tiers_benefit_matrix(): array { $plans=sf_tiers_public_plans(); $benefits=sf_tiers_table_exists('membership_tier_benefits')?sf_tiers_fetch_all('SELECT * FROM membership_tier_benefits WHERE is_public=1 ORDER BY sort_order, id'):[]; if(!$benefits){$benefits=[['benefit_key'=>'episodes','benefit_label'=>'Episode streaming'],['benefit_key'=>'full_music','benefit_label'=>'Full soundtrack'],['benefit_key'=>'playlists','benefit_label'=>'Playlists'],['benefit_key'=>'comments','benefit_label'=>'Fan comments'],['benefit_key'=>'feed','benefit_label'=>'Personalized feed'],['benefit_key'=>'downloads','benefit_label'=>'Downloads/offline'],['benefit_key'=>'founder','benefit_label'=>'Founder recognition']];}
  $matrix=[]; foreach($benefits as $benefit){$row=['key'=>$benefit['benefit_key'],'label'=>$benefit['benefit_label'],'plans'=>[]]; foreach($plans as $plan){$enabled=false;$value='—'; if(sf_tiers_table_exists('membership_tier_benefit_map')&&!empty($plan['id'])){$map=sf_tiers_fetch_one('SELECT * FROM membership_tier_benefit_map WHERE plan_id=? AND benefit_key=? LIMIT 1',[(int)$plan['id'],(string)$benefit['benefit_key']]); if($map){$enabled=!empty($map['is_enabled']);$value=$enabled?(string)($map['value_label']?:'Included'):'—';}} else {$features=array_map('strtolower',sf_tiers_plan_features($plan));$enabled=(bool)array_filter($features,fn($f)=>str_contains($f,str_replace('_',' ',strtolower((string)$benefit['benefit_key'])))||str_contains($f,strtolower((string)$benefit['benefit_label'])));$value=$enabled?'Included':'—';} $row['plans'][$plan['slug']??$plan['name']]=['enabled'=>$enabled,'value'=>$value]; } $matrix[]=$row; } return ['plans'=>$plans,'benefits'=>$matrix]; }
function sf_tiers_admin_summary(): array { $plans=sf_tiers_public_plans(); $active=sf_tiers_table_exists('user_subscriptions')?(int)(sf_tiers_fetch_one("SELECT COUNT(*) total FROM user_subscriptions WHERE status IN ('active','trialing') AND (current_period_end IS NULL OR current_period_end>=NOW())")['total']??0):0; return ['plans'=>count($plans),'public_plans'=>count(array_filter($plans,fn($p)=>($p['is_public']??1))), 'active_subscriptions'=>$active,'benefits'=>sf_tiers_table_exists('membership_tier_benefits')?(int)(sf_tiers_fetch_one('SELECT COUNT(*) total FROM membership_tier_benefits')['total']??0):0]; }
function sf_tiers_save_plan(array $data,int $id=0): int { if(!sf_tiers_table_exists('subscription_plans'))return 0; $name=trim((string)($data['name']??'')); if($name==='')return 0; $slug=trim((string)($data['slug']??'')); if($slug==='')$slug=strtolower(trim(preg_replace('/[^a-z0-9]+/i','-',$name),'-')); $price=max(0,(int)($data['price_cents']??0)); $interval=in_array(($data['billing_interval']??'month'),['month','year'],true)?$data['billing_interval']:'month'; $status=in_array(($data['status']??'active'),['active','inactive'],true)?$data['status']:'active'; $fields=['name'=>$name,'slug'=>$slug,'price_cents'=>$price,'billing_interval'=>$interval,'description'=>$data['description']??null,'status'=>$status]; foreach(['allows_full_music','allows_video_streaming','allows_playlists','allows_offline_downloads','is_featured'] as $col) if(sf_tiers_column_exists('subscription_plans',$col)) $fields[$col]=!empty($data[$col])?1:0; foreach(['public_badge','access_label','launch_position','sort_order','is_public'] as $col) if(sf_tiers_column_exists('subscription_plans',$col)) $fields[$col]=$col==='is_public'?(!empty($data[$col])?1:0):($data[$col]??($col==='sort_order'?100:null)); if($id>0){$sets=[];$vals=[];foreach($fields as $k=>$v){$sets[]="`{$k}`=?";$vals[]=$v;} $vals[]=$id; sf_tiers_execute('UPDATE subscription_plans SET '.implode(',',$sets).' WHERE id=?',$vals); return $id;} $keys=array_keys($fields); sf_tiers_execute('INSERT INTO subscription_plans (`'.implode('`,`',$keys).'`) VALUES ('.implode(',',array_fill(0,count($keys),'?')).')',array_values($fields)); return (int)(sf_tiers_db()?->lastInsertId()?:0); }
?>
