<?php
require_once __DIR__ . '/membership.php';
require_once __DIR__ . '/billing.php';

function sf_ops_db(): ?PDO { return sf_db(); }
function sf_ops_table_exists(string $table): bool { $pdo=sf_ops_db(); if(!$pdo)return false; try{$s=$pdo->prepare('SHOW TABLES LIKE ?');$s->execute([$table]);return (bool)$s->fetchColumn();}catch(Throwable $e){return false;} }
function sf_ops_fetch_all(string $sql,array $params=[]): array { $pdo=sf_ops_db(); if(!$pdo)return []; try{$s=$pdo->prepare($sql);$s->execute($params);return $s->fetchAll()?:[];}catch(Throwable $e){error_log('Stonefellow ops fetch failed: '.$e->getMessage());return [];} }
function sf_ops_fetch_one(string $sql,array $params=[]): ?array { $rows=sf_ops_fetch_all($sql,$params); return $rows[0]??null; }
function sf_ops_execute(string $sql,array $params=[]): bool { $pdo=sf_ops_db(); if(!$pdo)return false; try{$s=$pdo->prepare($sql);return $s->execute($params);}catch(Throwable $e){error_log('Stonefellow ops execute failed: '.$e->getMessage());return false;} }
function sf_ops_h($value): string { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
function sf_ops_ticket_number(): string { return 'SF-' . date('ymd') . '-' . strtoupper(substr(bin2hex(random_bytes(4)),0,6)); }

function sf_lifecycle_summary(): array {
  $out=['members'=>0,'active'=>0,'trialing'=>0,'past_due'=>0,'canceling'=>0,'churn_risk'=>0,'free'=>0,'open_tasks'=>0,'support_open'=>0,'new_signups_7d'=>0];
  if(sf_ops_table_exists('users')){ $out['members']=(int)(sf_ops_fetch_one("SELECT COUNT(*) total FROM users WHERE role<>'admin'")['total']??0); $out['new_signups_7d']=(int)(sf_ops_fetch_one("SELECT COUNT(*) total FROM users WHERE role<>'admin' AND created_at>=DATE_SUB(NOW(), INTERVAL 7 DAY)")['total']??0); }
  if(sf_ops_table_exists('user_subscriptions')){
    foreach(sf_ops_fetch_all("SELECT status, COUNT(*) total FROM user_subscriptions GROUP BY status") as $r){ $out[(string)$r['status']]=(int)$r['total']; }
    $out['canceling']=(int)(sf_ops_fetch_one("SELECT COUNT(*) total FROM user_subscriptions WHERE cancel_at_period_end=1")['total']??0);
    $out['churn_risk']=(int)(sf_ops_fetch_one("SELECT COUNT(*) total FROM user_subscriptions WHERE status IN ('past_due','unpaid') OR cancel_at_period_end=1 OR (current_period_end IS NOT NULL AND current_period_end BETWEEN NOW() AND DATE_ADD(NOW(), INTERVAL 10 DAY))")['total']??0);
  }
  $out['free']=max(0,$out['members']-$out['active']-$out['trialing']);
  if(sf_ops_table_exists('member_retention_tasks'))$out['open_tasks']=(int)(sf_ops_fetch_one("SELECT COUNT(*) total FROM member_retention_tasks WHERE status IN ('open','in_progress')")['total']??0);
  if(sf_ops_table_exists('support_tickets'))$out['support_open']=(int)(sf_ops_fetch_one("SELECT COUNT(*) total FROM support_tickets WHERE status NOT IN ('resolved','closed')")['total']??0);
  return $out;
}
function sf_lifecycle_segments(): array {
  if(!sf_ops_table_exists('users')) return [];
  return sf_ops_fetch_all("SELECT u.id,u.email,u.display_name,u.status,u.created_at,u.last_login_at, sp.name plan_name, us.status subscription_status, us.current_period_end, us.cancel_at_period_end, (SELECT COUNT(*) FROM support_tickets st WHERE st.user_id=u.id AND st.status NOT IN ('resolved','closed')) open_tickets, (SELECT COUNT(*) FROM member_retention_tasks rt WHERE rt.user_id=u.id AND rt.status IN ('open','in_progress')) open_tasks FROM users u LEFT JOIN user_subscriptions us ON us.id=(SELECT us2.id FROM user_subscriptions us2 WHERE us2.user_id=u.id ORDER BY FIELD(us2.status,'active','trialing','past_due','unpaid','canceled','expired'), us2.current_period_end DESC, us2.id DESC LIMIT 1) LEFT JOIN subscription_plans sp ON sp.id=us.plan_id WHERE u.role<>'admin' ORDER BY CASE WHEN us.status IN ('past_due','unpaid') OR us.cancel_at_period_end=1 OR (us.current_period_end IS NOT NULL AND us.current_period_end BETWEEN NOW() AND DATE_ADD(NOW(), INTERVAL 10 DAY)) THEN 0 WHEN (SELECT COUNT(*) FROM support_tickets st2 WHERE st2.user_id=u.id AND st2.status NOT IN ('resolved','closed')) > 0 THEN 1 ELSE 2 END, u.created_at DESC LIMIT 300");
}
function sf_lifecycle_create_note(int $userId,string $note,string $type='general',string $visibility='admin'): bool { if(!$userId||trim($note)===''||!sf_ops_table_exists('member_lifecycle_notes')) return false; if(!in_array($type,['retention','billing','support','access','churn_risk','general'],true))$type='general'; if(!in_array($visibility,['admin','member'],true))$visibility='admin'; return sf_ops_execute('INSERT INTO member_lifecycle_notes (user_id,admin_user_id,note_type,note,visibility) VALUES (?,?,?,?,?)',[$userId,sf_current_user_id()?:null,$type,$note,$visibility]); }
function sf_lifecycle_create_task(int $userId,string $title,string $detail='',string $type='manual',string $priority='medium',string $dueAt=''): bool { if(!$userId||trim($title)===''||!sf_ops_table_exists('member_retention_tasks')) return false; if(!in_array($type,['welcome','renewal','past_due','cancel_save','upgrade','support_followup','manual'],true))$type='manual'; if(!in_array($priority,['low','medium','high','critical'],true))$priority='medium'; $due=$dueAt?str_replace('T',' ',$dueAt).(strlen($dueAt)===16?':00':''):null; return sf_ops_execute('INSERT INTO member_retention_tasks (user_id,assigned_admin_user_id,task_type,priority,title,detail,due_at) VALUES (?,?,?,?,?,?,?)',[$userId,sf_current_user_id()?:null,$type,$priority,$title,$detail?:null,$due]); }
function sf_lifecycle_update_task(int $taskId,string $status): bool { if($taskId<=0||!sf_ops_table_exists('member_retention_tasks'))return false; if(!in_array($status,['open','in_progress','done','dismissed'],true))return false; $done=$status==='done'?', completed_at=NOW()':''; return sf_ops_execute("UPDATE member_retention_tasks SET status=?{$done}, updated_at=NOW() WHERE id=?",[$status,$taskId]); }
function sf_lifecycle_notes(int $userId,int $limit=20): array { if(!$userId||!sf_ops_table_exists('member_lifecycle_notes'))return []; return sf_ops_fetch_all('SELECT n.*, u.email admin_email, u.display_name admin_name FROM member_lifecycle_notes n LEFT JOIN users u ON u.id=n.admin_user_id WHERE n.user_id=? ORDER BY n.created_at DESC LIMIT '.max(1,min(100,$limit)),[$userId]); }
function sf_lifecycle_tasks(int $userId=0,int $limit=100): array { if(!sf_ops_table_exists('member_retention_tasks'))return []; $where=$userId?'WHERE t.user_id=?':''; $params=$userId?[$userId]:[]; return sf_ops_fetch_all("SELECT t.*, u.email, u.display_name FROM member_retention_tasks t LEFT JOIN users u ON u.id=t.user_id {$where} ORDER BY FIELD(t.status,'open','in_progress','done','dismissed'), FIELD(t.priority,'critical','high','medium','low'), t.due_at ASC, t.created_at DESC LIMIT ".max(1,min(300,$limit)),$params); }

function sf_support_summary(): array { $out=['total'=>0,'new'=>0,'open'=>0,'pending_member'=>0,'pending_admin'=>0,'resolved'=>0,'closed'=>0,'urgent'=>0]; if(!sf_ops_table_exists('support_tickets'))return $out; foreach(sf_ops_fetch_all('SELECT status, COUNT(*) total FROM support_tickets GROUP BY status') as $r){$out[(string)$r['status']]=(int)$r['total'];$out['total']+=(int)$r['total'];} $out['urgent']=(int)(sf_ops_fetch_one("SELECT COUNT(*) total FROM support_tickets WHERE priority='urgent' AND status NOT IN ('resolved','closed')")['total']??0); return $out; }
function sf_support_tickets(int $userId=0,string $status='',int $limit=150): array { if(!sf_ops_table_exists('support_tickets'))return []; $where=[];$params=[]; if($userId){$where[]='st.user_id=?';$params[]=$userId;} if($status!==''){$where[]='st.status=?';$params[]=$status;} $sqlWhere=$where?'WHERE '.implode(' AND ',$where):''; return sf_ops_fetch_all("SELECT st.*, u.email, u.display_name, a.email assigned_admin_email FROM support_tickets st LEFT JOIN users u ON u.id=st.user_id LEFT JOIN users a ON a.id=st.assigned_admin_user_id {$sqlWhere} ORDER BY FIELD(st.status,'new','open','pending_admin','pending_member','resolved','closed'), FIELD(st.priority,'urgent','high','medium','low'), COALESCE(st.last_message_at, st.created_at) DESC LIMIT ".max(1,min(300,$limit)),$params); }
function sf_support_ticket(int $id,int $userId=0): ?array { if(!$id||!sf_ops_table_exists('support_tickets'))return null; $where='st.id=?';$params=[$id]; if($userId){$where.=' AND st.user_id=?';$params[]=$userId;} return sf_ops_fetch_one("SELECT st.*, u.email, u.display_name FROM support_tickets st LEFT JOIN users u ON u.id=st.user_id WHERE {$where} LIMIT 1",$params); }
function sf_support_messages(int $ticketId): array { if(!$ticketId||!sf_ops_table_exists('support_ticket_messages'))return []; return sf_ops_fetch_all('SELECT m.*, u.email, u.display_name FROM support_ticket_messages m LEFT JOIN users u ON u.id=m.user_id WHERE m.ticket_id=? ORDER BY m.created_at ASC, m.id ASC',[$ticketId]); }
function sf_support_create_ticket(int $userId,string $subject,string $body,string $category='other',string $priority='medium',string $source='member',array $links=[]): int { if(!sf_ops_table_exists('support_tickets')||trim($subject)==='')return 0; if(!in_array($category,['account','billing','technical','content','merch','feedback','other'],true))$category='other'; if(!in_array($priority,['low','medium','high','urgent'],true))$priority='medium'; if(!in_array($source,['member','admin','system'],true))$source='member'; $num=sf_ops_ticket_number(); $ok=sf_ops_execute('INSERT INTO support_tickets (ticket_number,user_id,subject,body,category,priority,status,source,subscription_id,order_id,invoice_id,content_type,content_id,content_slug,last_message_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW())',[$num,$userId?:null,$subject,$body?:null,$category,$priority,'new',$source,$links['subscription_id']??null,$links['order_id']??null,$links['invoice_id']??null,$links['content_type']??null,$links['content_id']??null,$links['content_slug']??null]); $id=$ok?(int)(sf_ops_db()?->lastInsertId()?:0):0; if($id&&$body!=='')sf_support_add_message($id,$userId,$body,$source,false); return $id; }
function sf_support_add_message(int $ticketId,int $userId,string $message,string $sender='member',bool $internal=false): bool { if(!$ticketId||trim($message)===''||!sf_ops_table_exists('support_ticket_messages'))return false; if(!in_array($sender,['member','admin','system'],true))$sender='member'; $ok=sf_ops_execute('INSERT INTO support_ticket_messages (ticket_id,user_id,sender_type,message,is_internal) VALUES (?,?,?,?,?)',[$ticketId,$userId?:null,$sender,$message,$internal?1:0]); if($ok&&sf_ops_table_exists('support_tickets')) sf_ops_execute("UPDATE support_tickets SET last_message_at=NOW(), status=CASE WHEN ?='admin' THEN 'pending_member' WHEN status='new' THEN 'open' ELSE status END, first_response_at=CASE WHEN ?='admin' AND first_response_at IS NULL THEN NOW() ELSE first_response_at END, updated_at=NOW() WHERE id=?",[$sender,$sender,$ticketId]); return $ok; }
function sf_support_update_ticket(int $ticketId,string $status,string $priority='',int $assignedAdminId=0): bool { if(!$ticketId||!sf_ops_table_exists('support_tickets'))return false; if(!in_array($status,['new','open','pending_member','pending_admin','resolved','closed'],true))$status='open'; $sets=['status=?'];$params=[$status]; if($priority&&in_array($priority,['low','medium','high','urgent'],true)){$sets[]='priority=?';$params[]=$priority;} if($assignedAdminId>0){$sets[]='assigned_admin_user_id=?';$params[]=$assignedAdminId;} if($status==='resolved')$sets[]='resolved_at=COALESCE(resolved_at,NOW())'; if($status==='closed')$sets[]='closed_at=COALESCE(closed_at,NOW())'; $params[]=$ticketId; return sf_ops_execute('UPDATE support_tickets SET '.implode(',',$sets).', updated_at=NOW() WHERE id=?',$params); }
?>
