<?php
require_once __DIR__ . '/settings.php';
require_once __DIR__ . '/notifications.php';
require_once __DIR__ . '/admin_security.php';

function sf_mon_db(): ?PDO { return sf_db(); }
function sf_mon_table_exists(string $table): bool { $pdo=sf_mon_db(); if(!$pdo)return false; try{$s=$pdo->prepare('SHOW TABLES LIKE ?');$s->execute([$table]);return (bool)$s->fetchColumn();}catch(Throwable $e){return false;} }
function sf_mon_fetch_all(string $sql,array $params=[]): array { $pdo=sf_mon_db(); if(!$pdo)return []; try{$s=$pdo->prepare($sql);$s->execute($params);return $s->fetchAll()?:[];}catch(Throwable $e){error_log('Stonefellow monitoring fetch failed: '.$e->getMessage());return [];} }
function sf_mon_fetch_one(string $sql,array $params=[]): ?array { $rows=sf_mon_fetch_all($sql,$params); return $rows[0]??null; }
function sf_mon_execute(string $sql,array $params=[]): bool { $pdo=sf_mon_db(); if(!$pdo)return false; try{$s=$pdo->prepare($sql);return $s->execute($params);}catch(Throwable $e){error_log('Stonefellow monitoring execute failed: '.$e->getMessage());return false;} }
function sf_mon_h($value): string { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
function sf_mon_key(string $prefix): string { return $prefix.'-'.date('Ymd-His').'-'.strtolower(substr(bin2hex(random_bytes(3)),0,6)); }
function sf_mon_ready(): bool { return sf_mon_table_exists('monitoring_health_snapshots') && sf_mon_table_exists('incident_records'); }
function sf_mon_severity_rank(string $severity): int { return ['info'=>1,'notice'=>2,'warning'=>3,'error'=>4,'critical'=>5,'low'=>2,'medium'=>3,'high'=>4][$severity] ?? 1; }
function sf_mon_incident_severity(string $severity): string { return match($severity){'critical'=>'critical','error'=>'high','warning'=>'medium','notice'=>'low',default=>'low'}; }
function sf_mon_admin_users(): array { return sf_mon_table_exists('users')?sf_mon_fetch_all("SELECT id,email,display_name FROM users WHERE role='admin' AND status='active' AND email IS NOT NULL AND email<>'' ORDER BY id ASC LIMIT 50"):[]; }
function sf_mon_summary(): array { $out=['health_score'=>0,'health_status'=>'unknown','open_incidents'=>0,'critical_incidents'=>0,'new_errors'=>0,'failed_alerts'=>0,'alerts_queued'=>0,'checks_critical'=>0]; if(sf_mon_table_exists('monitoring_health_snapshots')){ $h=sf_mon_fetch_one('SELECT * FROM monitoring_health_snapshots ORDER BY created_at DESC LIMIT 1'); if($h){$out['health_score']=(int)$h['health_score'];$out['health_status']=(string)$h['status'];}} if(sf_mon_table_exists('incident_records')){ $out['open_incidents']=(int)(sf_mon_fetch_one("SELECT COUNT(*) total FROM incident_records WHERE status IN ('open','investigating','monitoring')")['total']??0); $out['critical_incidents']=(int)(sf_mon_fetch_one("SELECT COUNT(*) total FROM incident_records WHERE severity='critical' AND status IN ('open','investigating','monitoring')")['total']??0);} if(sf_mon_table_exists('monitoring_error_events'))$out['new_errors']=(int)(sf_mon_fetch_one("SELECT COUNT(*) total FROM monitoring_error_events WHERE status='new'")['total']??0); if(sf_mon_table_exists('admin_alert_notifications')){ $out['failed_alerts']=(int)(sf_mon_fetch_one("SELECT COUNT(*) total FROM admin_alert_notifications WHERE delivery_status='failed'")['total']??0); $out['alerts_queued']=(int)(sf_mon_fetch_one("SELECT COUNT(*) total FROM admin_alert_notifications WHERE delivery_status='queued'")['total']??0);} if(sf_mon_table_exists('monitoring_service_checks'))$out['checks_critical']=(int)(sf_mon_fetch_one("SELECT COUNT(*) total FROM monitoring_service_checks WHERE status='critical' AND is_active=1")['total']??0); return $out; }
function sf_mon_metrics(): array { $m=['failed_notifications_24h'=>0,'failed_jobs_24h'=>0,'failed_payments_24h'=>0,'open_incidents'=>0,'critical_incidents'=>0,'php_log_size'=>0,'php_log_modified'=>null]; if(sf_mon_table_exists('notification_logs'))$m['failed_notifications_24h']=(int)(sf_mon_fetch_one("SELECT COUNT(*) total FROM notification_logs WHERE status='failed' AND created_at>=DATE_SUB(NOW(), INTERVAL 1 DAY)")['total']??0); if(sf_mon_table_exists('ops_job_runs'))$m['failed_jobs_24h']=(int)(sf_mon_fetch_one("SELECT COUNT(*) total FROM ops_job_runs WHERE run_status='failed' AND started_at>=DATE_SUB(NOW(), INTERVAL 1 DAY)")['total']??0); if(sf_mon_table_exists('payment_transactions'))$m['failed_payments_24h']=(int)(sf_mon_fetch_one("SELECT COUNT(*) total FROM payment_transactions WHERE status IN ('failed','error') AND created_at>=DATE_SUB(NOW(), INTERVAL 1 DAY)")['total']??0); elseif(sf_mon_table_exists('subscription_payments'))$m['failed_payments_24h']=(int)(sf_mon_fetch_one("SELECT COUNT(*) total FROM subscription_payments WHERE status IN ('failed','error') AND created_at>=DATE_SUB(NOW(), INTERVAL 1 DAY)")['total']??0); if(sf_mon_table_exists('incident_records')){$m['open_incidents']=(int)(sf_mon_fetch_one("SELECT COUNT(*) total FROM incident_records WHERE status IN ('open','investigating','monitoring')")['total']??0);$m['critical_incidents']=(int)(sf_mon_fetch_one("SELECT COUNT(*) total FROM incident_records WHERE severity='critical' AND status IN ('open','investigating','monitoring')")['total']??0);} $log=ini_get('error_log'); if($log&&is_file($log)){$m['php_log_size']=(int)filesize($log);$m['php_log_modified']=date('Y-m-d H:i:s',(int)filemtime($log));} return $m; }
function sf_mon_capture_error(string $source,string $severity,string $message,array $meta=[]): int { if(!sf_mon_table_exists('monitoring_error_events')||trim($message)==='')return 0; if(!in_array($source,['php','application','database','payment','media','email','job','security','manual'],true))$source='application'; if(!in_array($severity,['info','notice','warning','error','critical'],true))$severity='error'; $finger=hash('sha256',$source.'|'.$severity.'|'.substr($message,0,500).'|'.($meta['file_path']??'')); $existing=sf_mon_fetch_one('SELECT id FROM monitoring_error_events WHERE fingerprint=? AND status IN ("new","triaged","linked") LIMIT 1',[$finger]); if($existing){sf_mon_execute('UPDATE monitoring_error_events SET last_seen_at=NOW(), occurrence_count=occurrence_count+1, updated_at=NOW() WHERE id=?',[(int)$existing['id']]); return (int)$existing['id'];} $key=sf_mon_key('err'); sf_mon_execute('INSERT INTO monitoring_error_events (event_key,source,severity,message,file_path,line_number,route_path,request_method,ip_address,user_agent,user_id,fingerprint,metadata_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',[$key,$source,$severity,$message,$meta['file_path']??null,$meta['line_number']??null,$meta['route_path']??($_SERVER['SCRIPT_NAME']??null),$meta['request_method']??($_SERVER['REQUEST_METHOD']??null),$meta['ip_address']??($_SERVER['REMOTE_ADDR']??null),$meta['user_agent']??substr((string)($_SERVER['HTTP_USER_AGENT']??''),0,255),function_exists('sf_current_user_id')?(sf_current_user_id()?:null):null,$finger,json_encode($meta,JSON_UNESCAPED_SLASHES)]); $id=(int)(sf_mon_db()?->lastInsertId()?:0); sf_sec_audit('monitoring_error_recorded',$severity==='critical'?'critical':'warning','monitoring_error',$id,['source'=>$source,'severity'=>$severity]); return $id; }
function sf_mon_update_error(int $id,string $status): bool { if(!$id||!sf_mon_table_exists('monitoring_error_events'))return false; if(!in_array($status,['new','triaged','linked','resolved','ignored'],true))$status='triaged'; return sf_mon_execute('UPDATE monitoring_error_events SET status=?, updated_at=NOW() WHERE id=?',[$status,$id]); }
function sf_mon_recent_errors(int $limit=100): array { return sf_mon_table_exists('monitoring_error_events')?sf_mon_fetch_all('SELECT * FROM monitoring_error_events ORDER BY FIELD(status,"new","triaged","linked","resolved","ignored"), FIELD(severity,"critical","error","warning","notice","info"), last_seen_at DESC LIMIT '.max(1,min(300,$limit))):[]; }
function sf_mon_service_checks(): array { return sf_mon_table_exists('monitoring_service_checks')?sf_mon_fetch_all('SELECT * FROM monitoring_service_checks WHERE is_active=1 ORDER BY FIELD(status,"critical","warning","unknown","healthy"), check_group, check_label'):[]; }
function sf_mon_refresh_service_checks(array $metrics=[]): void { if(!sf_mon_table_exists('monitoring_service_checks'))return; $metrics=$metrics?:sf_mon_metrics(); $updates=[['failed_notifications_24h',$metrics['failed_notifications_24h']>=20?'critical':($metrics['failed_notifications_24h']>=5?'warning':'healthy'),(string)$metrics['failed_notifications_24h']],['failed_jobs_24h',$metrics['failed_jobs_24h']>=10?'critical':($metrics['failed_jobs_24h']>=3?'warning':'healthy'),(string)$metrics['failed_jobs_24h']],['failed_payments_24h',$metrics['failed_payments_24h']>=10?'critical':($metrics['failed_payments_24h']>=3?'warning':'healthy'),(string)$metrics['failed_payments_24h']],['open_incidents',$metrics['critical_incidents']>0?'critical':($metrics['open_incidents']>0?'warning':'healthy'),(string)$metrics['open_incidents']]]; foreach($updates as $u)sf_mon_execute('UPDATE monitoring_service_checks SET status=?, last_value=?, last_checked_at=NOW(), updated_at=NOW() WHERE check_key=?',[$u[1],$u[2],$u[0]]); }
function sf_mon_take_snapshot(): int { if(!sf_mon_table_exists('monitoring_health_snapshots'))return 0; $checks=function_exists('sf_system_health_checks')?sf_system_health_checks():[]; $score=function_exists('sf_health_score')?sf_health_score($checks):0; $failed=array_values(array_filter($checks,fn($c)=>empty($c['ok']))); $status=$score>=90?'healthy':($score>=75?'warning':'critical'); $metrics=sf_mon_metrics(); sf_mon_refresh_service_checks($metrics); $key=sf_mon_key('health'); sf_mon_execute('INSERT INTO monitoring_health_snapshots (snapshot_key,health_score,status,checks_total,checks_passed,checks_failed,failed_checks_json,metrics_json,created_by_user_id) VALUES (?,?,?,?,?,?,?,?,?)',[$key,$score,$status,count($checks),count($checks)-count($failed),count($failed),json_encode($failed,JSON_UNESCAPED_SLASHES),json_encode($metrics,JSON_UNESCAPED_SLASHES),function_exists('sf_current_user_id')?(sf_current_user_id()?:null):null]); $id=(int)(sf_mon_db()?->lastInsertId()?:0); sf_mon_execute('UPDATE monitoring_service_checks SET status=?, last_value=?, last_checked_at=NOW(), detail=?, updated_at=NOW() WHERE check_key="system_health_score"',[$status,(string)$score,count($failed).' failing checks']); if($status==='critical')sf_mon_create_incident('Critical system health score','System health score is '.$score.'%.','critical','monitoring',0,$id); return $id; }
function sf_mon_snapshots(int $limit=80): array { return sf_mon_table_exists('monitoring_health_snapshots')?sf_mon_fetch_all('SELECT * FROM monitoring_health_snapshots ORDER BY created_at DESC LIMIT '.max(1,min(200,$limit))):[]; }
function sf_mon_create_incident(string $title,string $summary='',string $severity='medium',string $source='monitoring',int $errorId=0,int $snapshotId=0): int { if(!sf_mon_table_exists('incident_records')||trim($title)==='')return 0; if(!in_array($severity,['low','medium','high','critical'],true))$severity='medium'; $key=sf_mon_key('inc'); sf_mon_execute('INSERT INTO incident_records (incident_key,title,summary,severity,status,source,related_error_id,related_health_snapshot_id,created_by_user_id) VALUES (?,?,?,?,?,?,?,?,?)',[$key,$title,$summary,$severity,'open',$source,$errorId?:null,$snapshotId?:null,function_exists('sf_current_user_id')?(sf_current_user_id()?:null):null]); $id=(int)(sf_mon_db()?->lastInsertId()?:0); if($id){sf_mon_incident_event($id,'created','warning','Incident opened.'); sf_mon_route_alert($id);} return $id; }
function sf_mon_update_incident(int $id,string $status,string $severity='',string $resolution=''): bool { if(!$id||!sf_mon_table_exists('incident_records'))return false; if(!in_array($status,['open','investigating','monitoring','resolved','closed'],true))$status='open'; $sets=['status=?'];$params=[$status]; if($severity&&in_array($severity,['low','medium','high','critical'],true)){$sets[]='severity=?';$params[]=$severity;} if($resolution!==''){$sets[]='resolution_notes=?';$params[]=$resolution;} if($status==='investigating')$sets[]='acknowledged_at=COALESCE(acknowledged_at,NOW())'; if($status==='resolved')$sets[]='resolved_at=COALESCE(resolved_at,NOW())'; if($status==='closed')$sets[]='closed_at=COALESCE(closed_at,NOW())'; $params[]=$id; $ok=sf_mon_execute('UPDATE incident_records SET '.implode(',',$sets).', updated_at=NOW() WHERE id=?',$params); if($ok)sf_mon_incident_event($id,'status_update','info','Incident status updated to '.$status.'.'); return $ok; }
function sf_mon_incident_event(int $id,string $type,string $status,string $message,array $meta=[]): bool { if(!$id||!sf_mon_table_exists('incident_events'))return false; return sf_mon_execute('INSERT INTO incident_events (incident_id,event_type,event_status,message,actor_user_id,metadata_json) VALUES (?,?,?,?,?,?)',[$id,$type,$status,$message,function_exists('sf_current_user_id')?(sf_current_user_id()?:null):null,json_encode($meta,JSON_UNESCAPED_SLASHES)]); }
function sf_mon_incidents(int $limit=120): array { return sf_mon_table_exists('incident_records')?sf_mon_fetch_all('SELECT i.*, e.event_key error_key, h.health_score FROM incident_records i LEFT JOIN monitoring_error_events e ON e.id=i.related_error_id LEFT JOIN monitoring_health_snapshots h ON h.id=i.related_health_snapshot_id ORDER BY FIELD(i.status,"open","investigating","monitoring","resolved","closed"), FIELD(i.severity,"critical","high","medium","low"), i.detected_at DESC LIMIT '.max(1,min(300,$limit))):[]; }
function sf_mon_incident(int $id): ?array { return $id&&sf_mon_table_exists('incident_records')?sf_mon_fetch_one('SELECT * FROM incident_records WHERE id=? LIMIT 1',[$id]):null; }
function sf_mon_incident_events(int $id): array { return $id&&sf_mon_table_exists('incident_events')?sf_mon_fetch_all('SELECT ev.*, u.email, u.display_name FROM incident_events ev LEFT JOIN users u ON u.id=ev.actor_user_id WHERE ev.incident_id=? ORDER BY ev.created_at DESC',[$id]):[]; }
function sf_mon_alerts(int $limit=150): array { return sf_mon_table_exists('admin_alert_notifications')?sf_mon_fetch_all('SELECT a.*, i.title incident_title, u.email user_email FROM admin_alert_notifications a LEFT JOIN incident_records i ON i.id=a.incident_id LEFT JOIN users u ON u.id=a.recipient_user_id ORDER BY FIELD(a.delivery_status,"queued","failed","sent","read","dismissed","skipped"), FIELD(a.severity,"critical","error","warning","notice","info"), a.created_at DESC LIMIT '.max(1,min(300,$limit))):[]; }
function sf_mon_rules(): array { return sf_mon_table_exists('alert_rules')?sf_mon_fetch_all('SELECT * FROM alert_rules ORDER BY FIELD(status,"active","paused","archived"), trigger_source, rule_label'):[]; }
function sf_mon_route_alert(int $incidentId): array { $out=['created'=>0,'sent'=>0,'failed'=>0]; $incident=sf_mon_incident($incidentId); if(!$incident||!sf_mon_table_exists('admin_alert_notifications'))return $out; $severity=$incident['severity']==='critical'?'critical':($incident['severity']==='high'?'error':'warning'); $rule=sf_mon_fetch_one("SELECT * FROM alert_rules WHERE status='active' AND trigger_source IN ('incident','custom') ORDER BY id ASC LIMIT 1"); $recipients=sf_mon_admin_users(); if(!$recipients)$recipients=[['id'=>null,'email'=>sf_notify_from_email(),'display_name'=>'Stonefellow Admin']]; foreach($recipients as $r){$key=sf_mon_key('alert');$logId=null;$status='queued'; if(!empty($rule['route_email'])&&filter_var((string)$r['email'],FILTER_VALIDATE_EMAIL)){ $logId=sf_notify_send_template('admin_incident_alert',['user_id'=>$r['id']??null,'email'=>$r['email'],'name'=>$r['display_name']?:'Admin'],['incident_title'=>$incident['title'],'incident_severity'=>$incident['severity'],'incident_status'=>$incident['status'],'incident_summary'=>$incident['summary'],'incident_url'=>sf_notify_absolute_url('admin/incidents.php?incident_id='.$incidentId)],['notification_type'=>'admin_incident','metadata'=>['incident_id'=>$incidentId],'dispatch'=>true]); $status=$logId?'sent':'failed'; }
    sf_mon_execute('INSERT INTO admin_alert_notifications (alert_key,rule_id,incident_id,recipient_user_id,recipient_email,channel,title,body,severity,delivery_status,notification_log_id,sent_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',[$key,$rule['id']??null,$incidentId,$r['id']??null,$r['email']??null,'email','Incident: '.$incident['title'],$incident['summary'],$severity,$status,$logId,$status==='sent'?date('Y-m-d H:i:s'):null]); $out['created']++; if($status==='sent')$out['sent']++; else $out['failed']++; } return $out; }
function sf_mon_mark_alert(int $id,string $status): bool { if(!$id||!sf_mon_table_exists('admin_alert_notifications'))return false; if(!in_array($status,['queued','sent','failed','read','dismissed','skipped'],true))$status='read'; $read=$status==='read'?', read_at=COALESCE(read_at,NOW())':''; return sf_mon_execute("UPDATE admin_alert_notifications SET delivery_status=?{$read}, updated_at=NOW() WHERE id=?",[$status,$id]); }
?>
