<?php
require_once __DIR__ . '/notifications.php';
require_once __DIR__ . '/member_lifecycle_support.php';
require_once __DIR__ . '/revenue_dashboard.php';
require_once __DIR__ . '/feed_personalization.php';
require_once __DIR__ . '/delivery_integrity.php';

function sf_sched_db(): ?PDO { return sf_db(); }
function sf_sched_table_exists(string $table): bool { $pdo=sf_sched_db();return $pdo instanceof PDO&&preg_match('/^[a-z0-9_]+$/i',$table)&&sf_notify_table_exists($table); }
function sf_sched_fetch_all(string $sql,array $params=[]): array { $pdo=sf_sched_db();if(!$pdo)return [];try{$s=$pdo->prepare($sql);$s->execute($params);return $s->fetchAll()?:[];}catch(Throwable $e){error_log('Stonefellow scheduler fetch failed: '.$e->getMessage());return [];} }
function sf_sched_fetch_one(string $sql,array $params=[]): ?array { $r=sf_sched_fetch_all($sql,$params);return $r[0]??null; }
function sf_sched_execute(string $sql,array $params=[]): bool { $pdo=sf_sched_db();if(!$pdo)return false;try{$s=$pdo->prepare($sql);return $s->execute($params);}catch(Throwable $e){error_log('Stonefellow scheduler execute failed: '.$e->getMessage());return false;} }
function sf_sched_h($value): string { return htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8'); }
function sf_sched_ready(): bool { return sf_sched_table_exists('ops_scheduled_jobs')&&sf_sched_table_exists('ops_job_runs'); }
function sf_msg_ready(): bool { return sf_sched_table_exists('member_message_campaigns')&&sf_sched_table_exists('member_message_recipients')&&sf_sched_table_exists('member_messages'); }
function sf_sched_jobs(): array { return sf_sched_ready()?sf_sched_fetch_all('SELECT * FROM ops_scheduled_jobs ORDER BY FIELD(status,"active","paused","archived"),FIELD(frequency,"hourly","daily","weekly","monthly","manual"),next_run_at,id'):[]; }
function sf_sched_runs(int $limit=80): array { return sf_sched_table_exists('ops_job_runs')?sf_sched_fetch_all('SELECT r.*,j.title FROM ops_job_runs r LEFT JOIN ops_scheduled_jobs j ON j.id=r.job_id ORDER BY r.started_at DESC,r.id DESC LIMIT '.max(1,min(200,$limit))):[]; }
function sf_sched_summary(): array { $o=['jobs'=>0,'active'=>0,'due'=>0,'runs'=>0,'failed'=>0,'running'=>0];if(!sf_sched_ready())return $o;$r=sf_sched_fetch_one("SELECT COUNT(*) jobs,SUM(status='active') active,SUM(status='active' AND frequency<>'manual' AND next_run_at IS NOT NULL AND next_run_at<=NOW()) due FROM ops_scheduled_jobs")?:[];$o['jobs']=(int)($r['jobs']??0);$o['active']=(int)($r['active']??0);$o['due']=(int)($r['due']??0);$r=sf_sched_fetch_one("SELECT COUNT(*) runs,SUM(run_status='failed') failed,SUM(run_status='started' AND started_at>=DATE_SUB(NOW(),INTERVAL 30 MINUTE)) running FROM ops_job_runs WHERE started_at>=DATE_SUB(NOW(),INTERVAL 7 DAY)")?:[];$o['runs']=(int)($r['runs']??0);$o['failed']=(int)($r['failed']??0);$o['running']=(int)($r['running']??0);return $o; }
function sf_sched_next_run(string $frequency,?string $time=null,?DateTimeImmutable $from=null): ?string {
 if($frequency==='manual')return null;$from=$from?:new DateTimeImmutable('now');$time=trim((string)$time);if(!preg_match('/^([01]\d|2[0-3]):[0-5]\d(?::[0-5]\d)?$/',$time))$time='08:00:00';if(strlen($time)===5)$time.=':00';
 if($frequency==='hourly')return $from->modify('+1 hour')->setTime((int)$from->modify('+1 hour')->format('H'),0,0)->format('Y-m-d H:i:s');
 $candidate=$from->setTime((int)substr($time,0,2),(int)substr($time,3,2),(int)substr($time,6,2));
 if($frequency==='daily'){if($candidate<=$from)$candidate=$candidate->modify('+1 day');return $candidate->format('Y-m-d H:i:s');}
 if($frequency==='weekly')return $candidate->modify('+7 days')->format('Y-m-d H:i:s');
 if($frequency==='monthly')return $candidate->modify('+1 month')->format('Y-m-d H:i:s');
 return null;
}
function sf_sched_save_job(array $data,int $id=0): int {
 if(!sf_sched_ready())return 0;$key=strtolower(trim((string)($data['job_key']??'')));$key=preg_replace('/[^a-z0-9_-]+/','_',$key)??'';$title=sf_delivery_clean_header((string)($data['title']??''),190);if($key===''||$title==='')return 0;$types=['dispatch_notifications','lifecycle_churn_scan','support_sla_scan','revenue_snapshot','engagement_score_refresh','custom'];$type=in_array((string)($data['job_type']??''),$types,true)?(string)$data['job_type']:'custom';$freq=in_array((string)($data['frequency']??''),['hourly','daily','weekly','monthly','manual'],true)?(string)$data['frequency']:'daily';$status=in_array((string)($data['status']??''),['active','paused','archived'],true)?(string)$data['status']:'paused';$time=trim((string)($data['schedule_time']??''))?:null;$explicit=trim((string)($data['next_run_at']??''));$next=$freq==='manual'?null:($explicit!==''&&strtotime($explicit)!==false?date('Y-m-d H:i:s',strtotime($explicit)):sf_sched_next_run($freq,$time));$description=sf_delivery_clean_text((string)($data['description']??''),5000);$vals=[$key,$type,$title,$description?:null,$freq,$time,$status,$next,sf_current_user_id()?:null];
 try{if($id>0){$s=sf_sched_db()->prepare('UPDATE ops_scheduled_jobs SET job_key=?,job_type=?,title=?,description=?,frequency=?,schedule_time=?,status=?,next_run_at=?,created_by_user_id=COALESCE(created_by_user_id,?),updated_at=NOW() WHERE id=?');$s->execute(array_merge($vals,[$id]));return $s->rowCount()>=0?$id:0;}$s=sf_sched_db()->prepare('INSERT INTO ops_scheduled_jobs (job_key,job_type,title,description,frequency,schedule_time,status,next_run_at,created_by_user_id) VALUES (?,?,?,?,?,?,?,?,?)');$s->execute($vals);return (int)sf_sched_db()->lastInsertId();}catch(Throwable $e){error_log('Stonefellow scheduler save failed: '.$e->getMessage());return 0;}
}
function sf_sched_due_jobs(int $limit=20): array { return sf_sched_ready()?sf_sched_fetch_all("SELECT * FROM ops_scheduled_jobs WHERE status='active' AND frequency<>'manual' AND next_run_at IS NOT NULL AND next_run_at<=NOW() ORDER BY next_run_at,id LIMIT ".max(1,min(100,$limit))):[]; }
function sf_sched_start_run(array $job): int { try{$s=sf_sched_db()->prepare("INSERT INTO ops_job_runs (job_id,job_key,run_status,metadata_json) VALUES (?,?,'started',?)");$s->execute([(int)$job['id'],(string)$job['job_key'],json_encode(['lease_started_at'=>date('c')],JSON_UNESCAPED_SLASHES)]);return (int)sf_sched_db()->lastInsertId();}catch(Throwable $e){return 0;} }
function sf_sched_finish_run(int $runId,bool $ok,array $counts,string $summary,string $error=''): void { if($runId<=0)return;sf_sched_execute('UPDATE ops_job_runs SET run_status=?,finished_at=NOW(),processed_count=?,success_count=?,failed_count=?,result_summary=?,error_message=?,metadata_json=? WHERE id=?',[$ok?'success':'failed',(int)($counts['processed']??0),(int)($counts['success']??$counts['sent']??0),(int)($counts['failed']??0),sf_delivery_clean_text($summary,5000),$error?sf_delivery_clean_text($error,5000):null,json_encode($counts,JSON_UNESCAPED_SLASHES),$runId]); }
function sf_sched_task_exists(int $userId,string $type,string $title): bool { if(!sf_sched_table_exists('member_retention_tasks'))return false;$r=sf_sched_fetch_one("SELECT id FROM member_retention_tasks WHERE user_id=? AND task_type=? AND title=? AND status IN ('open','in_progress','scheduled') LIMIT 1",[$userId,$type,$title]);return (bool)$r; }
function sf_sched_run_job(array $job,bool $manual=false): array {
 $id=(int)($job['id']??0);$key=(string)($job['job_key']??'manual');if($id<=0)return ['ok'=>false,'summary'=>'Invalid job.','counts'=>[]];if(!$manual&&(($job['status']??'')!=='active'||($job['frequency']??'manual')==='manual'))return ['ok'=>false,'summary'=>'Job is not eligible for an automatic run.','counts'=>[]];$pdo=sf_sched_db();$lock='job-'.$id;if(!sf_delivery_advisory_lock($pdo,$lock,1))return ['ok'=>false,'summary'=>'Job is already running.','counts'=>[]];$runId=0;$result=['processed'=>0,'success'=>0,'failed'=>0];$summary='';$ok=true;$error='';
 try{$runId=sf_sched_start_run($job);if(!$runId)throw new RuntimeException('Could not create run lease.');$type=(string)($job['job_type']??'custom');
  if($type==='dispatch_notifications'){$n=sf_notify_dispatch_pending(100);$m=sf_msg_send_due(10);$result=['processed'=>(int)$n['processed']+(int)$m['processed'],'success'=>(int)$n['sent']+(int)$m['sent'],'failed'=>(int)$n['failed']+(int)$m['failed']];$summary='Notification and due campaign dispatch complete.';}
  elseif($type==='revenue_snapshot'){$ok=sf_rev_save_snapshot();$result=['processed'=>1,'success'=>$ok?1:0,'failed'=>$ok?0:1];$summary='Revenue snapshot saved.';}
  elseif($type==='engagement_score_refresh'){$ok=sf_engagement_recalculate_member_scores();$result=['processed'=>1,'success'=>$ok?1:0,'failed'=>$ok?0:1];$summary='Engagement scores recalculated.';}
  elseif($type==='lifecycle_churn_scan'){foreach(sf_lifecycle_segments() as $m){$risk=($m['subscription_status']??'')==='past_due'||!empty($m['cancel_at_period_end'])||(!empty($m['current_period_end'])&&strtotime((string)$m['current_period_end'])<time()+864000);if(!$risk)continue;$result['processed']++;$title='Retention follow-up: '.($m['display_name']?:$m['email']);if(sf_sched_task_exists((int)$m['id'],'cancel_save',$title)){$result['success']++;continue;}if(sf_lifecycle_create_task((int)$m['id'],$title,'Automated churn-risk scan flagged this member.','cancel_save','high'))$result['success']++;else$result['failed']++;}$summary='Churn-risk scan complete.';}
  elseif($type==='support_sla_scan'){foreach(sf_support_tickets(0,'',200) as $t){if(in_array($t['status'],['resolved','closed'],true)||strtotime((string)($t['created_at']??'now'))>=time()-86400)continue;$result['processed']++;$title='Support SLA follow-up: '.$t['ticket_number'];if(!empty($t['user_id'])&&(sf_sched_task_exists((int)$t['user_id'],'support_followup',$title)||sf_lifecycle_create_task((int)$t['user_id'],$title,$t['subject']??'Open support ticket','support_followup','high')))$result['success']++;else$result['failed']++;}$summary='Support SLA scan complete.';}
  else{$result=['processed'=>1,'success'=>1,'failed'=>0];$summary='Custom/manual job logged.';}
  if($result['failed']>0&&$result['success']===0)$ok=false;
 }catch(Throwable $e){$ok=false;$result['failed']++;$summary='Job failed.';$error=$e->getMessage();error_log('Stonefellow scheduler job failed: '.$e->getMessage());}
 finally{sf_sched_finish_run($runId,$ok,$result,$summary,$error);$next=sf_sched_next_run((string)($job['frequency']??'manual'),$job['schedule_time']??null);sf_sched_execute('UPDATE ops_scheduled_jobs SET last_run_at=NOW(),next_run_at=?,run_count=run_count+1,failure_count=failure_count+?,updated_at=NOW() WHERE id=?',[$next,$ok?0:1,$id]);sf_delivery_advisory_unlock($pdo,$lock);}
 return ['ok'=>$ok,'summary'=>$summary,'counts'=>$result,'run_id'=>$runId];
}
function sf_sched_run_due(int $limit=20): array { $out=['processed'=>0,'success'=>0,'failed'=>0,'runs'=>[]];if(!sf_sched_ready())return $out;$pdo=sf_sched_db();if(!sf_delivery_advisory_lock($pdo,'due-jobs',1))return $out;try{foreach(sf_sched_due_jobs($limit) as $job){$out['processed']++;$r=sf_sched_run_job($job,false);$out['runs'][]=$r;if(!empty($r['ok']))$out['success']++;else$out['failed']++;}}finally{sf_delivery_advisory_unlock($pdo,'due-jobs');}return $out; }

function sf_msg_campaigns(int $limit=120): array { return sf_msg_ready()?sf_sched_fetch_all('SELECT c.*,u.email admin_email,u.display_name admin_name,(SELECT COUNT(*) FROM member_message_recipients r WHERE r.campaign_id=c.id) recipients,(SELECT COUNT(*) FROM member_message_recipients r WHERE r.campaign_id=c.id AND r.delivery_status="sent") sent_count FROM member_message_campaigns c LEFT JOIN users u ON u.id=c.created_by_user_id ORDER BY FIELD(c.status,"draft","scheduled","queued","sending","sent","paused","archived"),COALESCE(c.scheduled_at,c.created_at) DESC LIMIT '.max(1,min(200,$limit))):[]; }
function sf_msg_campaign(int $id): ?array { return $id>0&&sf_msg_ready()?sf_sched_fetch_one('SELECT * FROM member_message_campaigns WHERE id=? LIMIT 1',[$id]):null; }
function sf_msg_summary(): array { $o=['campaigns'=>0,'draft'=>0,'scheduled'=>0,'queued'=>0,'sending'=>0,'sent'=>0,'recipients'=>0,'in_app_unread'=>0];if(!sf_msg_ready())return $o;foreach(sf_sched_fetch_all('SELECT status,COUNT(*) total FROM member_message_campaigns GROUP BY status') as $r){$o[$r['status']]=(int)$r['total'];$o['campaigns']+=(int)$r['total'];}$o['recipients']=(int)(sf_sched_fetch_one('SELECT COUNT(*) total FROM member_message_recipients')['total']??0);$o['in_app_unread']=(int)(sf_sched_fetch_one("SELECT COUNT(*) total FROM member_messages WHERE status='unread'")['total']??0);return $o; }
function sf_msg_campaign_key(string $title): string { $base=strtolower(trim(preg_replace('/[^a-z0-9]+/i','-',$title)??'','-'))?:'member-message';return substr($base,0,95).'-'.date('ymd-His'); }
function sf_msg_save_campaign(array $data,int $id=0): int {
 if(!sf_msg_ready())return 0;$title=sf_delivery_clean_header((string)($data['title']??''),190);$subject=sf_delivery_clean_header((string)($data['subject']??''),190);$body=sf_delivery_clean_text((string)($data['body']??''),20000);if($title===''||$subject===''||trim($body)==='')return 0;$email=!empty($data['channel_email']);$inApp=!empty($data['channel_in_app']);if(!$email&&!$inApp)return 0;$key=trim((string)($data['campaign_key']??''))?:sf_msg_campaign_key($title);$key=preg_replace('/[^a-z0-9_-]+/i','_',strtolower($key))??'';$aud=in_array((string)($data['audience_filter']??''),['all_members','active_subscribers','free_members','churn_risk','engaged_members','support_open','manual'],true)?(string)$data['audience_filter']:'manual';$status=in_array((string)($data['status']??''),['draft','scheduled','queued','paused','archived'],true)?(string)$data['status']:'draft';$scheduled=trim((string)($data['scheduled_at']??''));$scheduled=$scheduled!==''&&strtotime($scheduled)!==false?date('Y-m-d H:i:s',strtotime($scheduled)):null;if($status==='scheduled'&&(!$scheduled||strtotime($scheduled)<=time()))return 0;$action=sf_delivery_safe_url((string)($data['action_url']??''));$honors=!empty($data['honors_preferences']);if(in_array($aud,['all_members','free_members','engaged_members'],true))$honors=true;$vals=[$key,$title,$subject,$body,$aud,$email?1:0,$inApp?1:0,$honors?1:0,$status,$scheduled,$action?:null,sf_current_user_id()?:null];
 try{if($id>0){$existing=sf_msg_campaign($id);if(!$existing||in_array((string)$existing['status'],['sending','sent'],true))return 0;$s=sf_sched_db()->prepare('UPDATE member_message_campaigns SET campaign_key=?,title=?,subject=?,body=?,audience_filter=?,channel_email=?,channel_in_app=?,honors_preferences=?,status=?,scheduled_at=?,action_url=?,created_by_user_id=COALESCE(created_by_user_id,?),updated_at=NOW() WHERE id=?');$s->execute(array_merge($vals,[$id]));return $id;}$s=sf_sched_db()->prepare('INSERT INTO member_message_campaigns (campaign_key,title,subject,body,audience_filter,channel_email,channel_in_app,honors_preferences,status,scheduled_at,action_url,created_by_user_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)');$s->execute($vals);return (int)sf_sched_db()->lastInsertId();}catch(Throwable $e){error_log('Stonefellow campaign save failed: '.$e->getMessage());return 0;}
}
function sf_msg_audience(string $filter,int $limit=1000): array { if(!sf_sched_table_exists('users')||$filter==='manual')return [];$base='SELECT DISTINCT u.id,u.email,u.display_name FROM users u';$where=" WHERE u.role<>'admin' AND u.status='active' AND u.email IS NOT NULL AND u.email<>''";if($filter==='active_subscribers'){$base.=' INNER JOIN user_subscriptions us ON us.user_id=u.id';$where.=" AND us.status IN ('active','trialing') AND (us.current_period_end IS NULL OR us.current_period_end>=NOW())";}elseif($filter==='free_members')$where.=" AND NOT EXISTS (SELECT 1 FROM user_subscriptions us WHERE us.user_id=u.id AND us.status IN ('active','trialing'))";elseif($filter==='churn_risk'){$base.=' INNER JOIN user_subscriptions us ON us.user_id=u.id';$where.=" AND (us.status IN ('past_due','unpaid') OR us.cancel_at_period_end=1 OR (us.current_period_end BETWEEN NOW() AND DATE_ADD(NOW(),INTERVAL 10 DAY)))";}elseif($filter==='engaged_members'){$base.=' INNER JOIN member_engagement_scores mes ON mes.user_id=u.id';$where.=' AND mes.score>=10';}elseif($filter==='support_open'){$base.=' INNER JOIN support_tickets st ON st.user_id=u.id';$where.=" AND st.status NOT IN ('resolved','closed')";}return sf_sched_fetch_all($base.$where.' ORDER BY u.id LIMIT '.max(1,min(5000,$limit))); }
function sf_msg_seed_recipients(int $campaignId): int { $c=sf_msg_campaign($campaignId);if(!$c||!in_array((string)$c['status'],['draft','scheduled','queued','paused'],true))return 0;$count=0;foreach(sf_msg_audience((string)$c['audience_filter']) as $u){$email=sf_delivery_safe_email((string)($u['email']??''));if($email===''||!sf_delivery_advisory_lock(sf_sched_db(),'campaign-recipient-'.$campaignId.'-'.$u['id'],1))continue;try{$s=sf_sched_db()->prepare('INSERT IGNORE INTO member_message_recipients (campaign_id,user_id,email) VALUES (?,?,?)');$s->execute([$campaignId,(int)$u['id'],$email]);$count+=$s->rowCount();}finally{sf_delivery_advisory_unlock(sf_sched_db(),'campaign-recipient-'.$campaignId.'-'.$u['id']);}}return $count; }
function sf_msg_create_member_message(int $userId,string $subject,string $body,string $type='notice',string $url='',array $meta=[]): int { if(!sf_sched_table_exists('member_messages')||$userId<=0)return 0;$subject=sf_delivery_clean_header($subject,190);$body=sf_delivery_clean_text($body,20000);$url=sf_delivery_safe_url($url);$campaignId=(int)($meta['campaign_id']??0);if($campaignId>0){$existing=sf_sched_fetch_one("SELECT id FROM member_messages WHERE user_id=? AND JSON_UNQUOTE(JSON_EXTRACT(metadata_json,'$.campaign_id'))=? LIMIT 1",[$userId,(string)$campaignId]);if($existing)return (int)$existing['id'];}try{$pdo=sf_sched_db();$pdo->beginTransaction();$s=$pdo->prepare('INSERT INTO member_message_threads (user_id,subject,thread_type,status,last_message_at,metadata_json) VALUES (?,?,"notice","open",NOW(),?)');$s->execute([$userId,$subject,json_encode($meta,JSON_UNESCAPED_SLASHES)]);$thread=(int)$pdo->lastInsertId();$s=$pdo->prepare('INSERT INTO member_messages (thread_id,user_id,sender_user_id,sender_type,subject,body,action_url,message_type,status,metadata_json) VALUES (?,?,?,"admin",?,?,?,?,"unread",?)');$s->execute([$thread,$userId,sf_current_user_id()?:null,$subject,$body,$url?:null,$type,json_encode($meta,JSON_UNESCAPED_SLASHES)]);$id=(int)$pdo->lastInsertId();$pdo->commit();return $id;}catch(Throwable $e){if(sf_sched_db()?->inTransaction())sf_sched_db()->rollBack();return 0;} }
function sf_msg_log_status(int $logId): string { if($logId<=0||!sf_notify_table_exists('notification_logs'))return '';$r=sf_sched_fetch_one('SELECT status FROM notification_logs WHERE id=? LIMIT 1',[$logId]);return (string)($r['status']??''); }
function sf_msg_send_campaign(int $campaignId,int $limit=250): array {
 $out=['processed'=>0,'sent'=>0,'failed'=>0,'skipped'=>0];$c=sf_msg_campaign($campaignId);if(!$c||!in_array((string)$c['status'],['scheduled','queued','sending'],true))return $out;$pdo=sf_sched_db();$lock='campaign-'.$campaignId;if(!sf_delivery_advisory_lock($pdo,$lock,1))return $out;
 try{sf_msg_seed_recipients($campaignId);$pdo->prepare("UPDATE member_message_campaigns SET status='sending',updated_at=NOW() WHERE id=? AND status IN ('scheduled','queued','sending')")->execute([$campaignId]);$rows=sf_sched_fetch_all("SELECT r.*,u.email,u.display_name,u.status user_status FROM member_message_recipients r INNER JOIN users u ON u.id=r.user_id WHERE r.campaign_id=? AND r.delivery_status IN ('queued','failed') AND u.status='active' ORDER BY r.id LIMIT ".max(1,min(1000,$limit)),[$campaignId]);
  foreach($rows as $r){$out['processed']++;$errors=[];$attempted=0;$completed=0;$skippedChannels=0;$messageId=(int)($r['member_message_id']??0);$logId=(int)($r['email_log_id']??0);$preferenceKey='member_message';$honors=!empty($c['honors_preferences']);
   if(!empty($c['channel_in_app'])){if($honors&&!sf_delivery_preference_enabled((int)$r['user_id'],$preferenceKey,'in_app'))$skippedChannels++;else{$attempted++;if(!$messageId)$messageId=sf_msg_create_member_message((int)$r['user_id'],(string)$c['subject'],(string)$c['body'],'promotion',(string)($c['action_url']??''),['campaign_id'=>$campaignId,'recipient_id'=>(int)$r['id']]);if($messageId)$completed++;else$errors[]='In-app delivery failed.';}}
   if(!empty($c['channel_email'])){if($honors&&!sf_delivery_preference_enabled((int)$r['user_id'],$preferenceKey,'email'))$skippedChannels++;else{$attempted++;$logId=sf_notify_send_template('member_message_notice',['user_id'=>(int)$r['user_id'],'email'=>$r['email'],'name'=>$r['display_name']?:$r['email']],['message_subject'=>$c['subject'],'message_body'=>$c['body'],'message_text'=>$c['body'],'action_url'=>$c['action_url']?:sf_notify_absolute_url('messages.php')],['notification_type'=>'member_message','metadata'=>['campaign_id'=>$campaignId,'recipient_id'=>(int)$r['id']],'idempotency_key'=>'campaign-'.$campaignId.'-recipient-'.$r['id'].'-email','honors_preferences'=>$honors,'dispatch'=>true])?:0;$status=sf_msg_log_status($logId);if(in_array($status,['sent','queued'],true))$completed++;elseif($status==='skipped')$skippedChannels++;else$errors[]='Email delivery failed.';}}
   $selected=(!empty($c['channel_email'])?1:0)+(!empty($c['channel_in_app'])?1:0);if($selected>0&&$skippedChannels===$selected){$status='skipped';$out['skipped']++;}elseif($attempted>0&&$completed===$attempted){$status='sent';$out['sent']++;}else{$status='failed';$out['failed']++;}$pdo->prepare('UPDATE member_message_recipients SET delivery_status=?,email_log_id=?,member_message_id=?,error_message=?,sent_at=CASE WHEN ?="sent" THEN COALESCE(sent_at,NOW()) ELSE sent_at END,updated_at=NOW() WHERE id=?')->execute([$status,$logId?:null,$messageId?:null,$errors?implode(' ',$errors):null,$status,(int)$r['id']]);
  }
  $remaining=(int)(sf_sched_fetch_one("SELECT COUNT(*) total FROM member_message_recipients WHERE campaign_id=? AND delivery_status IN ('queued','failed')",[$campaignId])['total']??0);$final=$remaining===0?'sent':'queued';$pdo->prepare('UPDATE member_message_campaigns SET status=?,sent_at=CASE WHEN ?="sent" THEN COALESCE(sent_at,NOW()) ELSE sent_at END,updated_at=NOW() WHERE id=?')->execute([$final,$final,$campaignId]);return $out;
 }finally{sf_delivery_advisory_unlock($pdo,$lock);}
}
function sf_msg_member_messages(int $userId,string $status='',int $limit=100): array { if($userId<=0||!sf_sched_table_exists('member_messages'))return [];$where='WHERE m.user_id=?';$p=[$userId];if(in_array($status,['unread','read','archived','dismissed'],true)){$where.=' AND m.status=?';$p[]=$status;}return sf_sched_fetch_all('SELECT m.* FROM member_messages m '.$where.' ORDER BY m.created_at DESC,m.id DESC LIMIT '.max(1,min(200,$limit)),$p); }
function sf_msg_update_member_message(int $userId,int $id,string $status='read'): bool { if($userId<=0||$id<=0||!in_array($status,['unread','read','archived','dismissed'],true)||!sf_sched_table_exists('member_messages'))return false;$read=$status==='read'?',read_at=COALESCE(read_at,NOW())':'';return sf_sched_execute("UPDATE member_messages SET status=?{$read},updated_at=NOW() WHERE id=? AND user_id=?",[$status,$id,$userId]); }
function sf_msg_due_campaigns(int $limit=20): array { return sf_msg_ready()?sf_sched_fetch_all("SELECT * FROM member_message_campaigns WHERE status IN ('scheduled','queued') AND (scheduled_at IS NULL OR scheduled_at<=NOW()) ORDER BY COALESCE(scheduled_at,created_at),id LIMIT ".max(1,min(100,$limit))):[]; }
function sf_msg_send_due(int $limit=20): array { $o=['campaigns'=>0,'processed'=>0,'sent'=>0,'failed'=>0,'skipped'=>0];$pdo=sf_sched_db();if(!$pdo||!sf_delivery_advisory_lock($pdo,'due-campaigns',1))return $o;try{foreach(sf_msg_due_campaigns($limit) as $c){$o['campaigns']++;$r=sf_msg_send_campaign((int)$c['id'],500);foreach(['processed','sent','failed','skipped'] as $k)$o[$k]+=(int)($r[$k]??0);}}finally{sf_delivery_advisory_unlock($pdo,'due-campaigns');}return $o; }
?>
