<?php
require_once __DIR__ . '/notifications.php';
require_once __DIR__ . '/member_lifecycle_support.php';
require_once __DIR__ . '/revenue_dashboard.php';
require_once __DIR__ . '/feed_personalization.php';

function sf_sched_db(): ?PDO { return sf_db(); }
function sf_sched_table_exists(string $table): bool { $pdo=sf_sched_db(); if(!$pdo)return false; try{$s=$pdo->prepare('SHOW TABLES LIKE ?');$s->execute([$table]);return (bool)$s->fetchColumn();}catch(Throwable $e){return false;} }
function sf_sched_fetch_all(string $sql,array $params=[]): array { $pdo=sf_sched_db(); if(!$pdo)return []; try{$s=$pdo->prepare($sql);$s->execute($params);return $s->fetchAll()?:[];}catch(Throwable $e){error_log('Stonefellow scheduler fetch failed: '.$e->getMessage());return [];} }
function sf_sched_fetch_one(string $sql,array $params=[]): ?array { $rows=sf_sched_fetch_all($sql,$params); return $rows[0]??null; }
function sf_sched_execute(string $sql,array $params=[]): bool { $pdo=sf_sched_db(); if(!$pdo)return false; try{$s=$pdo->prepare($sql);return $s->execute($params);}catch(Throwable $e){error_log('Stonefellow scheduler execute failed: '.$e->getMessage());return false;} }
function sf_sched_h($value): string { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
function sf_sched_ready(): bool { return sf_sched_table_exists('ops_scheduled_jobs') && sf_sched_table_exists('ops_job_runs'); }
function sf_msg_ready(): bool { return sf_sched_table_exists('member_message_campaigns') && sf_sched_table_exists('member_messages'); }
function sf_sched_jobs(): array { if(!sf_sched_ready())return []; return sf_sched_fetch_all('SELECT * FROM ops_scheduled_jobs ORDER BY FIELD(status,"active","paused","archived"), FIELD(frequency,"hourly","daily","weekly","monthly","manual"), next_run_at ASC, id ASC'); }
function sf_sched_runs(int $limit=80): array { if(!sf_sched_table_exists('ops_job_runs'))return []; return sf_sched_fetch_all('SELECT r.*, j.title FROM ops_job_runs r LEFT JOIN ops_scheduled_jobs j ON j.id=r.job_id ORDER BY r.started_at DESC, r.id DESC LIMIT '.max(1,min(200,$limit))); }
function sf_sched_summary(): array { $out=['jobs'=>0,'active'=>0,'due'=>0,'runs'=>0,'failed'=>0]; if(!sf_sched_ready())return $out; $row=sf_sched_fetch_one("SELECT COUNT(*) jobs, SUM(status='active') active, SUM(status='active' AND (next_run_at IS NULL OR next_run_at<=NOW())) due FROM ops_scheduled_jobs")?:[]; $out['jobs']=(int)($row['jobs']??0);$out['active']=(int)($row['active']??0);$out['due']=(int)($row['due']??0); if(sf_sched_table_exists('ops_job_runs')){ $r=sf_sched_fetch_one("SELECT COUNT(*) runs, SUM(run_status='failed') failed FROM ops_job_runs WHERE started_at>=DATE_SUB(NOW(), INTERVAL 7 DAY)")?:[]; $out['runs']=(int)($r['runs']??0);$out['failed']=(int)($r['failed']??0);} return $out; }
function sf_sched_next_run(string $frequency, ?string $time=null): ?string { if($frequency==='manual')return null; if($frequency==='hourly')return date('Y-m-d H:i:s',strtotime('+1 hour')); $t=$time?:'08:00:00'; if($frequency==='weekly')return date('Y-m-d '.$t,strtotime('+7 days')); if($frequency==='monthly')return date('Y-m-d '.$t,strtotime('+1 month')); return date('Y-m-d '.$t,strtotime('+1 day')); }
function sf_sched_save_job(array $data,int $id=0): int { if(!sf_sched_ready())return 0; $key=trim((string)($data['job_key']??'')); $title=trim((string)($data['title']??'')); if($key===''||$title==='')return 0; $type=in_array(($data['job_type']??'custom'),['dispatch_notifications','lifecycle_churn_scan','support_sla_scan','revenue_snapshot','engagement_score_refresh','custom'],true)?$data['job_type']:'custom'; $freq=in_array(($data['frequency']??'daily'),['hourly','daily','weekly','monthly','manual'],true)?$data['frequency']:'daily'; $status=in_array(($data['status']??'active'),['active','paused','archived'],true)?$data['status']:'active'; $time=trim((string)($data['schedule_time']??''))?:null; $next=trim((string)($data['next_run_at']??'')); $next=$next?str_replace('T',' ',$next).(strlen($next)===16?':00':''):sf_sched_next_run($freq,$time); $vals=[$key,$type,$title,$data['description']??null,$freq,$time,$status,$next,sf_current_user_id()?:null]; if($id>0){sf_sched_execute('UPDATE ops_scheduled_jobs SET job_key=?, job_type=?, title=?, description=?, frequency=?, schedule_time=?, status=?, next_run_at=?, created_by_user_id=COALESCE(created_by_user_id,?), updated_at=NOW() WHERE id=?',array_merge($vals,[$id]));return $id;} sf_sched_execute('INSERT INTO ops_scheduled_jobs (job_key,job_type,title,description,frequency,schedule_time,status,next_run_at,created_by_user_id) VALUES (?,?,?,?,?,?,?,?,?)',$vals); return (int)(sf_sched_db()?->lastInsertId()?:0); }
function sf_sched_due_jobs(int $limit=20): array { if(!sf_sched_ready())return []; return sf_sched_fetch_all("SELECT * FROM ops_scheduled_jobs WHERE status='active' AND (next_run_at IS NULL OR next_run_at<=NOW()) ORDER BY COALESCE(next_run_at, created_at) ASC LIMIT ".max(1,min(100,$limit))); }
function sf_sched_log_run(?int $jobId,string $key,string $status,array $counts=[],string $summary='',string $error=''): int { if(!sf_sched_table_exists('ops_job_runs'))return 0; sf_sched_execute('INSERT INTO ops_job_runs (job_id,job_key,run_status,finished_at,processed_count,success_count,failed_count,result_summary,error_message,metadata_json) VALUES (?,?,?,NOW(),?,?,?,?,?,?)',[$jobId,$key,$status,(int)($counts['processed']??0),(int)($counts['success']??($counts['sent']??0)),(int)($counts['failed']??0),$summary?:null,$error?:null,json_encode($counts,JSON_UNESCAPED_SLASHES)]); return (int)(sf_sched_db()?->lastInsertId()?:0); }
function sf_sched_run_job(array $job): array { $id=(int)($job['id']??0); $key=(string)($job['job_key']??'manual'); $type=(string)($job['job_type']??'custom'); $result=['processed'=>0,'success'=>0,'failed'=>0]; $summary=''; $ok=true; try{ if($type==='dispatch_notifications'){ $r=sf_notify_dispatch_pending(100); $result=['processed'=>(int)$r['processed'],'success'=>(int)$r['sent'],'failed'=>(int)$r['failed']]; $summary='Notification dispatch complete.'; }
    elseif($type==='revenue_snapshot'){ $ok=sf_rev_save_snapshot(); $result=['processed'=>1,'success'=>$ok?1:0,'failed'=>$ok?0:1]; $summary='Revenue snapshot saved.'; }
    elseif($type==='engagement_score_refresh'){ $ok=sf_engagement_recalculate_member_scores(); $result=['processed'=>1,'success'=>$ok?1:0,'failed'=>$ok?0:1]; $summary='Engagement scores recalculated.'; }
    elseif($type==='lifecycle_churn_scan'){ $members=sf_lifecycle_segments(); foreach($members as $m){ $risk=($m['subscription_status']??'')==='past_due'||!empty($m['cancel_at_period_end'])||(!empty($m['current_period_end'])&&strtotime((string)$m['current_period_end'])<time()+864000); if($risk){$result['processed']++; if(sf_lifecycle_create_task((int)$m['id'],'Retention follow-up: '.($m['display_name']?:$m['email']),'Automated churn-risk scan flagged this member.','cancel_save','high'))$result['success']++; else $result['failed']++;}} $summary='Churn-risk scan complete.'; }
    elseif($type==='support_sla_scan'){ $tickets=sf_support_tickets(0,'',200); foreach($tickets as $t){ if(!in_array($t['status'],['resolved','closed'],true)&&strtotime((string)($t['created_at']??'now'))<time()-86400){$result['processed']++; if(!empty($t['user_id'])&&sf_lifecycle_create_task((int)$t['user_id'],'Support SLA follow-up: '.$t['ticket_number'],$t['subject']??'Open support ticket','support_followup','high'))$result['success']++; else $result['failed']++;}} $summary='Support SLA scan complete.'; }
    else { $summary='Custom/manual job logged.'; $result=['processed'=>1,'success'=>1,'failed'=>0]; }
  }catch(Throwable $e){$ok=false;$result['failed']++;$summary='Job failed: '.$e->getMessage();}
  sf_sched_log_run($id,$key,$ok?'success':'failed',$result,$summary,$ok?'':$summary); if($id&&sf_sched_ready()){ $next=sf_sched_next_run((string)($job['frequency']??'manual'),$job['schedule_time']??null); sf_sched_execute('UPDATE ops_scheduled_jobs SET last_run_at=NOW(), next_run_at=?, run_count=run_count+1, failure_count=failure_count+?, updated_at=NOW() WHERE id=?',[$next,$ok?0:1,$id]); } return ['ok'=>$ok,'summary'=>$summary,'counts'=>$result]; }
function sf_sched_run_due(int $limit=20): array { $out=['processed'=>0,'success'=>0,'failed'=>0,'runs'=>[]]; foreach(sf_sched_due_jobs($limit) as $job){$out['processed']++;$r=sf_sched_run_job($job);$out['runs'][]=$r;if(!empty($r['ok']))$out['success']++;else $out['failed']++;} return $out; }

function sf_msg_campaigns(int $limit=120): array { if(!sf_msg_ready())return []; return sf_sched_fetch_all('SELECT c.*, u.email admin_email, u.display_name admin_name, (SELECT COUNT(*) FROM member_message_recipients r WHERE r.campaign_id=c.id) recipients, (SELECT COUNT(*) FROM member_message_recipients r WHERE r.campaign_id=c.id AND r.delivery_status="sent") sent_count FROM member_message_campaigns c LEFT JOIN users u ON u.id=c.created_by_user_id ORDER BY FIELD(c.status,"draft","scheduled","queued","sending","sent","paused","archived"), COALESCE(c.scheduled_at,c.created_at) DESC LIMIT '.max(1,min(200,$limit))); }
function sf_msg_campaign(int $id): ?array { return $id&&sf_msg_ready()?sf_sched_fetch_one('SELECT * FROM member_message_campaigns WHERE id=? LIMIT 1',[$id]):null; }
function sf_msg_summary(): array { $out=['campaigns'=>0,'draft'=>0,'scheduled'=>0,'queued'=>0,'sent'=>0,'recipients'=>0,'in_app_unread'=>0]; if(!sf_msg_ready())return $out; foreach(sf_sched_fetch_all('SELECT status, COUNT(*) total FROM member_message_campaigns GROUP BY status') as $r){$out[(string)$r['status']]=(int)$r['total'];$out['campaigns']+=(int)$r['total'];} $out['recipients']=(int)(sf_sched_fetch_one('SELECT COUNT(*) total FROM member_message_recipients')['total']??0); $out['in_app_unread']=(int)(sf_sched_fetch_one("SELECT COUNT(*) total FROM member_messages WHERE status='unread'")['total']??0); return $out; }
function sf_msg_campaign_key(string $title): string { $base=strtolower(trim(preg_replace('/[^a-z0-9]+/i','-',$title),'-'))?:'member-message'; return $base.'-'.date('ymd-His'); }
function sf_msg_save_campaign(array $data,int $id=0): int { if(!sf_msg_ready())return 0; $title=trim((string)($data['title']??'')); $subject=trim((string)($data['subject']??'')); $body=trim((string)($data['body']??'')); if($title===''||$subject===''||$body==='')return 0; $key=trim((string)($data['campaign_key']??''))?:sf_msg_campaign_key($title); $aud=in_array(($data['audience_filter']??'all_members'),['all_members','active_subscribers','free_members','churn_risk','engaged_members','support_open','manual'],true)?$data['audience_filter']:'all_members'; $status=in_array(($data['status']??'draft'),['draft','scheduled','queued','sending','sent','paused','archived'],true)?$data['status']:'draft'; $scheduled=trim((string)($data['scheduled_at']??'')); $scheduled=$scheduled?str_replace('T',' ',$scheduled).(strlen($scheduled)===16?':00':''):null; $vals=[$key,$title,$subject,$body,$aud,!empty($data['channel_email'])?1:0,!empty($data['channel_in_app'])?1:0,!empty($data['honors_preferences'])?1:0,$status,$scheduled,$data['action_url']??null,sf_current_user_id()?:null]; if($id>0){sf_sched_execute('UPDATE member_message_campaigns SET campaign_key=?, title=?, subject=?, body=?, audience_filter=?, channel_email=?, channel_in_app=?, honors_preferences=?, status=?, scheduled_at=?, action_url=?, created_by_user_id=COALESCE(created_by_user_id,?), updated_at=NOW() WHERE id=?',array_merge($vals,[$id]));return $id;} sf_sched_execute('INSERT INTO member_message_campaigns (campaign_key,title,subject,body,audience_filter,channel_email,channel_in_app,honors_preferences,status,scheduled_at,action_url,created_by_user_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',$vals); return (int)(sf_sched_db()?->lastInsertId()?:0); }
function sf_msg_audience(string $filter,int $limit=1000): array { if(!sf_sched_table_exists('users'))return []; $base="SELECT DISTINCT u.id,u.email,u.display_name FROM users u"; $where=" WHERE u.role<>'admin' AND u.status='active' AND u.email IS NOT NULL AND u.email<>''"; if($filter==='active_subscribers'){$base.=' INNER JOIN user_subscriptions us ON us.user_id=u.id';$where.=" AND us.status IN ('active','trialing') AND (us.current_period_end IS NULL OR us.current_period_end>=NOW())";} elseif($filter==='free_members'){$where.=" AND NOT EXISTS (SELECT 1 FROM user_subscriptions us WHERE us.user_id=u.id AND us.status IN ('active','trialing'))";} elseif($filter==='churn_risk'){$base.=' INNER JOIN user_subscriptions us ON us.user_id=u.id';$where.=" AND (us.status IN ('past_due','unpaid') OR us.cancel_at_period_end=1 OR (us.current_period_end IS NOT NULL AND us.current_period_end BETWEEN NOW() AND DATE_ADD(NOW(), INTERVAL 10 DAY)))";} elseif($filter==='engaged_members'){$base.=' INNER JOIN member_engagement_scores mes ON mes.user_id=u.id';$where.=' AND mes.score>=10';} elseif($filter==='support_open'){$base.=' INNER JOIN support_tickets st ON st.user_id=u.id';$where.=" AND st.status NOT IN ('resolved','closed')";} return sf_sched_fetch_all($base.$where.' ORDER BY u.created_at DESC LIMIT '.max(1,min(5000,$limit))); }
function sf_msg_seed_recipients(int $campaignId): int { $c=sf_msg_campaign($campaignId); if(!$c||!sf_sched_table_exists('member_message_recipients'))return 0; $count=0; foreach(sf_msg_audience((string)$c['audience_filter']) as $u){ if(sf_sched_execute('INSERT IGNORE INTO member_message_recipients (campaign_id,user_id,email) VALUES (?,?,?)',[$campaignId,(int)$u['id'],$u['email']??null]))$count++; } return $count; }
function sf_msg_create_member_message(int $userId,string $subject,string $body,string $type='notice',string $url='',array $meta=[]): int { if(!sf_sched_table_exists('member_messages'))return 0; sf_sched_execute('INSERT INTO member_message_threads (user_id,subject,thread_type,status,last_message_at,metadata_json) VALUES (?,?,?,?,NOW(),?)',[$userId,$subject,'notice','open',json_encode($meta,JSON_UNESCAPED_SLASHES)]); $thread=(int)(sf_sched_db()?->lastInsertId()?:0); sf_sched_execute('INSERT INTO member_messages (thread_id,user_id,sender_user_id,sender_type,subject,body,action_url,message_type,status,metadata_json) VALUES (?,?,?,?,?,?,?,?,?,?)',[$thread?:null,$userId,sf_current_user_id()?:null,'admin',$subject,$body,$url?:null,$type,'unread',json_encode($meta,JSON_UNESCAPED_SLASHES)]); return (int)(sf_sched_db()?->lastInsertId()?:0); }
function sf_msg_send_campaign(int $campaignId,int $limit=250): array { $out=['processed'=>0,'sent'=>0,'failed'=>0,'skipped'=>0]; $c=sf_msg_campaign($campaignId); if(!$c)return $out; sf_msg_seed_recipients($campaignId); sf_sched_execute("UPDATE member_message_campaigns SET status='sending', updated_at=NOW() WHERE id=?",[$campaignId]); $recipients=sf_sched_fetch_all("SELECT r.*, u.email, u.display_name FROM member_message_recipients r INNER JOIN users u ON u.id=r.user_id WHERE r.campaign_id=? AND r.delivery_status='queued' ORDER BY r.id ASC LIMIT ".max(1,min(1000,$limit)),[$campaignId]); foreach($recipients as $r){$out['processed']++;$messageId=0;$logId=null;$ok=true;$error=null; if(!empty($c['channel_in_app']))$messageId=sf_msg_create_member_message((int)$r['user_id'],(string)$c['subject'],(string)$c['body'],'notice',(string)($c['action_url']??''),['campaign_id'=>$campaignId]); if(!empty($c['channel_email'])){ $logId=sf_notify_send_template('member_message_notice',['user_id'=>(int)$r['user_id'],'email'=>$r['email'],'name'=>$r['display_name']?:$r['email']],['message_subject'=>$c['subject'],'message_body'=>nl2br(sf_sched_h($c['body'])),'message_text'=>$c['body'],'action_url'=>$c['action_url']?:sf_notify_absolute_url('messages.php'),'member_url'=>sf_notify_absolute_url('messages.php')],['notification_type'=>'member_message','metadata'=>['campaign_id'=>$campaignId],'dispatch'=>true]); }
    if(!$messageId && !$logId){$ok=false;$error='No enabled delivery channel completed.';} if($ok){$out['sent']++;sf_sched_execute("UPDATE member_message_recipients SET delivery_status='sent', email_log_id=?, member_message_id=?, sent_at=NOW(), updated_at=NOW() WHERE id=?",[$logId,$messageId?:null,(int)$r['id']]);} else {$out['failed']++;sf_sched_execute("UPDATE member_message_recipients SET delivery_status='failed', error_message=?, updated_at=NOW() WHERE id=?",[$error,(int)$r['id']]);}}
  $remaining=(int)(sf_sched_fetch_one("SELECT COUNT(*) total FROM member_message_recipients WHERE campaign_id=? AND delivery_status='queued'",[$campaignId])['total']??0); if($remaining===0)sf_sched_execute("UPDATE member_message_campaigns SET status='sent', sent_at=COALESCE(sent_at,NOW()), updated_at=NOW() WHERE id=?",[$campaignId]); else sf_sched_execute("UPDATE member_message_campaigns SET status='queued', updated_at=NOW() WHERE id=?",[$campaignId]); return $out; }
function sf_msg_member_messages(int $userId,string $status='',int $limit=100): array { if(!$userId||!sf_sched_table_exists('member_messages'))return []; $where='WHERE m.user_id=?';$params=[$userId]; if($status!==''){$where.=' AND m.status=?';$params[]=$status;} return sf_sched_fetch_all("SELECT m.* FROM member_messages m {$where} ORDER BY m.created_at DESC, m.id DESC LIMIT ".max(1,min(200,$limit)),$params); }
function sf_msg_update_member_message(int $userId,int $id,string $status='read'): bool { if(!$userId||!$id||!sf_sched_table_exists('member_messages'))return false; if(!in_array($status,['unread','read','archived','dismissed'],true))$status='read'; $read=$status==='read'?', read_at=COALESCE(read_at,NOW())':''; return sf_sched_execute("UPDATE member_messages SET status=?{$read}, updated_at=NOW() WHERE id=? AND user_id=?",[$status,$id,$userId]); }
function sf_msg_due_campaigns(int $limit=20): array { if(!sf_msg_ready())return []; return sf_sched_fetch_all("SELECT * FROM member_message_campaigns WHERE status IN ('scheduled','queued') AND (scheduled_at IS NULL OR scheduled_at<=NOW()) ORDER BY COALESCE(scheduled_at,created_at) ASC LIMIT ".max(1,min(100,$limit))); }
function sf_msg_send_due(int $limit=20): array { $out=['campaigns'=>0,'processed'=>0,'sent'=>0,'failed'=>0]; foreach(sf_msg_due_campaigns($limit) as $c){$out['campaigns']++;$r=sf_msg_send_campaign((int)$c['id'],500);$out['processed']+=(int)$r['processed'];$out['sent']+=(int)$r['sent'];$out['failed']+=(int)$r['failed'];} return $out; }
?>
