<?php

declare(strict_types=1);

function sf_pch_env_float(string $name,float $default):float{$v=getenv($name);return$v!==false&&is_numeric($v)?(float)$v:$default;}
function sf_pch_thresholds():array{return[
 'error_rate_pct'=>sf_pch_env_float('SF_CUTOVER_ERROR_RATE_PCT',5),
 'payment_failure_rate_pct'=>sf_pch_env_float('SF_CUTOVER_PAYMENT_FAILURE_RATE_PCT',8),
 'media_failure_rate_pct'=>sf_pch_env_float('SF_CUTOVER_MEDIA_FAILURE_RATE_PCT',5),
 'p95_latency_ms'=>sf_pch_env_float('SF_CUTOVER_P95_LATENCY_MS',2500),
 'queue_depth'=>sf_pch_env_float('SF_CUTOVER_QUEUE_DEPTH',100),
 'critical_incidents'=>sf_pch_env_float('SF_CUTOVER_CRITICAL_INCIDENTS',1),
];}
function sf_pch_thresholds_valid():bool{foreach(sf_pch_thresholds() as$v)if($v<=0)return false;return true;}
function sf_pch_go_gate(int $runId):array{$keys=['cutover.candidate','cutover.promotion','cutover.backup','cutover.artifact','cutover.configuration','deployment.maintenance','rollback.thresholds','rollback.package','rollback.authority','monitoring.baseline','monitoring.incidents'];$rows=sf_admin_fetch_all('SELECT check_key,check_status,check_label FROM production_cutover_checks WHERE run_id=?',[$runId]);$status=[];foreach($rows as$row)$status[(string)$row['check_key']]=$row;$reasons=[];foreach($keys as$key)if(($status[$key]['check_status']??'pending')!=='passed')$reasons[]='Check not passed: '.($status[$key]['check_label']??$key).'.';$run=sf_pch_run($runId);if(!$run)$reasons[]='Cutover run is missing.';elseif(!empty($run['rollback_recommended']))$reasons[]='Rollback is currently recommended.';return['ok'=>!$reasons,'reasons'=>$reasons];}
function sf_pch_storage_health():?array{return sf_admin_table_exists('media_storage_health_runs')?sf_admin_fetch_one("SELECT * FROM media_storage_health_runs WHERE status='healthy' AND completed_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR) ORDER BY completed_at DESC,id DESC LIMIT 1"):null;}
function sf_pch_monitoring_baseline():?array{return sf_admin_table_exists('monitoring_health_snapshots')?sf_admin_fetch_one("SELECT * FROM monitoring_health_snapshots WHERE status='healthy' AND health_score>=90 AND created_at>=DATE_SUB(NOW(),INTERVAL 2 HOUR) ORDER BY created_at DESC,id DESC LIMIT 1"):null;}
function sf_pch_critical_incidents():int{return sf_admin_table_exists('incident_records')?(int)(sf_admin_fetch_one("SELECT COUNT(*) total FROM incident_records WHERE severity='critical' AND status IN ('open','investigating','monitoring')")['total']??0):0;}
function sf_pch_automated_results(int $runId):array{
 $run=sf_pch_run($runId);if(!$run)return[];$sha=strtolower((string)$run['target_commit_sha']);$candidate=sf_sa_candidate((int)$run['staging_candidate_id']);$promotion=sf_prod_promotion((int)$run['production_promotion_id']);$backup=sf_br_run((int)$run['backup_run_id']);$configured=strtolower(trim((string)(getenv('SF_RELEASE_COMMIT_SHA')?:'')));$env=strtolower(trim((string)(getenv('SF_ENV')?:'')));$storage=sf_pch_storage_health();$baseline=sf_pch_monitoring_baseline();$critical=sf_pch_critical_incidents();$candidateOk=$candidate&&($candidate['candidate_status']??'')==='frozen'&&hash_equals($sha,strtolower((string)$candidate['target_commit_sha']));$promotionOk=$promotion&&in_array((string)$promotion['promotion_status'],['approved','deploying','deployed','verified'],true)&&hash_equals($sha,strtolower((string)$promotion['target_commit_sha']));$artifactOk=$candidate&&$promotion&&hash_equals(strtolower((string)$candidate['artifact_sha256']),strtolower((string)$promotion['artifact_sha256']??''))&&hash_equals(strtolower((string)$candidate['artifact_sha256']),strtolower((string)$run['artifact_sha256']));$backupOk=$backup&&($backup['run_status']??'')==='verified'&&!empty($backup['verified_at'])&&strtotime((string)$backup['verified_at'])>=time()-86400;$checkpoints=sf_pch_checkpoints($runId);$checkpointOk=count($checkpoints)===5&&!array_filter($checkpoints,static fn($c)=>($c['checkpoint_status']??'')!=='passed');$metricsOk=$checkpointOk;foreach($checkpoints as$c){if((int)($c['blocker_count']??0)>0||!in_array((string)($c['checkpoint_status']??''),['passed'],true))$metricsOk=false;}
 return[
  'cutover.candidate'=>[$candidateOk,$candidateOk?'Frozen release candidate matches the cutover commit.':'Frozen release candidate is missing or mismatched.',['candidate_id'=>$run['staging_candidate_id']]],
  'cutover.promotion'=>[$promotionOk,$promotionOk?'Production promotion is approved for the exact commit.':'Production promotion is missing, unapproved, or mismatched.',['promotion_id'=>$run['production_promotion_id']]],
  'cutover.backup'=>[$backupOk,$backupOk?'Fresh verified backup is bound to the cutover.':'A verified backup from the last 24 hours is required.',['backup_id'=>$run['backup_run_id']]],
  'cutover.artifact'=>[$artifactOk,$artifactOk?'Candidate, promotion, and cutover artifact SHA-256 values match.':'Artifact SHA-256 binding does not match.',['artifact_sha256'=>$run['artifact_sha256']]],
  'cutover.configuration'=>[$env==='production'&&preg_match('/^[a-f0-9]{40}$/',$configured)&&hash_equals($sha,$configured),$env==='production'&&hash_equals($sha,$configured)?'Production environment and exact deployed commit are configured.':'SF_ENV=production and matching SF_RELEASE_COMMIT_SHA are required.',['environment'=>$env,'configured_commit'=>$configured]],
  'media.storage'=>[$storage!==null,$storage?'Fresh healthy protected-storage run is available.':'No healthy storage read/write/delete run from the last 24 hours.',['health_run'=>$storage['run_key']??null]],
  'rollback.thresholds'=>[sf_pch_thresholds_valid(),sf_pch_thresholds_valid()?'Rollback thresholds are configured with positive values.':'Rollback thresholds are missing or invalid.',sf_pch_thresholds()],
  'monitoring.baseline'=>[$baseline!==null,$baseline?'Healthy monitoring baseline captured at '.$baseline['created_at'].'.':'Capture a health snapshot of at least 90% within two hours.',['snapshot_id'=>$baseline['id']??null]],
  'monitoring.incidents'=>[$critical===0,$critical===0?'No unresolved critical incidents.':$critical.' unresolved critical incident(s).',['critical_incidents'=>$critical]],
  'hypercare.checkpoints'=>[$checkpointOk,$checkpointOk?'All five hypercare checkpoints passed.':'The 15m, 1h, 6h, 24h, and 72h checkpoints are not all passed.',['checkpoint_count'=>count($checkpoints)]],
  'hypercare.metrics'=>[$metricsOk,$metricsOk?'All recorded hypercare metrics remain within threshold.':'One or more hypercare checkpoints or metrics remain blocked.'],
  'certificate.production'=>[sf_pch_certificate_for_run($runId)!==null,sf_pch_certificate_for_run($runId)?'Production verification certificate is issued.':'Production verification certificate has not been issued.'],
 ];
}
function sf_pch_run_automated(int $runId):array{$run=sf_pch_run($runId);if(!$run||sf_pch_locked($run))return['ok'=>false,'processed'=>0,'passed'=>0,'failed'=>0];$out=['ok'=>true,'processed'=>0,'passed'=>0,'failed'=>0];foreach(sf_pch_automated_results($runId) as$key=>$r){$out['processed']++;$ok=(bool)$r[0];sf_pch_record($runId,$key,$ok?'passed':'failed',(string)$r[1],(array)($r[2]??[]));$ok?$out['passed']++:$out['failed']++;}sf_pch_evaluate_thresholds($runId);return$out;}
function sf_pch_record_decision(int $runId,string $type,string $note,string $reference,string $sha=''):bool{$run=sf_pch_run($runId);if(!$run||sf_pch_locked($run)||!in_array($type,['go','hold','rollback','abort','resume'],true))return false;$note=sf_pch_text($note,8000);$reference=sf_pch_text($reference,1000);$sha=strtolower(trim($sha));if(strlen($note)<20||strlen($reference)<8||($sha!==''&&!preg_match('/^[a-f0-9]{64}$/',$sha)))return false;if(in_array($type,['go','resume'],true)){if($type==='go'&&!sf_pch_go_gate($runId)['ok'])return false;if($type==='resume'&&(!empty($run['rollback_recommended'])||sf_pch_critical_incidents()>0))return false;}$ok=sf_admin_execute("INSERT INTO production_cutover_decisions (run_id,decision_type,decision_status,decision_note,evidence_reference,evidence_sha256,decided_by_user_id,decided_at) VALUES (?,?,'recorded',?,?,?,?,NOW())",[$runId,$type,$note,$reference,$sha?:null,sf_current_user_id()?:null]);if(!$ok)return false;$map=['go'=>'deploying','hold'=>'hold','rollback'=>'rolled_back','abort'=>'aborted','resume'=>'deploying'];$status=$map[$type];$cols='run_status=?,updated_by_user_id=?';$params=[$status,sf_current_user_id()?:null];if($type==='go')$cols.=',started_at=COALESCE(started_at,NOW())';if($type==='rollback'){$cols.=",rolled_back_at=NOW(),traffic_percent=0,maintenance_status='ended'";}if($type==='abort')$cols.=",traffic_percent=0,maintenance_status='ended'";$params[]=$runId;sf_admin_execute('UPDATE production_cutover_runs SET '.$cols.' WHERE id=?',$params);sf_pch_event($runId,'decision.'.$type,$note,['reference'=>$reference,'artifact_sha256'=>$sha],'verified');if($type==='rollback'&&function_exists('sf_mon_create_incident'))sf_mon_create_incident('Production rollback initiated',$note,'critical','cutover',0,0);return true;}
function sf_pch_set_traffic(int $runId,int $percent,string $note):bool{$run=sf_pch_run($runId);$stages=[0,1,5,10,25,50,100];if(!$run||sf_pch_locked($run)||!in_array((string)($run['run_status']??''),['deploying','stabilizing'],true)||!in_array($percent,$stages,true)||strlen(trim($note))<12)return false;$current=(int)($run['traffic_percent']??0);$currentIndex=array_search($current,$stages,true);$requestedIndex=array_search($percent,$stages,true);if($requestedIndex===false||$currentIndex===false)return false;if($percent>$current&&$requestedIndex!==$currentIndex+1)return false;if($percent<$current&&$percent!==0)return false;$nextStatus=$percent===100?'stabilizing':($percent===0?'hold':'deploying');$maintenance=$percent===100?'ended':($percent===0?'active':'active');$ok=sf_admin_execute('UPDATE production_cutover_runs SET traffic_percent=?,run_status=?,maintenance_status=?,updated_by_user_id=?,deployed_at=CASE WHEN ?=100 THEN COALESCE(deployed_at,NOW()) ELSE deployed_at END WHERE id=?',[$percent,$nextStatus,$maintenance,sf_current_user_id()?:null,$percent,$runId]);if($ok)sf_pch_event($runId,'traffic.changed','Production traffic changed to '.$percent.'%.',['from_percent'=>$current,'traffic_percent'=>$percent,'note'=>$note],'verified');return$ok;}
