<?php

declare(strict_types=1);

function sf_pch_text($value,int $max=12000):string{$value=trim((string)$value);return function_exists('mb_substr')?mb_substr($value,0,$max):substr($value,0,$max);}
function sf_pch_uuid():string{$b=random_bytes(16);$b[6]=chr((ord($b[6])&0x0f)|0x40);$b[8]=chr((ord($b[8])&0x3f)|0x80);$h=bin2hex($b);return substr($h,0,8).'-'.substr($h,8,4).'-'.substr($h,12,4).'-'.substr($h,16,4).'-'.substr($h,20);}
function sf_pch_ready():bool{return sf_admin_db() instanceof PDO&&sf_admin_table_exists('production_cutover_runs')&&sf_admin_table_exists('production_cutover_checks')&&sf_admin_table_exists('production_cutover_evidence')&&sf_admin_table_exists('production_cutover_events')&&sf_admin_table_exists('production_cutover_decisions')&&sf_admin_table_exists('production_hypercare_checkpoints')&&sf_admin_table_exists('production_hypercare_metrics')&&sf_admin_table_exists('production_verification_certificates');}
function sf_pch_locked(array $run):bool{return in_array((string)($run['run_status']??''),['completed','rolled_back','aborted','failed'],true);}
function sf_pch_run(int $id):?array{return sf_pch_ready()&&$id>0?sf_admin_fetch_one('SELECT * FROM production_cutover_runs WHERE id=? LIMIT 1',[$id]):null;}
function sf_pch_runs(int $limit=60):array{return sf_pch_ready()?sf_admin_fetch_all('SELECT * FROM production_cutover_runs ORDER BY created_at DESC,id DESC LIMIT '.max(1,min(200,$limit))):[];}
function sf_pch_checks(int $runId):array{return sf_pch_ready()&&$runId>0?sf_admin_fetch_all("SELECT * FROM production_cutover_checks WHERE run_id=? ORDER BY FIELD(severity,'critical','high','medium','low','info'),section_key,id",[$runId]):[];}
function sf_pch_events(int $runId,int $limit=200):array{return sf_pch_ready()&&$runId>0?sf_admin_fetch_all('SELECT * FROM production_cutover_events WHERE run_id=? ORDER BY created_at DESC,id DESC LIMIT '.max(1,min(500,$limit)),[$runId]):[];}
function sf_pch_decisions(int $runId):array{return sf_pch_ready()&&$runId>0?sf_admin_fetch_all('SELECT * FROM production_cutover_decisions WHERE run_id=? ORDER BY decided_at DESC,id DESC',[$runId]):[];}
function sf_pch_checkpoints(int $runId):array{return sf_pch_ready()&&$runId>0?sf_admin_fetch_all('SELECT * FROM production_hypercare_checkpoints WHERE run_id=? ORDER BY scheduled_for,id',[$runId]):[];}
function sf_pch_latest_certificate():?array{return sf_pch_ready()?sf_admin_fetch_one("SELECT * FROM production_verification_certificates WHERE certificate_status='verified' ORDER BY issued_at DESC,id DESC LIMIT 1"):null;}
function sf_pch_latest_completed():?array{return sf_pch_ready()?sf_admin_fetch_one("SELECT * FROM production_cutover_runs WHERE run_status='completed' AND overall_score=100 ORDER BY completed_at DESC,id DESC LIMIT 1"):null;}

function sf_pch_catalog():array{return[
 'cutover.candidate'=>['section'=>'cutover','label'=>'Frozen exact-commit release candidate','severity'=>'critical','automated'=>1],
 'cutover.promotion'=>['section'=>'cutover','label'=>'Approved production promotion matches candidate','severity'=>'critical','automated'=>1],
 'cutover.backup'=>['section'=>'cutover','label'=>'Fresh verified backup and restore point','severity'=>'critical','automated'=>1],
 'cutover.artifact'=>['section'=>'cutover','label'=>'Deployment artifact URL and SHA-256 match','severity'=>'critical','automated'=>1],
 'cutover.configuration'=>['section'=>'cutover','label'=>'Production environment and exact commit configured','severity'=>'critical','automated'=>1],
 'deployment.maintenance'=>['section'=>'deployment','label'=>'Maintenance window and communication active','severity'=>'high','automated'=>0],
 'deployment.migrations'=>['section'=>'deployment','label'=>'Migration ledger applied exactly once','severity'=>'critical','automated'=>0],
 'deployment.health'=>['section'=>'deployment','label'=>'Application, database, storage, workers, and schedulers healthy','severity'=>'critical','automated'=>0],
 'deployment.traffic'=>['section'=>'deployment','label'=>'Staged traffic activation completed without blocker','severity'=>'critical','automated'=>0],
 'auth.lifecycle'=>['section'=>'authentication','label'=>'Signup, login, recovery, session, and scoped admin verification','severity'=>'critical','automated'=>0],
 'commerce.membership'=>['section'=>'commerce','label'=>'Membership checkout, webhook, entitlement, invoice, and cancellation','severity'=>'critical','automated'=>0],
 'commerce.merchandise'=>['section'=>'commerce','label'=>'Merchandise checkout, inventory, receipt, refund, and order history','severity'=>'critical','automated'=>0],
 'commerce.reconciliation'=>['section'=>'commerce','label'=>'Stripe settlement and local reconciliation match','severity'=>'critical','automated'=>0],
 'media.audio'=>['section'=>'media','label'=>'Audio preview, protected stream, waveform, and progress verification','severity'=>'critical','automated'=>0],
 'media.video'=>['section'=>'media','label'=>'Video HLS, entitlement, poster, resume, and completion verification','severity'=>'critical','automated'=>0],
 'media.storage'=>['section'=>'media','label'=>'Fresh protected storage read/write/delete health','severity'=>'critical','automated'=>1],
 'delivery.email'=>['section'=>'delivery','label'=>'Transactional email delivery, bounce, complaint, and retry','severity'=>'critical','automated'=>0],
 'delivery.scheduler'=>['section'=>'delivery','label'=>'Scheduler, queue locks, publishing, and worker execution','severity'=>'critical','automated'=>0],
 'browser.synthetic'=>['section'=>'browser','label'=>'Public, member, checkout, and admin synthetic route matrix','severity'=>'critical','automated'=>0],
 'browser.quality'=>['section'=>'browser','label'=>'Desktop, mobile, accessibility, and performance verification','severity'=>'high','automated'=>0],
 'rollback.thresholds'=>['section'=>'rollback','label'=>'Rollback thresholds configured and approved','severity'=>'critical','automated'=>1],
 'rollback.package'=>['section'=>'rollback','label'=>'Code rollback package, commands, database decision, and restore point','severity'=>'critical','automated'=>0],
 'rollback.authority'=>['section'=>'rollback','label'=>'Named rollback authority and incident communication path','severity'=>'critical','automated'=>0],
 'monitoring.baseline'=>['section'=>'monitoring','label'=>'Healthy production monitoring baseline captured','severity'=>'critical','automated'=>1],
 'monitoring.incidents'=>['section'=>'monitoring','label'=>'No unresolved critical incidents at go-live','severity'=>'critical','automated'=>1],
 'hypercare.checkpoints'=>['section'=>'hypercare','label'=>'15m, 1h, 6h, 24h, and 72h checkpoints complete','severity'=>'critical','automated'=>1],
 'hypercare.metrics'=>['section'=>'hypercare','label'=>'Availability, latency, payments, media, email, and queue metrics within threshold','severity'=>'critical','automated'=>1],
 'handoff.known_issues'=>['section'=>'handoff','label'=>'Known issues register and ownership recorded','severity'=>'high','automated'=>0],
 'handoff.operations'=>['section'=>'handoff','label'=>'Operational ownership and support handoff approved','severity'=>'critical','automated'=>0],
 'certificate.production'=>['section'=>'certificate','label'=>'Production verification certificate issued for exact commit','severity'=>'critical','automated'=>1],
];}

function sf_pch_event(int $runId,string $type,string $message,array $payload=[],string $status='processed',string $sourceId=''):bool{
 if(!sf_pch_ready()||$runId<=0)return false;$status=in_array($status,['received','verified','processed','rejected'],true)?$status:'processed';$redacted=function_exists('sf_sim_redact')?sf_sim_redact($payload):$payload;$raw=$payload?json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE):'';$json=$payload?json_encode($redacted,JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE):null;$hash=$raw!==''?hash('sha256',$raw):null;
 return sf_admin_execute('INSERT INTO production_cutover_events (run_id,source_event_id,event_type,event_status,event_message,payload_hash,redacted_payload_json,actor_user_id,processed_at) VALUES (?,?,?,?,?,?,?,?,NOW())',[$runId,$sourceId?:null,sf_pch_text($type,120),$status,sf_pch_text($message,2000),$hash,$json,sf_current_user_id()?:null]);
}

function sf_pch_create_run(string $label,int $candidateId,int $promotionId,string $windowStart,string $windowEnd):int{
 if(!sf_pch_ready())return 0;$candidate=sf_sa_candidate($candidateId);$promotion=sf_prod_promotion($promotionId);if(!$candidate||($candidate['candidate_status']??'')!=='frozen'||!$promotion||!in_array((string)$promotion['promotion_status'],['approved','deploying','deployed'],true))return 0;$sha=strtolower((string)$candidate['target_commit_sha']);if(!preg_match('/^[a-f0-9]{40}$/',$sha)||!hash_equals($sha,strtolower((string)$promotion['target_commit_sha']))||!hash_equals(strtolower((string)$candidate['artifact_sha256']),strtolower((string)$promotion['artifact_sha256']??'')))return 0;$release=sf_rel_release((int)$candidate['deployment_release_id']);$backup=sf_br_run((int)$candidate['backup_run_id']);if(!$release||!$backup)return 0;$start=strtotime($windowStart);$end=strtotime($windowEnd);if($start===false||$end===false||$end<=$start)return 0;$pdo=sf_admin_db();if(!$pdo)return 0;$label=sf_pch_text($label,190)?:'Stonefellow production cutover '.substr($sha,0,12);
 try{$pdo->beginTransaction();$s=$pdo->prepare("INSERT INTO production_cutover_runs (run_key,run_label,staging_candidate_id,production_promotion_id,deployment_release_id,backup_run_id,target_branch,target_commit_sha,artifact_url,artifact_sha256,environment_key,maintenance_window_start,maintenance_window_end,run_status,created_by_user_id,updated_by_user_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,'draft',?,?)");$s->execute([sf_pch_uuid(),$label,$candidateId,$promotionId,(int)$candidate['deployment_release_id'],(int)$candidate['backup_run_id'],(string)$candidate['target_branch'],$sha,(string)$candidate['artifact_url'],strtolower((string)$candidate['artifact_sha256']),'production',date('Y-m-d H:i:s',$start),date('Y-m-d H:i:s',$end),sf_current_user_id()?:null,sf_current_user_id()?:null]);$id=(int)$pdo->lastInsertId();$i=$pdo->prepare('INSERT INTO production_cutover_checks (run_id,check_key,section_key,check_label,severity,is_required,is_automated) VALUES (?,?,?,?,?,1,?)');foreach(sf_pch_catalog() as$key=>$c)$i->execute([$id,$key,$c['section'],$c['label'],$c['severity'],(int)$c['automated']]);$pdo->commit();sf_pch_recalculate($id);sf_pch_event($id,'cutover.created','Production cutover run created.',['candidate_id'=>$candidateId,'promotion_id'=>$promotionId,'commit'=>$sha],'verified');sf_admin_audit('create_production_cutover','production_cutover_run',$id,null,['commit'=>$sha,'candidate_id'=>$candidateId]);return$id;}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();error_log('Production cutover create failed: '.$e->getMessage());return 0;}
}

function sf_pch_record(int $runId,string $key,string $status,string $message,array $evidence=[]):bool{
 $run=sf_pch_run($runId);$catalog=sf_pch_catalog();if(!$run||sf_pch_locked($run)||!isset($catalog[$key]))return false;$status=in_array($status,['pending','running','passed','failed','skipped'],true)?$status:'failed';$json=$evidence?json_encode($evidence,JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE):null;$message=sf_pch_text($message,8000);$hash=hash('sha256',$key.'|'.$status.'|'.$message.'|'.(string)$json);$ok=sf_admin_execute("UPDATE production_cutover_checks SET check_status=?,result_message=?,evidence_json=?,evidence_hash=?,checked_by_user_id=?,started_at=COALESCE(started_at,NOW()),completed_at=CASE WHEN ? IN ('passed','failed','skipped') THEN NOW() ELSE NULL END WHERE run_id=? AND check_key=?",[$status,$message,$json,$hash,sf_current_user_id()?:null,$status,$runId,$key]);if($ok){sf_pch_recalculate($runId);sf_pch_event($runId,'check.'.$status,$key.': '.$message,['check_key'=>$key,'evidence_hash'=>$hash]);}return$ok;
}

function sf_pch_manual_check(int $runId,string $key,string $status,string $message,string $type,string $reference,string $sha=''):bool{
 $catalog=sf_pch_catalog();if(!isset($catalog[$key])||!empty($catalog[$key]['automated']))return false;$message=sf_pch_text($message,8000);$reference=sf_pch_text($reference,1000);$sha=strtolower(trim($sha));if($status==='passed'&&(strlen($message)<20||strlen($reference)<8))return false;if($sha!==''&&!preg_match('/^[a-f0-9]{64}$/',$sha))return false;$ok=sf_admin_execute("INSERT INTO production_cutover_evidence (run_id,check_key,evidence_type,evidence_label,source_reference,artifact_sha256,metadata_json,verification_status,submitted_by_user_id,verified_by_user_id,verified_at) VALUES (?,?,?,?,?,?,NULL,'verified',?,?,NOW())",[$runId,$key,sf_pch_text($type,40),sf_pch_text($message,255),$reference,$sha?:null,sf_current_user_id()?:null,sf_current_user_id()?:null]);return$ok&&sf_pch_record($runId,$key,$status,$message,['evidence_type'=>$type,'source_reference'=>$reference,'artifact_sha256'=>$sha]);
}

function sf_pch_recalculate(int $runId):void{if(!sf_pch_ready()||$runId<=0)return;$r=sf_admin_fetch_one("SELECT SUM(is_required=1) required_checks,SUM(is_required=1 AND check_status='passed') passed_checks,SUM(is_required=1 AND check_status='failed') failed_checks,SUM(is_required=1 AND check_status IN ('pending','running','skipped')) pending_checks FROM production_cutover_checks WHERE run_id=?",[$runId])?:[];$required=(int)($r['required_checks']??0);$passed=(int)($r['passed_checks']??0);$failed=(int)($r['failed_checks']??0);$pending=(int)($r['pending_checks']??0);$score=$required?round($passed/$required*100,2):0;sf_admin_execute('UPDATE production_cutover_runs SET required_checks=?,passed_checks=?,failed_checks=?,pending_checks=?,overall_score=? WHERE id=?',[$required,$passed,$failed,$pending,$score,$runId]);}
function sf_pch_section_summary(int $runId):array{return sf_pch_ready()?sf_admin_fetch_all("SELECT section_key,COUNT(*) total,SUM(check_status='passed') passed,SUM(check_status='failed') failed,SUM(check_status IN ('pending','running','skipped')) pending,ROUND(SUM(check_status='passed')/COUNT(*)*100,1) score FROM production_cutover_checks WHERE run_id=? AND is_required=1 GROUP BY section_key ORDER BY section_key",[$runId]):[];}
