<?php
require_once __DIR__ . '/membership.php';
require_once __DIR__ . '/content_integrity.php';

function sf_publish_now(): string { return (new DateTimeImmutable('now'))->format('Y-m-d H:i:s'); }
function sf_publish_table_exists(string $table): bool { $pdo=sf_db();return $pdo instanceof PDO&&sf_content_table_exists($pdo,$table); }
function sf_publish_content_tables(): array { return ['episode'=>'episodes','video'=>'videos','song'=>'songs','album'=>'albums','product'=>'products','post'=>'creator_posts']; }
function sf_publish_statuses(): array { return ['draft'=>'Draft','scheduled'=>'Scheduled','published'=>'Published','archived'=>'Archived']; }
function sf_publish_access_levels(): array { return array_combine(sf_content_access_levels(),array_map(fn($v)=>ucwords(str_replace('_',' ',$v)),sf_content_access_levels())); }
function sf_publish_release_column(array $columns): string { return in_array('release_at',$columns,true)?'release_at':(in_array('published_at',$columns,true)?'published_at':''); }
function sf_publish_content_url(string $type,array $row): string { $slug=(string)($row['slug']??'');return match($type){'episode'=>sf_url('episode.php?slug='.urlencode($slug)),'video'=>sf_url('watch.php?slug='.urlencode($slug)),'song'=>sf_url('song.php?slug='.urlencode($slug)),'album'=>sf_url('album.php?slug='.urlencode($slug)),'product'=>sf_url('product.php?slug='.urlencode($slug)),'post'=>sf_url('comments.php?content_type=post&content_id='.(int)($row['id']??0)),default=>'#'}; }
function sf_publish_is_available(array $row,?string $accessLevel=null): bool { $state=sf_publish_row_state($row);if($state!=='published')return false;$required=(string)($row['access_level']??'public');return sf_access_allows($required,$accessLevel); }
function sf_publish_row_state(array $row): string {
  $status=(string)($row['status']??'draft');$now=time();$release=$row['release_at']??$row['published_at']??null;
  if(in_array($status,['published','scheduled'],true)&&$release&&strtotime((string)$release)>$now)return 'scheduled';
  if(in_array($status,['published','scheduled'],true)&&!empty($row['publish_window_start'])&&strtotime((string)$row['publish_window_start'])>$now)return 'scheduled';
  if(in_array($status,['published','scheduled'],true)&&!empty($row['publish_window_end'])&&strtotime((string)$row['publish_window_end'])<$now)return 'expired';
  return $status==='scheduled'?'published':$status;
}
function sf_publish_items(string $type=''): array {
  $tables=sf_publish_content_tables();if($type!==''&&!isset($tables[$type]))return [];$types=$type!==''?[$type=>$tables[$type]]:$tables;$rows=[];$pdo=sf_db();if(!$pdo instanceof PDO)return [];
  foreach($types as $contentType=>$table){if(!sf_content_table_exists($pdo,$table))continue;try{$cols=sf_content_columns($pdo,$table);$select=['id'];foreach(['title','name','slug','status','release_at','published_at','publish_window_start','publish_window_end','access_level','is_featured','description','excerpt','created_at','updated_at'] as $col)if(in_array($col,$cols,true))$select[]=$col;$release=sf_publish_release_column($cols);$order=$release!==''?'COALESCE(`'.$release.'`,created_at) DESC,id DESC':'id DESC';$sql='SELECT '.implode(',',array_unique($select)).' FROM `'.$table.'` ORDER BY '.$order.' LIMIT 300';foreach($pdo->query($sql)->fetchAll()?:[] as $row){$row['content_type']=$contentType;$row['display_title']=$row['title']??$row['name']??($contentType.' #'.$row['id']);$row['computed_state']=sf_publish_row_state($row);$row['public_url']=sf_publish_content_url($contentType,$row);$rows[]=$row;}}catch(Throwable $e){error_log('Stonefellow publishing item lookup failed: '.$e->getMessage());}}
  return $rows;
}
function sf_publish_reindex(string $type,int $id,array $row): void {
  $pdo=sf_db();if(!$pdo instanceof PDO||!sf_content_table_exists($pdo,'content_search_index')||!in_array($type,['song','album','video','episode','product'],true))return;
  $title=sf_content_clean_text((string)($row['title']??$row['name']??''),190);if($title==='')return;$state=sf_publish_row_state($row);$status=$state==='expired'?'archived':($state==='scheduled'?'scheduled':(string)($row['status']??'draft'));$access=in_array((string)($row['access_level']??'public'),sf_content_access_levels(),true)?(string)($row['access_level']??'public'):'public';
  try{$s=$pdo->prepare('INSERT INTO content_search_index (content_type,content_id,title,slug,description,keywords,content_url,access_level,status,is_featured,weight) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE title=VALUES(title),slug=VALUES(slug),description=VALUES(description),keywords=VALUES(keywords),content_url=VALUES(content_url),access_level=VALUES(access_level),status=VALUES(status),is_featured=VALUES(is_featured),updated_at=NOW()');$description=sf_content_clean_text((string)($row['description']??$row['excerpt']??''),5000);$s->execute([$type,$id,$title,$row['slug']??null,$description,$title.' '.$description,sf_publish_content_url($type,$row),$access,$status,!empty($row['is_featured'])?1:0,!empty($row['is_featured'])?90:50]);}catch(Throwable $e){error_log('Stonefellow search reindex failed: '.$e->getMessage());}
}
function sf_publish_apply(string $type,int $id,array $data): bool {
  $tables=sf_publish_content_tables();$table=$tables[$type]??'';$pdo=sf_db();if(!$pdo instanceof PDO||$id<=0||$table===''||!sf_content_table_exists($pdo,$table))return false;
  $requested=(string)($data['status']??'draft');if(!in_array($requested,sf_content_publish_statuses(),true))return false;$access=(string)($data['access_level']??'public');if(!in_array($access,sf_content_access_levels(),true))return false;
  $cols=sf_content_columns($pdo,$table);$releaseColumn=sf_publish_release_column($cols);$release=$releaseColumn!==''?sf_content_normalize_datetime($data[$releaseColumn]??$data['release_at']??$data['published_at']??null):null;$start=sf_content_normalize_datetime($data['publish_window_start']??null);$end=sf_content_normalize_datetime($data['publish_window_end']??null);
  if($requested==='scheduled'&&($release===null||strtotime($release)<=time()))return false;if($start&&$end&&strtotime($end)<=strtotime($start))return false;
  $storedStatus=$requested;if($requested==='scheduled'&&!sf_content_enum_allows($pdo,$table,'status','scheduled'))$storedStatus='published';if(!sf_content_enum_allows($pdo,$table,'status',$storedStatus))return false;
  try{$pdo->beginTransaction();$lock=$pdo->prepare('SELECT * FROM `'.$table.'` WHERE id=? FOR UPDATE');$lock->execute([$id]);$before=$lock->fetch();if(!$before){$pdo->rollBack();return false;}$sets=[];$values=[];$candidate=['status'=>$storedStatus,'access_level'=>$access,'is_featured'=>!empty($data['is_featured'])?1:0];if($releaseColumn!=='')$candidate[$releaseColumn]=$release;if(in_array('publish_window_start',$cols,true))$candidate['publish_window_start']=$start;if(in_array('publish_window_end',$cols,true))$candidate['publish_window_end']=$end;foreach($candidate as $col=>$value)if(in_array($col,$cols,true)){$sets[]='`'.$col.'`=?';$values[]=$value;}if(!$sets){$pdo->rollBack();return false;}$values[]=$id;$pdo->prepare('UPDATE `'.$table.'` SET '.implode(',',$sets).' WHERE id=?')->execute($values);$afterStmt=$pdo->prepare('SELECT * FROM `'.$table.'` WHERE id=?');$afterStmt->execute([$id]);$after=$afterStmt->fetch()?:array_merge($before,$candidate);if(sf_content_table_exists($pdo,'publishing_events'))$pdo->prepare('INSERT INTO publishing_events (content_type,content_id,event_type,status,metadata_json,created_by_user_id) VALUES (?,?,?,?,?,?)')->execute([$type,$id,'publish_update',$requested,json_encode(['before'=>$before,'after'=>$after],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),sf_current_user_id()?:null]);$pdo->commit();sf_publish_reindex($type,$id,$after);return true;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('Stonefellow publish apply failed: '.$e->getMessage());return false;}
}
function sf_publish_run_due(): array {
  $pdo=sf_db();if(!$pdo instanceof PDO)return ['ok'=>false,'changed'=>0,'checked'=>0,'message'=>'Database unavailable.'];if(!sf_content_advisory_lock($pdo,'publishing-due',2))return ['ok'=>false,'changed'=>0,'checked'=>0,'message'=>'Publishing run already active.'];$changed=0;$checked=0;
  try{foreach(sf_publish_content_tables() as $type=>$table){if(!sf_content_table_exists($pdo,$table))continue;$cols=sf_content_columns($pdo,$table);$release=sf_publish_release_column($cols);if($release==='')continue;$rows=$pdo->query('SELECT * FROM `'.$table.'` WHERE status IN ("scheduled","published") AND `'.$release.'` IS NOT NULL AND `'.$release.'`<=NOW() ORDER BY `'.$release.'` ASC LIMIT 500')->fetchAll()?:[];foreach($rows as $row){$checked++;if(($row['status']??'')==='scheduled'){$pdo->prepare('UPDATE `'.$table.'` SET status="published" WHERE id=? AND status="scheduled"')->execute([(int)$row['id']]);$row['status']='published';$changed++;}sf_publish_reindex($type,(int)$row['id'],$row);}if(in_array('publish_window_end',$cols,true)&&sf_content_enum_allows($pdo,$table,'status','archived')){$n=$pdo->exec('UPDATE `'.$table.'` SET status="archived" WHERE status="published" AND publish_window_end IS NOT NULL AND publish_window_end<NOW()');$changed+=(int)$n;}}if(sf_content_table_exists($pdo,'publishing_events'))$pdo->prepare('INSERT INTO publishing_events (content_type,content_id,event_type,status,metadata_json,created_by_user_id) VALUES ("system",0,"publish_due_run","completed",?,NULL)')->execute([json_encode(['checked'=>$checked,'changed'=>$changed],JSON_UNESCAPED_SLASHES)]);return ['ok'=>true,'changed'=>$changed,'checked'=>$checked];}catch(Throwable $e){error_log('Stonefellow due publishing failed: '.$e->getMessage());return ['ok'=>false,'changed'=>$changed,'checked'=>$checked,'message'=>'Publishing run failed.'];}finally{sf_content_advisory_unlock($pdo,'publishing-due');}
}
?>
