<?php
require_once __DIR__ . '/membership.php';

function sf_publish_now(): string { return (new DateTimeImmutable('now'))->format('Y-m-d H:i:s'); }
function sf_publish_table_exists(string $table): bool { $pdo=sf_db(); if(!$pdo)return false; try{$s=$pdo->prepare('SHOW TABLES LIKE ?');$s->execute([$table]);return (bool)$s->fetchColumn();}catch(Throwable $e){return false;} }
function sf_publish_content_tables(): array { return ['episode'=>'episodes','video'=>'videos','song'=>'songs','album'=>'albums','product'=>'products']; }
function sf_publish_statuses(): array { return ['draft'=>'Draft','scheduled'=>'Scheduled','published'=>'Published','archived'=>'Archived']; }
function sf_publish_access_levels(): array { return ['public'=>'Public','free_account'=>'Free Account','subscriber'=>'Subscriber','premium'=>'Premium','founding_fan'=>'Founding Fan']; }
function sf_publish_content_url(string $type, array $row): string { $slug=(string)($row['slug']??''); if($type==='episode')return sf_url('episode.php?slug='.urlencode($slug)); if($type==='video')return sf_url('watch.php?slug='.urlencode($slug)); if($type==='song')return sf_url('song.php?slug='.urlencode($slug)); if($type==='album')return sf_url('album.php?slug='.urlencode($slug)); if($type==='product')return sf_url('product.php?slug='.urlencode($slug)); return '#'; }
function sf_publish_is_available(array $row, ?string $accessLevel = null): bool { $status=(string)($row['status']??'draft'); if($status!=='published') return false; $now=time(); foreach(['release_at','publish_window_start'] as $key){ if(!empty($row[$key]) && strtotime((string)$row[$key])>$now) return false; } if(!empty($row['publish_window_end']) && strtotime((string)$row['publish_window_end'])<$now) return false; $required=(string)($row['access_level']??'public'); return sf_access_allows($required,$accessLevel); }
function sf_publish_row_state(array $row): string { $status=(string)($row['status']??'draft'); if($status==='published' && !empty($row['release_at']) && strtotime((string)$row['release_at'])>time()) return 'scheduled'; if($status==='published' && !empty($row['publish_window_end']) && strtotime((string)$row['publish_window_end'])<time()) return 'expired'; return $status; }
function sf_publish_items(string $type = ''): array { $tables=sf_publish_content_tables(); $types=$type!==''?[$type=>$tables[$type]??'']:$tables; $rows=[]; $pdo=sf_db(); foreach($types as $contentType=>$table){ if($table===''||!sf_publish_table_exists($table))continue; try{$cols=$pdo->query('SHOW COLUMNS FROM `'.str_replace('`','',$table).'`')->fetchAll(PDO::FETCH_COLUMN); $select=['id']; foreach(['title','name','slug','status','release_at','publish_window_start','publish_window_end','access_level','is_featured','created_at','updated_at'] as $col){ if(in_array($col,$cols,true))$select[]=$col; } $sql='SELECT '.implode(',',array_unique($select)).' FROM `'.str_replace('`','',$table).'` ORDER BY COALESCE(release_at, created_at) DESC, id DESC LIMIT 200'; if(!in_array('release_at',$cols,true))$sql='SELECT '.implode(',',array_unique($select)).' FROM `'.str_replace('`','',$table).'` ORDER BY id DESC LIMIT 200'; foreach(($pdo->query($sql)->fetchAll()?:[]) as $row){ $row['content_type']=$contentType; $row['display_title']=$row['title']??$row['name']??($contentType.' #'.$row['id']); $row['computed_state']=sf_publish_row_state($row); $row['public_url']=sf_publish_content_url($contentType,$row); $rows[]=$row; }}catch(Throwable $e){error_log('Stonefellow publishing item lookup failed: '.$e->getMessage());} } return $rows; }
function sf_publish_apply(string $type, int $id, array $data): bool { $tables=sf_publish_content_tables(); $table=$tables[$type]??''; $pdo=sf_db(); if(!$pdo||$table===''||!sf_publish_table_exists($table))return false; $allowed=['status','release_at','publish_window_start','publish_window_end','access_level','is_featured']; try{$cols=$pdo->query('SHOW COLUMNS FROM `'.str_replace('`','',$table).'`')->fetchAll(PDO::FETCH_COLUMN); $sets=[];$values=[]; foreach($allowed as $col){ if(array_key_exists($col,$data)&&in_array($col,$cols,true)){ $sets[]='`'.$col.'`=?'; $values[]=$data[$col]===''?null:$data[$col]; } } if(!$sets)return false; $values[]=$id; $ok=$pdo->prepare('UPDATE `'.str_replace('`','',$table).'` SET '.implode(',',$sets).' WHERE id=?')->execute($values); if($ok&&sf_publish_table_exists('publishing_events')){ $pdo->prepare('INSERT INTO publishing_events (content_type, content_id, event_type, status, metadata_json, created_by_user_id) VALUES (?, ?, ?, ?, ?, ?)')->execute([$type,$id,'publish_update',(string)($data['status']??'updated'),json_encode($data,JSON_UNESCAPED_SLASHES),sf_current_user_id()]); } return $ok; }catch(Throwable $e){error_log('Stonefellow publish apply failed: '.$e->getMessage()); return false;} }
function sf_publish_run_due(): array { $items=sf_publish_items(); $changed=0; foreach($items as $item){ if(($item['status']??'')==='scheduled' && !empty($item['release_at']) && strtotime((string)$item['release_at'])<=time()){ if(sf_publish_apply((string)$item['content_type'],(int)$item['id'],['status'=>'published']))$changed++; } } return ['ok'=>true,'changed'=>$changed]; }
?>
