<?php
require_once __DIR__ . '/admin_catalog.php';
require_once __DIR__ . '/settings.php';
require_once __DIR__ . '/store.php';

function sf_qa_root(): string { return realpath(__DIR__ . '/..') ?: dirname(__DIR__); }
function sf_qa_h($value): string { return sf_admin_h($value); }
function sf_qa_rel_path(string $path): string { return ltrim(str_replace('\\', '/', $path), '/'); }
function sf_qa_file_path(string $relative): string { return sf_qa_root() . '/' . sf_qa_rel_path($relative); }
function sf_qa_file_exists(string $relative): bool { return is_file(sf_qa_file_path($relative)); }
function sf_qa_dir_exists(string $relative): bool { return is_dir(sf_qa_file_path($relative)); }
function sf_qa_read_file(string $relative): string { $path = sf_qa_file_path($relative); return is_file($path) ? (string)file_get_contents($path) : ''; }
function sf_qa_contains(string $relative, array $needles): bool { $body = sf_qa_read_file($relative); if ($body === '') return false; foreach ($needles as $needle) if ($needle !== '' && strpos($body, $needle) !== false) return true; return false; }
function sf_qa_db_ready(): bool { return sf_db() instanceof PDO; }
function sf_qa_table_exists(string $table): bool { return sf_admin_table_exists($table); }
function sf_qa_columns(string $table): array { return sf_admin_table_columns($table); }
function sf_qa_status(string $status, string $label, string $detail = '', int $weight = 1): array { return ['status'=>$status,'label'=>$label,'detail'=>$detail,'weight'=>max(1,$weight)]; }
function sf_qa_score(array $checks): int { $points=0.0; $total=0.0; foreach($checks as $check){ $weight=(int)($check['weight']??1); $total+=$weight; $status=(string)($check['status']??'fail'); if(in_array($status,['pass','ready','ok'],true))$points+=$weight; elseif(in_array($status,['warn','preview','manual'],true))$points+=$weight*.7; elseif($status==='info')$points+=$weight*.5; } return $total>0?(int)round(($points/$total)*100):0; }
function sf_qa_grade(int $score): string { if($score>=97)return '10/10'; if($score>=90)return '9/10'; if($score>=80)return '8/10'; if($score>=70)return '7/10'; return 'Needs work'; }
function sf_qa_badge(string $status): string { $map=['pass'=>'active','ready'=>'active','ok'=>'active','warn'=>'draft','preview'=>'draft','manual'=>'draft','info'=>'draft','fail'=>'canceled','missing'=>'canceled']; return sf_admin_status_badge($map[$status] ?? $status); }

function sf_qa_migration_plan(): array {
  return [
    ['key'=>'base','file'=>'database/stonefellow_streaming_platform.sql','label'=>'Base streaming platform schema','tables'=>['media_assets','users','subscription_plans','user_subscriptions','albums','songs','song_files','episodes','playlists','playlist_songs','products','orders','order_items'],'notes'=>'Core public site, member, catalog, playlist, and merch tables.'],
    ['key'=>'001','file'=>'database/migrations/001_membership_video_tracking.sql','label'=>'Membership video tracking','tables'=>['content_access_grants','videos','video_files','audio_play_events','user_song_progress','video_watch_events','user_video_progress','user_episode_progress','admin_audit_log'],'notes'=>'Playback tracking, video catalog, grants, and audit log.'],
    ['key'=>'002','file'=>'database/migrations/002_video_playlist_runtime_seed.sql','label'=>'Video and playlist runtime seed','tables'=>['videos','video_files','playlists','playlist_songs'],'notes'=>'Runtime-safe seed/demo video and playlist records.'],
    ['key'=>'003','file'=>'database/migrations/003_media_upload_storage_metadata.sql','label'=>'Media upload metadata','tables'=>['media_assets'],'notes'=>'Extends asset metadata for uploads and pickers.'],
    ['key'=>'004','file'=>'database/migrations/004_billing_entitlements.sql','label'=>'Billing and subscription entitlements','tables'=>['billing_customers','subscription_checkouts','invoices','payment_transactions','billing_webhook_events'],'notes'=>'Checkout sessions, invoices, payments, webhooks, and entitlement records.'],
    ['key'=>'005','file'=>'database/migrations/005_merch_order_runtime.sql','label'=>'Merch order runtime','tables'=>['order_status_history','product_inventory_movements'],'notes'=>'Fulfillment queue, status history, and inventory movement.'],
    ['key'=>'006','file'=>'database/migrations/006_email_notifications.sql','label'=>'Email notification runtime','tables'=>['email_templates','notification_logs','notification_preferences','notification_webhook_events'],'notes'=>'Templates, queue/log, preferences, and webhook logging.'],
    ['key'=>'007','file'=>'database/migrations/007_site_settings_installer.sql','label'=>'Site settings and installer','tables'=>['site_settings','system_installation_checks'],'notes'=>'Runtime settings, health checks, and install readiness records.'],
    ['key'=>'008','file'=>'database/migrations/008_payment_gateway_adapter.sql','label'=>'Payment gateway adapter','tables'=>['payment_gateway_settings','payment_gateway_webhook_events'],'notes'=>'Sandbox, Stripe, PayPal adapter config and gateway webhook receipts.'],
    ['key'=>'009','file'=>'database/migrations/009_episode_video_admin_v2.sql','label'=>'Episode and video admin v2','tables'=>['seasons','video_chapters'],'notes'=>'Seasons, release scheduling, watch-next, and video chapters.'],
    ['key'=>'010','file'=>'database/migrations/010_production_readiness_qa_harness.sql','label'=>'Production readiness QA harness','tables'=>['qa_runs','qa_check_results'],'notes'=>'Persisted QA runs and check history.'],
    ['key'=>'011','file'=>'database/migrations/011_content_import_seed_manager.sql','label'=>'Content import seed manager','tables'=>['content_import_batches','content_import_rows'],'notes'=>'CSV/JSON import, seed manager, row audit, rollback support.'],
    ['key'=>'012','file'=>'database/migrations/012_audio_player_entitlements_v2.sql','label'=>'Audio player entitlements v2','tables'=>['user_player_state'],'notes'=>'Audio player queue/current track/player state.'],
    ['key'=>'013','file'=>'database/migrations/013_gateway_publishing_workflow_v1.sql','label'=>'Gateway publishing workflow + library/search','tables'=>['publishing_events','content_release_rules','member_library_items','content_search_index'],'notes'=>'Gateway readiness, publishing events, member library, watchlist, and search discovery index.'],
  ];
}

function sf_qa_required_columns(): array {
  return [
    'users'=>['id','email','password_hash','role','status','created_at'], 'subscription_plans'=>['id','name','slug','price_cents','status'], 'user_subscriptions'=>['id','user_id','plan_id','status','current_period_start','current_period_end'],
    'albums'=>['id','title','slug','status'], 'songs'=>['id','album_id','title','slug','access_level','status'], 'song_files'=>['id','song_id','file_type','file_path'], 'episodes'=>['id','title','slug','season_number','episode_number','status'], 'videos'=>['id','episode_id','title','slug','video_type','access_level','status'], 'video_files'=>['id','video_id','file_type','file_path'],
    'products'=>['id','name','slug','price_cents','status'], 'orders'=>['id','order_number','user_id','email','status','payment_status','total_cents'], 'email_templates'=>['id','template_key','subject','html_body','status'], 'notification_logs'=>['id','notification_type','recipient_email','status','created_at'],
    'site_settings'=>['id','setting_key','setting_value','setting_group'], 'payment_gateway_settings'=>['id','provider','mode','status'], 'qa_runs'=>['id','run_type','score','status','created_at'], 'qa_check_results'=>['id','qa_run_id','section','check_key','status','message'],
    'content_import_batches'=>['id','import_type','status','created_at'], 'content_import_rows'=>['id','batch_id','row_number','row_status'], 'user_player_state'=>['id','user_id','player_type','state_json'], 'publishing_events'=>['id','content_type','content_id','event_type','status'], 'content_release_rules'=>['id','content_type','content_id','rule_type','status'], 'member_library_items'=>['id','user_id','content_type','content_id','library_status'], 'content_search_index'=>['id','content_type','content_id','title','status'],
  ];
}

function sf_qa_environment_checks(): array { $checks=[]; $checks[]=sf_qa_status(version_compare(PHP_VERSION,'8.1.0','>=')?'pass':'fail','PHP version 8.1+',PHP_VERSION,2); $checks[]=sf_qa_status(extension_loaded('pdo')?'pass':'fail','PDO extension',extension_loaded('pdo')?'Loaded':'Missing',2); $checks[]=sf_qa_status(extension_loaded('pdo_mysql')?'pass':'warn','PDO MySQL extension',extension_loaded('pdo_mysql')?'Loaded':'Required on production',2); $checks[]=sf_qa_status(extension_loaded('json')?'pass':'fail','JSON extension',extension_loaded('json')?'Loaded':'Missing'); $checks[]=sf_qa_status(extension_loaded('fileinfo')?'pass':'warn','Fileinfo extension',extension_loaded('fileinfo')?'Loaded':'Recommended for uploads'); $checks[]=sf_qa_status(function_exists('password_hash')?'pass':'fail','Password hashing','Auth layer can hash passwords',2); $checks[]=sf_qa_status(sf_qa_db_ready()?'pass':'preview','Database connection',sf_qa_db_ready()?'Connected':'Static/no-database preview mode'); foreach(['config','storage','assets/images/uploads','assets/audio/uploads','assets/video/uploads','assets/documents/uploads'] as $dir){ $path=sf_qa_file_path($dir); $checks[]=sf_qa_status(is_dir($path)&&is_writable($path)?'pass':(is_dir($path)?'warn':'fail'),'Writable folder: '.$dir,is_dir($path)?(is_writable($path)?'Writable':'Exists but not writable'):'Missing',2); } foreach(['.env.example','deploy/preflight.php','docs/DEPLOYMENT_RUNBOOK.md'] as $file) $checks[]=sf_qa_status(sf_qa_file_exists($file)?'pass':'fail','Deployment file: '.$file,sf_qa_file_exists($file)?'Present':'Missing'); return $checks; }
function sf_qa_migration_checks(): array { $checks=[]; foreach(sf_qa_migration_plan() as $migration){ $fileOk=sf_qa_file_exists($migration['file']); $missing=[]; if(sf_qa_db_ready()) foreach($migration['tables'] as $table) if(!sf_qa_table_exists($table)) $missing[]=$table; $status=sf_qa_db_ready()?($fileOk&&!$missing?'pass':'fail'):($fileOk?'preview':'fail'); $detail=$fileOk?(!$missing?'File present'.(sf_qa_db_ready()?' and tables installed':'; database not connected for table verification'):'Missing tables: '.implode(', ',$missing)):'SQL file missing'; $checks[]=sf_qa_status($status,$migration['key'].' — '.$migration['label'],$detail,2); } foreach(sf_qa_required_columns() as $table=>$columns){ if(!sf_qa_db_ready()){ $checks[]=sf_qa_status('preview','Columns: '.$table,'Database not connected; expected columns are documented'); continue; } if(!sf_qa_table_exists($table)){ $checks[]=sf_qa_status('fail','Columns: '.$table,'Table missing',2); continue; } $missing=array_values(array_diff($columns,sf_qa_columns($table))); $checks[]=sf_qa_status($missing?'fail':'pass','Columns: '.$table,$missing?'Missing columns: '.implode(', ',$missing):'Required columns present',2); } return $checks; }

function sf_qa_public_routes(): array { return [['path'=>'index.php','label'=>'Home','type'=>'public'],['path'=>'series.php','label'=>'Series','type'=>'public'],['path'=>'episodes.php','label'=>'Episodes','type'=>'public'],['path'=>'episode.php','label'=>'Episode detail','type'=>'public/member upsell'],['path'=>'watch.php','label'=>'Watch page','type'=>'member-gated content'],['path'=>'music.php','label'=>'Music landing','type'=>'public'],['path'=>'player.php','label'=>'Streaming player','type'=>'public/member upsell'],['path'=>'album.php','label'=>'Album detail','type'=>'public/member upsell'],['path'=>'song.php','label'=>'Song detail','type'=>'public/member upsell'],['path'=>'library.php','label'=>'Member library','type'=>'login required'],['path'=>'watchlist.php','label'=>'Watchlist','type'=>'login required'],['path'=>'search.php','label'=>'Search discovery','type'=>'public discovery'],['path'=>'cast.php','label'=>'Cast','type'=>'public'],['path'=>'merch.php','label'=>'Merch','type'=>'public commerce'],['path'=>'product.php','label'=>'Product detail','type'=>'public commerce'],['path'=>'cart.php','label'=>'Cart','type'=>'commerce runtime'],['path'=>'checkout.php','label'=>'Merch checkout','type'=>'commerce runtime'],['path'=>'order-confirmation.php','label'=>'Order confirmation','type'=>'commerce runtime'],['path'=>'signup.php','label'=>'Signup','type'=>'auth'],['path'=>'signin.php','label'=>'Signin','type'=>'auth'],['path'=>'forgot-password.php','label'=>'Forgot password','type'=>'auth'],['path'=>'reset-password.php','label'=>'Reset password','type'=>'auth'],['path'=>'member.php','label'=>'Member dashboard','type'=>'login required'],['path'=>'playlists.php','label'=>'Member playlists','type'=>'paid member'],['path'=>'account.php','label'=>'Account','type'=>'login required'],['path'=>'account-billing.php','label'=>'Account billing','type'=>'login required'],['path'=>'subscribe.php','label'=>'Subscribe','type'=>'billing'],['path'=>'billing-checkout.php','label'=>'Billing checkout','type'=>'billing'],['path'=>'billing-success.php','label'=>'Billing success','type'=>'billing'],['path'=>'billing-cancel.php','label'=>'Billing cancel','type'=>'billing'],['path'=>'install.php','label'=>'Installer','type'=>'setup']]; }
function sf_qa_admin_routes(): array { $routes=[]; foreach(sf_admin_nav_links() as $key=>$item) $routes[]=['path'=>$item[1],'label'=>$item[0]]; return $routes; }
function sf_qa_api_routes(): array { return [['path'=>'api/audio-track.php','label'=>'Audio tracking','method'=>'POST JSON'],['path'=>'api/video-track.php','label'=>'Video tracking','method'=>'POST JSON'],['path'=>'api/playlist.php','label'=>'Playlist runtime','method'=>'GET/POST JSON'],['path'=>'api/cart.php','label'=>'Cart runtime','method'=>'GET/POST JSON'],['path'=>'api/membership-status.php','label'=>'Membership status','method'=>'GET JSON'],['path'=>'api/billing-webhook.php','label'=>'Billing webhook','method'=>'POST JSON'],['path'=>'api/payment-webhook.php','label'=>'Payment gateway webhook','method'=>'POST JSON'],['path'=>'api/notification-webhook.php','label'=>'Notification webhook','method'=>'POST JSON'],['path'=>'api/media-token.php','label'=>'Media token issuer','method'=>'POST JSON'],['path'=>'api/player-state.php','label'=>'Audio player state','method'=>'GET/POST JSON'],['path'=>'api/entitlement-check.php','label'=>'Entitlement check','method'=>'GET JSON'],['path'=>'api/publishing-tick.php','label'=>'Publishing due-run','method'=>'GET JSON'],['path'=>'api/member-library.php','label'=>'Member library','method'=>'GET/POST JSON'],['path'=>'api/search.php','label'=>'Search discovery','method'=>'GET JSON'],['path'=>'api/analytics-summary.php','label'=>'Analytics summary','method'=>'GET JSON']]; }
function sf_qa_utility_routes(): array { return [['path'=>'stream.php','label'=>'Signed stream endpoint'],['path'=>'download.php','label'=>'Signed download endpoint'],['path'=>'deploy/preflight.php','label'=>'Deployment preflight']]; }
function sf_qa_route_checks(): array { $checks=[]; foreach(sf_qa_public_routes() as $route){ $exists=sf_qa_file_exists($route['path']); $usesHeader=sf_qa_contains($route['path'],['includes/header.php',"require __DIR__ . '/includes/header.php'","require_once __DIR__ . '/includes/header.php'"]); $checks[]=sf_qa_status($exists&&$usesHeader?'pass':($exists?'warn':'fail'),$route['label'].' — '.$route['path'],$exists?($usesHeader?'Full page route present':'Route exists; header include not detected'):'Route file missing',2); } foreach(sf_qa_admin_routes() as $route){ $exists=sf_qa_file_exists($route['path']); $protected=sf_qa_contains($route['path'],['includes/admin_catalog.php','/../includes/admin_catalog.php','includes/admin_analytics.php','/../includes/admin_analytics.php','includes/qa.php','/../includes/qa.php']) || sf_qa_contains('includes/admin_catalog.php',['sf_require_admin']); $checks[]=sf_qa_status($exists&&$protected?'pass':($exists?'warn':'fail'),$route['label'].' — '.$route['path'],$exists?($protected?'Admin shell/protection detected':'Admin protection not detected'):'Route file missing',2); } foreach(sf_qa_api_routes() as $route){ $exists=sf_qa_file_exists($route['path']); $json=sf_qa_contains($route['path'],['sf_json_response']); $checks[]=sf_qa_status($exists&&$json?'pass':($exists?'warn':'fail'),$route['label'].' — '.$route['path'],$exists?($json?'JSON response contract detected':'JSON response helper not detected'):'API file missing',2); } foreach(sf_qa_utility_routes() as $route){ $checks[]=sf_qa_status(sf_qa_file_exists($route['path'])?'pass':'fail',$route['label'].' — '.$route['path'],sf_qa_file_exists($route['path'])?'Utility route present':'Utility route missing',2); } return $checks; }

function sf_qa_security_checks(): array { $checks=[]; $adminUnprotected=[]; foreach(sf_qa_admin_routes() as $route){ if(!sf_qa_file_exists($route['path'])) continue; $body=sf_qa_read_file($route['path']); if(strpos($body,'includes/admin_catalog.php')===false && strpos($body,'includes/admin_analytics.php')===false && strpos($body,'includes/qa.php')===false && strpos($body,'sf_require_admin')===false) $adminUnprotected[]=$route['path']; } $checks[]=sf_qa_status(!$adminUnprotected?'pass':'fail','Admin route protection',!$adminUnprotected?'All admin pages use the admin shell/protection layer':'Missing protection: '.implode(', ',$adminUnprotected),3); $checks[]=sf_qa_status(sf_qa_contains('includes/auth.php',['password_hash','password_verify'])?'pass':'fail','Password security','Auth layer uses PHP password hashing/verification',3); $checks[]=sf_qa_status(sf_qa_contains('includes/auth.php',['random_bytes'])?'pass':'fail','Token generation','CSRF/reset/remember tokens use cryptographic randomness',2); $checks[]=sf_qa_status(sf_qa_contains('includes/admin_catalog.php',['mime_prefixes','max_bytes','move_uploaded_file'])?'pass':'fail','Upload validation','Upload manager validates extension, MIME family, max size, and controlled folders',3); $checks[]=sf_qa_status(sf_qa_contains('includes/media_delivery.php',['hash_hmac','hash_equals','Accept-Ranges'])?'pass':'fail','Signed media delivery','Media endpoint validates signatures and supports range streaming',3); $checks[]=sf_qa_status(sf_qa_contains('includes/payment_gateway.php',['sf_payment_verify_webhook','SF_STRIPE_WEBHOOK_SECRET'])?'pass':'fail','Gateway webhook verification','Gateway adapters isolate webhook verification',2); $checks[]=sf_qa_status(sf_qa_contains('includes/db.php',['PDO::ATTR_ERRMODE','PDO::ATTR_EMULATE_PREPARES'])?'pass':'fail','Database connection hardening','PDO exceptions and native prepares configured',2); return $checks; }
function sf_qa_normalize_asset_path(?string $path): string { $path=trim((string)$path); if($path===''||preg_match('~^(https?:)?//|^data:~i',$path))return ''; $path=ltrim($path,'/'); if(strpos($path,'assets/')===0)return $path; if(preg_match('~^(images|audio|video|documents)/~',$path))return 'assets/'.$path; return $path; }
function sf_qa_asset_exists(?string $path): bool { $normalized=sf_qa_normalize_asset_path($path); if($normalized==='')return true; return sf_qa_file_exists($normalized); }
function sf_qa_content_audit(): array { $items=[]; foreach(sf_admin_albums() as $album){$path=$album['cover_path']??$album['cover']??'';$items[]=['section'=>'Album','title'=>$album['title']??'Untitled album','field'=>'cover','path'=>$path,'status'=>$path===''?'warn':(sf_qa_asset_exists($path)?'pass':'fail')];} foreach(sf_admin_songs() as $song){foreach(['cover','cover_path','preview_src','full_src','preview_file_path','full_file_path'] as $field){ if(array_key_exists($field,$song)&&trim((string)$song[$field])!=='')$items[]=['section'=>'Song','title'=>$song['title']??'Untitled song','field'=>$field,'path'=>$song[$field],'status'=>sf_qa_asset_exists($song[$field])?'pass':'fail']; }} foreach(sf_admin_episodes() as $episode){foreach(['poster_path','thumbnail_path','hero_path','poster','image'] as $field){ if(array_key_exists($field,$episode)&&trim((string)$episode[$field])!=='')$items[]=['section'=>'Episode','title'=>$episode['title']??'Untitled episode','field'=>$field,'path'=>$episode[$field],'status'=>sf_qa_asset_exists($episode[$field])?'pass':'fail']; }} foreach(sf_admin_videos() as $video){foreach(['poster_path','poster','src','trailer_src','preview_src','stream_src','file_path'] as $field){ if(array_key_exists($field,$video)&&trim((string)$video[$field])!=='')$items[]=['section'=>'Video','title'=>$video['title']??'Untitled video','field'=>$field,'path'=>$video[$field],'status'=>sf_qa_asset_exists($video[$field])?'pass':'fail']; }} if(function_exists('sf_store_products')) foreach(sf_store_products() as $product){$path=$product['image']??$product['image_path']??'';$items[]=['section'=>'Product','title'=>$product['name']??'Product','field'=>'image','path'=>$path,'status'=>$path===''?'warn':(sf_qa_asset_exists($path)?'pass':'fail')];} return $items; }
function sf_qa_content_checks(): array { $checks=[]; $items=sf_qa_content_audit(); $fails=count(array_filter($items,fn($i)=>($i['status']??'')==='fail')); $warns=count(array_filter($items,fn($i)=>($i['status']??'')==='warn')); $checks[]=sf_qa_status($fails?'fail':($warns?'warn':'pass'),'Media asset references',$fails?($fails.' missing asset references'):($warns?$warns.' references need review':'All referenced assets exist'),3); $checks[]=sf_qa_status(count(sf_admin_albums())>0?'pass':'warn','Albums available',count(sf_admin_albums()).' album records'); $checks[]=sf_qa_status(count(sf_admin_songs())>0?'pass':'warn','Songs available',count(sf_admin_songs()).' song records'); $checks[]=sf_qa_status(count(sf_admin_videos())>0?'pass':'warn','Videos available',count(sf_admin_videos()).' video records'); return $checks; }
function sf_qa_launch_checklist(): array { return [['title'=>'Run installer','detail'=>'Visit install.php, confirm server checks, enter DB credentials, run SQL, create admin, and lock installer.','url'=>'install.php','cta'=>'Open Installer'],['title'=>'Open launch checklist','detail'=>'Use this page after installation to check score, route registry, migration status, and manual launch items.','url'=>'admin/launch-checklist.php','cta'=>'Checklist'],['title'=>'Verify route matrix','detail'=>'Confirm every public, admin, API, media, and deployment route is present.','url'=>'admin/routes-checker.php','cta'=>'Routes'],['title'=>'Verify migrations','detail'=>'Confirm base schema and migrations 001 through 013 are installed.','url'=>'admin/migration-checker.php','cta'=>'Migrations'],['title'=>'Verify secure media','detail'=>'Confirm member-only full files use signed stream/download delivery and protected storage.','url'=>'admin/media-delivery.php','cta'=>'Secure Media'],['title'=>'Configure payments','detail'=>'Keep sandbox active until Stripe/PayPal keys and webhooks are verified.','url'=>'admin/payment-gateways.php','cta'=>'Payments'],['title'=>'Run preflight','detail'=>'Open deploy/preflight.php or run it from CLI before public launch.','url'=>'deploy/preflight.php','cta'=>'Preflight']]; }
function sf_qa_all_checks(): array { return ['Environment'=>sf_qa_environment_checks(),'Migrations'=>sf_qa_migration_checks(),'Routes'=>sf_qa_route_checks(),'Security'=>sf_qa_security_checks(),'Content'=>sf_qa_content_checks()]; }
function sf_qa_flatten(array $sections): array { $flat=[]; foreach($sections as $section=>$checks) foreach($checks as $check){$check['section']=$section;$flat[]=$check;} return $flat; }
function sf_qa_persist_run(string $runType='manual'): ?int { if(!sf_qa_db_ready()||!sf_qa_table_exists('qa_runs')||!sf_qa_table_exists('qa_check_results'))return null; $sections=sf_qa_all_checks(); $flat=sf_qa_flatten($sections); $score=sf_qa_score($flat); $status=$score>=95?'passed':'review'; try{$pdo=sf_db();$pdo->beginTransaction();$stmt=$pdo->prepare('INSERT INTO qa_runs (run_type, score, status, summary_json, created_by_user_id) VALUES (?, ?, ?, ?, ?)');$stmt->execute([$runType,$score,$status,json_encode(['sections'=>array_keys($sections)],JSON_UNESCAPED_SLASHES),sf_current_user_id()]);$runId=(int)$pdo->lastInsertId();$insert=$pdo->prepare('INSERT INTO qa_check_results (qa_run_id, section, check_key, status, message, detail_json) VALUES (?, ?, ?, ?, ?, ?)');foreach($sections as $section=>$checks)foreach($checks as $index=>$check)$insert->execute([$runId,$section,strtolower(preg_replace('/[^a-z0-9]+/i','_',(string)($check['label']??'check_'.$index))),$check['status']??'info',$check['label']??'',json_encode($check,JSON_UNESCAPED_SLASHES)]);$pdo->commit();sf_admin_audit('qa_run','qa_runs',$runId,null,['score'=>$score,'status'=>$status]);return $runId;}catch(Throwable $e){if(isset($pdo)&&$pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();error_log('Stonefellow QA persist failed: '.$e->getMessage());return null;} }
function sf_qa_recent_runs(): array { if(!sf_qa_db_ready()||!sf_qa_table_exists('qa_runs'))return []; return sf_admin_fetch_all('SELECT * FROM qa_runs ORDER BY created_at DESC, id DESC LIMIT 20'); }
function sf_qa_section_summary(): array { $summary=[]; foreach(sf_qa_all_checks() as $section=>$checks)$summary[]=['section'=>$section,'score'=>sf_qa_score($checks),'count'=>count($checks),'fails'=>count(array_filter($checks,fn($check)=>in_array(($check['status']??''),['fail','missing'],true))),'warnings'=>count(array_filter($checks,fn($check)=>in_array(($check['status']??''),['warn','preview','manual'],true)))]; return $summary; }
function sf_qa_render_check_table(array $checks, bool $showSection=false): void { echo '<div class="sf-admin-table-wrap"><table class="sf-admin-table"><thead><tr>'; if($showSection)echo '<th>Section</th>'; echo '<th>Check</th><th>Status</th><th>Detail</th></tr></thead><tbody>'; foreach($checks as $check){ echo '<tr>'; if($showSection)echo '<td>'.sf_qa_h($check['section']??'').'</td>'; echo '<td><strong>'.sf_qa_h($check['label']??'').'</strong></td><td>'.sf_qa_badge((string)($check['status']??'info')).'</td><td>'.sf_qa_h($check['detail']??'').'</td></tr>'; } echo '</tbody></table></div>'; }
?>
