<?php
require_once __DIR__ . '/membership_tiers.php';
require_once __DIR__ . '/feed_personalization.php';

function sf_rev_table_exists(string $table): bool { return sf_tiers_table_exists($table); }
function sf_rev_fetch_all(string $sql,array $params=[]): array { return sf_tiers_fetch_all($sql,$params); }
function sf_rev_fetch_one(string $sql,array $params=[]): ?array { return sf_tiers_fetch_one($sql,$params); }
function sf_rev_execute(string $sql,array $params=[]): bool { return sf_tiers_execute($sql,$params); }
function sf_rev_money(int $cents): string { return sf_tiers_money($cents); }
function sf_rev_zero(): array { return ['mrr_cents'=>0,'arr_cents'=>0,'subscription_revenue_cents'=>0,'merch_revenue_cents'=>0,'total_revenue_cents'=>0,'active_subscriptions'=>0,'paid_members'=>0,'checkout_starts'=>0,'checkout_completed'=>0,'checkout_conversion_rate'=>0,'grace_or_churn_risk'=>0,'comments'=>0,'reactions'=>0,'feed_saves'=>0,'transactions'=>0,'invoices'=>0,'orders'=>0]; }
function sf_rev_summary(int $days=30): array { $since=date('Y-m-d H:i:s',time()-$days*86400); $out=sf_rev_zero(); if(sf_rev_table_exists('user_subscriptions')){ $row=sf_rev_fetch_one("SELECT COUNT(*) active_subscriptions, COUNT(DISTINCT user_id) paid_members, COALESCE(SUM(CASE WHEN sp.billing_interval='year' THEN sp.price_cents/12 ELSE sp.price_cents END),0) mrr FROM user_subscriptions us INNER JOIN subscription_plans sp ON sp.id=us.plan_id WHERE us.status IN ('active','trialing') AND (us.current_period_end IS NULL OR us.current_period_end>=NOW())")?:[]; $out['active_subscriptions']=(int)($row['active_subscriptions']??0);$out['paid_members']=(int)($row['paid_members']??0);$out['mrr_cents']=(int)round((float)($row['mrr']??0));$out['arr_cents']=$out['mrr_cents']*12; $risk=sf_rev_fetch_one("SELECT COUNT(*) total FROM user_subscriptions WHERE status IN ('past_due','unpaid') OR cancel_at_period_end=1 OR (current_period_end IS NOT NULL AND current_period_end BETWEEN NOW() AND DATE_ADD(NOW(), INTERVAL 10 DAY))")?:[]; $out['grace_or_churn_risk']=(int)($risk['total']??0); }
  if(sf_rev_table_exists('payment_transactions')){ $row=sf_rev_fetch_one("SELECT COUNT(*) transactions, COALESCE(SUM(CASE WHEN transaction_type='subscription' THEN amount_cents ELSE 0 END),0) sub_rev, COALESCE(SUM(amount_cents),0) total_rev FROM payment_transactions WHERE status='paid' AND created_at>=?",[$since])?:[]; $out['transactions']=(int)($row['transactions']??0);$out['subscription_revenue_cents']=(int)($row['sub_rev']??0);$out['total_revenue_cents']=(int)($row['total_rev']??0); }
  if(sf_rev_table_exists('orders')){ $row=sf_rev_fetch_one("SELECT COUNT(*) orders, COALESCE(SUM(total_cents),0) merch FROM orders WHERE payment_status IN ('paid','authorized') AND created_at>=?",[$since])?:[]; $out['orders']=(int)($row['orders']??0);$out['merch_revenue_cents']=(int)($row['merch']??0);$out['total_revenue_cents'] += (int)($row['merch']??0); }
  if(sf_rev_table_exists('invoices')) $out['invoices']=(int)(sf_rev_fetch_one('SELECT COUNT(*) total FROM invoices WHERE created_at>=?',[$since])['total']??0);
  if(sf_rev_table_exists('subscription_checkouts')){ $row=sf_rev_fetch_one('SELECT COUNT(*) starts, SUM(status="completed") completed FROM subscription_checkouts WHERE created_at>=?',[$since])?:[]; $out['checkout_starts']=(int)($row['starts']??0);$out['checkout_completed']=(int)($row['completed']??0);$out['checkout_conversion_rate']=$out['checkout_starts']>0?round(($out['checkout_completed']/$out['checkout_starts'])*100,2):0; }
  if(sf_rev_table_exists('checkout_conversion_events')){ $row=sf_rev_fetch_one("SELECT SUM(event_type='start_checkout') starts, SUM(event_type='complete_checkout') completed FROM checkout_conversion_events WHERE created_at>=?",[$since])?:[]; if((int)($row['starts']??0)>0){$out['checkout_starts']=(int)$row['starts'];$out['checkout_completed']=(int)$row['completed'];$out['checkout_conversion_rate']=round(($out['checkout_completed']/$out['checkout_starts'])*100,2);} }
  if(sf_rev_table_exists('fan_comments'))$out['comments']=(int)(sf_rev_fetch_one('SELECT COUNT(*) total FROM fan_comments WHERE created_at>=?',[$since])['total']??0); if(sf_rev_table_exists('fan_reactions'))$out['reactions']=(int)(sf_rev_fetch_one('SELECT COUNT(*) total FROM fan_reactions WHERE created_at>=?',[$since])['total']??0); if(sf_rev_table_exists('member_feed_items'))$out['feed_saves']=(int)(sf_rev_fetch_one("SELECT COUNT(*) total FROM member_feed_items WHERE feed_status='saved' AND created_at>=?",[$since])['total']??0); return $out; }
function sf_rev_plan_breakdown(): array { if(!sf_rev_table_exists('user_subscriptions')) return []; return sf_rev_fetch_all("SELECT sp.name, sp.slug, sp.price_cents, sp.billing_interval, COUNT(us.id) active_subscriptions, COUNT(DISTINCT us.user_id) members, COALESCE(SUM(CASE WHEN sp.billing_interval='year' THEN sp.price_cents/12 ELSE sp.price_cents END),0) mrr_cents FROM subscription_plans sp LEFT JOIN user_subscriptions us ON us.plan_id=sp.id AND us.status IN ('active','trialing') AND (us.current_period_end IS NULL OR us.current_period_end>=NOW()) GROUP BY sp.id ORDER BY sp.sort_order, sp.price_cents"); }
function sf_rev_recent_transactions(int $limit=20): array { if(!sf_rev_table_exists('payment_transactions')) return []; return sf_rev_fetch_all("SELECT pt.*, u.email, u.display_name FROM payment_transactions pt LEFT JOIN users u ON u.id=pt.user_id ORDER BY pt.created_at DESC, pt.id DESC LIMIT ".max(1,min(100,$limit))); }
function sf_rev_checkout_funnel(int $days=30): array { $summary=sf_rev_summary($days); return [['label'=>'Pricing/Checkout Starts','count'=>$summary['checkout_starts'],'rate'=>100],['label'=>'Completed Checkouts','count'=>$summary['checkout_completed'],'rate'=>$summary['checkout_conversion_rate']],['label'=>'Active Subscriptions','count'=>$summary['active_subscriptions'],'rate'=>$summary['checkout_starts']?round(($summary['active_subscriptions']/$summary['checkout_starts'])*100,2):0]]; }
function sf_rev_record_conversion(string $event,int $planId=0,int $checkoutId=0,int $amount=0,string $source=''): void { if(!sf_rev_table_exists('checkout_conversion_events')) return; if(!in_array($event,['view_pricing','start_checkout','complete_checkout','cancel_checkout','fail_checkout','upgrade_click','downgrade_click'],true))return; sf_rev_execute('INSERT INTO checkout_conversion_events (user_id, plan_id, checkout_id, event_type, source, amount_cents) VALUES (?,?,?,?,?,?)',[sf_current_user_id()?:null,$planId?:null,$checkoutId?:null,$event,$source?:null,$amount]); }
function sf_rev_save_snapshot(): bool { if(!sf_rev_table_exists('launch_revenue_snapshots')) return false; $s=sf_rev_summary(30); return sf_rev_execute('INSERT INTO launch_revenue_snapshots (snapshot_date,mrr_cents,arr_cents,subscription_revenue_cents,merch_revenue_cents,total_revenue_cents,active_subscriptions,paid_members,checkout_starts,checkout_completed,checkout_conversion_rate,grace_or_churn_risk,comments,reactions,feed_saves,metadata_json) VALUES (CURDATE(),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE mrr_cents=VALUES(mrr_cents), arr_cents=VALUES(arr_cents), subscription_revenue_cents=VALUES(subscription_revenue_cents), merch_revenue_cents=VALUES(merch_revenue_cents), total_revenue_cents=VALUES(total_revenue_cents), active_subscriptions=VALUES(active_subscriptions), paid_members=VALUES(paid_members), checkout_starts=VALUES(checkout_starts), checkout_completed=VALUES(checkout_completed), checkout_conversion_rate=VALUES(checkout_conversion_rate), grace_or_churn_risk=VALUES(grace_or_churn_risk), comments=VALUES(comments), reactions=VALUES(reactions), feed_saves=VALUES(feed_saves), metadata_json=VALUES(metadata_json)',[$s['mrr_cents'],$s['arr_cents'],$s['subscription_revenue_cents'],$s['merch_revenue_cents'],$s['total_revenue_cents'],$s['active_subscriptions'],$s['paid_members'],$s['checkout_starts'],$s['checkout_completed'],$s['checkout_conversion_rate'],$s['grace_or_churn_risk'],$s['comments'],$s['reactions'],$s['feed_saves'],json_encode($s,JSON_UNESCAPED_SLASHES)]); }
function sf_rev_recent_snapshots(int $limit=30): array { if(!sf_rev_table_exists('launch_revenue_snapshots'))return []; return sf_rev_fetch_all('SELECT * FROM launch_revenue_snapshots ORDER BY snapshot_date DESC LIMIT '.max(1,min(120,$limit))); }
?>
