<?php
/**
 * Cross-cutting production controls for Stonefellow revenue, membership,
 * media access, and client-reported playback events.
 */
if (defined('SF_REVENUE_ACCESS_GOVERNANCE_LOADED')) return;
define('SF_REVENUE_ACCESS_GOVERNANCE_LOADED', true);
function sf_revenue_is_production(): bool { return function_exists('sf_is_production') && sf_is_production(); }
function sf_revenue_env_bool(string $name,bool $default=false): bool { if(function_exists('sf_env_bool'))return sf_env_bool($name,$default);$value=getenv($name);if($value===false||$value==='')return$default;return in_array(strtolower(trim((string)$value)),['1','true','yes','on'],true); }
function sf_revenue_sandbox_allowed(string $scope): bool { if(!sf_revenue_is_production())return true;$flag=$scope==='merch'?'SF_ALLOW_SANDBOX_MERCH':'SF_ALLOW_SANDBOX_SUBSCRIPTIONS';return sf_revenue_env_bool($flag,false); }
function sf_revenue_media_signing_ready(): bool { $secret=trim((string)(getenv('SF_MEDIA_SIGNING_KEY')?:''));return !sf_revenue_is_production()||strlen($secret)>=32; }
function sf_revenue_allowed_hosts(): array { if(function_exists('sf_security_allowed_hosts'))return array_map('strtolower',sf_security_allowed_hosts());$raw=trim((string)(getenv('SF_ALLOWED_HOSTS')?:''));return array_values(array_filter(array_map(static fn($v)=>strtolower(trim($v)),explode(',',$raw)))); }
function sf_revenue_request_host(): string { $host=strtolower(trim((string)($_SERVER['HTTP_HOST']??'')));return preg_match('/^[a-z0-9.-]+(?::\d{1,5})?$/',$host)?$host:''; }
function sf_revenue_same_origin_request(): bool { if(PHP_SAPI==='cli')return true;$source=trim((string)($_SERVER['HTTP_ORIGIN']??$_SERVER['HTTP_REFERER']??''));if($source==='')return !sf_revenue_is_production();$host=strtolower((string)(parse_url($source,PHP_URL_HOST)?:''));if($host==='')return false;$allowed=sf_revenue_allowed_hosts();if($allowed)return in_array($host,array_map(static fn($v)=>preg_replace('/:\d+$/','',$v),$allowed),true);return $host===preg_replace('/:\d+$/','',sf_revenue_request_host()); }
function sf_revenue_guard_json_write(string $scope,int $limit=240,int $windowSeconds=900): void { if(strtoupper((string)($_SERVER['REQUEST_METHOD']??'GET'))!=='POST'){if(function_exists('sf_json_response'))sf_json_response(['ok'=>false,'error'=>'method_not_allowed'],405);http_response_code(405);exit;}if(!sf_revenue_same_origin_request()){if(function_exists('sf_json_response'))sf_json_response(['ok'=>false,'error'=>'cross_origin_write_blocked'],403);http_response_code(403);exit;}if(function_exists('sf_security_session_rate_limit')){$userId=function_exists('sf_current_user_id')?(int)sf_current_user_id():0;$ip=(string)($_SERVER['REMOTE_ADDR']??'');$rate=sf_security_session_rate_limit('revenue|'.$scope.'|'.$userId.'|'.$ip,max(10,$limit),max(60,$windowSeconds));if(empty($rate['allowed'])){header('Retry-After: '.(int)($rate['retry_after']??60));if(function_exists('sf_json_response'))sf_json_response(['ok'=>false,'error'=>'rate_limited'],429);http_response_code(429);exit;}} }
function sf_revenue_normalize_currency($currency): string { $currency=strtoupper(trim((string)$currency));return preg_match('/^[A-Z]{3}$/',$currency)?$currency:''; }
function sf_revenue_provider_payment_verified(array $checkout,array $payment): array { $provider=strtolower(trim((string)($payment['provider']??$checkout['provider']??'')));$expectedAmount=max(0,(int)($checkout['amount_cents']??0));$expectedCurrency=sf_revenue_normalize_currency($checkout['currency']??'USD');$actualAmount=isset($payment['amount_cents'])?max(0,(int)$payment['amount_cents']):null;$actualCurrency=isset($payment['currency'])?sf_revenue_normalize_currency($payment['currency']):'';$paymentStatus=strtolower(trim((string)($payment['payment_status']??'')));$paymentId=trim((string)($payment['provider_payment_id']??''));$verified=!empty($payment['verified']);if($provider==='sandbox')return sf_revenue_sandbox_allowed('subscription')?['ok'=>true,'provider'=>$provider]:['ok'=>false,'error'=>'sandbox_disabled'];if(!in_array($provider,['stripe'],true))return ['ok'=>false,'error'=>'provider_not_supported'];if(!$verified)return ['ok'=>false,'error'=>'provider_not_verified'];if($paymentId==='')return ['ok'=>false,'error'=>'provider_payment_id_missing'];if(!in_array($paymentStatus,['paid','no_payment_required'],true))return ['ok'=>false,'error'=>'payment_not_settled'];if($actualAmount===null||$actualAmount!==$expectedAmount)return ['ok'=>false,'error'=>'payment_amount_mismatch'];if($actualCurrency===''||$actualCurrency!==$expectedCurrency)return ['ok'=>false,'error'=>'payment_currency_mismatch'];return ['ok'=>true,'provider'=>$provider]; }
function sf_revenue_redact_payload(array $payload,int $maxBytes=65535): array { $sensitive=['api_key','secret','password','token','card','number','cvc','authorization','client_secret'];$walk=static function($value,int $depth=0)use(&$walk,$sensitive){if($depth>8)return'[depth-limited]';if(!is_array($value)){if(is_string($value)&&strlen($value)>4000)return substr($value,0,4000).'…';return$value;}$out=[];foreach($value as$key=>$item){$name=strtolower((string)$key);$redact=false;foreach($sensitive as$needle)if(str_contains($name,$needle)){$redact=true;break;}$out[$key]=$redact?'[redacted]':$walk($item,$depth+1);}return$out;};$clean=$walk($payload);$json=json_encode($clean,JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE);if(is_string($json)&&strlen($json)>$maxBytes)return ['truncated'=>true,'sha256'=>hash('sha256',$json),'bytes'=>strlen($json)];return is_array($clean)?$clean:[]; }
function sf_revenue_record_duration(string $type,array $record): int { $seconds=(int)($record['duration_seconds']??$record['runtime_seconds']??0);if($seconds>0)return min($seconds,43200);$label=(string)($record['duration']??$record['runtime']??'');if(preg_match('/^(\d+):(\d{1,2})$/',$label,$m))return min(((int)$m[1]*60)+(int)$m[2],43200);if(preg_match('/(\d+)\s*min/i',$label,$m))return min((int)$m[1]*60,43200);return $type==='song'?30:0; }
function sf_revenue_tracking_metrics(string $type,int $contentId,array $record,string $eventType,int $position,int $reportedSeconds,float $reportedPercent,bool $fullAccess): array { $duration=sf_revenue_record_duration($type,$record);$preview=max(1,min(600,(int)($record['preview_seconds']??($type==='song'?30:120))));$maxPosition=$duration>0?$duration:43200;if(!$fullAccess)$maxPosition=min($maxPosition,$preview);$position=max(0,min($position,$maxPosition));$key=$type.'|'.$contentId;$now=microtime(true);$previous=$_SESSION['sf_verified_playback_clock'][$key]??null;$elapsed=is_array($previous)?max(0.0,$now-(float)($previous['time']??$now)):0.0;$maxDelta=is_array($previous)?max(5,(int)ceil($elapsed*1.5)+5):10;if(in_array($eventType,['play','pause','seek','error'],true))$reportedSeconds=0;$seconds=max(0,min($reportedSeconds,$maxDelta));$percent=$duration>0?min(100,max(0,($position/$duration)*100)):min(100,max(0,$reportedPercent));if(!$fullAccess&&$duration>$preview)$percent=min($percent,($preview/$duration)*100);$complete=$fullAccess&&$duration>0&&$position>=max(1,(int)floor($duration*0.9));if($eventType==='complete'&&!$complete)$eventType='progress';if($complete&&$eventType==='progress')$eventType='complete';$_SESSION['sf_verified_playback_clock'][$key]=['time'=>$now,'position'=>$position];return ['event_type'=>$eventType,'position_seconds'=>$position,'seconds_delta'=>$seconds,'percent_complete'=>round($percent,2),'duration_seconds'=>$duration,'full_access'=>$fullAccess,'eligible_for_member_progress'=>$fullAccess||(($record['access_level']??$record['access']??'')==='public')]; }
function sf_revenue_playlist_limits(array $member): array { $subscription=is_array($member['subscription']??null)?$member['subscription']:[];$maxPlaylists=(int)($subscription['max_playlists']??0);$maxTracks=(int)($subscription['max_playlist_tracks']??0);return ['playlists'=>$maxPlaylists>0?min($maxPlaylists,500):50,'tracks'=>$maxTracks>0?min($maxTracks,2000):500]; }
function sf_revenue_expire_subscription_grants(PDO $pdo,int $userId): void { if($userId<=0)return;try{$stmt=$pdo->prepare("UPDATE content_access_grants SET expires_at=LEAST(COALESCE(expires_at,NOW()),NOW()) WHERE user_id=? AND grant_type='subscription' AND (expires_at IS NULL OR expires_at>NOW())");$stmt->execute([$userId]);}catch(Throwable$e){error_log('Stonefellow subscription grant expiration failed: '.$e->getMessage());} }
function sf_revenue_provider_payment_duplicate(PDO $pdo,string $provider,string $paymentId): bool { if($paymentId==='')return false;try{$stmt=$pdo->prepare("SELECT id FROM payment_transactions WHERE provider=? AND provider_payment_id=? AND status IN ('authorized','paid','refunded') LIMIT 1");$stmt->execute([$provider,$paymentId]);return(bool)$stmt->fetchColumn();}catch(Throwable$e){return false;} }
?>