<?php
require_once __DIR__ . '/db.php';
require_once __DIR__ . '/ai_settings.php';
require_once __DIR__ . '/storyboard_generation.php';

function sf_theme_db(): ?PDO { return sf_db(); }
function sf_theme_table_exists(string $table): bool
{
    $pdo=sf_theme_db();if(!$pdo)return false;try{$stmt=$pdo->prepare('SHOW TABLES LIKE ?');$stmt->execute([$table]);return(bool)$stmt->fetchColumn();}catch(Throwable$e){error_log('Theme table check failed: '.$e->getMessage());return false;}
}
function sf_theme_ready(): bool { return sf_theme_table_exists('show_themes')&&sf_theme_table_exists('show_theme_images'); }
function sf_theme_h($value): string { return htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8'); }
function sf_theme_slug(string $name): string { $slug=strtolower(trim(preg_replace('/[^a-z0-9]+/i','-',$name)?:'theme','-'));return$slug?:'theme'; }
function sf_theme_default_palette(): array { return['background'=>'#030302','panel'=>'#0b0907','accent'=>'#d6ad6c','accent_secondary'=>'#c79a52','text'=>'#ead8bc','muted'=>'#b09b79','border'=>'rgba(214,173,108,.18)']; }
function sf_theme_default_image_slots(): array
{
    return[
        ['image_key'=>'home_hero','title'=>'Home Hero','page_location'=>'index.php hero','current_path'=>'images/home/home-hero.jpg','aspect_ratio'=>'16:9','recommended_size'=>'1920x1080','sort_order'=>10,'prompt'=>'Main cinematic brand hero for the show with the selected theme mood, signature setting, hero object, premium streaming-series poster feel.'],
        ['image_key'=>'series_characters_hero','title'=>'Series Characters Hero','page_location'=>'series-characters.php hero','current_path'=>'images/cast/cast-template-hero.png','aspect_ratio'=>'21:9','recommended_size'=>'1920x900','sort_order'=>20,'prompt'=>'Cinematic ensemble cast banner with silhouettes or portraits of the main characters, strong rim light, premium streaming directory feel.'],
        ['image_key'=>'character_portrait_main','title'=>'Main Character Portrait','page_location'=>'character.php hero/profile','current_path'=>'images/cast/cast-jax.png','aspect_ratio'=>'3:4','recommended_size'=>'1200x1600','sort_order'=>30,'prompt'=>'Main character portrait for the selected show theme, dramatic lighting, wardrobe and attitude consistent with the theme, premium streaming profile art.'],
        ['image_key'=>'music_hero','title'=>'Music Hero','page_location'=>'music.php hero','current_path'=>'images/music/music-hero-guitar.png','aspect_ratio'=>'16:10','recommended_size'=>'1600x1000','sort_order'=>40,'prompt'=>'Music page hero image that fits the show theme, performance energy, signature props, cinematic lighting.'],
        ['image_key'=>'album_cover','title'=>'Album Cover','page_location'=>'album/music/player pages','current_path'=>'images/music/soundtrack-cover.png','aspect_ratio'=>'1:1','recommended_size'=>'1400x1400','sort_order'=>50,'prompt'=>'Square soundtrack or album cover for the selected show theme, iconic object, title-safe composition, premium poster art.'],
        ['image_key'=>'episode_poster','title'=>'Episode Poster','page_location'=>'episodes.php cards','current_path'=>'images/episodes/template-card-01.png','aspect_ratio'=>'16:9','recommended_size'=>'1600x900','sort_order'=>60,'prompt'=>'Cinematic episode still/card artwork for the selected show theme, tension, environment, premium streaming card art.'],
        ['image_key'=>'merch_hero','title'=>'Merch Hero','page_location'=>'merch.php hero','current_path'=>'images/merch/merch-hero.png','aspect_ratio'=>'16:9','recommended_size'=>'1920x1080','sort_order'=>70,'prompt'=>'Premium merch campaign image for the selected show theme, apparel flatlay or modeled product, brand colors, studio lighting.'],
    ];
}
function sf_theme_all(): array { if(!sf_theme_ready())return[];try{return sf_theme_db()->query('SELECT * FROM show_themes ORDER BY is_active DESC,updated_at DESC,id DESC')->fetchAll()?:[];}catch(Throwable$e){return[];} }
function sf_theme_active(): ?array { if(!sf_theme_ready())return null;try{$row=sf_theme_db()->query('SELECT * FROM show_themes WHERE is_active=1 ORDER BY id DESC LIMIT 1')->fetch();return$row?:null;}catch(Throwable$e){return null;} }
function sf_theme_find(int $id): ?array { if(!sf_theme_ready()||$id<=0)return null;try{$stmt=sf_theme_db()->prepare('SELECT * FROM show_themes WHERE id=? LIMIT 1');$stmt->execute([$id]);$row=$stmt->fetch();return$row?:null;}catch(Throwable$e){return null;} }
function sf_theme_images(int $themeId): array { if(!sf_theme_ready()||$themeId<=0)return[];try{$stmt=sf_theme_db()->prepare('SELECT * FROM show_theme_images WHERE theme_id=? ORDER BY sort_order,id');$stmt->execute([$themeId]);return$stmt->fetchAll()?:[];}catch(Throwable$e){return[];} }
function sf_theme_image_find(int $id): ?array { if(!sf_theme_ready()||$id<=0)return null;try{$stmt=sf_theme_db()->prepare('SELECT * FROM show_theme_images WHERE id=? LIMIT 1');$stmt->execute([$id]);$row=$stmt->fetch();return$row?:null;}catch(Throwable$e){return null;} }
function sf_theme_image_by_key(int $themeId,string $imageKey): ?array { if(!sf_theme_ready()||$themeId<=0||trim($imageKey)==='')return null;try{$stmt=sf_theme_db()->prepare('SELECT * FROM show_theme_images WHERE theme_id=? AND image_key=? LIMIT 1');$stmt->execute([$themeId,$imageKey]);$row=$stmt->fetch();return$row?:null;}catch(Throwable$e){return null;} }
function sf_theme_palette(array $theme): array { $json=$theme['palette_json']??'';$data=is_string($json)?json_decode($json,true):(is_array($json)?$json:[]);return array_merge(sf_theme_default_palette(),is_array($data)?$data:[]); }
function sf_theme_provider(): ?array { foreach(sf_ai_providers()as$provider)if(!empty($provider['is_default_image']))return$provider;return sf_ai_provider('chatgpt'); }
function sf_theme_provider_ready(?array $provider=null): bool { $provider=$provider?:sf_theme_provider();return is_array($provider)&&sf_ai_provider_runtime_ready($provider,'image'); }
function sf_theme_clean_palette(array $palette): array { $defaults=sf_theme_default_palette();$clean=[];foreach($defaults as$key=>$default)$clean[$key]=sf_agentic_text($palette[$key]??$default,64,$default);return$clean; }
function sf_theme_create(array $data): int
{
    if(!sf_theme_ready())return 0;$name=sf_agentic_text($data['theme_name']??'New Theme',190,'New Theme');$slug=sf_theme_slug((string)($data['theme_slug']??$name));$palette=json_encode(sf_theme_clean_palette((array)($data['palette']??[])),JSON_UNESCAPED_SLASHES);$status=in_array((string)($data['status']??'draft'),['draft','preview','active','archived'],true)?(string)$data['status']:'draft';
    try{$stmt=sf_theme_db()->prepare('INSERT INTO show_themes (theme_name,theme_slug,description,mood_prompt,palette_json,status) VALUES (?,?,?,?,?,?)');$stmt->execute([$name,$slug,sf_agentic_text($data['description']??'',4000),sf_agentic_text($data['mood_prompt']??'',12000),$palette,$status]);$id=(int)sf_theme_db()->lastInsertId();foreach(sf_theme_default_image_slots()as$slot)sf_theme_upsert_image($id,$slot);return$id;}catch(Throwable$e){error_log('Theme create failed: '.$e->getMessage());return 0;}
}
function sf_theme_update(int $themeId,array $data): bool
{
    if(!sf_theme_ready()||$themeId<=0)return false;$status=in_array((string)($data['status']??'draft'),['draft','preview','active','archived'],true)?(string)$data['status']:'draft';$palette=json_encode(sf_theme_clean_palette((array)($data['palette']??[])),JSON_UNESCAPED_SLASHES);
    try{$stmt=sf_theme_db()->prepare('UPDATE show_themes SET theme_name=?,theme_slug=?,description=?,mood_prompt=?,palette_json=?,status=? WHERE id=?');return$stmt->execute([sf_agentic_text($data['theme_name']??'',190,'Theme'),sf_theme_slug((string)($data['theme_slug']??'')),sf_agentic_text($data['description']??'',4000),sf_agentic_text($data['mood_prompt']??'',12000),$palette,$status,$themeId]);}catch(Throwable$e){return false;}
}
function sf_theme_activate(int $themeId): bool
{
    if(!sf_theme_ready()||$themeId<=0)return false;try{$pdo=sf_theme_db();$pdo->beginTransaction();$pdo->exec('UPDATE show_themes SET is_active=0');$stmt=$pdo->prepare("UPDATE show_themes SET is_active=1,status='active' WHERE id=?");$ok=$stmt->execute([$themeId]);$pdo->commit();return$ok;}catch(Throwable$e){if(sf_theme_db()?->inTransaction())sf_theme_db()->rollBack();return false;}
}
function sf_theme_upsert_image(int $themeId,array $slot): bool
{
    if(!sf_theme_ready()||$themeId<=0)return false;try{$stmt=sf_theme_db()->prepare('INSERT INTO show_theme_images (theme_id,image_key,title,page_location,current_path,aspect_ratio,recommended_size,prompt,status,sort_order) VALUES (?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE title=VALUES(title),page_location=VALUES(page_location),current_path=VALUES(current_path),aspect_ratio=VALUES(aspect_ratio),recommended_size=VALUES(recommended_size),prompt=VALUES(prompt),status=VALUES(status),sort_order=VALUES(sort_order)');return$stmt->execute([$themeId,sf_theme_slug((string)($slot['image_key']??'image')),sf_agentic_text($slot['title']??'',190,'Image'),sf_agentic_text($slot['page_location']??'',190),sf_agentic_text($slot['current_path']??'',255),sf_agentic_text($slot['aspect_ratio']??'',40),sf_agentic_text($slot['recommended_size']??'',80),sf_agentic_text($slot['prompt']??'',12000),in_array((string)($slot['status']??'active'),['draft','active','generated','approved','archived'],true)?(string)$slot['status']:'draft',max(0,min(9999,(int)($slot['sort_order']??100)))]);}catch(Throwable$e){return false;}
}
function sf_theme_update_image(int $imageId,array $data): bool
{
    if(!sf_theme_ready()||$imageId<=0)return false;$status=in_array((string)($data['status']??'draft'),['draft','active','generated','approved','archived'],true)?(string)$data['status']:'draft';try{$stmt=sf_theme_db()->prepare('UPDATE show_theme_images SET title=?,page_location=?,current_path=?,generated_path=?,approved_path=?,aspect_ratio=?,recommended_size=?,prompt=?,status=?,sort_order=? WHERE id=?');return$stmt->execute([sf_agentic_text($data['title']??'',190,'Image'),sf_agentic_text($data['page_location']??'',190),sf_agentic_text($data['current_path']??'',255),sf_agentic_text($data['generated_path']??'',255),sf_agentic_text($data['approved_path']??'',255),sf_agentic_text($data['aspect_ratio']??'',40),sf_agentic_text($data['recommended_size']??'',80),sf_agentic_text($data['prompt']??'',12000),$status,max(0,min(9999,(int)($data['sort_order']??100))),$imageId]);}catch(Throwable$e){return false;}
}
function sf_theme_image_path(array $image,string $field): string { return trim((string)($image[$field]??'')); }
function sf_theme_image_src(array $image,string $field): string { $path=sf_theme_image_path($image,$field);return$path!==''?sf_asset($path):''; }
function sf_theme_image_status_summary(array $image): array { return['current'=>sf_theme_image_path($image,'current_path')!=='','generated'=>sf_theme_image_path($image,'generated_path')!=='','approved'=>sf_theme_image_path($image,'approved_path')!=='','status'=>(string)($image['status']??'draft')]; }
function sf_theme_approve_image(int $imageId): bool { $image=sf_theme_image_find($imageId);if(!$image||sf_theme_image_path($image,'generated_path')==='')return false;try{$stmt=sf_theme_db()->prepare("UPDATE show_theme_images SET approved_path=generated_path,status='approved' WHERE id=?");return$stmt->execute([$imageId]);}catch(Throwable$e){return false;} }
function sf_theme_reject_generated_image(int $imageId): bool { $image=sf_theme_image_find($imageId);if(!$image)return false;try{$status=sf_theme_image_path($image,'approved_path')!==''?'approved':'draft';$stmt=sf_theme_db()->prepare('UPDATE show_theme_images SET generated_path=NULL,status=? WHERE id=?');return$stmt->execute([$status,$imageId]);}catch(Throwable$e){return false;} }
function sf_theme_use_image_as_current(int $imageId,string $source='approved'): bool
{
    if($source!=='approved')return false;$image=sf_theme_image_find($imageId);if(!$image||($image['status']??'')!=='approved')return false;$path=sf_theme_image_path($image,'approved_path');if($path==='')return false;try{$stmt=sf_theme_db()->prepare("UPDATE show_theme_images SET current_path=?,status='active' WHERE id=?");return$stmt->execute([$path,$imageId]);}catch(Throwable$e){return false;}
}
function sf_theme_upload_error_message(int $code): string { $map=[UPLOAD_ERR_INI_SIZE=>'Uploaded file exceeds the server limit.',UPLOAD_ERR_FORM_SIZE=>'Uploaded file exceeds the form limit.',UPLOAD_ERR_PARTIAL=>'File upload was incomplete.',UPLOAD_ERR_NO_FILE=>'No file was selected.',UPLOAD_ERR_NO_TMP_DIR=>'Missing server upload directory.',UPLOAD_ERR_CANT_WRITE=>'Server could not write the uploaded file.',UPLOAD_ERR_EXTENSION=>'A PHP extension blocked the upload.'];return$map[$code]??'Unknown upload error.'; }
function sf_theme_upload_image(int $themeId,int $imageId,array $file): array
{
    $theme=sf_theme_find($themeId);$image=sf_theme_image_find($imageId);if(!$theme||!$image||(int)$image['theme_id']!==$themeId)return['ok'=>false,'message'=>'Theme image slot not found.'];$error=(int)($file['error']??UPLOAD_ERR_NO_FILE);if($error!==UPLOAD_ERR_OK)return['ok'=>false,'message'=>sf_theme_upload_error_message($error)];$tmp=(string)($file['tmp_name']??'');if($tmp===''||!is_uploaded_file($tmp))return['ok'=>false,'message'=>'Upload was not received by the server.'];$bytes=(string)file_get_contents($tmp);$validation=sf_agentic_validate_image_bytes($bytes,12*1024*1024);if(empty($validation['ok']))return['ok'=>false,'message'=>'Only valid JPG, PNG, or WEBP images under 12MB are allowed.'];$extension=['image/png'=>'png','image/jpeg'=>'jpg','image/webp'=>'webp'][$validation['mime']];$themeSlug=sf_theme_slug((string)$theme['theme_slug']);$imageKey=sf_theme_slug((string)$image['image_key']);$dir=dirname(__DIR__).'/assets/images/generated-themes/'.$themeSlug.'/uploads';if(!is_dir($dir)&&!mkdir($dir,0775,true))return['ok'=>false,'message'=>'Could not create theme upload directory.'];$fileName=$imageKey.'-upload-'.date('Ymd-His').'-'.bin2hex(random_bytes(4)).'.'.$extension;$absolute=$dir.'/'.$fileName;if(file_put_contents($absolute,$bytes,LOCK_EX)!==strlen($bytes))return['ok'=>false,'message'=>'Could not save uploaded image.'];@chmod($absolute,0640);$relative='images/generated-themes/'.$themeSlug.'/uploads/'.$fileName;try{$stmt=sf_theme_db()->prepare("UPDATE show_theme_images SET generated_path=?,last_generated_at=NOW(),status='generated' WHERE id=?");$stmt->execute([$relative,$imageId]);sf_theme_create_job($themeId,$imageId,'manual_upload','complete',['original_name'=>basename((string)($file['name']??'')),'mime'=>$validation['mime'],'size'=>strlen($bytes)],$relative,'');return['ok'=>true,'path'=>$relative,'message'=>'Replacement image uploaded into the Generated Preview slot. Approve it before publishing.'];}catch(Throwable$e){@unlink($absolute);return['ok'=>false,'message'=>'Could not register uploaded image.'];}
}
function sf_theme_create_job(int $themeId,?int $imageId,string $action,string $status,array $payload=[],string $path='',string $error=''): int
{
    if(!sf_theme_ready()||!sf_theme_table_exists('show_theme_image_jobs'))return 0;$status=in_array($status,['queued','running','complete','failed','canceled'],true)?$status:'failed';$json=json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE);if(is_string($json)&&strlen($json)>65535)$json=json_encode(['payload_hash'=>hash('sha256',$json),'truncated'=>true]);try{$stmt=sf_theme_db()->prepare('INSERT INTO show_theme_image_jobs (theme_id,theme_image_id,action_type,status,request_payload,generated_path,error_message,completed_at) VALUES (?,?,?,?,?,?,?,?)');$stmt->execute([$themeId,$imageId,substr($action,0,80),$status,$json,$path!==''?substr($path,0,255):null,$error!==''?substr($error,0,2000):null,in_array($status,['complete','failed','canceled'],true)?date('Y-m-d H:i:s'):null]);return(int)sf_theme_db()->lastInsertId();}catch(Throwable$e){return 0;}
}
function sf_theme_generation_prompt(array $theme,array $image): string
{
    return "<THEME_CONTEXT>\nMood: ".sf_agentic_text($theme['mood_prompt']??'',8000)."\nImage slot: ".sf_agentic_text($image['title']??'',190)."\nLocation: ".sf_agentic_text($image['page_location']??'',190)."\nAspect ratio: ".sf_agentic_text($image['aspect_ratio']??'',40)."\n</THEME_CONTEXT>\n<IMAGE_REQUEST>\n".sf_agentic_text($image['prompt']??'',8000)."\n</IMAGE_REQUEST>\nCreate one production-ready image. No text, UI, logos, signatures, watermarks, or unsafe content.";
}
function sf_theme_generate_image(array $theme,array $image): array
{
    $provider=sf_theme_provider();$themeId=(int)($theme['id']??0);$imageId=(int)($image['id']??0);if(!$themeId||!$imageId)return['ok'=>false,'message'=>'Theme image slot not found.'];$prompt=sf_theme_generation_prompt($theme,$image);$payload=['provider'=>$provider['provider_key']??'chatgpt','model'=>$provider['image_model']??'gpt-image-1','prompt_hash'=>hash('sha256',$prompt),'size'=>'1024x1024'];
    if(!sf_theme_provider_ready($provider)){sf_theme_create_job($themeId,$imageId,'generate_one','failed',$payload,'','Default image provider is not securely configured.');return['ok'=>false,'message'=>'Default image provider is not securely configured in admin/ai-settings.php.'];}
    $key=sf_ai_decrypt_secret($provider['encrypted_api_key']??'');$model=sf_agentic_model_name($provider['image_model']??'')?:'gpt-image-1';$jobId=sf_theme_create_job($themeId,$imageId,'generate_one','running',$payload);
    $result=sf_sbgen_http_json('https://api.openai.com/v1/images/generations',['Content-Type: application/json','Authorization: Bearer '.$key],['model'=>$model,'prompt'=>$prompt,'size'=>'1024x1024','quality'=>'medium','output_format'=>'png','n'=>1],max(30,(int)($provider['timeout_seconds']??120)),max(0,(int)($provider['max_retries']??1)));
    if(!$result['ok']){if($jobId>0)sf_theme_db()->prepare("UPDATE show_theme_image_jobs SET status='failed',error_message=?,completed_at=NOW() WHERE id=?")->execute([substr($result['error'],0,2000),$jobId]);return['ok'=>false,'message'=>'Image API request failed.'];}
    $base64=(string)($result['json']['data'][0]['b64_json']??'');$bytes=base64_decode($base64,true);$validation=$bytes!==false?sf_agentic_validate_image_bytes($bytes):['ok'=>false];if(empty($validation['ok'])){if($jobId>0)sf_theme_db()->prepare("UPDATE show_theme_image_jobs SET status='failed',error_message='Invalid generated image payload.',completed_at=NOW() WHERE id=?")->execute([$jobId]);return['ok'=>false,'message'=>'Generated image payload failed validation.'];}
    $dir=dirname(__DIR__).'/assets/images/generated-themes/'.sf_theme_slug((string)$theme['theme_slug']);if(!is_dir($dir)&&!mkdir($dir,0775,true))return['ok'=>false,'message'=>'Could not create generated theme directory.'];$file=sf_theme_slug((string)$image['image_key']).'-'.date('Ymd-His').'-'.bin2hex(random_bytes(4)).'.png';$absolute=$dir.'/'.$file;if(file_put_contents($absolute,$bytes,LOCK_EX)!==strlen($bytes))return['ok'=>false,'message'=>'Could not save generated image.'];@chmod($absolute,0640);$relative='images/generated-themes/'.sf_theme_slug((string)$theme['theme_slug']).'/'.$file;
    sf_theme_db()->prepare("UPDATE show_theme_images SET generated_path=?,last_generated_at=NOW(),status='generated' WHERE id=?")->execute([$relative,$imageId]);if($jobId>0)sf_theme_db()->prepare("UPDATE show_theme_image_jobs SET status='complete',generated_path=?,completed_at=NOW() WHERE id=?")->execute([$relative,$jobId]);
    $profile=(array)($GLOBALS['sf_agentic_active_profile']??[]);if(($profile['feature']??'')==='theme_image')sf_agentic_finalize_reservation('success',$result['json']['usage']??[]);
    return['ok'=>true,'path'=>$relative,'message'=>'Image generated. Review and approve before publishing.'];
}
function sf_theme_generate_all(int $themeId): array
{
    $theme=sf_theme_find($themeId);if(!$theme)return['ok'=>false,'message'=>'Theme not found.'];$images=sf_theme_images($themeId);$max=max(1,(int)(getenv('SF_AI_MAX_BULK_IMAGES')?:8));if(count($images)>$max)return['ok'=>false,'message'=>'Bulk generation exceeds the configured maximum.'];$results=[];$success=0;foreach($images as$image){$result=sf_theme_generate_image($theme,$image);$results[$image['image_key']]=$result;if(!empty($result['ok']))$success++;else break;}sf_agentic_finalize_reservation($success===count($images)?'success':'failed',[],$success===count($images)?'':'Bulk image generation stopped after a failed item.');return['ok'=>$success===count($images),'results'=>$results,'message'=>$success===count($images)?'All images generated for review.':'Bulk generation stopped safely after a failure.'];
}
?>
