<?php

declare(strict_types=1);

function sf_sa_candidate(int $id): ?array { return sf_sa_ready()&&$id>0?sf_admin_fetch_one('SELECT * FROM staging_release_candidates WHERE id=? LIMIT 1',[$id]):null; }
function sf_sa_candidates(int $limit=50): array { return sf_sa_ready()?sf_admin_fetch_all('SELECT * FROM staging_release_candidates ORDER BY created_at DESC,id DESC LIMIT '.max(1,min(200,$limit))):[]; }
function sf_sa_latest_frozen_candidate(): ?array { return sf_sa_ready()?sf_admin_fetch_one("SELECT * FROM staging_release_candidates WHERE candidate_status='frozen' ORDER BY frozen_at DESC,id DESC LIMIT 1"):null; }
function sf_sa_candidate_for_commit(string $sha,string $status='frozen'): ?array { $sha=strtolower(trim($sha));if(!sf_sa_ready()||!preg_match('/^[a-f0-9]{40}$/',$sha))return null;return sf_admin_fetch_one('SELECT * FROM staging_release_candidates WHERE target_commit_sha=? AND candidate_status=? ORDER BY created_at DESC,id DESC LIMIT 1',[$sha,$status]); }

function sf_sa_candidate_event(int $candidateId,string $type,string $message,array $metadata=[],string $status='recorded'): bool {
    if(!sf_sa_ready()||$candidateId<=0)return false;$status=in_array($status,['recorded','verified','rejected'],true)?$status:'recorded';$json=$metadata?json_encode($metadata,JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE):null;return sf_admin_execute('INSERT INTO staging_release_candidate_events (candidate_id,event_type,event_status,event_message,metadata_json,actor_user_id) VALUES (?,?,?,?,?,?)',[$candidateId,sf_sa_text($type,120),$status,sf_sa_text($message,2000),$json,sf_current_user_id()?:null]);
}

function sf_sa_release_for_commit(string $sha): ?array {
    if(!sf_admin_table_exists('deployment_releases'))return null;return sf_admin_fetch_one("SELECT * FROM deployment_releases WHERE git_sha=? AND release_status IN ('draft','ready','deploying','deployed') ORDER BY created_at DESC,id DESC LIMIT 1",[$sha]);
}

function sf_sa_candidate_gate(int $activationRunId): array {
    $reasons=[];$run=sf_sa_run($activationRunId);if(!$run||($run['run_status']??'')!=='passed'||(float)($run['overall_score']??0)!==100.0)$reasons[]='A 100% passed staging activation run is required.';$sha=strtolower((string)($run['target_commit_sha']??''));if(!preg_match('/^[a-f0-9]{40}$/',$sha))$reasons[]='Activation run requires an exact 40-character commit SHA.';
    $catalog=$sha&&sf_admin_table_exists('catalog_readiness_snapshots')?sf_admin_fetch_one("SELECT * FROM catalog_readiness_snapshots WHERE target_commit_sha=? AND snapshot_status='passed' AND overall_score=100 ORDER BY created_at DESC,id DESC LIMIT 1",[$sha]):null;if(!$catalog)$reasons[]='No 100% catalog snapshot matches the activation commit.';
    $certificate=$sha&&sf_slc_ready()?sf_admin_fetch_one("SELECT * FROM staging_launch_certification_runs WHERE target_commit_sha=? AND run_status='passed' AND overall_score=100 ORDER BY completed_at DESC,id DESC LIMIT 1",[$sha]):null;if(!$certificate)$reasons[]='No 100% launch certificate matches the activation commit.';
    $coverage=$certificate?sf_sa_scenario_coverage((int)$certificate['id']):['ok'=>false,'missing'=>array_keys(sf_sim_catalog())];if(empty($coverage['ok']))$reasons[]='Missing passed integration scenarios: '.implode(', ',array_slice($coverage['missing']??[],0,10)).'.';
    $backup=sf_dor_latest_verified_backup(24);if(!$backup)$reasons[]='A fully verified backup from the last 24 hours is required.';
    $release=$sha?sf_sa_release_for_commit($sha):null;if(!$release)$reasons[]='Create a deployment release record for the activation commit.';elseif(function_exists('sf_dor_release_gate')){$releaseGate=sf_dor_release_gate((int)$release['id']);if(empty($releaseGate['ok']))foreach(array_slice($releaseGate['reasons']??[],0,10) as$reason)$reasons[]='Release: '.$reason;}
    return ['ok'=>!$reasons,'reasons'=>array_values(array_unique($reasons)),'run'=>$run,'catalog'=>$catalog,'certificate'=>$certificate,'coverage'=>$coverage,'backup'=>$backup,'release'=>$release];
}

function sf_sa_create_candidate(int $activationRunId,string $label,string $artifactUrl,string $artifactSha,string $notes=''): int {
    if(!sf_sa_ready())return 0;$gate=sf_sa_candidate_gate($activationRunId);if(empty($gate['ok']))return 0;$artifactUrl=trim($artifactUrl);$artifactSha=strtolower(trim($artifactSha));if(!filter_var($artifactUrl,FILTER_VALIDATE_URL)||!str_starts_with(strtolower($artifactUrl),'https://')||!preg_match('/^[a-f0-9]{64}$/',$artifactSha))return 0;$run=$gate['run'];$label=sf_sa_text($label,190)?:'Stonefellow RC '.substr((string)$run['target_commit_sha'],0,12);$pdo=sf_admin_db();if(!$pdo)return 0;
    try{$pdo->beginTransaction();$pdo->prepare("UPDATE staging_release_candidates SET candidate_status='superseded' WHERE target_commit_sha=? AND candidate_status IN ('draft','ready')")->execute([$run['target_commit_sha']]);$s=$pdo->prepare("INSERT INTO staging_release_candidates (candidate_key,candidate_label,activation_run_id,catalog_snapshot_id,launch_certification_run_id,backup_run_id,deployment_release_id,target_branch,target_commit_sha,artifact_url,artifact_sha256,candidate_status,release_notes,created_by_user_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,'ready',?,?)");$s->execute([sf_sa_uuid(),$label,$activationRunId,(int)$gate['catalog']['id'],(int)$gate['certificate']['id'],(int)$gate['backup']['id'],(int)$gate['release']['id'],(string)$run['target_branch'],(string)$run['target_commit_sha'],$artifactUrl,$artifactSha,sf_sa_text($notes,30000)?:null,sf_current_user_id()?:null]);$id=(int)$pdo->lastInsertId();$pdo->commit();sf_sa_candidate_event($id,'candidate.created','Exact-commit release candidate created.',['activation_run_id'=>$activationRunId,'artifact_sha256'=>$artifactSha],'verified');sf_admin_audit('create_staging_release_candidate','staging_release_candidate',$id,null,['commit'=>$run['target_commit_sha'],'artifact_sha256'=>$artifactSha]);return$id;}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();error_log('Release candidate create failed: '.$e->getMessage());return 0;}
}

function sf_sa_freeze_candidate(int $candidateId,string $notes): array {
    $candidate=sf_sa_candidate($candidateId);if(!$candidate||($candidate['candidate_status']??'')!=='ready')return['ok'=>false,'message'=>'Candidate is missing or not ready.'];$notes=sf_sa_text($notes,30000);if(strlen($notes)<30)return['ok'=>false,'message'=>'Freeze notes must document scope, owners, and rollback threshold.'];$gate=sf_sa_candidate_gate((int)$candidate['activation_run_id']);if(empty($gate['ok']))return['ok'=>false,'message'=>'Candidate gate no longer passes: '.implode(' ',array_slice($gate['reasons'],0,5))];$sha=strtolower((string)$candidate['target_commit_sha']);if(!hash_equals($sha,strtolower((string)$gate['run']['target_commit_sha'])))return['ok'=>false,'message'=>'Candidate commit binding changed.'];$ok=sf_admin_execute("UPDATE staging_release_candidates SET candidate_status='frozen',freeze_notes=?,frozen_by_user_id=?,frozen_at=NOW() WHERE id=? AND candidate_status='ready'",[$notes,sf_current_user_id()?:null,$candidateId]);if($ok){sf_sa_candidate_event($candidateId,'candidate.frozen','Release candidate frozen for production approval.',['commit'=>$sha,'artifact_sha256'=>$candidate['artifact_sha256']],'verified');sf_admin_audit('freeze_staging_release_candidate','staging_release_candidate',$candidateId,$candidate,['status'=>'frozen']);}return['ok'=>$ok,'message'=>$ok?'Release candidate is frozen and immutable for promotion.':'Candidate freeze failed.'];
}

function sf_sa_activation_summary(): array {
    $run=sf_sa_latest_passed();$candidate=sf_sa_latest_frozen_candidate();$sha=strtolower(trim((string)(getenv('SF_RELEASE_COMMIT_SHA')?:'')));$candidateMatches=$candidate&&preg_match('/^[a-f0-9]{40}$/',$sha)&&hash_equals($sha,strtolower((string)$candidate['target_commit_sha']));return['schema_ready'=>sf_sa_ready(),'latest_run'=>$run,'latest_candidate'=>$candidate,'release_commit'=>$sha,'candidate_matches_release'=>$candidateMatches,'operationally_ready'=>$run&&$candidate&&$candidateMatches];
}
