<?php
declare(strict_types=1);

function sf_vp3_clip_uuid():string{$b=random_bytes(16);$b[6]=chr((ord($b[6])&0x0f)|0x40);$b[8]=chr((ord($b[8])&0x3f)|0x80);$h=bin2hex($b);return sprintf('%s-%s-%s-%s-%s',substr($h,0,8),substr($h,8,4),substr($h,12,4),substr($h,16,4),substr($h,20));}
function sf_vp3_clip_settings_path():string{$p=trim((string)(getenv('SF_VP3_CLIPS_SETTINGS_PATH')?:''));return$p!==''?$p:(realpath(dirname(__DIR__))?:dirname(__DIR__)).'/storage/private/vp3-clips-bridge.json';}
function sf_vp3_clip_crypto_key():string{$raw=trim((string)(getenv('SF_VP3_BRIDGE_SETTINGS_KEY')?:getenv('SF_HASH_SALT')?:''));if(strlen($raw)<32)throw new RuntimeException('Set SF_VP3_BRIDGE_SETTINGS_KEY to a unique 32+ character secret.');return hash('sha256',$raw,true);}
function sf_vp3_clip_encrypt(string $plain):array{$n=random_bytes(12);$tag='';$c=openssl_encrypt($plain,'aes-256-gcm',sf_vp3_clip_crypto_key(),OPENSSL_RAW_DATA,$n,$tag,'stonefellow-vp3-clips-v1');if($c===false)throw new RuntimeException('Bridge settings encryption failed.');return['cipher'=>base64_encode($c),'nonce'=>base64_encode($n),'tag'=>base64_encode($tag)];}
function sf_vp3_clip_decrypt(array $box):string{$p=openssl_decrypt(base64_decode((string)($box['cipher']??''),true)?:'','aes-256-gcm',sf_vp3_clip_crypto_key(),OPENSSL_RAW_DATA,base64_decode((string)($box['nonce']??''),true)?:'',base64_decode((string)($box['tag']??''),true)?:'','stonefellow-vp3-clips-v1');return is_string($p)?$p:'';}
function sf_vp3_clip_settings():array{$path=sf_vp3_clip_settings_path();if(!is_file($path))return[];$d=json_decode((string)file_get_contents($path),true);if(!is_array($d))return[];$d['bridge_secret']=isset($d['secret_box'])?sf_vp3_clip_decrypt((array)$d['secret_box']):'';return$d;}
function sf_vp3_clip_save_settings(array $input):array{
 $current=sf_vp3_clip_settings();$api=rtrim(trim((string)($input['api_base']??$current['api_base']??'')),'/');if(!filter_var($api,FILTER_VALIDATE_URL)||strtolower((string)parse_url($api,PHP_URL_SCHEME))!=='https')throw new RuntimeException('VP3 API base must be an HTTPS URL.');
 $bridge=trim((string)($input['bridge_uuid']??$current['bridge_uuid']??''));if(!preg_match('/^[0-9a-f-]{36}$/i',$bridge))throw new RuntimeException('Enter a valid VP3 bridge ID.');$secret=trim((string)($input['bridge_secret']??''));if($secret==='')$secret=(string)($current['bridge_secret']??'');if(strlen($secret)<32)throw new RuntimeException('Enter the bridge secret shown by VP3.');
 $data=['schema_version'=>1,'api_base'=>$api,'bridge_uuid'=>$bridge,'secret_box'=>sf_vp3_clip_encrypt($secret),'source_creator_uuid'=>trim((string)($input['source_creator_uuid']??$current['source_creator_uuid']??'')),'source_show_uuid'=>trim((string)($input['source_show_uuid']??$current['source_show_uuid']??'')),'updated_at'=>date(DATE_ATOM)];
 $path=sf_vp3_clip_settings_path();$dir=dirname($path);if(!is_dir($dir)&&!mkdir($dir,0770,true)&&!is_dir($dir))throw new RuntimeException('Private bridge settings directory could not be created.');$tmp=$path.'.tmp.'.bin2hex(random_bytes(5));file_put_contents($tmp,json_encode($data,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),LOCK_EX);chmod($tmp,0640);if(!rename($tmp,$path)){@unlink($tmp);throw new RuntimeException('Bridge settings could not be finalized.');}return$data;
}
function sf_vp3_clip_tables_ready():bool{$pdo=sf_db();if(!$pdo)return false;foreach(['vp3_clips','vp3_clip_jobs','vp3_clip_sync_events','media_objects'] as $t){try{$s=$pdo->prepare('SHOW TABLES LIKE ?');$s->execute([$t]);if(!$s->fetchColumn())return false;}catch(Throwable){return false;}}return true;}
function sf_vp3_clip_sources():array{$pdo=sf_db();if(!$pdo||!sf_vp3_clip_tables_ready())return[];$sql="SELECT mo.id,mo.object_key,mo.entity_type,mo.entity_id,mo.role,mo.storage_key,mo.duration_seconds,mo.mime_type,mo.status,msp.driver,msp.provider_key FROM media_objects mo JOIN media_storage_providers msp ON msp.id=mo.provider_id WHERE mo.status='ready' AND mo.mime_type LIKE 'video/%' AND mo.role IN ('original','stream','preview') ORDER BY mo.is_primary DESC,mo.id DESC LIMIT 300";return$pdo->query($sql)->fetchAll()?:[];}
function sf_vp3_clip_by_id(int $id):?array{$pdo=sf_db();if(!$pdo)return null;$s=$pdo->prepare('SELECT vc.*,mo.storage_key source_storage_key,mo.mime_type source_mime,msp.driver source_driver FROM vp3_clips vc JOIN media_objects mo ON mo.id=vc.source_media_object_id JOIN media_storage_providers msp ON msp.id=mo.provider_id WHERE vc.id=? LIMIT 1');$s->execute([$id]);$r=$s->fetch();return is_array($r)?$r:null;}
function sf_vp3_clip_by_uuid(string $uuid):?array{$pdo=sf_db();if(!$pdo)return null;$s=$pdo->prepare('SELECT * FROM vp3_clips WHERE clip_uuid=? LIMIT 1');$s->execute([$uuid]);$r=$s->fetch();return is_array($r)?$r:null;}
function sf_vp3_clip_list(int $limit=100):array{$pdo=sf_db();if(!$pdo||!sf_vp3_clip_tables_ready())return[];$limit=max(1,min(300,$limit));return$pdo->query('SELECT vc.*,mo.entity_type source_type,mo.entity_id source_id FROM vp3_clips vc JOIN media_objects mo ON mo.id=vc.source_media_object_id ORDER BY vc.updated_at DESC,vc.id DESC LIMIT '.$limit)->fetchAll()?:[];}
function sf_vp3_clip_save(array $input,int $userId):int{
 $pdo=sf_db();if(!$pdo||!sf_vp3_clip_tables_ready())throw new RuntimeException('Import migration 027 before creating clips.');$id=max(0,(int)($input['id']??0));$objectId=(int)($input['source_media_object_id']??0);$s=$pdo->prepare("SELECT * FROM media_objects WHERE id=? AND status='ready' AND mime_type LIKE 'video/%' AND role IN ('original','stream','preview') LIMIT 1");$s->execute([$objectId]);$object=$s->fetch();if(!is_array($object))throw new RuntimeException('Select a ready video source.');
 $start=max(0,(float)($input['trim_start_seconds']??0));$end=(float)($input['trim_end_seconds']??0);$sourceDuration=(float)($object['duration_seconds']??0);if($end<=0&&$sourceDuration>0)$end=min($sourceDuration,$start+60);$duration=$end-$start;if($duration<1||$duration>180)throw new RuntimeException('Clip duration must be between 1 and 180 seconds.');if($sourceDuration>0&&$end>$sourceDuration+0.05)throw new RuntimeException('Clip end exceeds source duration.');
 $title=trim((string)($input['title']??''));if($title===''||strlen($title)>190)throw new RuntimeException('Enter a clip title up to 190 characters.');$destination=trim((string)($input['destination_url']??''));if(!filter_var($destination,FILTER_VALIDATE_URL)||strtolower((string)parse_url($destination,PHP_URL_SCHEME))!=='https')throw new RuntimeException('Destination must be an HTTPS URL.');$owner=trim((string)($input['rights_owner_name']??''));if($owner===''||strlen($owner)>190)throw new RuntimeException('Enter the rights owner.');$aspect=(string)($input['aspect_ratio']??'9:16');if(!in_array($aspect,['9:16','1:1','4:5','16:9'],true))$aspect='9:16';$scheduled=trim((string)($input['scheduled_at']??''));$scheduled=$scheduled!==''?str_replace('T',' ',$scheduled).(strlen($scheduled)===16?':00':''):null;$expires=trim((string)($input['rights_expires_at']??''));$expires=$expires!==''?str_replace('T',' ',$expires).(strlen($expires)===16?':00':''):null;$now=date('Y-m-d H:i:s');
 $values=[$objectId,(string)$object['entity_type'],(int)$object['entity_id'],$title,substr(trim((string)($input['caption']??'')),0,2000),$start,$end,(int)ceil($duration),max($start,min($end,(float)($input['poster_at_seconds']??max(1,$start+1)))),$aspect,$destination,substr(trim((string)($input['destination_label']??'Watch more')),0,80),$owner,!empty($input['rights_confirmed'])?1:0,$expires,$scheduled,$now,$userId];
 if($id>0){$stmt=$pdo->prepare('UPDATE vp3_clips SET source_media_object_id=?,source_entity_type=?,source_entity_id=?,title=?,caption=?,trim_start_seconds=?,trim_end_seconds=?,duration_seconds=?,poster_at_seconds=?,aspect_ratio=?,destination_url=?,destination_label=?,rights_owner_name=?,rights_confirmed=?,rights_expires_at=?,scheduled_at=?,source_updated_at=?,updated_by_user_id=?,local_status=IF(local_status IN (\'published\',\'scheduled\',\'pending\'),\'ready\',local_status),last_error=NULL WHERE id=?');$stmt->execute([...$values,$id]);return$id;}
 $uuid=sf_vp3_clip_uuid();$token=bin2hex(random_bytes(32));$stmt=$pdo->prepare("INSERT INTO vp3_clips (clip_uuid,public_token,source_media_object_id,source_entity_type,source_entity_id,title,caption,trim_start_seconds,trim_end_seconds,duration_seconds,poster_at_seconds,aspect_ratio,destination_url,destination_label,rights_owner_name,rights_confirmed,rights_expires_at,scheduled_at,local_status,source_updated_at,created_by_user_id,updated_by_user_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'draft',?,?,?)");$stmt->execute([$uuid,$token,...$values,$userId]);return(int)$pdo->lastInsertId();
}
function sf_vp3_clip_output_root():string{$configured=trim((string)(getenv('SF_VP3_CLIPS_ROOT')?:'storage/private/vp3_clips'));$base=realpath(dirname(__DIR__))?:dirname(__DIR__);return str_starts_with($configured,'/')?rtrim($configured,'/\\'):$base.'/'.trim(str_replace('\\','/',$configured),'/');}
